haskell/haskell-language-server

- .gitmodules
- README.md
- cabal.project
Some people do not like git submodules, so this might be overkill
> Embed ghcide as a git submodule

- ide.cabal
- src/Ide/Plugin/Example.hs
Now generates a constant code action, which adds a TODO comment on the current line.  My standard "hello world" code action.
> Clean up cabal file, make code action work

- hie.yaml.cbl
N.B. this might need a matching change to the stack hie.yml.
> The target is 'haskell-ide' not 'ide' - change it in hie.yaml.cbl

- .gitmodules
N.B. The below git error when doing a submodule init or recursive clone
with the alanz repo as the submodule.
Admittedly this is quite likely the wrong fix and instead whatever is going on cloning alanz/ghcide should be fixed instead.
```
error: Server does not allow request for unadvertised object 956e11dff8059b1b78ea487db7d6dcb3430ad6c4
Fetched in submodule path 'ghcide', but it did not contain 956e11dff8059b1b78ea487db7d6dcb3430ad6c4. D
irect fetching of that commit failed.
```
> The @alanz repo fails to clone, use digital-assets

- src/Ide/Plugin/Example.hs
For emacs, make sure code lens is enabled, by setting (via customize)
Lsp Lens Auto Enable to 't'.
> Add CodeLens example

- exe/Wrapper.hs
- hie.yaml.cbl
- ide.cabal
- src/Ide/Cradle.hs
- src/Ide/Options.hs
- src/Ide/Version.hs
Seems to work as advertised, handing over to haskell-ide.
Need to harmonise options though.
Closes #13
> Brute force copy of hie-wrapper from hie to ide

- .gitignore
- install.hs
- install/Setup.hs
- install/cabal.project
- install/hie-install.cabal
- install/shake.project
- install/shake.yaml
- install/src/BuildSystem.hs
- install/src/Cabal.hs
- install/src/Env.hs
- install/src/Help.hs
- install/src/HieInstall.hs
- install/src/Print.hs
- install/src/Stack.hs
- install/src/Version.hs
Renamed the string stuff to be "haskell-ide-" instead of "hie-",
nothing else changed.
Initial hand tests show it working for stack installs.
Closes #14
> Brute-force copy of install.hs from hie

- install/src/Cabal.hs
- install/src/Stack.hs
Tha package name still referred the old name
> Fix install.hs targets

- .gitignore
- cabal.project
- install/src/Cabal.hs
I forgot to add wrapper to cabal install targets
> Add wrapper to cabal install target

- install/src/Cabal.hs
- install/src/Env.hs
- install/src/HieInstall.hs
* apply changes of https://github.com/haskell/haskell-ide-engine/pull/1632
> Check there is one ghc in $PATH

- hie.yaml.cbl
- hie.yaml.stack
* And add a working version in the stack one
> Warn in hie.yaml.* that they do not currently work

- .gitmodules
- cabal.project
- exe/Main.hs
- haskell-language-server.cabal
- src/Ide/Cradle.hs
- src/Ide/Plugin/Example.hs
- src/Ide/Plugin/Ormolu.hs
- src/Ide/Version.hs
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack.yaml
Supports whole module and range formatting.
Does not yet extract options from the hie-bios cradle.
Closes #30
> Formatting via Ormolu plugin

- .gitmodules
- cabal.project
- exe/Main.hs
- haskell-language-server.cabal
- src/Ide/Plugin/Config.hs
- src/Ide/Plugin/Example.hs
- src/Ide/Plugin/Floskell.hs
- src/Ide/Plugin/Formatter.hs
- src/Ide/Plugin/Ormolu.hs
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack.yaml
- test/functional/FormatSpec.hs
First pass only, need to (re-)enable tests, and find a way of selecting between
multiple formatters. Apart from only installing a single formatter plugin.
Note: this PR currently depends on #41, so is much noisier than it should be.
Published as a "show and tell"
>  Generalize formatter plugin support, add Floskell

- install/src/Cabal.hs
- install/src/Env.hs
- install/src/Help.hs
- install/src/HieInstall.hs
- install/src/Print.hs
- install/src/Stack.hs
- install/src/Version.hs
* Remove unused imports
* Pass verbosity shake arg to build tools (cabal and stack)
* Use custom cabal.project-${ghcVersion} if exists
* I added cabal.project-ghc-8.8.2 that will be used by the script
* Change targets to "hls"
> Port hie changes in install script of pull #1665

- cabal.project
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack.yaml
* To avoid build issues
* Also use `lts-5.2` in stack-8.8.2.yaml
> Use cabal helper head

- hie.yaml.cbl
- hie.yaml.stack
I removed missing `hls-tests` component and added `func-test`.
I also added `hls-test-utils` component, but it does not work (stack 2.1.3), so I left it commented.
> fix missing component(hls-tests) in hie.yaml samples (added func-test)

- .circleci/config.yml
- .gitmodules
- exe/Main.hs
- haskell-language-server.cabal
- src/Ide/Plugin.hs
- src/Ide/Plugin/GhcIde.hs
The way PartialHandlers are chained in ghcide means earlier ones get masked by
ones added later in the chain.
Create GhcIde plugin so the underlying hover handler can be combined with other
configured hover handlers at the haskell-language-server combined handler.
Requires https://github.com/digital-asset/ghcide/pull/490
> Create plugin for wrapping the handlers from ghcide

- exe/Arguments.hs
- exe/Main.hs
- exe/Wrapper.hs
- src/Ide/Logger.hs
- src/Ide/Plugin.hs
- src/Ide/Version.hs
* More renaming hie to hls
* Add `-j` argument to control the number of threads
* Show arguments and plugins when starting lsp server
> Some minor changes

- install.hs
- install/Setup.hs
- install/hls-install.cabal
- install/shake.yaml
- install/src/Cabal.hs
- install/src/Env.hs
- install/src/Help.hs
- install/src/HlsInstall.hs
- install/src/Stack.hs
I hope we will not have to backport big changes from hie
> Complete renaming from hie to hls in install script

- cabal.project
- exe/Main.hs
* With the actual version of hie-bios, loading modules from the ghcide submodule failed, see https://github.com/mpickering/hie-bios/pull/166#issuecomment-613091664
* We can either wait to an hie-bios release [with the patch included](https://github.com/mpickering/hie-bios/pull/166) and remove the git dependency or merge this as is
> Use patched version of hie-bios to load ghcide modules

- src/Ide/Cradle.hs
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack.yaml
* It needs a ghcide version compatible with the hie-bios patch:  https://github.com/alanz/ghcide/pull/1
> Use patched version of hie-bios in stack config

- test/functional/FormatSpec.hs
- test/utils/TestUtils.hs
Apparently I dropped the commit that fixed the tests instead of sqashing it 😭
> Fix Brittany test suite

- cabal.project
- exe/Main.hs
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack.yaml
I force pushed to the PR https://github.com/mpickering/hie-bios/pull/166 so the commit hash is wrong.
> Fix source packages for hie-bios

- cabal.project
- haskell-language-server.cabal
- src/Ide/Plugin/Brittany.hs
- src/Ide/Plugin/Floskell.hs
- src/Ide/Plugin/Formatter.hs
- src/Ide/Plugin/Ormolu.hs
- src/Ide/PluginUtils.hs
- src/Ide/Types.hs
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack.yaml
- test/functional/FormatSpec.hs
Additionally:
* Move makeDiffTextEdit from Haskell-IDE-Engine to PluginUtils.
* Fix version constraing for `ghc-check`
* Add version constraint for ormolu
* update index-state and stack.yaml
Considerably simplifies the plugin, since they do the heavy lifting. See https://github.com/tweag/ormolu/issues/516 for the upstream issue.
Ought to fix #48
> Update to ormolu 0.5.0 and simplify plugin

- cabal.project
- exe/Arguments.hs
- exe/Main.hs
- haskell-language-server.cabal
- src/Ide/Plugin/Example.hs
- src/Ide/Plugin/Example2.hs
- src/Ide/Plugin/Formatter.hs
- src/Ide/Plugin/Ormolu.hs
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
Commit 256f8b50415a08454d471a6a28f742c0a1e39978
And now re-rebased on a68273a3f8b30e1bc48eba6e7053163ca4e5bc47
now 3dde18f06ea18731bb3befa0d81af9a6b894d917
> Rebase on mpickering ghcide at wip/multi-rebase

- exe/Arguments.hs
- exe/Main.hs
- haskell-language-server.cabal
- src/Ide/Plugin/Example.hs
- src/Ide/Plugin/Example2.hs
- src/Ide/Types.hs
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack.yaml
At commit b4c3619346f4fe89ac036322fdd9ed178fb66685
> Use mpickering/hls ghcide branch

- ChangeLog.md
No release yet, but starting the monthly tag process.
> Preparing ChangeLog for first official tagging.

- exe/Main.hs
lately hls was begging about that
> Fix haddock parsing errors

- .circleci/config.yml
- cabal.project
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack.yaml
@alanz @fendor I think we can create a new release of haskell-lsp with updated bounds before merging this, to avoid extra submodules?
Also the mpickering hie-bios fork should have the changes from the fendor fork now
> Get building with ghc-8.10

- exe/Main.hs
> Activate typechecking in non-lsp mode

- cabal.project
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack.yaml
Since afaict, the current shake ref has been removed by force-pushing.
> Update extra-deps to use latest fork version of shake

- cabal.project-8.10.1
* It let us isolate temporary config tweaks in its own config file like `allow-newer` and turning off docs
* The install.hs script will pick it auto
* But you have to remember use it wen building using directly cabal
> Create specific project file for ghc-8.10.

- cabal.project
- exe/Main.hs
- haskell-language-server.cabal
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack.yaml
Using mpickering ghcide at 044a009201bfc66e76b54ad2fb3377d57d54e71e
Adding some tweaks for the hover formatting.
> Use latest mpickering hls, with hover tweaks added

- cabal.project
- exe/Main.hs
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack.yaml
At e7adaca189a86c6ac7b434fec29055c80d0468ac
Clears the way for #107
> Use new mpickering/ghcide/hls

- src/Ide/Plugin.hs
- src/Ide/Plugin/Example.hs
- src/Ide/Plugin/Example2.hs
- src/Ide/Plugin/GhcIde.hs
- src/Ide/Types.hs
fixes #71 and #87
This fix requires the **ghcide**'s `Development.IDE.Plugin.Completions` module to expose `getCompletionsLSP`
> [#87] Fix completion via ghcide's `getCompletionsLSP`

- README.md
- install/src/HlsInstall.hs
* Mainly "install from source" instructions and "project configuration"
* And the lovely "It's time to join the project!" 🥰 
* It would fix #85
> Port hie README partially

- README.md
Add subsection for emacs/doom-emacs integration
> Add emacs/doom-emacs integration sub-section

- haskell-language-server.cabal
* The pr adding tast-ant-xml was built succesfullt [with cabal in ci](https://circleci.com/gh/haskell/haskell-language-server/379?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link)
* It used:
```
- tasty-1.2.3 (lib) (requires download & build)
- tasty-rerun-1.1.17 (lib) (requires download & build)
- tasty-hunit-0.10.0.2 (lib) (requires download & build)
- tasty-expected-failure-0.11.1.2 (lib) (requires download & build)
- tasty-ant-xml-1.1.6 (lib) (requires download & build)
```
* The next commit (mine! ✋ ) changed the hackage index from 2020-05-13T21:21:45Z to 2020-05-17T20:25:21Z and triggered the build error picking;
```
- tasty-1.3.1 (lib) (requires download & build)
- tasty-rerun-1.1.17 (lib) (requires download & build)
- tasty-hunit-0.10.0.2 (lib) …
```
> Add lower bound to tasty-ant-xml

- src/Ide/Plugin.hs
- src/Ide/Plugin/Brittany.hs
- src/Ide/Plugin/Example.hs
- src/Ide/Plugin/Example2.hs
- src/Ide/Plugin/Floskell.hs
- src/Ide/Plugin/GhcIde.hs
- src/Ide/Plugin/Ormolu.hs
- src/Ide/Plugin/Pragmas.hs
- src/Ide/Types.hs
This is a precursor to a Retrie plugin with a RenameProvider
> Add plugin support for Rename providers

- exe/Arguments.hs
This will mean that it is multithreaded by default, but will match the behaviour in ghcide.
alanz/vscode-hie-server#230
> Default the number of Shake threads to 0 (automatic)

- README.md
> Add zlibc to readme

- README.md
* Copying them from hie
* I've not included Oni cause i dont know if it will work
* Closes #85
> Complete editor integrations

- haskell-language-server.cabal
- hie.yaml.cbl
- hie.yaml.stack
* To workaround the issues involving the stack based cradle: #114 and #121 
* I've not changed the build info of the previous private lib, in the hope we will restore it
* I've tested it locally:
* You can open `Test.Hls.Util` after building the project with test enabled `stack build --test --no-run.tests`
* When opening exe/Main.hs after deleting `.stack-work`, it hits https://github.com/mpickering/ghcide/issues/50 but it seems it does not need a `stack build`(it starts the initial ghc session)
> Convert private lib in common stanza

- .circleci/config.yml
* CI always red is not good, we have to check that them at least builds
* I think separate tests could be useful in its own
> Separate ghcide tests and disable them for now

- exe/Main.hs
- haskell-language-server.cabal
- src/Ide/Plugin/Config.hs
- src/Ide/Plugin/StylishHaskell.hs
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack.yaml
- test/functional/Format.hs
- test/testdata/StylishHaskell.hs
Is it OK to use "stylishHaskellCmd:" error message when the name of the plugin is "stylish-haskell"? All existing plugins have names without "-", so I couldn't find an example for this kind of naming.
Done:
> [Plugin] stylish-haskell formatter

- haskell-language-server.cabal
- test/functional/Format.hs
- test/testdata/BrittanyCRLF.formatted_document.hs
- test/testdata/BrittanyCRLF.formatted_range.hs
- test/testdata/BrittanyLF.formatted_document.hs
- test/testdata/BrittanyLF.formatted_range.hs
- test/testdata/Format.formatted_document.hs
- test/testdata/Format.formatted_document_with_tabsize.hs
- test/testdata/Format.formatted_range.hs
- test/testdata/Format.formatted_range_with_tabsize.hs
- test/testdata/Format.ormolu.formatted.hs
- test/testdata/Format.ormolu.unchanged.hs
- test/testdata/StylishHaksell.format_document.hs
- test/testdata/StylishHaksell.format_range.hs
- test/testdata/StylishHaksell.formatted_document.hs
- test/testdata/StylishHaksell.formatted_range.hs
This PR introduces a golden testing facility and restores most of the format tests.
Related comments: https://github.com/haskell/haskell-language-server/pull/146#discussion_r436191050
@alanz, I want to join this project team. Is it possible to join?
> Introduce golden testing

- README.md
- hie.yaml.cbl
- hie.yaml.stack
- install/hie.yaml.cbl
- install/hie.yaml.stack
- install/stack.yaml
* Rework hie.yaml templates (exclude some directories like `testdata`)
* Add stack.yaml to install/ folder
* Add Stack and Cabal templates for hie.yaml for install/ folder
* Add and cleanup documentation about hie.yaml
* Add comment about building for Stack
Closes #121
Closes #145
Note: Because my personal computer runs on Windows + WSL1 + there is a bug with WSL1 + Cabal, I can't test the Cabal flavor.
If anybody would be kind enough to give it a try, I would appreciate 😄
> feat(hie-bios): Multi-cradle, ignore directories

- README.md
- install/src/Stack.hs
> Remove last occurrences of shake.yaml

- .gitmodules
- cabal.project
- exe/Main.hs
- haskell-language-server.cabal
- src/Ide/Plugin/Example.hs
- src/Ide/Plugin/Example2.hs
- stack-8.10.1.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack.yaml
Based on https://github.com/wz1000/ghcide/tree/hls-2
> Update to new hls

- shell.nix
My personal workflow is to use this shell to have `binutils-unwrapped` and similar in scope.
> Use shell.nix from Haskell-IDE-Engine

- README.md
> doc(preprocessor): Document the preprocessor limitation

- cabal.project
The patched version just relaxed some upper bounds. Those changes have since been upstreamed.
This is necessary for #161, since cabal-plan 0.7 also relaxes the upper bound on Aeson.
> Use cabal-plan from Hackage

- cabal.project
- exe/Main.hs
- stack-8.10.1.yaml
- stack-8.8.3.yaml
At 747ec1401c62257ec849319eb2dda966a8008b09
Also bump cabal-project index-state to 2020-07-01T16:33:28Z
stack 8.10.1 to nightly-2020-06-29
stack 8.8.3  to lts-16.3
> Bump ghcide to wz1000 hls-2 branch

- haskell-language-server.cabal
- src/Ide/Version.hs
Cabal as a dependency is a pretty hefty price to pay for simply getting the build architecture, which already seems to be in System.Info. Probably just accidentally copied over from when HIE used Cabal for dealing with .cabal files
> Remove dependency on Cabal

- .gitmodules
- cabal.project
- exe/Main.hs
- haskell-language-server.cabal
- src/Ide/Cradle.hs
- stack-8.10.1.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack.yaml
Updates the submodule as well, PR for hls-2 is here: https://github.com/wz1000/ghcide/pull/6
> Update hie-bios 0.6.1

- install/src/Stack.hs
This way we avoid install executables from ghcide or other subpackages
Fixes #198
> Fix install script stack targets

- cabal.project
- stack-8.8.3.yaml
- stack-8.8.4.yaml
* Updating hackage index to get last version of ghc-exactprint, compatible with ghc-8.8.4
* Adding a `stack-8.8.4.yaml` using the last `ghc-8.8.3` resolver but informing explicitly `compiler: ghc-8.8.4`
I am getting errors compiling floskell in windows, but it is reproduced with other ghc versions. I get to compile downloading floskell locally and adding it as subpackage in `cabal.project`. 
To report upstream 🤷‍♂️ : https://github.com/ennocramer/floskell/issues/50
> Add support for ghc-8.8.4

- .gitignore
- README.md
- exe/Main.hs
- haskell-language-server.cabal
- src/Ide/Plugin/Eval.hs
- test/functional/Eval.hs
- test/functional/Main.hs
- test/testdata/eval/T1.hs
- test/testdata/eval/T1.hs.expected
- test/testdata/eval/T2.hs
- test/testdata/eval/T2.hs.expected
- test/testdata/eval/T3.hs
- test/testdata/eval/T3.hs.expected
- test/testdata/eval/T4.hs
- test/testdata/eval/T4.hs.expected
- test/testdata/eval/T5.hs
- test/testdata/eval/T5.hs.expected
- test/testdata/eval/T6.hs
- test/testdata/eval/T6.hs.expected
- test/testdata/eval/T7.hs
- test/testdata/eval/T7.hs.expected
- test/testdata/eval/hie.yaml
- test/testdata/eval/test.cabal
```
-- | A plugin inspired by the REPLoid feature of Dante[1] which allows
--     to evaluate code in comment prompts and splice the results right below:
--
--    > example :: [String]
--    > example = ["This is an example", "of", "interactive", "evaluation"]
--    >
--    > -- >>> intercalate " " example
--    > -- "This is an example of interactive evaluation"
--    > --
```
Closes #51
> Simple Eval plugin

- README.md
Thanks to @pepeiborra at #208, I discovered that it is actually currently possible to get docs for dependencies to show up in HLS. Based on a discussion about this on IRC a few days ago, I suspect this is not widely known. Indeed, AFAICT, the `-haddock` flag is completely undocumented.
I don't know if this is necessarily the best part of the README in which to mention the workaround for this, but I feel it ought to be in there somewhere.
I was also unsure whether it's worth explaining how to specify a GHC flag for dependencies of a project, and which method to mention for doing so. Personally, I've just decided to bite the bullet and go with:
```
program-default-options
ghc-options: -haddock
```
in my global cabal config, but I'd guess that's not suitable for everyone.
> Mention docs on hover feature in README

- README.md
- src/Ide/Plugin/Config.hs
- test/functional/Completion.hs
- test/functional/Format.hs
This matches up with how other language servers name their configuration section (see https://marketplace.visualstudio.com/items?itemName=rust-lang.rust), and the new VS Code extension has already done this rename.
Unfortunately we forgot to also change it in haskell-language-server. This is a bit of a growing pain and will break people's configs, but thankfully the only configuration option that seems to have any effect in hls at the moment is the formatter. We need to follow this up with the equivalent change in haskell-ide-engine too.
> Rename the configuration section from languageServerHaskell => haskell

- cabal.project
- stack-8.10.1.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack-8.8.4.yaml
- stack.yaml
- test/functional/Deferred.hs
- test/functional/TypeDefinition.hs
* After make sure with dont need `documentation: true` for sure
* This is related with #208 and #209, where i learned that hls/ghcide is using the docs included in ~~hie~~`.hi` files when you pass `-haddock` to ghc and no the docs generated by the haddock tool (with `documentation: true`)
* See the mentioned issue/pr for more context
> Use -haddock for cabal and stack

- shell.nix
I've done a bit more work on this, fixing compatibility with all supported ghc versions and adding some comments on the rationale behind the approach.
```
pepeiborra@devvm370 ~/s/ide (shell-nix)> nix-shell -run "cabal build --dry-run"
Resolving dependencies...
Build profile: -w ghc-8.8.3 -O1
In order, the following would be built (use -v for more details):
- ghcide-0.2.0 (exe:ghcide-test-preprocessor) (first run)
- lsp-test-0.11.0.2 (lib) (requires build)
- streaming-commons-0.2.1.2 (lib) (requires download & build)
- conduit-extra-1.3.5 (lib) (requires build)
- hie-bios-0.6.1 (lib) (requires build)
- ghcide-0.2.0 (lib) (first run)
- haskell-language-server-0.2.2.0 (lib) (first run)
- haskell-language-server-0.2.2.0 (exe:haskell-language-server-wrapper) (first run)
- …
```
> Shell nix further steps

- exe/Arguments.hs
- exe/Main.hs
- exe/Wrapper.hs
closes #238 
Also correctly shuts down the language server if `--version` was given.
Minor rework of argument parser.
This might cause breakage, since combinations such as `haskell-language-server --version --lsp` used to be valid but are not anymore. Not sure if and how important that is, though. I think we can change it if it is important, but we might lose the stronger types or increase the complexity of the arguments parser.
> Add numeric-version option for wrapper and server

- cabal.project
- haskell-language-server.cabal
- src/Ide/Plugin/Config.hs
- stack-8.10.1.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack-8.8.4.yaml
- stack.yaml
- test/functional/Format.hs
- test/testdata/BrittanyCRLF.formatted_document.hs
- test/testdata/BrittanyCRLF.formatted_range.hs
- test/testdata/BrittanyLF.formatted_document.hs
- test/testdata/BrittanyLF.formatted_range.hs
- test/testdata/Format.brittany.formatted.hs
- test/testdata/Format.brittany_post_floskell.formatted.hs
- test/testdata/Format.floskell.formatted.hs
- test/utils/Test/Hls/Util.hs
- test/wrapper/Main.hs
This also requires a bump to lsp-test to fix a test, and drops the
trick that the wrapper tests used to find the wrapper executable since
it was just confusing
> Accept the legacy "languageServerHaskell" config name

- src/Ide/Plugin/Eval.hs
- test/functional/Eval.hs
- test/testdata/eval/T8.hs
- test/testdata/eval/T8.hs.expected
Fix for https://github.com/haskell/haskell-language-server/issues/218
If an error takes place during test evaluation is returned as the result of the test.
I have added a test.
> Fix for Eval plugin: Error from tests not reported 

- .github/workflows/build.yml
Also use zip as compression method for Windows
Fixes #225
> Rename binaries before uploading

- install.hs
Seeing as, since #209, the README suggests globally enabling `-haddock`, it's rather unfortunate for that not to work with HLS' own installation script...
> Fix haddock parse error in install.hs

- haskell-language-server.cabal
- src/Ide/Plugin/Ormolu.hs
There's two independent changes here:
1. Fix the rendering of the CPP extension as a flag; there might be a better way to fix this.
2. Do not process LANGUAGE and OPTIONS pragmas for Ormolu, since I believe Ormolu is going to process those anyway. @mrkkrp is that right?
Fixes #245
> Ormolu flags

- .circleci/config.yml
Hoogle nor happy nor cabal-helper shouldn't be needed anymore. CI is still flakey so the tests are failing. Trying to fix it as we speak, sorry about that
> Remove redundant CircleCI steps

- .circleci/config.yml
Fixes #252 
Turns out Tasty was trying to run every single test in parallel at once, which is why when #247 added two extra tests it was just enough to push it over the limit and cause things to fail
> Slow down Tasty by limiting it to -j1

- haskell-language-server.cabal
- test/functional/Command.hs
- test/functional/Completion.hs
- test/functional/Deferred.hs
- test/functional/Definition.hs
- test/functional/Diagnostic.hs
- test/functional/Format.hs
- test/functional/FunctionalBadProject.hs
- test/functional/FunctionalCodeAction.hs
- test/functional/FunctionalLiquid.hs
- test/functional/Highlight.hs
- test/functional/Progress.hs
- test/functional/Reference.hs
- test/functional/Rename.hs
- test/functional/Symbol.hs
- test/functional/TypeDefinition.hs
Use @? and @?= instead, since they give easier to read error messages. The `shouldX` functions all just end up dumping the Show instance of a HSpecFailure or what have you which is hard to read. It also doesn't look like hspec-expectations is that actively maintained anymore
> Remove hspec-expectations

- .circleci/config.yml
AFAIK, CircleCI's cache system treats a restore key as a prefix of a real cache key, not the exact cache key.
If the prefix(restore key) matches with many cache keys, the recent most cache will be restored.
In our setting, we have two different key schemes for saving cache
1. `stack-cache-{{ .Environment.HIE_CACHE }}-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "stack-build.txt" }}`
2. `stack-cache-{{ .Environment.HIE_CACHE }}-{{ arch }}-{{ .Environment.CIRCLE_JOB }}-{{ checksum "stack-build.txt" }}-{{ checksum "all-cabal.txt" }}`
However, 1. is a prefix of 2., so every prefix (restore key) that matches with 1. also matches with 2., and 2. is created later in the CI script so it's the one that will always be restored.
Ref: …
> Remove a redundant caching step

- README.md
`hie.yaml` should be at the top since root is decided by `hie.yaml` as a first priority.
> add hie.yaml to coc configuration

- .gitmodules
- exe/Main.hs
- src/Ide/Plugin/Retrie.hs
At b7de7ae89469693b76d92ca433119d91d3a9aac0
> Use wz1000/hls-3 ghcide branch

- src/Ide/Plugin.hs
When there are no plugins provided that provide a pluginRenameProvider
This also applies to the other capabilities
Fixes #190
> Fix rename capability being declared

- exe/Main.hs
- haskell-language-server.cabal
I honestly don't know what this entails and the documentation is hard to find but I think it fixes the problem described in https://github.com/haskell/vscode-haskell/issues/255
> Make the AGPL flag manual in cabal

- .circleci/config.yml
- nix/sources.json
- shell.nix
- src/Ide/Plugin/Example.hs
Fixes #294 - although I could not repro the problem in the issue, I found that nix-shell was failing due to fourmulu. 
The CI job should ensure that this doesn't break silently again, and I added instructions on what to do when it breaks.
The example ParsedModule commit is unrelated - let me know if you prefer me to send it in a separate PR
> Add a Nix CI job + a Hoogle option

- ChangeLog.md
Admittedly 'Forourmolu' is probably no sillier than the current name...
> Fix typo in changelog

- exe/Arguments.hs
- exe/Main.hs
- exe/Wrapper.hs
- src/Ide/Version.hs
For making #305 simpler
Example:
```
> haskell-language-server --probe-tools
haskell-language-server version: 0.3.0.0 (GHC: 8.8.3) (PATH: /home/munin/.cabal/store/ghc-8.8.3/haskell-language-server-0.3.0.0-50ac3c2ce9988216a5f58c897e446f023d24f554e742bcae93fcc77e9a6ded73/bin/haskell-language-server)
Tool versions found on the $PATH
cabal:		3.0.0.0
stack:		2.1.3.1
ghc:		8.8.3
```
```
>  haskell-language-server .
haskell-language-server version: 0.3.0.0 (GHC: 8.8.3) (PATH: /home/munin/.cabal/store/ghc-8.8.3/haskell-language-server-0.3.0.0-50ac3c2ce9988216a5f58c897e446f023d24f554e742bcae93fcc77e9a6ded73/bin/haskell-language-server)
(haskell-language-server)Ghcide setup tester in /home/munin/Documents/haskell/hls.
Report bugs at https://github.com/haskell/haskell-language-server/issues
Tool …
```
> Probe tools cli

- src/Ide/Version.hs
As discovered by https://github.com/haskell/haskell-language-server/pull/306#issuecomment-671829315, I forgot to actually check that a tool is on the path!
Therefore, currently HLS breaks for everyone who built it from source since the commit 0b12fcb4a2cddffdf0a5e25c799a6a5c5cb8b490 and has not every tool installed.
> Return nothing if tool is not on the PATH

- stack-8.10.1.yaml
- stack-8.10.2.yaml
* Although it seems 8.10.3 will be released soon
* I've updated the stack-8.10.1.yaml resolver before using it as base for stack-8.10.2.yaml
* Tested locally with cabal
* Fixes #298
> Add support for ghc-8.10.2

- stack-8.10.1.yaml
- stack-8.10.2.yaml
* To fix the build for stack 8.10.1 and 8.10.2 (broken by #308)
> Restrict opentelemetry version for stack builds

- README.md
Coc site [1] now shows an example config with a top level `{}` that includes everything. Without it, `Coc` complains about syntax error in the config file, and the language server will not be loaded. 
```json
{
"languageserver": {
"go": {
"command": "gopls",
"rootPatterns": ["go.mod"],
"trace.server": "verbose",
"filetypes": ["go"]
}
}
}
```
[1] https://github.com/neoclide/coc.nvim
> Coc config file requires a {} nesting everything

- README.md
This also corrects filetypes supported, as `lhaskell` is the correct filetype for literate haskell in vim-land, and file extensions (`hs`, `lhs`) don't matter as coc understands vim filetypes, not file extensions.
> Simplify coc.nvim instructions

- install/hls-install.cabal
- install/src/Stack.hs
This PR corrects two occurrences of `haskell-language-engine` by `haskell-language-server`. This corrects a URL that was directing to a non-existing repository.
> Replace wrong occurrences of "engine" by "server"

- README.md
- exe/Main.hs
- haskell-language-server.cabal
- src/Ide/Plugin/ImportLens.hs
This adds a new code lens for displaying explicit import lists on import declarations. There is hopefully an animated gif that illustrates it.
> Explicit imports lens (as seen on Twitter)

- .gitignore
> feat(git): Add install/hie.yaml to gitignore

- stack.yaml
* The actual `stack.yaml` didnt work for me (i was testing it trying to reproduce #327):
```
PS D:\dev\ws\haskell\hls> stack build
Error: While constructing the build plan, the following exceptions were encountered:
In the dependencies for HsYAML-aeson-0.2.0.0:
aeson dependency cycle detected: aeson, these, aeson, ghcide
needed due to haskell-language-server-0.3.0.0 -> HsYAML-aeson-0.2.0.0
Dependency cycle detected in packages:
[aeson,these,aeson,ghcide]
In the dependencies for aeson-pretty-0.8.8:
aeson dependency cycle detected: aeson, these, aeson, ghcide
needed due to ghcide-0.2.0 -> aeson-pretty-0.8.8
In the dependencies for brittany-0.12.1.1:
aeson dependency cycle detected: aeson, these, aeson, ghcide
needed due to haskell-language-server-0.3.0.0 -> brittany-0.12.1.1
In the …
```
> Copy working stack-8.6.5.yaml to stack.yaml

- src/Ide/Plugin/Eval.hs
- test/functional/Eval.hs
- test/testdata/eval/T9.hs
- test/testdata/eval/T9.hs.expected
> Apply the module pragmas for evaluation

- README.md
I think this kind of documentation, even though it may seem obvious to HLS maintainers, are helpful to newcomers who wish to give it a shot hacking HLS 😄
> doc(hack): Add explanation to hack and test HLS

- README.md
Just noticed these were pointing to the old addresses
> Update VS Code Haskell URL/repo

- nix/sources.json
- nix/sources.nix
- shell.nix
https://github.com/haskell/haskell-language-server/issues/325
retrie is no longer appears to be marked broken:
https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/haskell-modules/hackage-packages.nix#L215948
Hello, I was goofing around looking at "good first issues" and stumbled on this TODO in the code when poking around. I noticed a couple of tests failed, but I think that was happening before I did anything. Also, I wasn't sure about commit message / branch naming conventions. I tried mimicking: https://github.com/haskell/haskell-language-server/pull/331
> tech(nix): update niv and remove allowbroken

- src/Ide/Plugin/Eval.hs
- test/functional/Eval.hs
- test/testdata/eval/T10.hs
- test/testdata/eval/T10.hs.expected
- test/testdata/eval/T11.hs
- test/testdata/eval/T11.hs.expected
- test/testdata/eval/T12.hs
- test/testdata/eval/T12.hs.expected
- test/testdata/eval/T13.hs
- test/testdata/eval/T13.hs.expected
- test/testdata/eval/T9.hs
- test/testdata/eval/T9.hs.expected
This pull request implements `:kind` and `:kind!` commands ala GHCi to Eval plugin.
The former displays the kind of a given type and the latter also displays the normalised form of a given type.
```haskell
-- >>> type N = 1
-- >>> type M = 40
-- >>> :kind N + M + 1
```
evaluates to:
```haskell
-- >>> type N = 1
-- >>> type M = 40
-- >>> :kind N + M + 1
-- N + M + 1 :: Nat
```
And
```haskell
-- >>> type N = 1
-- >>> type M = 40
-- >>> :kind! N + M + 1
```
evaluates to:
```haskell
-- >>> type N = 1
-- >>> type M = 40
-- >>> :kind! N + M + 1
-- N + M + 1 :: Nat
-- = 42
```
> Adds `:kind` and `:kind!` commands to Eval Plugin

- src/Ide/Plugin/Retrie.hs
Retrie is very slow and memory hungry on modules with lots of CPP.
For instance, it runs out of memory on Development.IDE.GHC.Compat.
This creates problems when rewriting (particularly folding). As a low key
workaround, this adds new code actions that rewrite only in the current file.
Rewriting on files without a cradle is also very slowbecause it results
in calls to hie-bios that fail after consulting with Cabal. Thus exclude them.
> Add single file rewrites and ignore unknown files

- haskell-language-server.cabal
```
16:18 <maralorn> Should I expect any trouble when building current ghcide (hls-3 branch to be precise) with hie-bios 0.7.0?
16:19 <maralorn> Apparently it does compile without issues.
16:21 <fendor> maralorn, no, the breaking change is in the config type, which neither hls nor ghcide explicltly use
16:21 <fendor> so, everything should just work fine for both these projects
```
I tested. This builds with newest hie-bios for me.
> Bump bounds of hie-bios to 0.7.0

- src/Ide/Plugin/ImportLens.hs
> Fix ImportLens plugin to work with GHC 8.10

- src/Ide/Plugin/Eval.hs
- test/functional/Eval.hs
- test/testdata/eval/T14.hs
- test/testdata/eval/T14.hs.expected
- test/testdata/eval/T15.hs
- test/testdata/eval/T15.hs.expected
- test/testdata/eval/T16.hs
- test/testdata/eval/T16.hs.expected
- test/testdata/eval/T17.hs
- test/testdata/eval/T17.hs.expected
- test/testdata/eval/T18.hs
- test/testdata/eval/T18.hs.expected
- test/testdata/eval/T19.hs
- test/testdata/eval/T19.hs.expected
- test/testdata/eval/T20.hs
- test/testdata/eval/T20.hs.expected
This implements `:type` command ala GHCi.
It also restructures the handling of GHCi-Like command and adds an exception for unknown command.
```haskell
{-# LANGUAGE TypeApplications #-}
foo :: Show a => a -> String
foo = show
-- >>> :type foo @Int
-- foo @Int :: Int -> String
-- >>> :type +v foo @Int
-- foo @Int :: Show Int => Int -> String
-- >>> :type 40 + 2
-- 40 + 2 :: forall a. Num a => a
-- >>> :type +d 40 + 2
-- 40 + 2 :: Integer
-- >>> default (Word)
-- >>> :type +d 40 + 2
-- 40 + 2 :: Word
-- >>> :type +nope 12
-- parse error on input ‘+’
-- >>> :nooope 42
-- unknown command 'nooope'
```
Currently, `:type +d` ignores `default` declarations specified in the module, though it can handle `default`s declared in the same `>>>` prompt group.
I once tried to obtain the module's …
> Implements `:type [+v/+d]` in Eval Plugin

- .github/ISSUE_TEMPLATE.md
The purpose would be to reduce the amount of back and forths we usually ask before we can properly answer a question. 
It might be overkill to ask that much information.
> Add ISSUE_TEMPLATE for github

- ChangeLog.md
- haskell-language-server.cabal
Still needs the editorial part of the ChangeLog
> Initial preparation for 0.4.0 tag

- README.md
Thought that it just not working on Windows yet, but figured that it does only few weeks later. This wasn't obvious for me that -- >>> should be keyed in to make Evaluate widget appear: in gif below it is already there and just above the example function so my selective blindness completely dismissed it.
> README clarify how exactly to use code evaluation

- exe/Main.hs
- src/Ide/Plugin.hs
- src/Ide/Plugin/Brittany.hs
- src/Ide/Plugin/Eval.hs
- src/Ide/Plugin/Example.hs
- src/Ide/Plugin/Example2.hs
- src/Ide/Plugin/Floskell.hs
- src/Ide/Plugin/Formatter.hs
- src/Ide/Plugin/Fourmolu.hs
- src/Ide/Plugin/GhcIde.hs
- src/Ide/Plugin/ImportLens.hs
- src/Ide/Plugin/Ormolu.hs
- src/Ide/Plugin/Pragmas.hs
- src/Ide/Plugin/Retrie.hs
- src/Ide/Types.hs
To improve the ergonomics of HLS plugin development. 
I also picked the -Werror and Open imports PRs
> Rebase on ghcide HEAD

- src/Ide/Plugin/ImportLens.hs
This prevents the lenses from disappearing while editing, which causes lots of unpleasant jumping
> Use stale data in explicit imports lens

- cabal.project
- hls-plugin-api/src/Ide/Plugin/GhcIde.hs
- plugins/default/src/Ide/Plugin/Example.hs
- plugins/default/src/Ide/Plugin/Example2.hs
- plugins/default/src/Ide/Plugin/ImportLens.hs
- plugins/default/src/Ide/Plugin/Retrie.hs
- src/Ide/Main.hs
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack-8.8.4.yaml
- stack.yaml
For https://github.com/haskell/ghcide/pull/784
> bump ghcide submodule

- README.md
* To make clear that important step of the install.hs script
* Closes #401
> Mention the copy of executables wit ghc version

- README.md
> Include .editorconfig in the contributing section

- plugins/default/src/Ide/Plugin/Eval.hs
- test/functional/Eval.hs
- test/testdata/eval/T21.hs
- test/testdata/eval/T21.hs.expected
- test/testdata/eval/T22.hs
- test/testdata/eval/T22.hs.expected
- test/testdata/eval/T23.hs
- test/testdata/eval/T23.hs.expected
- test/testdata/eval/T24.hs
- test/testdata/eval/T24.hs.expected
- test/testdata/eval/T25.hs
- test/testdata/eval/T25.hs.expected
This pull-request consists of two changes to Eval plugin:
1. Bugfix: a proper treatment of multilined results.
Previously, GHCi-like commands in Eval plugin doesn't treat multilined results properly.
For example, with the current Eval plugin we get:
```haskell
f :: forall k n a. (KnownNat k, KnownNat n, Typeable a)
=> Proxy k -> Proxy n -> Proxy a -> ()
f _ _ _ = ()
-- >>> :type f
-- f :: forall k1 (k2 :: Nat) (n :: Nat) (a :: k1).
(KnownNat k2, KnownNat n, Typeable a) =>
Proxy k2 -> Proxy n -> Proxy a -> ()
```
Apparlently, the last two lines must be prefixed with `--`.
This pull request addresses this issue and now it seems that the plugin returns the same result as GHCi:
```haskell
-- >>> :type f
-- f :: forall k1 (k2 :: Nat) (n :: Nat) (a :: k1).
--      (KnownNat k2, KnownNat n, …
```
> Eval plugin: proper multilined results handling and command-name abbreviations

- plugins/default/src/Ide/Plugin/Retrie.hs
This way we don't have to send the imports back and forth on every code action
Fixes #407
> Retrie - calculate imports in the command handler

- README.md
Should reduce some confusion in #425
> Clarify that eval is a lens

- README.md
Update the Emacs set up notes to reflect that latest changes in lsp-haskell. The latest version of lsp-haskell sets the default server to `haskell-language-server-wrapper`. The old variable `lsp-haskell-process-path-hie` is deprecated.
> Upate Emacs setup notes

- hls-plugin-api/hls-plugin-api.cabal
- test/functional/Tactic.hs
* Closes #173
* One step forward for #1
> Use ghcide master and prepare hls-plugin-api-0.4.1.0

- exe/Wrapper.hs
Currently, if `haskell-language-server-wrapper` is called with `--cwd`, a cradle will first be loaded and _then_ the change of working directory will happen. This commit reorders this such that if `--cwd` is supplied, the very first action is to change directory. This means a cradle will be found with `--cwd`, rather than the directory that `haskell-language-server-wrapper` was called in.
> wrapper: cd to --cwd earlier

- install/src/Cabal.hs
- install/src/Stack.hs
This saves quite a bit of diskspace for linux, by using hardlinks to avoid having 3 copies of the main executable on disk.
I guess it should also work for MacOS (that would be `"darwin"`?).
I built this locally and it tested it for a Stack install.
> install: create hls hardlinks instead of copies except on Windows

- .github/workflows/build.yml
- docs/releases.md
> Generate .gz tars of all the binaries for macOS and Linux in GitHub Actions

- README.md
Just something I stumbled over while reading the README.
> Update GHC version 8.12 to 9.0 in README

- stack-8.10.1.yaml
- stack-8.10.2.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack-8.8.4.yaml
- stack.yaml
I just pinned it with extra-deps in all cases.
Alternatively `0.1.3.0` appears in `nightly-2020-09-22` and should appear in `lts-16.16` in a few days. So I could instead bump ghc `8.8.3` and up to use the updated resolvers (and I guess remove other extra deps that no longer need to be pinned)?
> Bump ormolu to 0.1.3.0

- README.md
Given relative feature-parity with HIE and #473 this line is no longer true, I believe.
> Update README: HLS is no longer in *very* early stage

- hie.yaml.cbl
- hie.yaml.stack
- plugins/tactics/src/Ide/Plugin/Tactic/CodeGen.hs
- stack-8.10.2.yaml
- test/functional/Tactic.hs
- test/testdata/tactic/GoldenGADTAuto.hs
- test/testdata/tactic/GoldenGADTAuto.hs.expected
- test/testdata/tactic/GoldenGADTDestruct.hs
- test/testdata/tactic/GoldenGADTDestruct.hs.expected
Consider the following:
```hs
{-# LANGUAGE GADTs #-}
module GoldenGADTDestruct where
data CtxGADT where
MkCtxGADT :: (Show a, Eq a) => a -> CtxGADT
ctxGADT :: CtxGADT -> String
ctxGADT gadt = _decons
```
If we select `case split on gadt` at `_decons`, the Tactic Plugin in HEAD introduces instance dictionary in data constructor:
```hs
{-# LANGUAGE GADTs #-}
module T4 where
data CtxGADT where
MkCtxGADT :: (Show a, Eq a) => a -> CtxGADT
ctxGADT :: CtxGADT -> Bool
ctxGADT gadt = (case gadt of { (MkCtxGADT sa ea a) -> _ })
```
As it stands, generated pattern includes dictionary argumetns, which must not (cannot) appear in the source language.
This behaviour is due to the call to the `dataConInstArgTys`, which also includes dictionary argument.
This pull-request changes to use …
> Tactic plugin: Excludes Dictionary arguments in GADTs in Destruct Tactic

- README.md
Follow up to #440, as doom has now updated the relevant packages.
> Update doom emacs install instructions in README

- README.md
Make them instructions a little more detailed and consistent, add a
section on spacemacs.
> Improve the emacs instructions a little

- cabal.project
- haskell-language-server.cabal
- stack-8.10.1.yaml
- stack-8.10.2.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack-8.8.4.yaml
- stack.yaml
`stylish-haskell-0.12` uses `ghc-lib-parser` instead of `haskell-src-exts`, so it should be more reliable.
Surprisingly, this update did not require any changes in the code.
CC @jaspervdj.
> Bump stylish-haskell to 0.12.2.0

- ChangeLog.md
- haskell-language-server.cabal
Originally tried to just push to master but got a slap on the wrist when the remote rejected me. Probably a good thing master is now a protected branch!
> Prepare 0.5.1

- .editorconfig
indent_style = space 
makes it impossible to write Makefiles
> Restrict editor config to Haskell file, to avoid affecting Makefiles or other tab-based formats

- stack-8.8.3.yaml
Bump the lts version to resolve an issue with these-1.1.1
these-1.1.1 fails to build on some machine due to a bug in gcc. This
was worked around in these-1.1.1.1
> Fix stack build for ghc-8.8.3 failing on some machines

- README.md
This topic tends to confuse people, which is unsurprising since there
are several parts which can in principle be configured separately. I've
tried to explain this a bit better.
I also tried to give some brief documentation on the language server
settings that we provide. In the process I found that a few of them seem
to be currently unused, so I'm not sure what to say about them.
> Expand explanation of how to configure HLS

- .github/workflows/build.yml
- .github/workflows/test.yml
- cabal.project
- test/functional/Command.hs
- test/functional/Completion.hs
- test/functional/Deferred.hs
- test/functional/Definition.hs
- test/functional/Diagnostic.hs
- test/functional/Eval.hs
- test/functional/Format.hs
- test/functional/FunctionalBadProject.hs
- test/functional/FunctionalCodeAction.hs
- test/functional/FunctionalLiquid.hs
- test/functional/HieBios.hs
- test/functional/Highlight.hs
- test/functional/ModuleName.hs
- test/functional/Progress.hs
- test/functional/Reference.hs
- test/functional/Rename.hs
- test/functional/Symbol.hs
- test/functional/Tactic.hs
- test/functional/TypeDefinition.hs
- test/utils/Test/Hls/Util.hs
- test/wrapper/Main.hs
Following the discussion in #6 , it looks like we should probably move away from CircleCI at some point. This adds GitHub Actions CI workflows, reusing the infrastructure we already have for the static binaries. It should run the tests on linux, macOS and windows now.
> Add GitHub Actions CI for testing

- plugins/tactics/src/Ide/Plugin/Tactic/CodeGen.hs
- test/functional/Tactic.hs
- test/testdata/tactic/GoldenFoldr.hs.expected
- test/testdata/tactic/GoldenListFmap.hs.expected
- test/testdata/tactic/GoldenPureList.hs.expected
- test/testdata/tactic/GoldenSwap.hs.expected
- test/testdata/tactic/GoldenSwapMany.hs
- test/testdata/tactic/GoldenSwapMany.hs.expected
The tactics plugin is a bit stupid when working with infix-defined datacons, both in expressions and patterns. For example it will produce `(,) a b` and `(:) a as` rather than the more natural `(a, b)` and `a : as`. This PR makes it do the right thing.
The solution is to inspect the data con when building an expression or pattern. Unfortunately tuples are extra special in GHC, so this introduces a special case for tuples, and another for everyday infix things (like list).
There's a bit of annoying fiddling in order to build the infix pattern. The logic is in `infixifyPatIfNecessary`, which is the only thing I'm not super comfortable with in the diff.
Fixes #468
> Use infix notation for destructing and splitting infix data cons

- .circleci/config.yml
- hie.yaml.stack
- plugins/tactics/hls-tactics-plugin.cabal
- plugins/tactics/src/Ide/Plugin/Tactic.hs
- plugins/tactics/src/Ide/Plugin/Tactic/Debug.hs
- plugins/tactics/src/Ide/Plugin/Tactic/Machinery.hs
- plugins/tactics/src/Ide/Plugin/Tactic/Tactics.hs
- plugins/tactics/src/Ide/Plugin/Tactic/Types.hs
- plugins/tactics/test/AutoTupleSpec.hs
- plugins/tactics/test/Main.hs
- test/functional/Tactic.hs
- test/testdata/tactic/GoldenBigTuple.hs
- test/testdata/tactic/GoldenBigTuple.hs.expected
The `auto` tactic attempts to prune unhelpful branches in order to avoid an exponential blowup of search space. On one these optimizations is to not build a data constructor if it doesn't result in new types to solve. For example, we're trying to avoid the following pathological example:
```haskell
data Tree a = Leaf a | Branch (Tree a) (Tree a)
-- given the following hole:
pureTree :: a -> Tree a
pureTree a = _
-- we DO NOT want to fill it with
pureTree a = Branch _ _
```
The reasoning here is that both goals in `Branch _ _` have type `Tree a`, which is already the type we're trying to solve, so introducing `Branch` doesn't make any progress.
This check is performed in the `splitAuto` tactic, but I got it backwards and it wasn't explicitly tested for. The only code which hit it was `pure …
> Fix a bug in tactics preventing split of split

- test/functional/Tactic.hs
This appears to be the fix for the flaky tactics fixes, and should unblock #521 and #166. Thanks to @jneira for all of his hard work in tracking it down.
> Wait for diagnostics in tactics tests

- cabal.project
- stack-8.10.1.yaml
- stack-8.10.2.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack-8.8.4.yaml
> Use implicit-hie-0.1.2.0

- stack.yaml
* It is not being built in ci (cause it is identical to `stack-8.6.5.yaml`) :thinking:
> Add missing tactic subpackage in default stack.yaml

- plugins/tactics/hls-tactics-plugin.cabal
- plugins/tactics/src/Ide/Plugin/Tactic.hs
- plugins/tactics/src/Ide/Plugin/Tactic/CodeGen.hs
- plugins/tactics/src/Ide/Plugin/Tactic/Context.hs
- plugins/tactics/src/Ide/Plugin/Tactic/GHC.hs
- plugins/tactics/src/Ide/Plugin/Tactic/Judgements.hs
- plugins/tactics/src/Ide/Plugin/Tactic/Machinery.hs
- plugins/tactics/src/Ide/Plugin/Tactic/Tactics.hs
- plugins/tactics/src/Ide/Plugin/Tactic/Types.hs
- plugins/tactics/test/AutoTupleSpec.hs
- plugins/tactics/test/UnificationSpec.hs
- test/functional/Tactic.hs
- test/testdata/tactic/GoldenApplicativeThen.hs
- test/testdata/tactic/GoldenApplicativeThen.hs.expected
- test/testdata/tactic/GoldenShow.hs
- test/testdata/tactic/GoldenShow.hs.expected
- test/testdata/tactic/GoldenShowCompose.hs
- test/testdata/tactic/GoldenShowCompose.hs.expected
- test/testdata/tactic/GoldenShowMapChar.hs
- test/testdata/tactic/GoldenShowMapChar.hs.expected
- test/testdata/tactic/GoldenSuperclass.hs
- test/testdata/tactic/GoldenSuperclass.hs.expected
This PR allows tactics to use methods from given constraints, meaning it can solve holes like this:
```haskell
showMe :: Show a => a -> String
showMe = _
```
It will not, however, discover instances. So this one *won't* solve:
```haskell
showMe :: Int -> String
showMe = _
```
There's quite a lot of finicky details going on in order to support this. The primary challenge is that our types are running after the typechecker has finished, meaning it's already solved the constraints and inlined their evidence. Our solution is to look up the written polymorphic type and unify it with the final, typechecked type. We can use the polymorphic type to find the theta context, and instantiate every class method in the theta.
In addition, this PR fixes a subtle bug in our unification code, which could …
> Tactics support for using given constraints

- test/functional/Tactic.hs
Due to an oversight in how we handle polymorphic class methods (fixed in #537), having an applicative context introduces `(*>)` into scope, which causes an exponential explosion in the search space. On fast machines it seems like we can get through this test before the timeout, but on CI it's flakey.
> Ignore flakey tactics test

- plugins/tactics/src/Ide/Plugin/Tactic/CodeGen.hs
- plugins/tactics/src/Ide/Plugin/Tactic/Judgements.hs
- plugins/tactics/src/Ide/Plugin/Tactic/Machinery.hs
- plugins/tactics/src/Ide/Plugin/Tactic/Tactics.hs
- plugins/tactics/src/Ide/Plugin/Tactic/Types.hs
- test/functional/Tactic.hs
- test/testdata/tactic/GoldenSafeHead.hs
- test/testdata/tactic/GoldenSafeHead.hs.expected
This PR tweaks the scoring metric to heavily penalize not using top-level function arguments when defining functions. Presumably if they were added to the type sig, someone had intention behind it. Note that this doesn't prevent us from deriving `const`, since we have no better alternatives in that case.
Furthermore, this fixes a bug where recursive calls were added to the `jLocalHypothesis` rather than `jAmbientHypothesis`. The former is for locally introduced variables, for which usage is rewarded. The result was that we were accidentally rewarding recursive calls! Instead we'd like to penalize them, so this PR adds a field which counts recursive calls and penalizes them.
Fixes #539
> Better scoring metric for deriving safeHead

- plugins/tactics/src/Ide/Plugin/Tactic/Auto.hs
- plugins/tactics/src/Ide/Plugin/Tactic/Context.hs
- plugins/tactics/src/Ide/Plugin/Tactic/Machinery.hs
- test/functional/Tactic.hs
- test/testdata/tactic/GoldenFish.hs
The tactics plugin was only discovering skolem types present in the hole, rather than anywhere in the hypothesis. #541 gives the following repro:
```haskell
foo :: Monad m => (a -> m b) -> (b -> m c) -> (a -> m c)
foo f g a = _
```
here, the hole has type `_ :: m c`, which means tactics doesn't realize `a` and `b` are skolems, and instead treats them as unifiable variables. Thus the insane solution of `f a`.
Fixes #541
> Discover skolems in the hypothesis, not just goal

- .circleci/config.yml
- cabal.project
- plugins/default/src/Ide/Plugin/Eval.hs
- plugins/default/src/Ide/Plugin/ImportLens.hs
- plugins/default/src/Ide/Plugin/Retrie.hs
- plugins/tactics/src/Ide/Plugin/Tactic.hs
- stack-8.10.1.yaml
- stack-8.10.2.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack-8.8.4.yaml
- stack.yaml
* ghcide at d76fbf9
* minor changes needed in retrie, tactics and import plugins
* closes #526
> Use ghcide master head (d76fbf9)

- .circleci/config.yml
- .github/workflows/test.yml
- stack.yaml
* Fix `stack.yaml` extra-deps
* Add default `stack.yaml` to circleci, to prevent more breakages
* Fix `tasty --rerun` separating `func-test` from `wrapper-test`
* `wrapper-test` is the last suite and it was updating `.tasty-rerun-log`, marking it as all green, so the next execution was executing all tests again always
> Fix tasty rerun 

- plugins/default/src/Ide/Plugin/Eval.hs
- plugins/default/src/Ide/Plugin/Retrie.hs
- plugins/tactics/src/Ide/Plugin/Tactic.hs
- plugins/tactics/src/Ide/Plugin/Tactic/Types.hs
* To get support for CPP/LHS preprocessing in the Eval plugin.
> Bump up ghcide submodule to version 0.5.0

- ChangeLog.md
- cabal.project
- haskell-language-server.cabal
* i want to add screenshots for hlint and module plugins
> Prepare 0.6 release

- .github/workflows/build.yml
See https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
> Replace deprecated set-env with temporary files

- README.md
Is my understanding correct, that with the latest release of `v0.6.0` and https://github.com/haskell/haskell-language-server/pull/166 hlint is again supported? Then it makes sense to delete this.
I'm currently not seeing any hlint diagnostics, but that's likely content for a new issue. Is it ghc 8.10+ only?
> README: hlint is supported

- cabal.project
- stack-8.10.1.yaml
- stack-8.10.2.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack-8.8.4.yaml
- stack.yaml
> # Changelog for implicit-hie-cradle
> 
> ## 0.3.0.0
> Match `implicit-hie`'s cradle type ordering.
> This is technically a breaking change.
> Update implicit-hie & ghcide

- .github/ISSUE_TEMPLATE.md
Filling it out was tedious because one had to replace the instructions rather than simply adding.
> Use comments & simplify issue template

- hls-plugin-api/src/Ide/Plugin/Formatter.hs
I have tested this error message with cabal. By setting `haskell-language-server/haskell-language-server.cabal`:
```
flag agpl
description: Enable AGPL dependencies
default:     True
manual:      True
```
to 
```
flag agpl
description: Enable AGPL dependencies
default:     False
manual:      True
```
using `cabal build exe:haskell-language-server`
And after setting my editor to use `cabal exec which haskell-language-server` and the Brittany formatter. I can see the error message show up correctly.
I thought about adding a test to `haskell-language-server/test/functional/Format.hs` for when `AGPL` is false, but wasn't sure if it would ever be run. Do CI tests with this flag on or off?
Please let me know if style should be changed or if the error message is too verbose.
> Improve missing brittany format provider error message (#269)

- plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
This restores the hlint formatting from haskell-ide-engine
Closes #553
What it looks like now (in emacs)
> Hlint: bring over idea2Message for formatting

- .github/workflows/test.yml
As chocolatey applies the workaround: https://gitlab.haskell.org/ghc/ghc/-/issues/18550#note_309996
> Enable ghc-8.10.2 for windows

- .github/workflows/build.yml
- .github/workflows/test.yml
* [leveraging @mistuke work in chocolatey](https://github.com/Mistuke/GhcChoco/issues/10#issuecomment-727654070) (thanks again)
* follow up of #617 
* testing build in my repo: https://github.com/jneira/haskell-language-server/actions/runs/380677453
* it lets us to not have to build locally this version #276
> Add build to ghc-8.10.2 and windows

- stack-8.10.1.yaml
- stack-8.10.2.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack-8.8.4.yaml
- stack.yaml
- For 8.8.4 + 8.10.2 I just bumped to latest resolvers which include ormolu 0.1.4.1
- For 8.6.* I had to also pin `Diff` to `0.4.0`.
> Bump ormolu to 0.1.4.1

- plugins/default/src/Ide/Plugin/Fourmolu.hs
~~**The Problem**: fourmolu plugin sets its indentation size from the editor (inferred from source file tab size or EditorConfig) when no `fourmolu.yaml` found. In other words: different formatting results between the plugin and the cli.~~
~~This little fix will prevent fourmolu from getting the editor's `tabSize`.~~
~~Hopefully, it will solve the problem.~~
**EDIT**:
> > And when I test it with fourmolu.yaml, it prioritizes the editor's indentation level over the config file even without EditorConfig.
>
> Ah, that is the wrong way round. Should be a one line fix.
It fixes fourmolu plugin's use of FormattingOptions.
> Fix fourmolu plugin inconsistent formatting

- plugins/tactics/hls-tactics-plugin.cabal
`cabal build all` was failing for me.
```
Preprocessing test suite 'tests' for hls-tactics-plugin-0.5.1.0..
Building test suite 'tests' for hls-tactics-plugin-0.5.1.0..
ghc: could not execute: hspec-discover
cabal: Failed to build test:tests from hls-tactics-plugin-0.5.1.0.
```
Adding `hspec-discover` to the `build-tool-depends` fixes this.
> Add hspec-discover to build-tool-depends in tactics plugin

- README.md
I noticed browsing the GHCIDE code would blow things up spectacularly, and by looking at the LSP error buffer, I noticed it tried to build using Cabal :sweat_smile:
> Add Ghcide hie.yaml instruction for Stack users

- plugins/default/src/Ide/Plugin/ModuleName.hs
- test/functional/ModuleName.hs
- test/testdata/moduleName/hie.yaml
- test/testdata/moduleName/mainlike.hs.expected
Currently, module name plugin treats basename of file as module name.
This inferes, for example, the module name of `app/exe01.hs` as `exe01`, contrary to the expectation that they must be `Main`.
This pull-requests addresses this issue by defaulting to `Main` when the file name is starting with non-upper cases.
Perhaps, the logic itself can be refined so that it infers it `Main` only when the lowercased file is located right after the source-dirs?
> Module Name Plugin: Treat modules starting with lowercase as Main module

- .circleci/config.yml
- .github/workflows/nix.yml
- README.md
- nix/default.nix
- nix/sources.json
- shell.nix
* Switch to the haskell-updates branch, so that we get Stackage nightly packages
* Remove the hard-coded list of packages, let cabal2nix find out
* A Github Action to exercise the Nix script and warm up a Cachix cache
> Upgrade the Nix build system

- hls-plugin-api/src/Ide/Plugin.hs
- test/functional/FunctionalCodeAction.hs
- test/testdata/addPragmas/hie.yaml
- test/testdata/hie.yaml
- test/testdata/redundantImportTest/hie.yaml
- test/utils/Test/Hls/Util.hs
Enable and fix most of the tests in test/functional/FunctionalCodeAction.hs.
Fix the fallback handler for code action literals. It was stubbed out, so the tests that disabled code action literal support were all failing.
HLS has no support right now for adding dependencies to the the cabal file, which means there can be no "Add <module> as a dependency" code action, and the related tests are still disabled (but with a better message than just "Broken").
In #611, OP reports that the test "falls back to pre 3.8 code actions" is flaky. Even on master, this test is passing consistently on my end, so I'm not sure ... but I think I know what's causing the flakiness and I think I fixed it. In that test, the client sends an executeCommand request; the client waits for an applyEdit request; the …
> Fix and enable disabled code action unit tests, fix fallback handler

- plugins/hls-explicit-imports-plugin/hls-explicit-imports-plugin.cabal
- plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
I can't install HLS master successfully, and this is my log: https://paste.ubuntu.com/p/Gf2gnjPhJc/ (I am using dynamic linked haskell packages on Arch Linux)
I noticed that we didn't write the header file to the sdist of the plugin. Is this necessary? I'm not sure, but after adding `extra-source-files` to the package description, I could install HLS without error.
> Add extra-source-files for split plugins

- plugins/default/src/Ide/Plugin/ModuleName.hs
This should fix #564
The operation to perform is recalculated before being applied.
>  idempotent command and code cleanup

- test/functional/FunctionalCodeAction.hs
- test/testdata/testdata.cabal
The other copy of this clause is a few lines above the one I deleted.
> Delete duplicate cabal clause for applyrefact2

- test/functional/Symbol.hs
- test/testdata/hie.yaml
Actually I had to leave several of these tests disabled because it seems HLS can't extract as many symbols as HIE could. But the disabled tests are at least documented more clearly now.
> Fix document symbols unit tests.

- haskell-language-server.cabal
- test/functional/Completion.hs
- test/functional/FunctionalCodeAction.hs
- test/testdata/completion/hie.yaml
- test/utils/Test/Hls/Util.hs
Fix and enable the unit tests for code completion.
My understanding is that we use the request textDocument/completion to get code completions at a point, and the request completionItem/resolve to get more details about a particular suggested completion. E.g. we might ask "Complete 'Pub_'." and get "['Publish', 'Public']" and then ask "resolve 'Publish'" and get "'Publish' is a method defined in ...". Right now, there is no support for the resolve request, so the relevant tests are disabled.
"Pub_" |-> "Publish" is a plain text completion, but there is a more sophisticated kind of completion called a snippet that does things like "Pub_" |-> "Publish ${something special}". There's code for handling snippets, but its disabled in ghcide. The relevant tests are disabled as well.
The diff is …
> Enable code completion tests

- test/functional/Highlight.hs
- test/testdata/hie.yaml
Well, the one highlight unit test.
This PR has a commit in common with #657 . This shared commit moves some utility functions. Leave comments wherever is convenient. Merging both PRs will not produce a merge conflict, nor will it duplicate the commit.
> Enable highlight unittests

- plugins/default/src/Ide/Plugin/Pragmas.hs
- stack.yaml
This PR adds the completions of language pragmas to the `Pragmas` plugin.  Once this change is accepted, the completion code [here](https://github.com/haskell/ghcide/blob/baafe2cb82215f992ded3e3c1bd03507553aae86/src/Development/IDE/Plugin/Completions/Logic.hs#L564-L565) can be removed.
Also, starts addressing https://github.com/haskell/ghcide/issues/936
> Add pragmas completions

- hie.yaml.stack
I am submitting this hoping that someone more knowledgable than me will have a long look at it.
Changes:
- fixed some incorrect component name (e.g. hls-hlint-plugin:lib:hls-hlint-plugin)
- added entries for recently added plugins
- ordered components alphabetically
- all targets reported by 'stack ide targets' are now covered, except for:
ghcide:exe:ghcide-bench
ghcide:exe:ghcide-test-preprocessor
ghcide:test:ghcide-tests
ghcide:bench:benchHist
hie-compat:lib
Doubts/Notes:
* Coverage is not comprehensive, haskell-language-server still returns a lot of 'Files that failed"
* What is this for?
- path: "./.stack-work/"
component: "haskell-language-server:lib"
* What is this for?
- path: "./exe/Arguments.hs"
component: "haskell-language-server:exe:haskell-language-server"
as …
> fixed hie.yaml.stack

- plugins/default/src/Ide/Plugin/Eval.hs
- plugins/default/src/Ide/Plugin/ModuleName.hs
- plugins/tactics/src/Ide/Plugin/Tactic/CodeGen.hs
- plugins/tactics/src/Ide/Plugin/Tactic/Judgements.hs
- plugins/tactics/src/Ide/Plugin/Tactic/Tactics.hs
Few minor simplifications I randomly stumbled upon when reading the code.
> Remove unnecessary pluginId setting and user Better Map functions in tactics plugin

- plugins/default/src/Ide/Plugin/Pragmas.hs
> Do not suggest explicitly disabled pragmas

- ChangeLog.md
- cabal.project
- exe/Wrapper.hs
- haskell-language-server.cabal
- hls-plugin-api/hls-plugin-api.cabal
- nix/default.nix
- shell.nix
- src/Ide/Main.hs
- stack-8.10.1.yaml
- stack-8.10.2.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack-8.8.4.yaml
- stack.yaml
- test/functional/Completion.hs
- test/functional/FunctionalCodeAction.hs
- test/testdata/Format.brittany.formatted.hs
- test/testdata/Format.brittany_post_floskell.formatted.hs
- test/testdata/Format.floskell.formatted.hs
- test/testdata/Highlight.hs
- test/testdata/completion/Completion.hs
- test/testdata/completion/Context.hs
- test/testdata/redundantImportTest/src/CodeActionRedundant.hs
- test/testdata/redundantImportTest/src/MultipleImports.hs
* This will not be the final commit ([ghcide has to be released yet](https://github.com/haskell/ghcide/pull/940)) but let's see what has to say ci.
> Prepare 0.7.0 release (includes bump ghcide to 0.6.0.1)

- README.md
Generation of hoogle data files is disabled for now. Therefore the instruction to execute 'data' target is removed.
> README: Remove instructions to execute data target

- haskell-language-server.cabal
- test/functional/FunctionalCodeAction.hs
- test/testdata/hlint/ApplyRefact1.hs
- test/testdata/hlint/ApplyRefact3.hs
- test/testdata/hlint/ApplyRefact4.hs
- test/testdata/hlint/ApplyRefact5.hs
- test/testdata/hlint/cpp/ApplyRefact2.hs
- test/testdata/hlint/cpp/ApplyRefact3.hs
- test/testdata/hlint/cpp/hie.yaml
- test/testdata/hlint/cpp/test.h
- test/testdata/hlint/hie.yaml
- test/testdata/hlint/ignore/.hlint.yaml
- test/testdata/hlint/ignore/ApplyRefact.hs
- test/testdata/hlint/ignore/hie.yaml
- test/testdata/hlint/lambdacase/ApplyRefact1.hs
- test/testdata/hlint/lambdacase/hie.yaml
- test/utils/Test/Hls/Util.hs
* As a previous step to #635, to compare behaviour with master and let clear what will be fixed (or broken)
> Add hlint tests over cpp, extensions and ignore hints 

- .github/workflows/build.yml
- ChangeLog.md
- haskell-language-server.cabal
* To include #677 that fixes #676
> Prepare 0.7.1

- exe/Main.hs
- exe/Plugins.hs
- haskell-language-server.cabal
- To make progress towards #164
- It uses cabal flags and cpp conditions to let users install the project with a specific plugin set
To assemble the desired hls version you could do:
- `cabal install`: all plugins and formatters by default like the actual behaviour
- `cabal install -f-all-plugins -f-all-formatters`: only ghcide plugin (it is fixed)
- `cabal install -f-all-formatters -f+floskell`: all non formatting plugins and only floskell as formatter
- `cabal install -f-all-plugins -f-all-formatters -f+hlint -f+fourmolu`: only ghcide (fixed) and hlint plugins and fourmolu as formatter
The plan would be change the install script to take in account plugins and:
* let user list the concrete list of plugins
* prepare some predefined plugins sets and set the appropiate cabal flags …
> Add plugins conditionally at compile time

- .github/workflows/build.yml
* I tried to fix it with d44743 but i did not test it and didnt work
* This one fixes it, tested in this release: https://github.com/jneira/haskell-language-server/releases/tag/0.7.1.test
> Fix ghc version for windows 8.10.2.2 in github build workflow

- CONTRIBUTING.md
- haskell-language-server.cabal
- hls-plugin-api/src/Ide/Plugin.hs
- hls-plugin-api/src/Ide/Plugin/Config.hs
- plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
- test/functional/Config.hs
- test/functional/FunctionalCodeAction.hs
- test/functional/Main.hs
Make it possible to provide config for a plugin in a regular way, by
using a namespace in the json config space. So we have
```
haskell.plugin.hlint.globalOn
haskell.plugin.importLens.globalOn
```
It is also possible to have finer-grain config, so the individual
parts of a plugin can also be separately enabled/disabled.
Closes #513
> Introduce generic config for plugins

- plugins/tactics/hls-tactics-plugin.cabal
- plugins/tactics/src/Ide/Plugin/Tactic/CodeGen.hs
- plugins/tactics/src/Ide/Plugin/Tactic/KnownStrategies.hs
- plugins/tactics/src/Ide/Plugin/Tactic/KnownStrategies/QuickCheck.hs
- test/functional/Tactic.hs
- test/testdata/tactic/GoldenArbitrary.hs
- test/testdata/tactic/GoldenArbitrary.hs.expected
Christmas comes early for QuickCheck users! This PR adds support for generating `arbitrary` --- including the tricky business of ensuring termination. It can be run by calling `Attempt to fill hole` on anything of the form `arbitrary :: Gen A` for some type `A`.
> Add a known tactic for writing arbitrary instances

- test/functional/Progress.hs
Liquid Haskell is gone, delete the related code. Test the progress messages from
some of our other plugins. Help HLS load the testfiles for the warnings are
warnings test.
> Fix and enable progress message tests.

- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/test/exe/Main.hs
- ghcide/test/src/Development/IDE/Test.hs
> Retry a failed cradle if the cradle descriptor changes

- ChangeLog.md
- ghcide/CHANGELOG.md
* I've changed the formatting, to fix markdownlint warnings
> Prepare 0.8.0 release

- .github/workflows/bench.yml
- .github/workflows/nix.yml
- .github/workflows/test.yml
The previous attempt didn't work, so here we go again
> Auto cancel redundant workflows (attempt #2)

- .github/workflows/build.yml
- ChangeLog.md
- cabal.project
- ghcide/CHANGELOG.md
- ghcide/ghcide.cabal
- haskell-language-server.cabal
- hls-plugin-api/hls-plugin-api.cabal
* This pr include version bumps for all components (hls itself, hls-plugin-api and ghcide)
* A hackage index update
* Also a fix to macos builds
* And a mention to lib versions and ghcide-0.6.0.2 changelog
Follow up of #1149
> Prepare 0.8.0 (versions)

- .circleci/config.yml
Now that we have mostly streamlined the GitHub Actions (Windows cache still not working) the CircleCI jobs have become the bottleneck. 
Changes:
- Drop Cabal job (redundant)
- Drop ghc-default job (what is ghc-default?)
- Drop tests (already covered)
I have also enabled "auto cancel redundant builds" in the Project settings, which should help immensely.
> Streamline CircleCI jobs

- install/src/HlsInstall.hs
Now that ghcide has been merged into hls repo and there are no submodules to speak of, this command seems redundant.
> Remove no longer needed git submodule update

- hie-cabal.yaml
```
Failed to parse result of calling cabal
cabal: Unknown target 'hls-splice-plugin:lib'.
The package hls-splice-plugin has no component 'lib'.
```
IIRC,  the prefix `lib:` can be left out in this case, but in order to keep the consistency with other components, I keep it.
> Fix wrong component name of splice plugin in hie.yaml

- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Parse/Token.hs
> Quick fix for #1158

- plugins/hls-class-plugin/src/Ide/Plugin/Class.hs
- test/functional/Class.hs
- test/testdata/class/T4.expected.hs
- test/testdata/class/T4.hs
The previous version wraps a method starting with `_` wrongly with parentheses.
> Fix toMethodName bug of the Class plugin

- haskell-language-server.cabal
- plugins/hls-class-plugin/hls-class-plugin.cabal
- plugins/hls-eval-plugin/hls-eval-plugin.cabal
- plugins/hls-explicit-imports-plugin/hls-explicit-imports-plugin.cabal
- plugins/hls-haddock-comments-plugin/hls-haddock-comments-plugin.cabal
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
- plugins/hls-splice-plugin/hls-splice-plugin.cabal
Fixes #1175 
Backport branch: https://github.com/haskell/haskell-language-server/tree/0.8.0-hackage
Tested: 
```
[nix-shell:/tmp]$ tar xzf ~/scratch/ide/dist-newstyle/sdist/haskell-language-server-0.8.0.0.tar.gz 
[nix-shell:/tmp]$ cd haskell-language-server-0.8.0.0/
[nix-shell:/tmp/haskell-language-server-0.8.0.0]$ cabal configure && cabal build
Resolving dependencies...
Build profile: -w ghc-8.10.2 -O1
In order, the following would be built (use -v for more details):
- brittany-0.13.1.0 (exe:brittany) (requires build)
- fourmolu-0.3.0.0 (exe:fourmolu) (requires build)
- ghcide-0.7.0.0 (exe:ghcide-test-preprocessor) (requires build)
- ghcide-0.7.0.0 (exe:ghcide) (requires build)
- haskell-language-server-0.8.0.0 (lib) (first run)
- ghcide-0.7.0.0 (exe:ghcide-bench) (requires build)
- …
```
> Prepare for Hackage

- plugins/default/src/Ide/Plugin/Pragmas.hs
- test/functional/FunctionalCodeAction.hs
- test/testdata/addPragmas/NeedsPragmas.hs
- test/testdata/addPragmas/TypeApplications.hs
- test/testdata/addPragmas/hie.yaml
- test/testdata/addPragmas/test.cabal
Only errors produced by the type checker were checked for mentions of a pragma
that could be enabled. Many parse errors suggest enabling a pragma:
* `@` -> `TypeApplications`
* `forall` -> `RankNTypes`. Although `ScopedTypeVariables` would be a better
suggestion, IMO.
* ...
Generate suggestions for these too.
> Suggest adding pragmas for parse errors too

- hls-exactprint-utils/LICENSE
- hls-exactprint-utils/hls-exactprint-utils.cabal
Metadata and License related changes, required to upload `hls-exactprint-utils `to Hackage, which is needed by `hls-tactics-plugin` and `hls-splice-plugin`.
> Preparation for uploading `hls-exactprint-utils`

- ghcide/src/Development/IDE/GHC/Compat.hs
- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/test/exe/Main.hs
Fixes https://github.com/haskell/haskell-language-server/issues/1164
> Make adding missing constraint work in presence of 'forall' (fixes #1164)

- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
Maybe we should update the `author` field (and others)
//cc @alanz @ndmitchell
> Complete hls-hlint-plugin package metadata

- README.md
> Installation from Hackage - add README section

- .github/workflows/test.yml
- ghcide/bench/config.yaml
- ghcide/bench/exe/Main.hs
- ghcide/bench/hist/Main.hs
- ghcide/bench/lib/Experiments.hs
- ghcide/bench/lib/Experiments/Types.hs
- shake-bench/src/Development/Benchmark/Rules.hs
Couple of changes:
- Fix an issue with allocation stats, moving all the logic to the `shake-bench` package
- Support examples with multiple files of interest
- Extend the 2 examples we have with an additional file of interest 
- add two new experiments: 
- "getCompletions": to measure the performance of completions alone
- "getDefinition after edit": to measure the performance of getDefinition when stale
> Benchmark improvements

- plugins/hls-haddock-comments-plugin/hls-haddock-comments-plugin.cabal
Uploaded hls-haddock-comments plugin, with some metadata changes.
> Update package description of haddock comments plugin

- ghcide/src/Development/IDE/LSP/Outline.hs
Module outline is not a good fit for useWithStaleFast, changing branches should not break document outlines permanently (until edited again).
The problem here is that there is no way for the user to refresh the module outline, unlike completions, hovers, etc.
> Switch module outline to useWtihStale

- ghcide/ghcide.cabal
- haskell-language-server.cabal
Parallel GC is a win in my machine (16 cores) as well as in the Github workers: https://github.com/pepeiborra/ide/actions/runs/475393491
Total time is up to 15% shorter, depending on the amount of allocations:
```
example             version    name                         success   samples   startup              setup                   userTime              delayedTime             totalTime             maxResidency   allocatedBytes
Cabal-3.0.0.0       upstream   edit                         True      100       10.606544538000001   0.0                     40.510003497          5.165696400000001e-2    40.575701216000006    2MB            402MB
Cabal-3.0.0.0       HEAD       edit                         True      100       10.203424828000001   0.0                     36.683176274999994 …
```
> Do not disable parallel GC

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/Core/Tracing.hs
- ghcide/src/Development/IDE/Types/Shake.hs
- ghcide/test/exe/Main.hs
In haskell/ghcide#959 I tried to fix a problem with diagnostics:
- PROBLEM: when early cut-off kicks in and a stage is skipped (e.g. `TypeCheck`) its diagnostics are lost
- SOLUTION: when creating diagnostics for a new version of a document, start from the diagnostics for the previous version.
The assumption in the solution is that starting with the previous diagnostics is sound because they will get updated incrementally as the rules are re-run. If a rule is not re-run then it must have been cut-off and its diagnostics are still valid.
But hold on, the "build" graph is dynamic, so the rules to be run for a file can change at any time! So it's not always the case that if a rule is not re-run, its diagnostics are still valid. For instance, the graph for a non-FOI changes when it becomes a …
> Fix sticky diagnostics

- .github/workflows/nix.yml
- nix/default.nix
- nix/sources.json
This also updates the all-hackage snapshot to include hiedb, required for #704
> Update nixpkgs to ghc 8.10.3

- .github/mergify.yml
The mergify config is not completely updated and is required to remove them to unblock
https://github.com/haskell/haskell-language-server/pull/1173
> Remove runs dropped by #1173

- .github/mergify.yml
- .github/workflows/test.yml
- cabal.project
- ghcide/ghcide.cabal
- haskell-language-server.cabal
* With this configuration, even including macOS builds, the full test workflow takes 47 minutes (https://github.com/jneira/haskell-language-server/actions/runs/471611988). Now it takes 1h 27m 24s (https://github.com/haskell/haskell-language-server/actions/runs/471363372)
* Testing macOs builds takes only 58 min: https://github.com/jneira/haskell-language-server/actions/runs/471344446 so maybe we could add them
* I've dropped optional restore keys cause the builds were hitting other incompatible cache, so it was rebuilding everything in every run cause the final store was not being saved. 😟
> Test only last ghc minor version and fix windows cache

- README.md
- ghcide/src/Development/IDE/Plugin/Completions.hs
- test/functional/Completion.hs
As discussed in #680 `haskell.completionSnippetsOn` is unused, but this flag should be honored.
This PR fixes this problem.
> Use completionSnippetsOn flag

- .github/mergify.yml
- .github/workflows/test.yml
* As it continues being unreliable (taking more than 1h30m to finish): https://github.com/haskell/haskell-language-server/pull/635/checks?check_run_id=1686429279
* ~~We have to remove them from github settings check~~removed
> Disable win 8.6.4 job

- hie-cabal.yaml
- hie-stack.yaml
- plugins/hls-eval-plugin/hls-eval-plugin.cabal
Add an entry for hls-eval-plugin/test/Eval.hs in hie-[stack|cabal].yaml
> Minor eval plugin fixes

- plugins/hls-retrie-plugin/src/Ide/Plugin/Retrie.hs
`NormalizedUriJSON` was wrapping a `NormalizedUri` to add JSON encoding/decoding capabilities. This was a bad idea because `NormalizedUri` embeds a hash, which was not decoding cleanly. This was making some Retrie commands fail.
The Retrie plugin needs a test suite, but I don't want to embed the test suite in `func-test`. I have a plan to make it easy, or at least possible, to package integration test suites with plugins, but there's a few pieces missing yet
> Fix bug in Retrie "fold/unfold in local file" commands

- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/test/exe/Main.hs
This PR fixes another diagnostics bug introduced by #1188. Diagnostics are tricky but this was a silly mistake.
When a rule runs, the ide must always send the diagnostics returned by the rule. The only case where saved diagnostics are to be reused is early cutoff. 
This is what the description of #1188 stated, I have no idea why then in the implementation I changed the non early-cutoff case.
> Stale diagnostics fix

- ghcide/CHANGELOG.md
- ghcide/bench/config.yaml
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/Rules.hs
Mainly to get rid of the sticky diagnostics bug, although there's quite a few more nice changes in there
> Prepare ghcide release v0.7.1

- ghcide/CHANGELOG.md
- ghcide/exe/Main.hs
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/Service.hs
- ghcide/src/Development/IDE/Types/Options.hs
- src/Ide/Main.hs
So that clients of Ghcide-the-library can change them at will. 
I need this at work, so including a version bump - will upload to Hackage as soon as it lands
> Expose shake options used

- ghcide/src/Development/IDE/Types/Exports.hs
- ghcide/test/exe/Main.hs
Fixes #1211.
When extending the import of a type operator with one of its constructors, don't
forget to put parentheses around the type operator.
> Parenthesise type operators when extending import lists

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/GHC/ExactPrint.hs
- ghcide/src/Development/IDE/GHC/Orphans.hs
- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs
- ghcide/test/exe/Main.hs
This is a big PR with several changes, split in well defined commits for ease of review. 
If we are going to use ghc-exactprint in code actions, It makes sense to cache the annotated AST in the Shake graph
Code actions that intend to preserve user formatting cannot use the existing `Development.IDE.GHC.ExactPrint.Graft` abstraction, which throws away all format. So instead we introduce a weaker `Rewrite` abstraction that does fewer things:
- It doesn't annotate things for you (so it doesn't destroy user format)
- It doesn't provide a Monoid instance (for now)
- It doesn't use SYB to perform the replacement
- It doesn't diff to compute the result
The use case is code actions where you don't have the SrcSpan that you need to edit at hand, and instead you need to traverse the AST manually to …
> Use exact print for suggest missing constraint code actions

- ghcide/.hlint.yaml
- ghcide/src/Development/IDE/Core/Tracing.hs
- ghcide/src/Development/IDE/LSP/LanguageServer.hs
- ghcide/src/Development/IDE/LSP/Server.hs
- ghcide/src/Development/IDE/Plugin/HLS.hs
These traces can be useful to diagnose performance issues
https://user-images.githubusercontent.com/26626/104844700-9ff16400-58c9-11eb-8d6d-53e9694cc292.mov
> Add traces for HLS providers

- plugins/default/src/Ide/Plugin/Pragmas.hs
- test/functional/Completion.hs
Fixes #1187.
Separate the list of pragmas used for completion from the list of pragmas used
to suggest enabling a language extension to fix an error. The former now include
the `No-` variants of the language extensions, e.g., `NoDuplicateRecordFields`.
> Complete the No- variants of language extensions and Strict extension

- haskell-language-server.cabal
#1234 duplicated the "category: Development" in haskell-language-server.cabal and it's giving a warning when I build.
> Delete redundant "category: Development".

- plugins/default/src/Ide/Plugin/Pragmas.hs
Current plugin does not list `Safe`, `Trustworthy`, etc.
This PR adds those pragmas.
> Add non reversable pragma completion

- README.md
As suggested here: https://github.com/haskell/haskell-language-server/issues/1160#issuecomment-758487866
> Add dynamic linking common issue

- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/src/Development/IDE/Plugin/CodeAction/PositionIndexed.hs
- ghcide/test/exe/Main.hs
- hls-plugin-api/src/Ide/PluginUtils.hs
This pr adds suggestions for removing elements of the export list causing an error or a warning. It also adds a special suggestion to remove all such elements at once:
It looked a lot like the remove imports suggestions, so I tried to use things from there, but this wasn't always possible.
> Remove undefined exports suggestions

- .github/mergify.yml
- .github/workflows/bench.yml
- ghcide/bench/hist/Main.hs
- ghcide/ghcide.cabal
- shake-bench/src/Development/Benchmark/Rules.hs
The heap profiles are generated using `+RTS -h` and rendered using http://hackage.haskell.org/package/eventlog2html
The artefact tree for a given example&experiment looks as follows:
```
ghcide/bench-results/Cabal-3.0.0.0/upstream/
├── completions_after_edit.benchmark-gcStats
├── completions_after_edit.csv
├── completions_after_edit.diff.svg
├── completions_after_edit.eventlog                # new
├── completions_after_edit.eventlog.html           # new
├── completions_after_edit.hp                      # new
├── completions_after_edit.log
├── completions_after_edit.svg
```
Other changes:
* Fix a bug (introduced in #1178) affecting the live bytes svg diagrams.
* Enable Shake parallelism for the benchmark rules (the benchmarks themselves are guarded by a Shake resource so there's only one …
> Benchmarks: generate heap profiles

- ghcide/src/Development/IDE/Plugin/CodeAction.hs
The "Disable warnings" quick fix is probably not what we want to show first in a redundant import:
> Reorder code actions to put remove redundant imports first

- ghcide/src/Development/IDE/Plugin/Completions.hs
- ghcide/src/Development/IDE/Plugin/HLS.hs
- haskell-language-server.cabal
- plugins/default/src/Ide/Plugin/Pragmas.hs
- test/functional/Completion.hs
In #1218 I introduced a `maxCompletions` config setting, and added code to enforce it in ghcide. 
This PR applies the max completions limit to all plugins, not just ghcide. While doing this I noticed that the pragmas plugin was producing completions without considering the prefix, this is fixed now.
> Enforce max completions over all plugins

- exe/Plugins.hs
- ghcide/exe/Main.hs
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/LSP/HoverDefinition.hs
- ghcide/src/Development/IDE/LSP/LanguageServer.hs
- ghcide/src/Development/IDE/Plugin.hs
- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/src/Development/IDE/Plugin/Completions.hs
- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- ghcide/src/Development/IDE/Plugin/HLS.hs
- ghcide/src/Development/IDE/Plugin/HLS/GhcIde.hs
- ghcide/src/Development/IDE/Plugin/Test.hs
- ghcide/src/Development/IDE/Plugin/TypeLenses.hs
- ghcide/test/exe/Main.hs
This is a continuation of the work started in #701 to split out ghcide functionality in HLS plugins.
Splitting provides several benefits: 
- Commands can be declared independently, which couldn't be done with the lower level plugin model in ghcide
- Each provider gets its own error handling
- Providers can run in parallel
Later on, we may want to break completions down further as discussed in #724
Closes #724
> Break down ghcide functionality in HLS plugins

- ghcide/bench/hist/Main.hs
- ghcide/ghcide.cabal
- shake-bench/src/Development/Benchmark/Rules.hs
The -eventlog runtime is not reliable when combined with +RTS -h
leading to undiagnosed crashes and infinite loops.
The crashes are sporadic and seem to arise more frequently in the lsp-types
example, although we have not investigated deeply since there is a simple
alternative that doesn't crash: the vanilla runtime.
> Produce heap profiles the old fashioned way, from .hp files

- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
`Ide.Plugin.Hlint` uses `applyRefactorings'`, which is only available in `apply-refact >= 0.9`
> Tighten dependency on apply-refact

- ghcide/session-loader/Development/IDE/Session.hs
Achieves this by adding a HashMap from NormalizedFilePath
to its respective `hie.yaml` location.
This works nicely with the existing implementation, but
increases the memory usage (and I am not sure whether by a considerable amount).
This change is motivated by https://github.com/mpickering/hie-bios/pull/264
where we set the build-dir for cabal based projects to some config
directory in order to avoid recompilation issues whenever users invoked
`cabal build`.
However, this uncovered an issue in the existing code-base, as HLS will
ask for the compilation options for generated modules, such as
`Paths_*`, by looking for the responsible `hie.yaml` file and using an
internal cache for the options. This used to be fine, until the
aforementioned hie-bios change, since now `Paths_*` module will …
> Add custom cache layer for session loading

- ChangeLog.md
- docs/releases.md
- haskell-language-server.cabal
* This is a minimal release, without revising subpackages versions or preparing anything to upload them to hackage.
* Do you think we should update the cabal.project hackage index and stackage resolvers as part of the release?
* We cant upload to hackage at least until ghc-exactprint has a release including the commit we are checking in the source-repository-package
* I've added a [checklist](https://github.com/haskell/haskell-language-server/compare/master...jneira:prepare-0.9.0?expand=1#diff-ddff4241c2f41c415cbf4ff22e0dc609d1c50ace49f413673a8eb79ed2f02ff0) with the steps i've done for this one (see https://github.com/haskell/haskell-language-server/pull/704#issuecomment-769189470) //cc @bubba 
@pepeiborra feel free to add directly in the desctiption whatever you think is needed about …
> Prepare 0.9.0

- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs
An unfortunate side effect of recent changes is that the extend import suggestions ended up at the bottom of the list.
This change puts back all code actions provider together so they can be reordered more easily, and restores the previous order where extend imports would be near the top of the list
> Restore code actions order

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/GHC/Compat.hs
- ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs
- ghcide/src/Development/IDE/Plugin/Completions.hs
- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- ghcide/src/Development/IDE/Plugin/Completions/Types.hs
- ghcide/test/exe/Main.hs
- ghcide/test/src/Development/IDE/Test.hs
- plugins/hls-explicit-imports-plugin/src/Ide/Plugin/ExplicitImports.hs
- test/functional/Completion.hs
This builds on the work done by @gdevanla in haskell/ghcide#930 and @berberman in #1246  to reenable completions to automatically extend import lists. 
There were two issues that led to this feature getting disabled:
1. the imports were extended multiple times. This is addressed by using a Command that recomputes the edit on invocation, instead reusing the edit computed at completion time
2. the imports were extended wrongly. This is addressed by using ghc-exactprint to ensure the extension is always well formed
While I was there, I also took the chance to drop snippets when typing an infix combinator
> Reenable auto extend imports and drop snippets for infix completions

- plugins/hls-splice-plugin/hls-splice-plugin.cabal
Required for #1287. Sets version lower bound for `ghcide` (for `Development.IDE.GHC.ExactPrint `) and bumps version to `0.2.0.0`.
> hls-splice-plugin-0.2.0.0

- ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs
- ghcide/test/exe/Main.hs
> Don't extend import list with child if the parent has been imported as (..)

- plugins/hls-eval-plugin/hls-eval-plugin.cabal
> Bum up hls-eval-plugin to 0.2

- hls-plugin-api/src/Ide/Plugin/Config.hs
- test/functional/Config.hs
Hi, I've made a change to make default configuration to be used if `initializationOptions` doesn't have `haskell` or `languageServerHaskell` key in it. There are some issue where the server returns `haskell-lsp: configuration parse error.`. This change shouldn't break any existing configuration because it adds safety net instead of straight failing.
Also, I actually made the same change to https://github.com/haskell/haskell-ide-engine/pull/1802 first before realizing there's a new project. I'm not sure if this can be considered as bug fix, so I'll keep it open there.
> Use default config on missing configuration section

- plugins/hls-splice-plugin/hls-splice-plugin.cabal
As raised in #1287, current uploaded version of hls-splice-plugin-0.2.0.0 contradicts with the uploaded veresion of ghcide-0.7.3.0.
Since the code of hls-splice-plugin contained in 0.9.0-hackage compiles with ghcide-0.7.3.0 (I confirmedIt with ghc 8.8) and same functionality as in 0.9.0, just updating cabal file would suffice.
> hls-splice-plugin-0.3.0.0-prepare

- plugins/hls-splice-plugin/hls-splice-plugin.cabal
**NOTE**: This PR is NOT for releasing 0.9.0 to Hackage; it is preparatory PR to make sure we make another release of the Splice Plugin on Hackage when the next (not 0.9.0) release of HLS has been made; no immediate Hackage release of the bumped version of Splice Plugin is planned.
This PR further bumps the version of `hls-splice-plugin` to 0.4.0.0 and also changes author and maintainer fields to `https://github.com/haskell/haskell-language-server/contributors`, rather than my names and address alone.
Note that code of hls-splice-pluigin-0.3.0.0 is inconsistent with the current master branch - it uses locally defined `rangeToRealSrcSpan` function, which collides with (not yet released) the most recent ghcide's API.
This PR  is to make sure the further release of hls-splice-plugin to be …
> Splice Plugin: preparatory version bump for the next (not 0.9.0) HLS release

- ghcide/src/Development/IDE/Plugin/Completions.hs
- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- ghcide/test/exe/Main.hs
Closes #1308
Not sure if this will have significant impact on performance...
> Trigger extending import only when the item is not in scope

- ghcide/bench/hist/Main.hs
As mentioned in #1306 the benchmark suite can occasionally fail with errors like below. I don't know what causes this. One theory is that it's caused by Shake trying to compute the output file digest. To eliminate potential variables and since we don't need output digests, let's disable them. 
After doing this, I've run the benchmark suite several times without seeing any more errors
Fixes #1306 (hopefully)
```
Error when running Shake build system:
at want, called at bench/hist/Main.hs:87:16 in main:Main
* Depends on: bench_example_HLS
at need, called at src/Development/Benchmark/Rules.hs:154:37 in shake-bench-0.1.0.0-inplace:Development.Benchmark.Rules
* Depends on: bench-results/bench_example_HLS/HEAD/edit.heap.svg
* Raised the exception: …
```
> [benchmark] check digests for input files only

- .github/mergify.yml
- .github/workflows/bench.yml
- ghcide/.gitignore
- ghcide/bench/config.yaml
- ghcide/bench/hist/Main.hs
- shake-bench/src/Development/Benchmark/Rules.hs
* Disable parallel GC as it leads to occasional segfaults when combined with heap profiling
* Lower the frequency of heap profiles to speed up benchmarks (I'll make it configurable in a follow-up change)
* Reduce samples from 100 to 50 to speed up benchmarks
While I was there I also changed some of the artefact file extensions for consistency
> [benchmarks] speed up CI

- ghcide/bench/hist/Main.hs
- shake-bench/src/Development/Benchmark/Rules.hs
This is to remove the noise caused by a clean cache on the first experiment that is run.
> [benchmark] add warmups

- ghcide/bench/hist/Main.hs
- shake-bench/src/Development/Benchmark/Rules.hs
Simple fix of a shake-bench TODO
> [shake-bench] extract project dependencies action (for the HEAD binary)

- ghcide/bench/hist/Main.hs
- shake-bench/src/Development/Benchmark/Rules.hs
The eventless contain opentelemetry traces of various ghcide actions and handlers, and can be inspected with e.g. `eventlog-to-tracy`.
> [shake-bench] collect eventlogs

- .github/workflows/bench.yml
Same trick as used for the test workflow
> Cancel earlier queued benchmarks

- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic.hs
- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/CodeGen.hs
- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Context.hs
- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Judgements.hs
- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Machinery.hs
- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Naming.hs
- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Tactics.hs
- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Types.hs
- plugins/hls-tactics-plugin/test/AutoTupleSpec.hs
- test/functional/Tactic.hs
- test/testdata/tactic/FmapBoth.hs
- test/testdata/tactic/FmapBoth.hs.expected
The `Hypothesis` is all of the values in scope that the tactics engine knows about. It used to be a `Map OccName HyInfo`, mapping names to the information we have about them. But this is unhelpful for two reasons:
1. Almost nowhere in the code do we lookup by name
2. Class methods get instantiated for every concrete type, meaning we couldn't have two givens for different types in scope
Worse, it actively encouraged a bad style where we'd iterate through the keys of the hypothesis, and then need to look up the value in the map we were iterating. All of these callsites have now been simplified to just take the `HyInfo` directly, rather than an `OccName` that we'd subsequently need to lookup.
This PR refactors some of the underlying machinery. It's a bit simplistic now, but paves the way for …
> Refactor the hypothesis type in hls-tactics-plugin

- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/src/Development/IDE/Types/HscEnvEq.hs
Fixes #1348 in the sense that I cannot repro anymore
> Fix code actions regression

- ghcide/CHANGELOG.md
- ghcide/exe/Main.hs
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Main.hs
- ghcide/test/exe/Main.hs
- haskell-language-server.cabal
- src/Ide/Main.hs
> Default main for ghcide 

- ghcide/ghcide.cabal
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs
Hopefully this will get rid of the sporadic exceptions
I also took the chance to speed up the test suite a bit.
Someone else should build the PR locally and test that the Eval plugin still works and performs well /cc @tittoassini @konn
> Fix the Eval plugin sporadic exceptions

- plugins/default/src/Ide/Plugin/StylishHaskell.hs
Would it be better to log something in `otherwise` case of `getMergedConfig`?
> Make StylishHaskell plugin recognize extensions from DynFlags

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/Main.hs
- ghcide/test/exe/Main.hs
- hls-plugin-api/hls-plugin-api.cabal
- hls-plugin-api/src/Ide/Plugin/Config.hs
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
- src/Ide/Main.hs
This adds a field in the `defaultMain` driver to specify the default config, replacing two callbacks and making things a bit saner. 
The rest of the changes are to deal with the use of `def` in various places which had to be turned into a parameter.
> Sanitize the setup of the default Ide.Config

- ghcide/session-loader/Development/IDE/Session.hs
We were using the HieBios implicit cradle before, which could have inconsistent results and may
result in 'setInitialDynFlags' failing
> use implicit-hie cradle from setInitialDynFlags

- ghcide/.hlint.yaml
- ghcide/exe/Main.hs
- ghcide/src/Development/IDE/LSP/LanguageServer.hs
- ghcide/src/Development/IDE/Main.hs
- ghcide/test/exe/Main.hs
- src/Ide/Main.hs
Test for https://github.com/haskell/haskell-language-server/pull/1357
Involved re-jigging 'runWithDb' to be within the callback to 'runLanguageServer' so that the database location
is derived from the 'rootPath' of the LSP session, and not the starting CWD of the ghcide process.
I have verified that the test fails without the mentioned commit.
> Add test for multi-component goto def and make runLanguageServer responsible for hiedb

- ghcide/src/Development/IDE/Plugin/Completions.hs
- ghcide/test/exe/Main.hs
Imo we'd better notify users that we modified source code without their permission.
> Show window message when auto extending import lists

- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/LSP/HoverDefinition.hs
- ghcide/src/Development/IDE/LSP/Notifications.hs
HLS is too chatty. Lowering the severity of some log messages should indirectly
increase the visibility of all other messages
> Tone down some logInfos to logDebug

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/Plugin/Completions.hs
- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- ghcide/src/Development/IDE/Spans/Documentation.hs
@cocreature confirmed that DA are not depending on this anymore and we are free to drop it. 
Closes #784
> Lose the ghc-lib flag

- exe/Wrapper.hs
- ghcide/exe/Main.hs
- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/src/Development/IDE/Main.hs
- haskell-language-server.cabal
- src/Ide/Main.hs
As discussed in https://github.com/haskell/haskell-language-server/pull/1375 the ghc lib dir used for initializing  the unsafe dynflags needs to be configurable for clients that rely on custom session loading options
> Configuration for initial ghc lib dir

- ghcide/CHANGELOG.md
- ghcide/src/Development/IDE/Core/Rules.hs
As usual, release notes are mostly trimmed down to user visible changes.
Uploading this to Hackage will require uploading hls-plugin-api too, I'll do both.
> Prepare ghcide release 0.7.5

- ghcide/bench/config.yaml
It times out since the lsp-1.0 patch, and I don't have time to look into it
> Disable HLS benchmark example

- ChangeLog.md
- GenChangelogs.hs
Before this PR, the script creates `([PR number)](link)`, which makes `)` after the PR number also clickable. This PR fixes so that only the PR number is treated as a link.
> Fix GenChangelog script format

- .gitignore
- .stylish-haskell.yaml
- CONTRIBUTING.md
- ghcide/.stylish-haskell.yaml
- hls-plugin-api/.stylish-haskell.yaml
- nix/default.nix
- shell.nix
Resolves partially #693.
I will format code base after this PR. I think it's quite hard to find a time slot when there is no "big" PR, so it's maybe better to send the setting first, and format after (in time slots between big PRs), so that other big PRs can use the setting to format them by their own.
> Add a pre commit hook for code formatting

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/Compile.hs
- ghcide/src/Development/IDE/Core/RuleTypes.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/test/data/THUnboxed/THA.hs
- ghcide/test/data/THUnboxed/THB.hs
- ghcide/test/data/THUnboxed/THC.hs
- ghcide/test/data/THUnboxed/hie.yaml
- ghcide/test/exe/Main.hs
1. Modules that use TH themselves but aren't depended on by anything that uses TH don't need to be compiled
2. Any module that needs to be compiled and uses unboxed sums/tuples needs to be compiled using object code
3. Any module that is depended on by anything that uses object code needs to be compiled using object code.
Logic from https://gitlab.haskell.org/ghc/ghc/-/blob/963e1e9aedf0ee70d4e817640ec9845ed00ce0cf/compiler/GHC/Driver/Make.hs#L2268
> Use object code for TH+UnboxedTuples/Sums

- haskell-language-server.cabal
- plugins/hls-class-plugin/hls-class-plugin.cabal
- plugins/hls-eval-plugin/hls-eval-plugin.cabal
- plugins/hls-explicit-imports-plugin/hls-explicit-imports-plugin.cabal
- plugins/hls-haddock-comments-plugin/hls-haddock-comments-plugin.cabal
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
- plugins/hls-splice-plugin/hls-splice-plugin.cabal
- plugins/hls-tactics-plugin/hls-tactics-plugin.cabal
The plugins were all updated to lsp-1.0 in #1284 and need a minor version bump in order to be upload able to Hackage. 
I am also going to upload all the plugins I have Hackage maintainer access (class, imports, and retrie). This is in order to make them usable with ghcide 0.7.5.0, which was released earlier today. 
Ideally we would have a CI job that would detect Cabal version updates and automatically upload to Hackage.
> Bump plugins versions

- hls-plugin-api/src/Ide/Plugin/Config.hs
It was likely forgotten to add in this change:
<https://github.com/haskell/haskell-language-server/pull/1218/files>
> Plugin Config: Add maxCompletions to JSON instance

- test/functional/Format.hs
- test/testdata/format/Format.floskell.formatted.hs
- test/testdata/format/Format.floskell.initial.hs
- test/testdata/format/Format.ormolu_post_floskell.formatted.hs
The test passes, and I cannot repro the issue with VSCode, so the issue must be down to a difference in how CoC and VSCode implement the LSP spec. 
I believe it worked before the lsp-1.0 upgrade, which means that something has changed between *haskell-lsp* and *lsp* in how the initial configuration is handled. 
The full LSP log (see the Gist below) from the test shows that *lsp-test* generates a `workspace/didChangeConfiguration` with the formatter config. It could be that CoC doesn't send this notification, and instead expects the server to request the config. @wz1000 @bubba is it possible that *haskell-lsp* does request the config at startup, whereas *lsp* does not?
https://gist.github.com/pepeiborra/fcad435bdf8717ceeecf392549329c19
There's nothing else to do here, so this closes #1376. …
> Add a test for #1376

- .github/workflows/bench.yml
- ghcide/bench/config.yaml
The example was commented out in #1388
> Reenable HLS example benchmark

- ghcide/src/Development/IDE.hs
- ghcide/src/Development/IDE/Core/Service.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/Main.hs
- ghcide/src/Development/IDE/Plugin/Completions.hs
- ghcide/src/Development/IDE/Plugin/HLS.hs
- hls-plugin-api/src/Ide/PluginUtils.hs
- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic.hs
- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/LanguageServer.hs
`Ide.PluginUtils.getClientConfig` was using `instance Default Config` instead of the configured default HLS config.
This is only relevant when using ghcide as a library, no visible user impact for HLS.
> Fix the handling of default HLS config again

- ChangeLog.md
- ghcide/ghcide.cabal
- haskell-language-server.cabal
- hie-compat/hie-compat.cabal
- hls-plugin-api/hls-plugin-api.cabal
- plugins/hls-class-plugin/hls-class-plugin.cabal
- plugins/hls-eval-plugin/hls-eval-plugin.cabal
- plugins/hls-explicit-imports-plugin/hls-explicit-imports-plugin.cabal
- plugins/hls-haddock-comments-plugin/hls-haddock-comments-plugin.cabal
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
- plugins/hls-splice-plugin/hls-splice-plugin.cabal
- plugins/hls-tactics-plugin/hls-tactics-plugin.cabal
As mentioned in https://github.com/haskell/haskell-language-server/issues/1310#issuecomment-781590900, we consider releasing the major 1 version of HLS (and maybe plugins?)
~~This PR currently bumps only HLS, but if we decide to do so, I will bump other plugins too~~.
Now this PR bumps all versions including GHCIDE.
> Prepare 1.0.0 release

- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/CaseSplit.hs
- test/functional/Tactic.hs
- test/testdata/tactic/SplitPattern.hs
- test/testdata/tactic/SplitPattern.hs.expected
This PR fixes #1426. The old logic accidentally would only replace top-level `VarPat`s. This one instead does an SYB traversal over the bound patterns and replaces a `VarPat` with its case-matches. The implementation here is a bit stupid --- it does one traversal for each `body`, but this is user-written code, so all inputs involved are small constants.
> Correctly split non-varpats in tactics

- ChangeLog.md
Update changelog to include a (kinda) important bug fix.
> Last preparation for 1.0.0.0

- plugins/hls-eval-plugin/hls-eval-plugin.cabal
Closes #1436
The config intent was set 9.0 but 0.9 was used
> Correct megaparsec lower bound

- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/test/exe/Main.hs
> Extract the qualified name from already imported module

- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/src/Development/IDE/Core/Compile.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/Types/Options.hs
ghcide sets a custom unit id for the internal component. While this is mostly an internal implementation detail, it leaks out when trying to reuse interface files produced by ghc, which will need to be configured with `--this-unit-id fake_uid`. This is fine, but what if in the future ghcide changes the fake uid string? 
This PR adds a flag to control the fake uid string which can be used to get some protection against future ghcide changes.
Additionally, we should probably change the default value to "main", which is the name ghc uses for the default component, in order to make the scenario above, reusing interface files produced by ghc, work out of the box in most cases. Thoughts @fendor @wz1000 ?
> Customize the unitId used for the fake internal component

- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic.hs
- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/CodeGen.hs
- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Judgements.hs
- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/KnownStrategies/QuickCheck.hs
- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/LanguageServer.hs
- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Machinery.hs
- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Tactics.hs
- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Types.hs
Refinery implements the tactics search by growing a search tree and collapsing back the results of each branch. But this is a complicated thing to think about, because there is data moving in three different directions. The `Judgement` moves from root to leaves, while the "extract" moves from leaves to root --- and the `TacticState` moves sideways between branches, just to make things hard.
This PR formalizes the extract to as a dedicated type `Synthesized` (it corresponds to a synthesized attribute in the lingo of [attribute grammars](https://en.wikipedia.org/wiki/Attribute_grammar)). Having this new conceptual clarity made me realize that I used to be using the `TacticState` as a hacky way of passing information back up the search tree. So this PR chops out a lot of that complexity and …
> Simplify tactics state structure

- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
- stack-8.10.2.yaml
- stack-8.10.3.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack-8.8.4.yaml
- stack.yaml
* We were using it only in the code path for ghc < 8.10
* But I guess some change in either `ghc-exacprint` or `apply-refact` has exposed the ghc-wrapper  for the code path used in ghc-8.10 here (`applyRefact'`)
* Fixes #591
> Use runtime ghc libdir for ghc-exactprint and ghc-8.10

- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Tactics.hs
#1453 introduced a slight bug where I forgot to update the extract's knowledge of introduced scoped variables when running `intros`. This made the scoring function reject lots of otherwise good programs, and a bunch of tests went red.
Found it this morning when seeing mysterious failures in an unrelated part of the codebase.
This makes it look like the tactics tests aren't being run as part of CI :scream: How do we get them to run?
> Add new variables to the extract when doing intros

- ghcide/test/exe/Main.hs
Earlier boot-def failed in ~1/20 runs on my machine.
After this fix, I ran the test 200 times and observed 0 failures.
> Fix non-determinism in boot-def test

- cabal.project
- ghcide/ghcide.cabal
> Haddock upper bound

- ghcide/src/Development/IDE/Main.hs
It was registered on initialise, but since we don't go through that code path
when we are not in lsp mode, we get errors when things like hlint try to use it.
> Register IDE configuration when called via the command line

- ghcide/src/Development/IDE/GHC/ExactPrint.hs
- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic.hs
- plugins/hls-tactics-plugin/test/GoldenSpec.hs
- plugins/hls-tactics-plugin/test/golden/LayoutBind.hs
- plugins/hls-tactics-plugin/test/golden/LayoutBind.hs.expected
- plugins/hls-tactics-plugin/test/golden/LayoutDollarApp.hs
- plugins/hls-tactics-plugin/test/golden/LayoutDollarApp.hs.expected
- plugins/hls-tactics-plugin/test/golden/LayoutLam.hs
- plugins/hls-tactics-plugin/test/golden/LayoutLam.hs.expected
- plugins/hls-tactics-plugin/test/golden/LayoutOpApp.hs
- plugins/hls-tactics-plugin/test/golden/LayoutOpApp.hs.expected
In #1486, it's pointed out that always inserting a leading space when grafting trees will break layout (and thus the parse) if you're grafting into a `do` block. Yikes.
This PR adds a function `graftExpr` which tracks the tree context of the graft's destination. If the immediate parent of the destination is a function application, or a few other things, we need to insert that space.
And hey, while we're looking at context, let's use it to determine if we need parentheses!
Fixes #1486
> Context-aware ExactPrint grafting for HsExpr

- .github/workflows/bench.yml
- ghcide/bench/config.yaml
They are still failing.
/cc @pepeiborra
> Disable HLS benchmarks

- ghcide/src/Development/IDE/Core/FileExists.hs
- ghcide/src/Development/IDE/Core/FileStore.hs
- ghcide/src/Development/IDE/Core/OfInterest.hs
- ghcide/src/Development/IDE/Core/Service.hs
- ghcide/src/Development/IDE/LSP/Notifications.hs
- ghcide/test/exe/Main.hs
This removes the need to poll the file system for source files (we still do it for interface files). 
The implementation is remarkably simple, as it uses the watch notifications only to *dirty* the Shake node, but we still reuse the existing code to compute the result of the rule.
Closes #803
> Drive GetModificationTime using watched file events

- plugins/hls-tactics-plugin/src/Ide/Plugin/Tactic/Tactics.hs
- plugins/hls-tactics-plugin/test/CodeAction/AutoSpec.hs
- plugins/hls-tactics-plugin/test/golden/AutoEndo.hs
- plugins/hls-tactics-plugin/test/golden/AutoEndo.hs.expected
Tactics was afraid of running endomorphisms in an attempt to cut down on the size of generated trees. But it doesn't seem to be an issue in practice, so why not.
Fixes #1447
> Let Wingman's apply tactic run endomorphisms

- haskell-language-server.cabal
* I think that include plugins should be something cabal should not choose at its will, depending it they are buildable or not, but by the user explicitly (and fail if they are not buildable) 
* We are uploading all plugins before hls so all of them are available for now
> Set all plugin flags to manual

- ghcide/src/Development/IDE/Core/Compile.hs
- ghcide/src/Development/IDE/Core/FileExists.hs
- ghcide/src/Development/IDE/Core/FileStore.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/LSP/LanguageServer.hs
Extends the changes introduced in #1487 to interface files. 
To verify:
```
[nix-shell:~/scratch/ide]$ cabal exec cabal run ghcide-bench -- -- --example-package-name Cabal --example-module Distribution/Simple.hs --example-package-version 3.0.0.0 -s "edit" --samples 1 --shake-profiling /tmp/ghcide --no-clean
Up to date
Config {verbosity = Normal, shakeProfiling = Just "/tmp/ghcide", otMemoryProfiling = Nothing, outputCSV = "results.csv", buildTool = Cabal, ghcideOptions = [], matches = ["edit"], repetitions = Just 1, ghcide = "ghcide", timeoutLsp = 60, example = GetPackage {exampleName = "Cabal", exampleModules = ["Distribution/Simple.hs"], exampleVersion = Version {versionBranch = [3,0,0,0], versionTags = []}}}
starting test
Setting up document contents took 7.18s
Running edit benchmark …
```
> Avoid always rerunning GetModificationTime for interface files too

- ghcide/src/Development/IDE/Core/FileExists.hs
- ghcide/src/Development/IDE/Core/RuleTypes.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/Core/Tracing.hs
- ghcide/src/Development/IDE/GHC/ExactPrint.hs
- ghcide/src/Development/IDE/Types/Options.hs
The current implementation of progress reporting uses `actionBracket` which has O(logC) complexity in the number of registered Cleanups (https://github.com/ndmitchell/shake/issues/797).
Since we do progress reporting for every File and Rule updated, the worst case complexity is around O(F*R*logC) for all the files in the project. In large projects, this is quite expensive.
Since `otTracedAction` is implemented using `actionBracket` too, I have made it conditional on eventlogs being enabled.
For reviewers understanding: I had to move some types around to avoid cyclic module dependencies.
> Add an option to control progress reporting

- ghcide/src/Development/IDE/Core/Shake.hs
Even if the rule body does not produce diagnostics, it is still possible to get
a BadDependency diagnostic. To avoid a debugging nightmare if this ever happens,
let's make sure to log any unexpected diagnostics
> Log a warning for every diagnostic received when doDiagnostics=False

- ghcide/src/Development/IDE/Core/Compile.hs
- ghcide/src/Development/IDE/Core/FileStore.hs
- ghcide/src/Development/IDE/Core/OfInterest.hs
- ghcide/src/Development/IDE/Core/RuleTypes.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/GHC/Util.hs
Some of these were unnecessary, while others were very inefficient
> Review early cutoff fingerprints

- ghcide/src/Development/IDE/Core/Debouncer.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/Main.hs
These shared locks introduce contention and resulting in decreasing performance as the core count increases.
The async debouncer that we use in ghcide to deduplicate diagnostics is backed by a single lock containing  a Hashmap indexed by rule key used to store all the pending actions. We then grab this lock for every rule execution, for rules with diagnostics. In total, a rule execution grabs the lock twice: 
1. To enqueue the diagnostics update in the debouncer
2. When the update fires, to clean up
We then hold the lock for as long as it takes to update the map and cancel the previous async, if any. There is a bit of room for improvement here, by combining HashMap accesses as well as executing the cancel outside the lock.
Moreover, I have added an option to install a different Debouncer, …
> Improve thread contention around diagnostics

- plugins/hls-tactics-plugin/src/Wingman/Types.hs
There's been some confusion lately on which parts of LSP are from Wingman and which parts aren't. This PR prefixes each of my code actions with "Wingman:", which is an inelegant (but effective) solution.
> Add wingman branding to code actions

- ghcide/ghcide.cabal
- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/src/Control/Concurrent/Strict.hs
- ghcide/src/Development/IDE/Core/Debouncer.hs
- ghcide/src/Development/IDE/Core/FileExists.hs
- ghcide/src/Development/IDE/Core/FileStore.hs
- ghcide/src/Development/IDE/Core/IdeConfiguration.hs
- ghcide/src/Development/IDE/Core/OfInterest.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/GHC/Warnings.hs
- ghcide/src/Development/IDE/Types/HscEnvEq.hs
These strict versions enforce a new pattern: evaluate outside the lock
This is to minimize the time the lock is held and should help with contention
Eventually, it might make sense to upstream these primitives /cc @ndmitchell
> Introduce strict versions of modifyVar to improve contention

- plugins/hls-tactics-plugin/src/Wingman/CodeGen.hs
- plugins/hls-tactics-plugin/src/Wingman/CodeGen/Utils.hs
- plugins/hls-tactics-plugin/test/CodeAction/AutoSpec.hs
- plugins/hls-tactics-plugin/test/golden/AutoEmptyString.hs
- plugins/hls-tactics-plugin/test/golden/AutoEmptyString.hs.expected
When synthesizing `[] :: String`, Wingman will now produce `""` instead of `[]`
> Use string literals to synthesize the empty string

- ghcide/CHANGELOG.md
- ghcide/bench/config.yaml
I want to upload a new ghcide release to Hackage
> Prepare ghcide 1.1.0

- plugins/hls-tactics-plugin/src/Wingman/CodeGen.hs
- plugins/hls-tactics-plugin/src/Wingman/CodeGen/Utils.hs
- plugins/hls-tactics-plugin/src/Wingman/GHC.hs
- plugins/hls-tactics-plugin/src/Wingman/Judgements.hs
- plugins/hls-tactics-plugin/src/Wingman/KnownStrategies/QuickCheck.hs
- plugins/hls-tactics-plugin/src/Wingman/LanguageServer.hs
- plugins/hls-tactics-plugin/src/Wingman/Machinery.hs
- plugins/hls-tactics-plugin/src/Wingman/Tactics.hs
- plugins/hls-tactics-plugin/src/Wingman/Types.hs
- plugins/hls-tactics-plugin/test/CodeAction/AutoSpec.hs
- plugins/hls-tactics-plugin/test/CodeAction/DestructSpec.hs
- plugins/hls-tactics-plugin/test/golden/AutoPatSynUse.hs
- plugins/hls-tactics-plugin/test/golden/AutoPatSynUse.hs.expected
- plugins/hls-tactics-plugin/test/golden/LayoutSplitPatSyn.hs
- plugins/hls-tactics-plugin/test/golden/LayoutSplitPatSyn.hs.expected
Wingman was overly-specialized to `DataCon` in its provenance and splitting. This is unnecessary, and lead to some bugs where pattern synonyms wouldn't behave properly.
> Use ConLikes instead of DataCons

- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/src/Development/IDE/Plugin/CodeAction/Args.hs
- ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs
- ghcide/test/exe/Main.hs
> Use TextEdit to insert new imports

- plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
Uploading to Hackage for compatibility with ghcide 1.1.0.0
> bump retrie plugin version

- README.md
- hls-plugin-api/src/Ide/Plugin/Config.hs
> Remove max number of problems config option

- plugins/hls-tactics-plugin/src/Wingman/LanguageServer/TacticProviders.hs
- plugins/hls-tactics-plugin/src/Wingman/Plugin.hs
While investigating a solution to #1571, I wanted to add some more context to the `TacticProvider`. But this required changing a huge amount of code just to thread my value around. 
This PR makes a record type for `TacticProvider` and passes that around instead.
> Cleanup the TacticProviders interface

- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/src/Development/IDE/Plugin/CodeAction/Args.hs
- test/functional/FunctionalCodeAction.hs
Closes #1556
Suggestions are welcome! /cc @isovector 
Several examples:
| Code Action Title                                | Before                    | After                                       | Code Action Kind                          |
| ------------------------------------------------ | ------------------------- | ------------------------------------------- | ----------------------------------------- |
| Add stuffA to the import list of ModuleA         | `import ModuleA (stuffB)` | `import ModuleA (stuffB, stuffA)`           | `quickfix.import.extend.thing.topLevel`   |
| Add A to the import list of ModuleA              | `import ModuleA ()`       | `import ModuleA (A)`                        | `quickfix.import.extend.thing.topLevel`   |
| Add A(Constructor) to the import list of …
> Add custom code action kinds for import related code actions

- .github/workflows/nix.yml
- nix/default.nix
- nix/sources.json
- nix/sources.nix
- shell.nix
> Update nixpkgs to ghc 8.10.4

- ghcide/ghcide.cabal
It is currently referring to a deprecated location.
> Update homepage and other urls for ghcide

- plugins/hls-tactics-plugin/src/Wingman/CodeGen.hs
- plugins/hls-tactics-plugin/src/Wingman/Machinery.hs
- plugins/hls-tactics-plugin/src/Wingman/Plugin.hs
- plugins/hls-tactics-plugin/src/Wingman/Tactics.hs
- plugins/hls-tactics-plugin/test/CodeAction/AutoSpec.hs
- plugins/hls-tactics-plugin/test/golden/AutoZip.hs
- plugins/hls-tactics-plugin/test/golden/AutoZip.hs.expected
This is the first of three PRs cleaning up how Wingman approaches its proof search. It now attempts to synthesize homomorphic case splits if possible, and will only fall back to a regular split if the homomorphic one didn't lead to any solutions. This aggressively prunes the search tree in most cases, and means we have more auto gas to spend on harder proofs. As a result, we can now synthesize a solution to `zip`, which was previously too expensive to find.
> Try a homomorphic destruct before a standard destruct

- plugins/hls-tactics-plugin/src/Wingman/Judgements.hs
- plugins/hls-tactics-plugin/src/Wingman/Tactics.hs
- plugins/hls-tactics-plugin/src/Wingman/Types.hs
Today, Wingman tries to destruct terms in any order. For example, when trying to synthesize `zip`, it will try the following solutions:
```haskell
\ l_a l_b
-> case l_b of
[]
-> case l_a of
[] -> _
(a : l_a3) -> _
(b : l_b3)
-> case l_a of
[] -> _
(a : l_a5) -> _
```
and
```haskell
\ l_a l_b
-> case l_a of
[]
-> case l_b of
[] -> _
(b : l_b3) -> _
(a : l_a3)
-> case l_b of
[] -> _
(b : l_b5) -> _
```
These two solutions are equal modulo the order in which we did a pattern match. But it's stupid to explore both paths, since they _cannot_ produce different answers. 
Instead, this PR introduces a canonical ordering on the destructing on terms, using the natural ordering of introduction in the hypothesis. In particular, Wingman will not try to destruct anything that was introduced before …
> Give a canonical ordering for destructing terms in Wingman

- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Code.hs
- plugins/hls-eval-plugin/test/Eval.hs
- plugins/hls-eval-plugin/test/testdata/TNoImplicitPrelude.hs
- plugins/hls-eval-plugin/test/testdata/TNoImplicitPrelude.hs.expected
Hi,
This PR is pretty much what it says on the tin :)
The reason I need this is because the codebase at work uses `{-# NoImplicitPrelude #-}`, together with a custom prelude that includes `show :: Show a => a -> Text`, which doesn't play well with the Eval plugin. Currently, we get errors like:
```
Request workspace/executeCommand failed.
Message: Couldn't match type ‘Text’ with ‘[Char]’
Expected type: IO String
Actual type: IO Text
Code: -32603 
```
This is because the `Print` class, as defined on `Ide.Plugin.Eval.Code`, uses whatever `show` is in scope. Having a qualified Prelude in scope when `Print` is defined should be enough to avoid that, and I can't think of any drawbacks.
Thanks for your consideration and for all the great work on HLS so far!
> Ensure eval plugin Print class doesn't rely on Prelude being in scope

- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/src/Development/IDE/Types/HscEnvEq.hs
- ghcide/src/Development/IDE/Types/KnownTargets.hs
We currently duplicate all the known targets on every cradle reload, which leaks space and leads to slower performance in `GetLocatedImports`. 
The trivial fix is to use a `Set` instead of a list, since the order doesn't matter here.
> Avoid duplicating known targets and import paths

- exe/Plugins.hs
- ghcide/exe/Arguments.hs
- ghcide/exe/Main.hs
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Plugin/TypeLenses.hs
- haskell-language-server.cabal
- hls-plugin-api/hls-plugin-api.cabal
- hls-plugin-api/src/Ide/Plugin/ConfigUtils.hs
- hls-plugin-api/src/Ide/Plugin/Properties.hs
- hls-plugin-api/src/Ide/PluginUtils.hs
- hls-plugin-api/src/Ide/Types.hs
- plugins/hls-tactics-plugin/src/Wingman/LanguageServer.hs
- plugins/hls-tactics-plugin/src/Wingman/Plugin.hs
- plugins/hls-tactics-plugin/src/Wingman/Types.hs
- plugins/hls-tactics-plugin/test/Server.hs
- plugins/hls-tactics-plugin/test/Utils.hs
- src/Ide/Arguments.hs
- src/Ide/Main.hs
With #691, each plugin is able to have a generic config:
```json
{
"pluginName":{
"globalOn":false,
"codeActionsOn":false,
"codeLensOn":false,
"diagnosticsOn":false,
"hoverOn":false,
"symbolsOn":false,
"formattingOn":false,
"completionOn":false,
"renameOn":false,
"config":{
}
}
``` 
where particularly, `config` is an arbitrary JSON object representing the dedicated, or the extra custom config, which can be parsed and used by the plugin. However, this is hard to be documented and used from the clinet side -- I don't know much about other lsp clients, but for vscode, we have to write the [schema](https://code.visualstudio.com/api/references/contribution-points#Configuration-schema) manually, like @jneira did in https://github.com/haskell/vscode-haskell/pull/361, which is kind of cumbersome. …
> Regularize custom config of plugins

- ghcide/ghcide.cabal
base16-bytestring 1.0.1.0 has recently entered stackage nightly.
I have build haskell-language-server with that version and it seems to work fine.
Note: As of now implicit-hie-cradle and retrie also need this bump.
> Relax ghcides upper bound on base16-bytestring

- ghcide/src/Development/IDE/LSP/Outline.hs
- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- ghcide/test/exe/Main.hs
This branch replaces the `CiClass`/`SkClass` item kinds for completions and document symbols with `CiInterface`/`SkInterface` (see the linked issue for the motivation behind this change).
Additionally, the symbol icons for type families which were previously `SkClass` have been replaced with `SkFunction`.
> Use CiInterface/SkInterface for typeclass symbols

- exe/Plugins.hs
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/LSP/LanguageServer.hs
- ghcide/src/Development/IDE/LSP/Notifications.hs
- ghcide/src/Development/IDE/Plugin/HLS.hs
- ghcide/src/Development/IDE/Plugin/HLS/GhcIde.hs
- haskell-language-server.cabal
- hls-plugin-api/hls-plugin-api.cabal
- hls-plugin-api/src/Ide/Types.hs
- plugins/hls-brittany-plugin/hls-brittany-plugin.cabal
- plugins/hls-class-plugin/hls-class-plugin.cabal
- plugins/hls-eval-plugin/hls-eval-plugin.cabal
- plugins/hls-explicit-imports-plugin/hls-explicit-imports-plugin.cabal
- plugins/hls-haddock-comments-plugin/hls-haddock-comments-plugin.cabal
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
- plugins/hls-splice-plugin/hls-splice-plugin.cabal
- plugins/hls-tactics-plugin/hls-tactics-plugin.cabal
Rebased #1585 and extracted ghcide notification handlers
> Add ability for plugins to handle file change notifications

- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Code.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/GHC.hs
- plugins/hls-eval-plugin/test/Eval.hs
- plugins/hls-eval-plugin/test/testdata/TIt.hs
- plugins/hls-eval-plugin/test/testdata/TIt.hs.expected
Closes #1577
#438 introduced an alternative way to evaluate expressions: we wrapped expressions with `asPrint`, and then used `compileExpr` to get the coerced result `IO String`. However, it broke functionality of `it` variable -- referencing the last evaluated result.
This PR restores the old eval plugin's behaviour: there is no special treatment for expressions anymore; instead, expressions are just statements, and we redirect the output of `execStmt` to a temporary file to get the same result as `compileExpr`.
> Eval plugin: evaluate expressions as statements

- ghcide/src/Development/IDE/Plugin/Completions.hs
- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- ghcide/src/Development/IDE/Plugin/Completions/Types.hs
- hls-plugin-api/src/Ide/Plugin/Config.hs
- hls-plugin-api/src/Ide/Types.hs
- test/functional/Completion.hs
* Remove `haskell.completionSnippetsOn`
* Use `Properties` (#1576) to define the custom config, including switches of whether to enable snippets and auto extending import lists.
Clients now shoud provide JSON value like:
```json
"ghcide-completions":{
"globalOn":true,
"config":{
"autoExtendOn":true,
"snippetsOn":true
},
"completionOn":true
}
```
in the section `haskell.plugin` to control completions plugin.
> Use custom config for completions plugin

- .github/workflows/bench.yml
- .github/workflows/nix.yml
- .github/workflows/test.yml
* `paths-ignore` doesnt work with required checks branch protection rules:  https://github.community/t/path-filtering-on-required-pull-request-checks/18402/3
* so we have to remove it, fortunately `skip-duplicate-actions` which was being already used can be used to get the same functionality: https://github.com/marketplace/actions/skip-duplicate-actions#option-1-skip-entire-jobs
> Remove ignored paths

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Plugin/HLS.hs
- ghcide/test/exe/Main.hs
- hls-plugin-api/src/Ide/Plugin/ConfigUtils.hs
- hls-plugin-api/src/Ide/PluginUtils.hs
- hls-plugin-api/src/Ide/Types.hs
- src/Ide/Main.hs
- test/functional/FunctionalCodeAction.hs
Order of execution matters for notification plugins, so best to avoid unnecessary reorderings
> Avoid reordering plugins

- ghcide/src/Development/IDE/Core/Compile.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/Types/Options.hs
- test/functional/Progress.hs
https://user-images.githubusercontent.com/26626/112764331-e23ccd00-8fff-11eb-96fe-7149223b50b6.mov
> Civilized indexing progress reporting

- ghcide/src/Development/IDE/Main.hs
For users of ghcide as a library - right now it is impossible to register custom commands when using `defaultMain`
> Do not override custom commands

- ghcide/src/Development/IDE/LSP/LanguageServer.hs
Restarting the session will result in progress reporting and other messages
being sent to the client, which might have already closed the stream
Result of @berberman investigation in #1628
> Shut the Shake session on exit, instead of restarting it

- ghcide/src/Development/IDE/LSP/LanguageServer.hs
I believe that this will help understand the "resource vanished - broken pipe" test failures
> log exceptions before killing the server

- .github/workflows/bench.yml
- .github/workflows/test.yml
* Attempt to fix properly the combination of ignore paths and required build checks
* Unfortunately the unique solution i have found is make all steps of the build dedpend on the `skip-duplicate-action` outcome
* There is a feature request to make jobs exit early with a specific  status: https://github.com/actions/runner/issues/662 but is is not being implemented
> Fix ignore paths

- ghcide/src/Development/IDE/LSP/LanguageServer.hs
As discussed in #1628, there are two places where we call `exit`, so `Barrier` is no longer suitable in this case.
> Replace Barrier with MVar in lsp main

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/test/data/hiding/FVec.hs
- ghcide/test/data/hiding/HideQualifyDuplicateRecordFields.expected.hs
- ghcide/test/data/hiding/HideQualifyDuplicateRecordFields.hs
- ghcide/test/data/hiding/HideQualifyDuplicateRecordFieldsSelf.hs
- ghcide/test/exe/Main.hs
This pr is about #1457.
The details can be seen [here](https://github.com/haskell/haskell-language-server/issues/1457#issuecomment-812395051).
Please figure me out if I violated any rules about the project.
> optimize ambiguity import suggestions

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/Tracing.hs
This was done only for otTracedAction but not for otTracedHandler and otTracedProvider
> Skip tracing unless eventlog is enabled

- .github/workflows/test.yml
- plugins/hls-tactics-plugin/hls-tactics-plugin.cabal
- plugins/hls-tactics-plugin/test/Main.hs
- plugins/hls-tactics-plugin/test/Spec.hs
* tasty can show duration of each test case
* timeout set in `defaultTestRunner` can be applied
* cli options of the test executable are unified with others in our code base
> Wrap test suite of tactics plugin into tasty test tree

- exe/Main.hs
- exe/Wrapper.hs
- ghcide/exe/Arguments.hs
- ghcide/exe/Main.hs
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Main.hs
- ghcide/test/exe/Main.hs
- plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
- src/Ide/Arguments.hs
- src/Ide/Main.hs
Consolidated commands in `defaultMain` and added support for defining Custom ones
> support custom Ide commands

- ghcide/exe/Arguments.hs
- ghcide/exe/Main.hs
- ghcide/src/Development/IDE/Main.hs
- src/Ide/Arguments.hs
- src/Ide/Main.hs
We can't use `switch` with alternative combinators, since it never fails.
> Fix ghcide and HLS enter lsp mode by default

- plugins/hls-tactics-plugin/src/Wingman/Tactics.hs
- plugins/hls-tactics-plugin/test/CodeAction/DestructAllSpec.hs
- plugins/hls-tactics-plugin/test/golden/DestructAllFunc.hs
- plugins/hls-tactics-plugin/test/golden/DestructAllFunc.hs.expected
> Wingman: "Destruct all" only on ADTs

- haskell-language-server.cabal
- hls-plugin-api/hls-plugin-api.cabal
- hls-test-utils/hls-test-utils.cabal
- plugins/hls-brittany-plugin/hls-brittany-plugin.cabal
- plugins/hls-class-plugin/hls-class-plugin.cabal
- plugins/hls-eval-plugin/hls-eval-plugin.cabal
- plugins/hls-explicit-imports-plugin/hls-explicit-imports-plugin.cabal
- plugins/hls-haddock-comments-plugin/hls-haddock-comments-plugin.cabal
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
- plugins/hls-splice-plugin/hls-splice-plugin.cabal
- plugins/hls-stylish-haskell-plugin/hls-stylish-haskell-plugin.cabal
- plugins/hls-tactics-plugin/hls-tactics-plugin.cabal
* Bump lower bounds for `hls-plugin-api`
* Add bounds for `hls-test-utils`
* Fix invalid `homepage`
* Remove some redundant bounds
> Adjust bounds

- ChangeLog.md
- haskell-language-server.cabal
- plugins/hls-brittany-plugin/hls-brittany-plugin.cabal
- plugins/hls-class-plugin/hls-class-plugin.cabal
- plugins/hls-eval-plugin/hls-eval-plugin.cabal
- plugins/hls-explicit-imports-plugin/hls-explicit-imports-plugin.cabal
- plugins/hls-haddock-comments-plugin/hls-haddock-comments-plugin.cabal
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
- plugins/hls-splice-plugin/hls-splice-plugin.cabal
- plugins/hls-tactics-plugin/hls-tactics-plugin.cabal
I think we should release ghcide 1.2 first, no?
> Prepare 1.1.0 release

- .github/workflows/build.yml
- ChangeLog.md
- ghcide/CHANGELOG.md
- ghcide/ghcide.cabal
- haskell-language-server.cabal
- hls-test-utils/hls-test-utils.cabal
- plugins/hls-brittany-plugin/hls-brittany-plugin.cabal
- plugins/hls-class-plugin/hls-class-plugin.cabal
- plugins/hls-eval-plugin/hls-eval-plugin.cabal
- plugins/hls-explicit-imports-plugin/hls-explicit-imports-plugin.cabal
- plugins/hls-haddock-comments-plugin/hls-haddock-comments-plugin.cabal
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
- plugins/hls-splice-plugin/hls-splice-plugin.cabal
- plugins/hls-stylish-haskell-plugin/hls-stylish-haskell-plugin.cabal
- plugins/hls-tactics-plugin/hls-tactics-plugin.cabal
Closes #1681
This will be the final preparation for 1.1.0 release. We should create tag `ghcide-v1.2.0.2` and `1.1.0` on the squashed commit of this PR, and upload `ghcide-1.2.0.2` to hackage.
> Prepare ghcide 1.2.0.2 and HLS 1.1.0

- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/test/exe/Main.hs
fix: #1690
In follow up to my response to @July541's PR (#1694), I have written a different solution to cover the cases of filling holes with infix operators.
applying the "replace _ with (+)" code action to
```haskell
test :: Int -> Int -> Int
test a1 a2 = a1 `_` a2
```
now results in 
```haskell
test :: Int -> Int -> Int
test a1 a2 = a1 + a2
```
rather than 
```haskell
test :: Int -> Int -> Int
test a1 a2 = a1 `(+)` a2
```
Note: This solution depends on `processHoleSuggestions` returning infix functions in their prefix form (e.g. `(+)`) to determine if a function infix/prefix. I imagine there might be a nicer way of doing this.
Edit: In some commit messages I have written "postfix" by mistake instead of "prefix"
> Fix: #1690 - Infix typed holes are now filled using infix notation

- install/hls-install.cabal
This helps packaging on FreeBSD where we build installer executable as a
separate package.
> Add executable stanza in hls-install.cabal.

- README.md
As suggested in https://github.com/haskell/haskell-language-server/issues/703#issuecomment-815464067, suggesting an update to README Installation Instructions - adding Homebrew installation section.
> Add haskell-language-server Homebrew installation instructions

- plugins/hls-tactics-plugin/src/Wingman/CaseSplit.hs
- plugins/hls-tactics-plugin/test/CodeAction/DestructSpec.hs
- plugins/hls-tactics-plugin/test/golden/DestructPun.hs
- plugins/hls-tactics-plugin/test/golden/DestructPun.hs.expected
> Wingman: case split on punned record fields

- plugins/hls-tactics-plugin/src/Wingman/EmptyCase.hs
- plugins/hls-tactics-plugin/src/Wingman/LanguageServer.hs
- plugins/hls-tactics-plugin/src/Wingman/Plugin.hs
This PR adds heralds to Wingman's use of `runAction`. As a result, the debug logs now look like this:
```haskell
2021-04-16 12:44:22.935457349 [ThreadId 590] INFO hls:	finish: Wingman.getIdeDynflags.GetModSummaryWithoutTimestamps (took 0.00s)
2021-04-16 12:44:22.935495533 [ThreadId 592] INFO hls:	finish: codeLens.GetGlobalBindingTypeSigs (took 0.00s)
2021-04-16 12:44:22.935756369 [ThreadId 594] INFO hls:	finish: Wingman.codeLensProvider.GetAnnotatedParsedSource (took 0.00s)
2021-04-16 12:44:22.936314236 [ThreadId 598] INFO hls:	finish: ModuleName.GetParsedModule (took 0.00s)
2021-04-16 12:44:22.936271495 [ThreadId 596] INFO hls:	finish: Wingman.codeLensProvider.GetBindings (took 0.00s)
2021-04-16 12:44:22.93657869 [ThreadId 600] INFO hls:	finish: Wingman.emptyCaseScrutinees.TypeCheck …
```
> Add heralds to Wingman's use of runAction

- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- ghcide/test/exe/Main.hs
Fix #1738.
From [docs](https://hackage.haskell.org/package/ghc-8.6.5/docs/HsBinds.html#t:Sig), the signature of a class method should be `ClassOpSig`.
> Fix class method completion

- ghcide/src/Development/IDE/Core/FileStore.hs
Not sure why we don't have a warning check for unused imports? But this one seems to have slipped through.
> Delete an unused import

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/GHC/ExactPrint.hs
- ghcide/src/Generics/SYB/GHC.hs
- plugins/hls-tactics-plugin/src/Wingman/Plugin.hs
This PR is the first of a few to simplify the `ExactPrint` module. It separates the custom SYB stuff, which is more useful than just for ExactPrint.
> Tease apart the custom SYB from ExactPrint

- ghcide/src/Development/IDE/Core/FileExists.hs
- ghcide/src/Development/IDE/Core/FileStore.hs
- ghcide/src/Development/IDE/Core/IdeConfiguration.hs
- ghcide/src/Development/IDE/Core/OfInterest.hs
- ghcide/src/Development/IDE/Plugin/Completions.hs
The fact Shake exports liftIO is mostly because it wasn't in base when Shake started using it. Better to get it from the right place, as we usually do.
> Explicitly import liftIO if you need it, rather than getting it from Shake

- ghcide/src/Development/IDE/Core/Shake.hs
- hls-graph/hls-graph.cabal
- hls-graph/src/Development/IDE/Graph.hs
- hls-graph/src/Development/IDE/Graph/Database.hs
- hls-graph/src/Development/IDE/Graph/Internal/Action.hs
- hls-graph/src/Development/IDE/Graph/Internal/Options.hs
- hls-graph/src/Development/IDE/Graph/Internal/Rules.hs
- hls-graph/src/Development/IDE/Graph/Rule.hs
- stack-8.10.2.yaml
- stack-8.10.3.yaml
- stack-8.10.4.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack-8.8.4.yaml
- stack.yaml
To ensure that we really are using our own types, and our own library, it's useful to newtype wrap the Action, ShakeOptions and Rules types. That means that if we accidentally use Shake, it's a type error. It's also step 1 towards replacing Shake, but even if we don't, it makes the abstraction more robust.
In order to further enhance the abstraction, I've changed `addBuiltinRule` for `addRule` which doesn't do the linting and tracking stuff, and simplified the "extra" feature in Shake to only allow a single value, as that's all we need. Fairly minor changes, but cut down on the complexity of the interface to Shake, where we're only using a subset.
There's a potential performance cost to newtype wrapping when it's a list, but if we had to we could switch to the newtype coercion stuff, and …
> Wrap the Shake functions with newtypes

- ghcide/src/Development/IDE/Plugin/Completions.hs
- ghcide/src/Development/IDE/Plugin/HLS/GhcIde.hs
- ghcide/src/Development/IDE/Plugin/TypeLenses.hs
- hls-plugin-api/src/Ide/Plugin/ConfigUtils.hs
- hls-plugin-api/src/Ide/Types.hs
- plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
- plugins/hls-tactics-plugin/src/Wingman/Plugin.hs
As discussed in https://github.com/haskell/vscode-haskell/issues/378#issuecomment-820711751, in order to make the generated vscode extension schema more handy, this PR introduces a new data type taking place of the old `pluginCustomConfig` in `PluginDescriptor`:
```haskell
data ConfigDescriptor = ConfigDescriptor {
configEnableGenericConfig :: Bool,
configHasDiagnostics      :: Bool,
configCustomConfig        :: CustomConfig
}
```
* We shouold set `configHasDiagnostics` to `True` explicitly in plugin like hlint, so that we could generate `diagnosticsOn` option for it.
* Plugin will have single `globalOn` option only if it has one capability; otherwise we use specific capabilities such as `codeActionOn`, `codeLensOn`, etc. as options.
* Normally, we won't hope disable capabilities of …
> Improve vscode extension schema generation

- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/LSP/Notifications.hs
- ghcide/src/Development/IDE/Main.hs
This is to prevent progress messages being sent to the LSP client before Initialization is done, as discussed in #1749 and #1750.
> Delay the Shake session setup until the Initialized handler

- plugins/hls-tactics-plugin/src/Wingman/Auto.hs
- plugins/hls-tactics-plugin/src/Wingman/Context.hs
- plugins/hls-tactics-plugin/src/Wingman/KnownStrategies.hs
- plugins/hls-tactics-plugin/src/Wingman/LanguageServer.hs
- plugins/hls-tactics-plugin/src/Wingman/Plugin.hs
- plugins/hls-tactics-plugin/src/Wingman/Types.hs
> Wingman: configurable auto search depth

- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/test/exe/Main.hs
Fix #1768.
Normally, there only one ident info has the same name as the target module, but if the type constructor and the data constructor have the same name, it will deduce two, which causes the original matching pattern to fail and [fallback](https://github.com/haskell/haskell-language-server/blob/master/ghcide/src/Development/IDE/Plugin/CodeAction.hs#L790).
Without affecting the previous work, I re-ordered the match result by making the one with a parent in front of the one without if it has two items.
> Fix wrong extend import while type constuctor and data constructor have the same name

- nix/default.nix
This PR supersede #1779.
Fixes this GitHub nix action issue:
```
error: attribute 'run' missing, at /Users/runner/work/haskell-language-server/haskell-language-server/nix/default.nix:83:24
(use '--show-trace' to show detailed location information)
Error: Process completed with exit code 1.
```
> Pin nix-pre-commit-hooks

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/OfInterest.hs
- ghcide/src/Development/IDE/Core/ProgressReporting.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/Types/Options.hs
- ghcide/test/exe/Main.hs
- hls-test-utils/src/Test/Hls.hs
- plugins/hls-splice-plugin/test/Main.hs
- test/utils/Test/Hls/Command.hs
Rework of #1770. Summary of changes:
1. progress reporting logic extracted into its own module
2. Removed one layer of async handling, reducing the chances of race conditions
3. Correctly implement the LSP spec for `window/workDoneProgress/create` by waiting until the client has responded
4. Fix bugs: division by zero (when `todo` is 0) and handling when `NoProgress` 
5. Performance: the reporting loop is now O(1) instead of O(N) in the number of files
I think this is the best we can do to close #1749 while sharing the same logic for both tests and app code
> Progress reporting improvements

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/ProgressReporting.hs
- ghcide/test/exe/Main.hs
- ghcide/test/exe/Progress.hs
Fix a bug introduced in #1784 - progress counting is now done using two counters instead of `HashMap` traversals for efficiency, second attempt to get the logic right.
Added some unit tests too.
I suspect that there are more bugs left...
> Fix progress counting

- hls-test-utils/hls-test-utils.cabal
Hackage rejects packages without bounds on `base`.
> Add bounds for base in hls-test-utils

- plugins/hls-stylish-haskell-plugin/hls-stylish-haskell-plugin.cabal
That was my fault ─ I'll pay attention to the bounds of `base` package next time.
> Add bounds for base in hls-stylish-haskell-plugin

- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
* Without the upper bound, cabal picks hlint-3.* which brings ghc-lib-9.* causing compile errors (what this has not been catched by ci before?)
* This has to be backported to hackage-1.1.0 to make progress towards #1774
> Add upper bound to hlint

- ghcide/test/exe/Main.hs
Before https://github.com/haskell/haskell-language-server/pull/1578 signatures in multiple lines didn't create any suggestions. The deleted test intended to showcase this, however the actual reason it didn't create any suggestion was that it had a parser error: note that `=> a -> Bool` starts at the begining of the line. 
After https://github.com/haskell/haskell-language-server/pull/1578 multiline signatures create suggestions, so new tests are added instead.
> Replace faulty signature test

- plugins/hls-refine-imports-plugin/src/Ide/Plugin/RefineImports.hs
- plugins/hls-refine-imports-plugin/test/testdata/F.hs
- plugins/hls-refine-imports-plugin/test/testdata/G.hs
- plugins/hls-refine-imports-plugin/test/testdata/WithOverride.expected.hs
- plugins/hls-refine-imports-plugin/test/testdata/WithOverride.hs
- plugins/hls-refine-imports-plugin/test/testdata/hie.yaml
The problem
If module F imports and exports G, but it also has it's own bindings defined like this:
```
module F (module F, module G) where
import G
f1 :: String
f1 = "f1"
```
And the usage of F is
```
import F (f1, g1)
```
before this pr it will suggest refinement like
```
import G (g1)
```
This is definitely wrong.
The correct one should be not suggesting refinement in this case, since `f1` is definitely needed, so does module F
See the attached test change for full example
> Fix unwanted import refinement

- exe/Wrapper.hs
- install/src/Cabal.hs
- install/src/Stack.hs
- src/Ide/Version.hs
Closes #1728
As discussed in the issue, executables like `haskell-language-server-8.10` are really confusing - they could be the symlink of `haskell-language-server-8.10.2`, `haskell-language-server-8.10.3`, or even `haskell-language-server-8.10.4`, but those are definitely not interchangeable. So it's time to remove them. Now running `./cabal-hls-install hls-8.10.4` will create `haskell-language-server-wrapper`, `haskell-language-server`, and `haskell-language-server-8.10.4`.
> Remove hls-ghc-x.y from install script and wrapper

- ghcide/src/Development/IDE/Core/Rules.hs
Path comparisons are not accurate if non canonical. This is causing some unnecessary re-indexing of hie files on my end
> Canonicalize hiedb path before comparing

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/FileStore.hs
- ghcide/src/Development/IDE/Core/RuleTypes.hs
- ghcide/test/exe/Main.hs
We don't need the 2X faster but unsafe getmodtime anymore since GetModificationTime is no longer called O(N) times but only O(FOI) times, where N is the number of known targets and FOI is the number of files of interest.
The main problem with the internal implementation of `getModTime` is that it's not cross platform. The `unix` package implements support for more platforms: https://github.com/haskell/unix/blob/master/System/Posix/Files/Common.hsc#L344-L365
This change switches to the safer `unix` implementation, which provides nanosecond resolution in systems that support it.
> Replace the unsafe getmodtime with safe posix calls

- ghcide/CHANGELOG.md
- ghcide/bench/config.yaml
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/OfInterest.hs
- ghcide/src/Development/IDE/Core/RuleTypes.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- haskell-language-server.cabal
- hls-graph/hls-graph.cabal
- hls-graph/src/Development/IDE/Graph.hs
- hls-plugin-api/hls-plugin-api.cabal
- hls-plugin-api/src/Ide/Plugin/ConfigUtils.hs
- hls-test-utils/hls-test-utils.cabal
- plugins/hls-brittany-plugin/hls-brittany-plugin.cabal
- plugins/hls-class-plugin/hls-class-plugin.cabal
- plugins/hls-eval-plugin/hls-eval-plugin.cabal
- plugins/hls-explicit-imports-plugin/hls-explicit-imports-plugin.cabal
- plugins/hls-haddock-comments-plugin/hls-haddock-comments-plugin.cabal
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-refine-imports-plugin/hls-refine-imports-plugin.cabal
- plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
- plugins/hls-splice-plugin/hls-splice-plugin.cabal
- plugins/hls-stylish-haskell-plugin/hls-stylish-haskell-plugin.cabal
- plugins/hls-tactics-plugin/hls-tactics-plugin.cabal
I have tried to relax constraints where possible and bump version numbers where needed, but this is impossibly hard to get right without some automation.
Once the release is landed, I plan to upload the following to Hackage:
- ghcide
- his-plugin-api
- hls-graph
- explicit imports plugin
EDIT: took the chance to include some pure refactorings that change module signatures.
> Prepare ghcide release v1.3.0.0

- .github/workflows/bench.yml
- cabal.project
- haskell-language-server.cabal
- nix/default.nix
- plugins/hls-floskell-plugin/LICENSE
- plugins/hls-floskell-plugin/hls-floskell-plugin.cabal
- plugins/hls-floskell-plugin/src/Ide/Plugin/Floskell.hs
- plugins/hls-floskell-plugin/test/Main.hs
- plugins/hls-floskell-plugin/test/testdata/Floskell.formatted_document.hs
- plugins/hls-floskell-plugin/test/testdata/Floskell.formatted_range.hs
- plugins/hls-floskell-plugin/test/testdata/Floskell.hs
- stack-8.10.2.yaml
- stack-8.10.3.yaml
- stack-8.10.4.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.2.yaml
- stack-8.8.3.yaml
- stack-8.8.4.yaml
- stack.yaml
- test/functional/Format.hs
Its basic structure is copied from `hls-brittany-plugin`.
> Extract floskell plugin as a standalone plugin

- plugins/hls-tactics-plugin/src/Wingman/Tactics.hs
- plugins/hls-tactics-plugin/test/CodeAction/RefineSpec.hs
- plugins/hls-tactics-plugin/test/golden/RefineGADT.expected.hs
- plugins/hls-tactics-plugin/test/golden/RefineGADT.hs
- plugins/hls-tactics-plugin/test/golden/RefineReader.expected.hs
- plugins/hls-tactics-plugin/test/golden/RefineReader.hs
Refine was a little too eager; building single constructors before we had a chance to destructure the ones it bound.
> Refine should either do intros or split, not both

- .github/workflows/nix.yml
We should skip running cachix jobs on PRs opend from forked repos
> Skip cachix jobs if token is unset

- shell.nix
Closes #1846
We should enter `devShell` rather than the shell of `defaultPackage`.
> Fix flake compat

- ghcide/src/Development/IDE/Core/FileStore.hs
`GetModificationTime_ True` and `GetModificationTime_ False` are equal and have the same hash, so we are effectively deleting the same key twice, which is redundant.
We can further simplify by using the pattern synonym which hides this implementation detail.
> No need to delete the same key twice

- .github/mergify.yml
- .github/workflows/nix.yml
- default.nix
We have decided to maintain the nix packaging (building HLS binaries in nix) in #1827. Ideally, we are always have HLS binaries prepared without `cabal-install`. However, PRs that update project dependencies like #1858 may be blocked by nix ci, since nixpkgs does not have the new dependency yet, and even if it has, a bump of nixpkgs is required. It's unreasonable to require every contributor to handle nix things, so this PR add a fallback in CI, which uses `cabal-install` to build HLS in case some required packages are missing in nixpkgs.
Also adds `default.nix`, so that the legacy `nix-build` can work.
> Use cabal-install if nix is failing in CI

- .github/workflows/nix.yml
Following #1859
Just figured out it should be `refs/heads/master` instead of `ref/heads/master`...
> Fix condition of nix build job

- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/src/Development/IDE/Plugin/CodeAction/Args.hs
- ghcide/src/Development/IDE/Plugin/HLS/GhcIde.hs
This PR attempts to split the big code action provider in ghcide. I want to minimize the trivial changes in implementation functions (`suggestExtendImport`, `suggestImportDisambiguation`, etc.), so I refactored `Development.IDE.Plugin.CodeAction.Args` to keep the automatic function arguments passing, making it compatible with the old code. However, iiuc the provider should be broken down into different **providers**, rather than **descriptors** like this PR does. One of our initial goals is to make those code actions switchable,  but providers are anonymous, whereas descriptors have their names, so it's not clear how to generate configuration per provider. Thus this PR introduces some new descriptors for ghcide code actions. This might not be reasonable, but with the abstraction of …
> Split ghcide actions into different descriptors

- plugins/hls-fourmolu-plugin/src/Ide/Plugin/Fourmolu.hs
- plugins/hls-ormolu-plugin/src/Ide/Plugin/Ormolu.hs
Nobody likes `PackageImports`. And it's unnecessary since #1823.
> Avoid package-qualified import in Fourmolu plugin

- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/Core/Tracing.hs
Opentelemetry traces have proven very useful for understanding the evaluation and performance of the Shake rules. This change adds more information to those traces:
- What mode a rule is running in - is this a full rerun (dependencies changed) or just a lookup in the values state?
- Whether the rule value changed after running
> Trace more Shake evaluation details

- .github/workflows/bench.yml
- .github/workflows/nix.yml
- .github/workflows/test.yml
- flake.nix
IIUC, nixpkgs won't have `apply-refact-0.9.3.0` which we introduced in #1858 at least in two weeks, so we'd better add this package ourselves for now, in case someone wants to use binaries produced by `nix build`.
> Fix nix build for #1858

- README.md
> Update IRC details in README.md

- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/src/Development/IDE.hs
- ghcide/src/Development/IDE/Core/Actions.hs
- ghcide/src/Development/IDE/Core/FileExists.hs
- ghcide/src/Development/IDE/Core/FileStore.hs
- ghcide/src/Development/IDE/Core/OfInterest.hs
- ghcide/src/Development/IDE/Core/RuleTypes.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/LSP/Notifications.hs
- ghcide/src/Development/IDE/Main.hs
- ghcide/src/Development/IDE/Types/Options.hs
- ghcide/src/Development/IDE/Types/Shake.hs
- ghcide/test/exe/Main.hs
- hls-graph/src/Development/IDE/Graph/Database.hs
- plugins/default/src/Ide/Plugin/Example.hs
- plugins/default/src/Ide/Plugin/Example2.hs
- plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
- plugins/hls-tactics-plugin/src/Wingman/LanguageServer.hs
_NOTE: This is a technology preview of something I have been working on for several months. It requires extending `his-graph` to accept the set of keys that have changed since the last build as an input, of which there isn't a final implementation yet. There is a Shake implementation (https://github.com/ndmitchell/shake/pull/802), but it might end up being reimplemented  in #1759 instead. Details still being worked out._
This PR extends ghcide to keep track of the set of rules that have changed since the last successful build. This information is then shard with his-graph, which can then use it to minimize the amount of build rules visited.
When his-graph runs a rule, it first tells it whether its dependencies have changed. Ghcide uses this information to skip evaluation and perform a …
> Technology preview: Keep track of changes to minimize rebuilds

- plugins/hls-tactics-plugin/src/Wingman/CodeGen.hs
- plugins/hls-tactics-plugin/src/Wingman/Context.hs
- plugins/hls-tactics-plugin/src/Wingman/GHC.hs
- plugins/hls-tactics-plugin/src/Wingman/Judgements.hs
- plugins/hls-tactics-plugin/src/Wingman/LanguageServer.hs
- plugins/hls-tactics-plugin/src/Wingman/Machinery.hs
- plugins/hls-tactics-plugin/src/Wingman/Tactics.hs
- plugins/hls-tactics-plugin/src/Wingman/Types.hs
- plugins/hls-tactics-plugin/test/AutoTupleSpec.hs
- plugins/hls-tactics-plugin/test/CodeAction/DestructSpec.hs
- plugins/hls-tactics-plugin/test/golden/DestructDataFam.expected.hs
- plugins/hls-tactics-plugin/test/golden/DestructDataFam.hs
- plugins/hls-tactics-plugin/test/golden/DestructTyFam.expected.hs
- plugins/hls-tactics-plugin/test/golden/DestructTyFam.hs
- plugins/hls-tactics-plugin/test/golden/DestructTyToDataFam.expected.hs
- plugins/hls-tactics-plugin/test/golden/DestructTyToDataFam.hs
This PR fixes a bug where type families would be opaque to Wingman, even if they weren't stuck. Now, we normalize any types coming into the judgment.
Fixes #1874
> Let Wingman peek through type families

- plugins/hls-explicit-imports-plugin/src/Ide/Plugin/ExplicitImports.hs
This is intended for custom LSP servers and generalises the current filtering of Prelude
> [explicit-imports] Take in a predicate to filter modules

- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/src/Development/IDE/LSP/LanguageServer.hs
- ghcide/src/Development/IDE/Main.hs
lsp HEAD no longer sets the current directory to the workspace root (https://github.com/haskell/lsp/pull/326) so we need to remove this assumption from the ghcide codebase. There are 3 places where this is relevant:
1. In the call to `loadCradle`, or rather, in the GHC session returned by it, where any relative paths in the flags returned by the cradle will expect to be resolved from the directory where the `hie.yaml` file lives - should change the working directory to the hie.yaml location
2. In the logic to `setInitialDynFlags`, where we search for a `hie.yaml` file in the current directory - should use the workspace root instead
3. In the LSP initialisation handler, where the current directory is included in the hiedb cache dir hash - should use the workspace root instead
> Fix getCurrentDirectory calls in ghcide

- .circleci/config.yml
Figuring out stuff from circleci logs is currently pretty annoying due to stack's ansi terminal progress output:
This are great when running stack interactively, but they clutter output in CI.
This behavior can be disabled by using `--no-terminal`. From `stack build --help`:
```
--[no-]terminal          Enable/disable overriding terminal detection in the
case of running in a false terminal
```
> Cleanup stack build output in circleci

- .github/workflows/bench.yml
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Spans/AtPoint.hs
When reusing .hie files from a cloud cache, the paths may not match the local file system. 
Let's fall back to the hiedb in case it contains local paths
> Fall back to hiedb for invalid srcspan paths

- plugins/hls-refine-imports-plugin/hls-refine-imports-plugin.cabal
It's currently missing in the hackage tarball:
```
Refine Imports
WithOverride (golden): Error while initializing: ResponseError {_code = InternalError, _message = "Error on initialize: /build/haskell-hls-refine-imports-plugin/src/hls-refine-imports-plugin-1.0.0.0/test/testdata: changeWorkingDirectory: does not exist (No such file or directory)", _xdata = Nothing}
Error while initializing: ResponseError {_code = InternalError, _message = "Error on initialize: /build/haskell-hls-refine-imports-plugin/src/hls-refine-imports-plugin-1.0.0.0/test/testdata: changeWorkingDirectory: does not exist (No such file or directory)", _xdata = Nothing}
FAIL (1.42s)
```
> Include testdata in hls-refine-imports-plugin.cabal

- plugins/hls-tactics-plugin/src/Wingman/Metaprogramming/Lexer.hs
- plugins/hls-tactics-plugin/test/CodeAction/RunMetaprogramSpec.hs
- plugins/hls-tactics-plugin/test/golden/MetaUseSymbol.expected.hs
- plugins/hls-tactics-plugin/test/golden/MetaUseSymbol.hs
The metaprogram parser used to choke on symbol identifiers, which meant it was impossible to ever reference things like `(<>)`. This works correctly now.
> Allow symbol identifiers in tactics

- plugins/hls-tactics-plugin/COMMANDS.md
- plugins/hls-tactics-plugin/src/Wingman/KnownStrategies.hs
- plugins/hls-tactics-plugin/src/Wingman/Metaprogramming/Parser.hs
- plugins/hls-tactics-plugin/src/Wingman/Metaprogramming/Parser.hs-boot
- plugins/hls-tactics-plugin/src/Wingman/Metaprogramming/Parser/Documentation.hs
- plugins/hls-tactics-plugin/test/CodeAction/RunMetaprogramSpec.hs
- plugins/hls-tactics-plugin/test/golden/MetaPointwise.expected.hs
- plugins/hls-tactics-plugin/test/golden/MetaPointwise.hs
This PR adds the `pointwise` command, which restricts the hypotheses available to holes so that they line up with top-level destructed terms.
> Add pointwise command to the metaprogram parser

- plugins/hls-tactics-plugin/src/Wingman/Context.hs
- plugins/hls-tactics-plugin/src/Wingman/EmptyCase.hs
- plugins/hls-tactics-plugin/src/Wingman/GHC.hs
- plugins/hls-tactics-plugin/src/Wingman/Judgements/Theta.hs
- plugins/hls-tactics-plugin/src/Wingman/KnownStrategies.hs
- plugins/hls-tactics-plugin/src/Wingman/LanguageServer.hs
- plugins/hls-tactics-plugin/src/Wingman/LanguageServer/Metaprogram.hs
- plugins/hls-tactics-plugin/src/Wingman/LanguageServer/TacticProviders.hs
- plugins/hls-tactics-plugin/src/Wingman/Machinery.hs
- plugins/hls-tactics-plugin/src/Wingman/Metaprogramming/Lexer.hs
- plugins/hls-tactics-plugin/src/Wingman/Metaprogramming/Parser.hs
- plugins/hls-tactics-plugin/src/Wingman/Plugin.hs
- plugins/hls-tactics-plugin/src/Wingman/Types.hs
- plugins/hls-tactics-plugin/test/AutoTupleSpec.hs
- plugins/hls-tactics-plugin/test/UnificationSpec.hs
I'd managed to keep `IO` out of `TacticsM` thus far, but over time, it was beginning to creek. Rather than just looking up things like `Monoid` if they were needed, I'd build a big static map of everything that might need to be looked up (`KnownThings`). And then, since user code in the metaprograms would need to look things up in the module, I stuck the _parser_ in `IO`, plus a bunch of tomfoolery to make everything work. 
This PR just bites the bullet and puts some `IO` into `TacticsM`, allowing for runtime lookups. In doing so, it removes `KnownThings` and a bunch of cruft around the `Parser`. Everything is cleaner and there's a lot of red.
> Perform name lookup directly in TacticsM

- docs/releases.md
> Add manual upload instructions

- .github/workflows/build.yml
- .github/workflows/test.yml
As pointed out by @mouse07410 in #1913, we can build HLS with GHC 8.10.5 on macOS just by removing CommandLineTools from the environment.
This PR tries to adopt this workaround in a rather ad-hoc manner.
> Workaround for GHC 8.10.5 on macOS

- plugins/hls-tactics-plugin/src/Wingman/CodeGen.hs
- plugins/hls-tactics-plugin/src/Wingman/Judgements.hs
- plugins/hls-tactics-plugin/src/Wingman/Judgements/Theta.hs
- plugins/hls-tactics-plugin/src/Wingman/Machinery.hs
- plugins/hls-tactics-plugin/src/Wingman/Tactics.hs
- plugins/hls-tactics-plugin/src/Wingman/Types.hs
- plugins/hls-tactics-plugin/test/CodeAction/RunMetaprogramSpec.hs
- plugins/hls-tactics-plugin/test/golden/MetaCataAST.expected.hs
- plugins/hls-tactics-plugin/test/golden/MetaCataAST.hs
Wingman was incorrectly adding GADT equalities to the global substitution, meaning it would think type equalities persisted between GADT branches. This lead to #1937, and is easily fixed by tracking this evidence in the local `Judgment`, rather than the global `TacticState`.
Fixes #1937
> Properly scope GADT equality evidence in the judgment

- plugins/hls-tactics-plugin/COMMANDS.md
- plugins/hls-tactics-plugin/src/Wingman/GHC.hs
- plugins/hls-tactics-plugin/src/Wingman/KnownStrategies.hs
- plugins/hls-tactics-plugin/src/Wingman/Metaprogramming/Parser.hs
- plugins/hls-tactics-plugin/src/Wingman/Metaprogramming/Parser/Documentation.hs
- plugins/hls-tactics-plugin/src/Wingman/Tactics.hs
- plugins/hls-tactics-plugin/test/CodeAction/RunMetaprogramSpec.hs
- plugins/hls-tactics-plugin/test/golden/MetaDeepOf.expected.hs
- plugins/hls-tactics-plugin/test/golden/MetaDeepOf.hs
- plugins/hls-tactics-plugin/test/golden/MetaTry.hs
- plugins/hls-tactics-plugin/test/golden/MetaWithArg.expected.hs
- plugins/hls-tactics-plugin/test/golden/MetaWithArg.hs
This PR is a bit of a hodge-podge, sorry! It primarily removes the `try` and `*` tactic operators, replacing them with better functionality. 
`try` has become a regular tactic, while `*` deserves to rot away. Instead, there is now `nested` which nests a function call into itself as many times as necessary to typecheck. This is the original motivation for `*`, but it never actually succeeded at that.
In order to get `nested` working, I needed to be able to work with _unsaturated_ function applications (Wingman tries really hard to saturate everything, and then eta reduce everything before presenting it.) The application tactics now take a new `Saturation` parameter, letting you tweak how many unsaturated arguments they take, and there's a corresponding `with_arg` tactic to shift into an …
> Wingman: Tactical support for deep recursion

- plugins/hls-tactics-plugin/src/Wingman/Auto.hs
- plugins/hls-tactics-plugin/src/Wingman/Context.hs
- plugins/hls-tactics-plugin/src/Wingman/KnownStrategies.hs
- plugins/hls-tactics-plugin/src/Wingman/Machinery.hs
- plugins/hls-tactics-plugin/src/Wingman/Metaprogramming/Parser.hs
- plugins/hls-tactics-plugin/src/Wingman/Tactics.hs
- plugins/hls-tactics-plugin/test/CodeAction/AutoSpec.hs
- plugins/hls-tactics-plugin/test/golden/AutoTypeLevel.expected.hs
- plugins/hls-tactics-plugin/test/golden/AutoTypeLevel.hs
This PR makes `getCurrentDefinitions` return polymorphic types, which in turn allows the `recursion` tactic to do polymorphic recursion. Combined with #1942, this means Wingman is now smart enough to `auto` its way through some dependently-typed programs.
> Wingman: Make getCurrentDefinitions return polymorphic types

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/Compile.hs
This can save significant amounts of memory on large repos, as shown by the heap profiles generated using the edit experiment on a module with >10K transitive deps.
BEFORE
AFTER
> avoid holding onto the hie bytestring when indexing

- plugins/hls-eval-plugin/hls-eval-plugin.cabal
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs
- plugins/hls-eval-plugin/test/Main.hs
- plugins/hls-eval-plugin/test/cabal.project
- plugins/hls-eval-plugin/test/info-util/InfoUtil.hs
- plugins/hls-eval-plugin/test/info-util/info-util.cabal
- plugins/hls-eval-plugin/test/testdata/TI_Info.hs
- plugins/hls-eval-plugin/test/testdata/TInfo.hs
- plugins/hls-eval-plugin/test/testdata/TInfoBang.hs
- plugins/hls-eval-plugin/test/testdata/TInfoBangMany.hs
- plugins/hls-eval-plugin/test/testdata/TInfoMany.hs
- plugins/hls-eval-plugin/test/testdata/cabal.project
- plugins/hls-eval-plugin/test/testdata/test.cabal
99% of the code is copied from [`GHCi.UI.info`](https://gitlab.haskell.org/ghc/ghc/-/blob/master/ghc/GHCi/UI.hs#L1529) and the functions called from there. Ideally this would be exported from `GHCi.UI` but sadly that's not the case.
Note that the tests commit is marked as [WIP] because, when running the tests on my machine, I keep getting the instances in different orders. I haven't been able to figure out the source of nondeterminism.
This should eventually close #402
> Add :info command in Eval plugin

- ghcide/src/Development/IDE/GHC/ExactPrint.hs
- plugins/hls-tactics-plugin/src/Wingman/EmptyCase.hs
- plugins/hls-tactics-plugin/src/Wingman/GHC.hs
- plugins/hls-tactics-plugin/test/CodeLens/EmptyCaseSpec.hs
- plugins/hls-tactics-plugin/test/golden/EmptyCaseLamCase.expected.hs
- plugins/hls-tactics-plugin/test/golden/EmptyCaseLamCase.hs
> Wingman: Code lens for empty lambda case

- .github/workflows/build.yml
- cabal-ghc901.project
- cabal.project
See also discussion here: https://github.com/haskell/haskell-language-server/pull/1912#issuecomment-862982762
Is this sensible, @jneira?
> Add ghc-9.0.1 to the build release script

- plugins/hls-tactics-plugin/src/Wingman/LanguageServer/TacticProviders.hs
- plugins/hls-tactics-plugin/src/Wingman/Machinery.hs
- plugins/hls-tactics-plugin/src/Wingman/Tactics.hs
- plugins/hls-tactics-plugin/test/CodeAction/DestructSpec.hs
- plugins/hls-tactics-plugin/test/ProviderSpec.hs
- plugins/hls-tactics-plugin/test/golden/ProviderHomomorphism.hs
This PR changes the behavior of the `homo` tactic, ensuring that it is total and well-typed to apply. Before, it would just automatically fill in the data constructors, regardless of whether they were the right type. The new logic is to check which data constructors are possible in the domain, and which in the codomain, and to subtract the latter from the former. If this set is non-empty, it means either the thing won't type check, or that due to some GADT equalities, it's impossible to map some constructors. Either way, the tactic should fail, and does now.
Fixes #565
> Wingman: Ensure homomorphic destruct covers all constructors in the domain

- plugins/hls-tactics-plugin/src/Wingman/LanguageServer/Metaprogram.hs
- plugins/hls-tactics-plugin/src/Wingman/Metaprogramming/Parser.hs
Fixes #1964 
This is a hard thing to test, so I tested it by eyeball instead.
> Wingman: Add the correct file offset to metaprogram parse errors

- plugins/hls-tactics-plugin/src/Wingman/Tactics.hs
- plugins/hls-tactics-plugin/test/CodeAction/RunMetaprogramSpec.hs
- plugins/hls-tactics-plugin/test/golden/IntrosTooMany.expected.hs
- plugins/hls-tactics-plugin/test/golden/IntrosTooMany.hs
> Wingman: Don't introduce too many variables

- plugins/hls-tactics-plugin/src/Wingman/EmptyCase.hs
- plugins/hls-tactics-plugin/test/CodeLens/EmptyCaseSpec.hs
- plugins/hls-tactics-plugin/test/Utils.hs
- plugins/hls-tactics-plugin/test/golden/EmptyCaseSpuriousGADT.hs
> Wingman: Don't suggest empty case lenses for case exprs with no data cons

- plugins/hls-tactics-plugin/src/Wingman/LanguageServer.hs
- plugins/hls-tactics-plugin/src/Wingman/Metaprogramming/Parser.hs
- plugins/hls-tactics-plugin/src/Wingman/Metaprogramming/ProofState.hs
- plugins/hls-tactics-plugin/src/Wingman/Types.hs
> Wingman: Config option to suppress proofstate styling

- plugins/hls-tactics-plugin/hls-tactics-plugin.cabal
The plugin builds fine with megaparsec-8.0
> relax megaparsec constraint in hls-tactics-plugin

- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/test/exe/Main.hs
Usually, when the type constructor is used but the data constructor isn't, we
only suggest importing the type constructor. When the data constructor and type
constructor share the same name we get mixed up and suggest importing both.
The solution is to do a better job filtering out the data cons when we know we
are looking for a type con.
Closes #1932 .
> Don't suggest import an unnecessary data constructor.

- cabal-ghc901.project
- cabal.project
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/OfInterest.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/Types/Exports.hs
- stack-8.10.2.yaml
- stack-8.10.3.yaml
- stack-8.10.4.yaml
- stack-8.10.5.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.3.yaml
- stack-8.8.4.yaml
- stack-9.0.1.yaml
- stack.yaml
> Initialize ExportsMap using hiedb exports

- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/Import/FindImports.hs
The goal is to avoid having multiple copies of the same `NormalizedFilePath` value in the heap. 
A previous attempt was using hash consing (https://github.com/haskell/lsp/pull/340) but I think this small change should be enough.
> Maximize sharing of NormalizedFilePath values in getLocatedImports

- .github/workflows/nix.yml
- cabal-ghc901.project
- configuration-ghc-901.nix
- flake.nix
- stack-9.0.1.yaml
As discussed in https://github.com/haskell/haskell-language-server/issues/1871#issuecomment-859990650, this PR attempts to maintain a nix configuration that works for ghc 9.0.1. It's still work in progress, see the CI for results.
> nix: add support for ghc 9.0.1

- cabal-ghc901.project
- configuration-ghc-901.nix
- stack-9.0.1.yaml
* To fix ci for ghc-9.0.1
* Fixes #2016
> Use operational master commit to fix build for ghc-9.0.1

- .github/workflows/test.yml
- test/functional/FunctionalCodeAction.hs
* The job is being flaky since i added it, it usually hangs until is cancelled
* Let's see if we can workaround it only disabling hls tests
> Disable hls tests for win and ghc-9.0.1

- .circleci/config.yml
- stack-8.10.2.yaml
- stack-8.10.3.yaml
- stack-8.10.4.yaml
- stack-8.10.5.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.3.yaml
- stack-8.8.4.yaml
- stack-9.0.1.yaml
- stack.yaml
CircleCI is running OOM during linking (except in the 9.0.1 build for some reason). 
I don't know what has changed, but perhaps we can simply avoid linking at all?
I don't use stack so this change is untested - let's see if it helps.
> Enable dynamic linking in stack builds

- ghcide/bench/config.yaml
- ghcide/bench/lib/Experiments.hs
- ghcide/ghcide.cabal
- ghcide/test/exe/Main.hs
- ghcide/test/src/Development/IDE/Test.hs
- ghcide/test/src/Development/IDE/Test/Diagnostic.hs
Let's find out how expensive hole fits are across GHC versions and benchmark examples
> Add benchmarks for hole fits

- ghcide/src/Development/IDE/GHC/Orphans.hs
- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/src/Development/IDE/Plugin/Completions.hs
- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- ghcide/src/Development/IDE/Plugin/Completions/Types.hs
- ghcide/src/Development/IDE/Types/Exports.hs
- ghcide/test/exe/Main.hs
- plugins/hls-tactics-plugin/src/Wingman/Types.hs
Provide completions for non-imported modules and automatically inserts new imports when necessary. The identifiers are extracted from the exports map, which no longer includes entries from `*.Internal` modules. 
Things left for future work:
- Qualified imports
- Better display of completion suggestions by default
This partially closes #1327
https://user-images.githubusercontent.com/26626/127127619-d92ba213-65d8-409c-a73d-35bbe13cc759.mov
> Completions from non-imported modules

- .circleci/config.yml
- stack-8.10.2.yaml
- stack-8.10.3.yaml
- stack-8.10.4.yaml
- stack-8.10.5.yaml
- stack-8.6.4.yaml
- stack-8.6.5.yaml
- stack-8.8.3.yaml
- stack-8.8.4.yaml
- stack-9.0.1.yaml
* From #2038
* Build times are close to having `.stack-work` and we avoid issues with conflicts in the linker phase 
* https://app.circleci.com/pipelines/github/jneira/haskell-language-server/644/workflows/ba2d76ab-341b-4bb0-a2df-109a677878e2
> Remove .stack-work from circleci cache

- ChangeLog.md
- ghcide/ghcide.cabal
- haskell-language-server.cabal
- hie-compat/hie-compat.cabal
- hls-plugin-api/hls-plugin-api.cabal
- hls-test-utils/hls-test-utils.cabal
- plugins/hls-brittany-plugin/hls-brittany-plugin.cabal
- plugins/hls-call-hierarchy-plugin/hls-call-hierarchy-plugin.cabal
- plugins/hls-class-plugin/hls-class-plugin.cabal
- plugins/hls-eval-plugin/hls-eval-plugin.cabal
- plugins/hls-explicit-imports-plugin/hls-explicit-imports-plugin.cabal
- plugins/hls-floskell-plugin/hls-floskell-plugin.cabal
- plugins/hls-fourmolu-plugin/hls-fourmolu-plugin.cabal
- plugins/hls-haddock-comments-plugin/hls-haddock-comments-plugin.cabal
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-module-name-plugin/hls-module-name-plugin.cabal
- plugins/hls-ormolu-plugin/hls-ormolu-plugin.cabal
- plugins/hls-pragmas-plugin/hls-pragmas-plugin.cabal
- plugins/hls-refine-imports-plugin/hls-refine-imports-plugin.cabal
- plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
- plugins/hls-splice-plugin/hls-splice-plugin.cabal
- plugins/hls-stylish-haskell-plugin/hls-stylish-haskell-plugin.cabal
- plugins/hls-tactics-plugin/hls-tactics-plugin.cabal
CC: @jneira, @berberman, @pepeiborra, @isovector
Resolves partially: #1990.
> Prepare 2021 July Release [HLS 1.3.0]

- plugins/hls-pragmas-plugin/src/Ide/Plugin/Pragmas.hs
- plugins/hls-pragmas-plugin/test/Main.hs
- plugins/hls-pragmas-plugin/test/testdata/DeferredTypeErrors.expected.hs
- plugins/hls-pragmas-plugin/test/testdata/DeferredTypeErrors.hs
> Don't suggest disabling type errors

- plugins/hls-tactics-plugin/hls-tactics-plugin.cabal
- plugins/hls-tactics-plugin/src/Wingman/LanguageServer/TacticProviders.hs
- plugins/hls-tactics-plugin/src/Wingman/Metaprogramming/Parser.hs
- plugins/hls-tactics-plugin/src/Wingman/Tactics.hs
- plugins/hls-tactics-plugin/src/Wingman/Types.hs
- plugins/hls-tactics-plugin/test/CodeAction/IntroDestructSpec.hs
- plugins/hls-tactics-plugin/test/golden/IntroDestructLetBinding.expected.hs
- plugins/hls-tactics-plugin/test/golden/IntroDestructLetBinding.hs
- plugins/hls-tactics-plugin/test/golden/IntroDestructMany.expected.hs
- plugins/hls-tactics-plugin/test/golden/IntroDestructMany.hs
- plugins/hls-tactics-plugin/test/golden/IntroDestructOne.expected.hs
- plugins/hls-tactics-plugin/test/golden/IntroDestructOne.hs
- plugins/hls-tactics-plugin/test/golden/IntroDestructProvider.hs
The number of times I find myself refining a lambda and then immediately destruct it is staggering, so I thought --- why not put them together into one.
> Wingman: "Intro and destruct" code action

- plugins/hls-brittany-plugin/LICENSE
- plugins/hls-brittany-plugin/hls-brittany-plugin.cabal
- plugins/hls-brittany-plugin/src/Ide/Plugin/Brittany.hs
This is the same function I have written for my brittany PR(https://github.com/lspitzner/brittany/pull/351) but there hasn't been any movement on that yet. 
It'd be great if we could have this temporary fix merged until something similar is supported by upstream brittany.
> [#2005] Fix Formatting When Brittany Returns Warnings

- plugins/hls-ormolu-plugin/hls-ormolu-plugin.cabal
Ormolu 0.2 fixes compatibility with GHC 9. Turns out adding `ghc-api-compat` here is enough for GHC 9 compatibility.
Builds fine and all tests pass.
> Allow ormolu 0.2 and fix compatibility with GHC 9

- .github/workflows/test.yml
- cabal-ghc901.project
- cabal.project
- configuration-ghc-901.nix
It was never enabled in github workflow.
Also we should test it with GHC 9 now.
> Enable tests for ormolu plugin

- README.md
Just add links to the top-level sections to make it a bit less bare.
> Add a bit more prose and some links to the README

- shake-bench/src/Development/Benchmark/Rules.hs
We need the log of threading operations so that eventlog-to-tracy can
produe a valid trace. Without it, eventlog-to-tracy will generate an
invalid trace where all the spans are impossibly on the same thread and
tracy may/will crash
> [ghcide-bench] preserve threading details in eventlogs

- ghcide/bench/lib/Experiments.hs
I noticed that the edit experiment is reporting bogus "user time"
numbers because waitForProgressDone is being satisfied by the previous
iteration build.
The fix is easy: wait for a freshly started build first.
> [ghcide-bench] fix edit experiment

- ghcide/bench/lib/Experiments.hs
- ghcide/src/Development/IDE/Core/Rules.hs
When doing reactive change tracking we track the set of dirty keys as opposed to conservative change tracking where we check every key on every build.
Filepath identity becomes even more important in this setting, opening a new type of bug where the filepath used in the dirty key is equivalent but not structurally equal to the filepath used in the dependency graph.
This can happen e.g. with cradle dependencies where hie-bios gives us a set of relative paths and we create GetFileModification keys for them as dependencies of the GhcSession, but the LSP client raises FileWatched notifications using absolute paths that we use to create dirty keys.
To prevent this class of bugs, we would need to strengthen the notion of NormalizedFilePath to make it always absolute/relative. In practice, since …
> Fix filepath identity in cradle dependencies when using reactive change tracking

- .github/workflows/bench.yml
- ghcide/bench/config.yaml
- ghcide/bench/hist/Main.hs
- ghcide/bench/lib/Experiments.hs
- ghcide/bench/lib/Experiments/Types.hs
This is useful in the context of #2060 to compare performance with and without reactive change tracking
> [ghcide-bench] Support extra args in examples

- ghcide/bench/lib/Experiments.hs
When the example includes >1 modules (like the Cabal example), this is the sequence of events:
```
--> didChange A.hs
--> didChange B.hs
<-- [ProgressDone (abort the previous progress, if any)]
<-- ProgressStart (for A.hs change)
<-- ProgressDone (aborted)
<-- ProgressStart (for B.hs change)
<-- ProgressDone
```
The edit and "after edit" experiments usually want to wait until the final set of diagnostics is produced. Currently the edit experiment waits for one progress start and one progress done, while the "after edit" experiments wait for one progress done. This is only correct if there is only one module in the example. When there are two or more, as seen above, it's not enough. The experiment needs to ignore the aborted progress done events and wait until the last progress done event. …
> [benchmarks] Fix edit and "after edit" experiments

- ghcide/exe/Arguments.hs
This is just a convenience to be able to use the ghcide binary with the Haskell vscode extension and enable debug traces
> [ghcide] support -d cli switch

- ghcide/exe/Arguments.hs
- ghcide/src/Development/IDE/Core/Service.hs
- ghcide/src/Development/IDE/Core/Shake.hs
This is a convenience to generate Shake profiles when running tests.  
I also took the chance to delete some dead code and to force the generation of a profile report before shutdown
> GHCIDE_BUILD_PROFILING env var

- README.md
This PR fixes the GitHub Actions badge links
Before, clicking on either badge would lead to the badge's SVG file
> fix GitHub Actions badges

- cabal-ghc901.project
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/FileStore.hs
- stack-9.0.1.yaml
* Update stack dependencies and add ourmolu, floskell formatters and class, refine imports plugins
* Enable shake-bench for stack and ghc-9.0.1
* ~~Use hie-bios master~~ Use last hie-bios
* Clean up cabal-ghc901.project
* Make progress towards #297
> Update ghc-9.0.1 support

- ghcide/test/exe/Main.hs
> perform a GC before find resolution

- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- plugins/hls-pragmas-plugin/src/Ide/Plugin/Pragmas.hs
- plugins/hls-pragmas-plugin/test/Main.hs
* Move the basic pragmas completion from GCHIDE to the pragmas module
* Add closing pragmas snippet  "-#}"
> Move pragmas completion to pragmas plugin

- ghcide/src/Development/IDE/Core/FileStore.hs
- stack-8.10.6.yaml
https://www.stackage.org/lts-18.7
> update LTS for GHC 8.10.6

- plugins/hls-pragmas-plugin/src/Ide/Plugin/Pragmas.hs
- plugins/hls-pragmas-plugin/test/Main.hs
Pragmas are not case sensitive - so the language pragma should auto complete with values accordingly
> case sensitive language pragmas fix

- .circleci/config.yml
- .github/workflows/test.yml
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/FileStore.hs
- stack-8.10.7.yaml
* 8.10.6 did not live much time 😄 
* I am getting error about boot packages locally, building with stack:
```
.....
In the dependencies for ghcide-1.4.1.0:
directory needed, but this GHC boot package has been pruned (issue #4510); you need to add the
package explicitly to extra-deps  (latest matching version is 1.3.6.2)
ghc-boot needed, but this GHC boot package has been pruned (issue #4510); you need to add the
package explicitly to extra-deps  (latest matching version is 9.0.1)
process needed, but this GHC boot package has been pruned (issue #4510); you need to add the
package explicitly to extra-deps  (latest matching version is 1.6.13.2)
time needed, but this GHC boot package has been pruned (issue #4510); you need to add the
package explicitly to extra-deps  (latest matching version …
```
> Add ghc-8.10.7 support

- CITATION.cff
GitHub now supports citation files https://docs.github.com/en/github/creating-cloning-and-archiving-repositories/creating-a-repository-on-github/about-citation-files. Might as well use that to link to the HLS paper many of us were involved in.
> Create a citation

- .github/workflows/test.yml
It fails to build with transient segfaults
> Disable window job for ghc-8.10.2

- .gitpod.yml
Let's try out a gitpod integration that adds a button to the PR description
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2167"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> enable the PR gitpod badge and drop the label

- hls-plugin-api/src/Ide/Types.hs
- test/functional/FunctionalCodeAction.hs
It's quite unclear in the spec, but in
https://github.com/microsoft/language-server-protocol/issues/970
it's suggested that the intention is that the kinds given in `only`
should be used as *prefix* filters of the generated code action kinds.
That is to say, if the client asks for `only = [ CodeActionRefactor ]`,
we should give them all kinds of refactoring code actions, including
those whose kind is `CodeActionRefactorInline` (because as "hierarchical
strings" they are represented as `"refactor"` and `"refactor.inline"`).
This is quite important for the client: e.g. I hit this because I wanted
to ask for all the import quickfixes so I could present them to the user
to pick one. But they use various subkinds of `"quickfix.import"`, so
currently you cannot ask for them all (asking for …
> Filter code actions based on prefix, not equality

- .github/workflows/hackage.yml
* run a cabal update
* show the entire diff if the package version is already released
* fix condition existence of a previous version released
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2177"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix hackage release

- .github/workflows/rerun.yml
* to rerun other workflows via pr comments
* see https://github.com/marketplace/actions/rerun-actions
> * rerun-actions should only be run on comment creation. See the below examples for how to do this.
> * the PR either must have an ok-to-test label present on the PR, or the user who writes a command must be an organization member, or repo owner, contributor, or collaborator. 
The action is triggered by adding a comment in the pr with
> The following commands are supported by this action:
>    /rerun-all - rerun all failed workflows.
>    /rerun-workflow <workflow name> - rerun a specific failed workflow. Only one workflow name can be specified. Multiple /rerun-workflow commands are allowed per comment.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/21 …
> Add rerun workflow

- shake-bench/shake-bench.cabal
* to make progress the hackage release script
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2178"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
https://github.com/jneira/haskell-language-server/runs/3556360579?check_suite_focus=true
```
Run # This will throw an error if there is any difference cause we have to bump up the package version
diff -r -x '*.md' -x data ./incoming/shake-bench-0.1.0.0/shake-bench.cabal ./current/shake-bench-0.1.0.0/shake-bench.cabal
23,25c23
<         diagrams-contrib,
<         diagrams-core,
<         diagrams-lib,
```
> Bump up shake-bench version

- ghcide/src/Development/IDE/Plugin/Completions.hs
- ghcide/test/exe/Main.hs
This fixes an oversight from #2040 where I forgot to weave in the project exports map. 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2187"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Completions for project identifiers

- ChangeLog.md
- docs/contributing/releases.md
- ghcide/ghcide.cabal
- ghcide/test/exe/Main.hs
- haskell-language-server.cabal
- plugins/hls-brittany-plugin/hls-brittany-plugin.cabal
- plugins/hls-call-hierarchy-plugin/README.md
- plugins/hls-call-hierarchy-plugin/hls-call-hierarchy-plugin.cabal
- plugins/hls-class-plugin/hls-class-plugin.cabal
- plugins/hls-explicit-imports-plugin/hls-explicit-imports-plugin.cabal
- plugins/hls-ormolu-plugin/hls-ormolu-plugin.cabal
- plugins/hls-pragmas-plugin/hls-pragmas-plugin.cabal
- plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
- plugins/hls-tactics-plugin/hls-tactics-plugin.cabal
- shake-bench/shake-bench.cabal
* Added instructions about the automated hackage release
* Initial list of prs in the changelog
* Make progress towards #2176
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2182"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Prepare 1.4.0

- .github/workflows/build.yml
- .github/workflows/test.yml
* i am tired to have to attach manually the 8.8.4 windows to relases :sweat_smile: 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2199"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Apply workaround for 8.8.4 and windows to enable it in ci

- ghcide/ghcide.cabal
This package is a transient dependency of `haskell-language-server`.
However, only the library is needed. These three flags give the option for
those who do not need the executables to disable them.
`executable`:
* Toggles the `ghcide` executable
* enabled by default.
`test-exe`:
* Toggles the `ghcide-test-preprocessor` executable
* disabled by default
`bench-exe`:
* Toggles the `ghcide-bench` executable
* disabled by default
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2212"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ghcide: Add flags to toggle building each executable

- ghcide/ghcide.cabal
- ghcide/src/Text/Fuzzy.hs
I found a noticeable perf regression in completions performance when trying to upgrade our custom Sigma IDE from HLS 1.2 to 1.4. The reason is that 1.3 added support for local completions from hiedb and that brings an additional >500k identifiers into scope, so the performance of fuzzy matching becomes a bottleneck.
The fuzzy package is parametric on the text type via the `TextualMonoid` type class. Specializing the `Fuzzy.filter` function to `Text` cuts the allocations by 66% and the time by ~33%.
I sent [a PR](https://github.com/joom/fuzzy/pull/3) upstream, but it might take a while to get merged. Since the license (MIT) allows for it, let's inline the code here and drop the dependency until then.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2215">< …
> Inline Text.Fuzzy to add INLINABLE pragmas

- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
This is the second completions performance issue (after #2215) uncovered by upgrading Sigma IDE from HLS 1.2 to 1.4. 
The problem is that `getCompletions` returns the completions strictly, only to have them cropped to `maxCompletions` in hls-plugin-api. This is bad because there is an O(nlogn) `nubOrdBy` in the result thunk, and it can take a second or more to nub >100k results.
Thankfully `nubOrdBy` is lazy in the result so the fix is simple. By restoring result laziness in `getCompletions`, only up to `maxCompletions` results are processed by `nubOrdBy`.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2217"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Return completions lazily for massive savings

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- ghcide/src/Development/IDE/Plugin/Completions/Types.hs
- ghcide/src/Text/Fuzzy/Parallel.hs
Following #2215  and #2217 this is another performance improvement to completions driven by the large Sigma codebase.
On every completion attempt we need to match the prefix against all the identifiers in the project, with a cost of O(Identifiers*C) where C is the average number of characters per identifier. This PR parallelises the matching and uses vectors to reduce the amount of allocations and enable in-place sorting of the results.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2225"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Parallel fuzzy filtering

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/GHC/Compat/Units.hs
Just need to use the pattern synonym for `ExposePackage` defined in `Compute.Core`
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2234"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix build with fbghc

- ghcide/exe/Main.hs
- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/src/Development/IDE/Core/Compile.hs
- ghcide/src/Development/IDE/LSP/LanguageServer.hs
- ghcide/src/Development/IDE/Main.hs
- ghcide/src/Development/IDE/Plugin/Test.hs
- ghcide/test/exe/Main.hs
- hls-plugin-api/src/Ide/PluginUtils.hs
- hls-plugin-api/src/Ide/Types.hs
- hls-test-utils/src/Test/Hls.hs
- plugins/hls-splice-plugin/test/Main.hs
- plugins/hls-tactics-plugin/src/Wingman/AbstractLSP/TacticActions.hs
- plugins/hls-tactics-plugin/src/Wingman/Debug.hs
- plugins/hls-tactics-plugin/test/Utils.hs
The ghcide test plugin installs a `CustomMethod` handler that allows to interact with the build queue and do things like waiting for the queue to be empty. It's installed by the ghcide main driver but not by the HLS test driver. 
This PR refactors things so that it will be installed automatically by the `defaultMain` driver.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2243"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Enable the ghcide test plugin in HLS test suites

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- ghcide/src/Text/Fuzzy/Parallel.hs
- ghcide/test/exe/Main.hs
This improves the performance of completions by around 25% on a large project (>500k identifiers) and also removes the use of unsafe primitives in the previous in-place solution
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2240"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Partial sort of fuzzy filtering results

- .github/workflows/build.yml
- docs/contributing/releases.md
* In addition to artifacts automatically generated by github
* Motivation from #2216
> * autogenerated and would depend on github not messing with the tarball layout (they did so at least twice) for the hash to be stable
> * depend on the tag (yeah, if you force push, the hash changes too)
> * have bad tarball names like 1.4.0.tar.gz, causing trouble for ghcup
* Moreover it could include submodules if we return to use them
* Closes #2216
//cc @hasufell 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2248"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Generate custom source tarball 

- cabal-ghc901.project
- cabal-ghc921.project
- configuration-ghc-901.nix
- stack-9.0.1.yaml
* After a ghc-9.0.1 compat versions has been published in hackage (see https://github.com/HeinrichApfelmus/operational/issues/29)
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2249"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove custom version of operational

- .github/workflows/test.yml
- cabal-ghc901.project
- cabal.project
- plugins/hls-fourmolu-plugin/hls-fourmolu-plugin.cabal
- plugins/hls-fourmolu-plugin/src/Ide/Plugin/Fourmolu.hs
- stack-9.0.1.yaml
Addresses the relevant checklist item in #297.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2254"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump Fourmolu to 0.4

- .github/workflows/test.yml
* Without using skip-duplicate-actions which is failing due to github access permission. 
* See https://github.com/fkirc/skip-duplicate-actions/issues/103 and https://docs.github.com/en/actions/learn-github-actions/workflow-syntax-for-github-actions#concurrency
* We can keep skip-duplicate-actions, as it is cancelling and skipping using other criteria. But i suspect it can only cancel others if the branch source of the pr belongs to this repo
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2310"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [skip circleci] Add option to effectively cancel prev runs

- plugins/hls-tactics-plugin/src/Wingman/Judgements/SYB.hs
- plugins/hls-tactics-plugin/src/Wingman/LanguageServer.hs
- plugins/hls-tactics-plugin/src/Wingman/LanguageServer/Metaprogram.hs
There's been a lot of work done on making hover and getDefinition immediately responsive at startup by using persisted data.
Unfortunately we didn't install tests to preserve this fragile property. We should add those tests to the func-test testsuite.
The problem here is that Tactics installs a hover handler that depends on the TypeCheck rule. Since there is no persistent provider for this rule, it blocks until the file can be typechecked. Since HLS does not implement partial responses (and neither do most LSP clients anyway), this blocks all the other hover providers.
The solution is to install a new build rule GetMetaprograms that depends on TypeCheck, install a persistent provider for it that returns the empty list of meta programs, and switch the hover provider to useWithStaleFast. …
> Prevent Tactics hover provider from blocking at startup

- ghcide/exe/Main.hs
- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/src/Development/IDE/Core/RuleTypes.hs
- ghcide/src/Development/IDE/Core/Tracing.hs
- ghcide/src/Development/IDE/Main.hs
- src/Ide/Main.hs
Just some minor improvements and workarounds for Tracy where the traces visualise fine in Chrome but get butchered by the `import-chrome` script provided by Tracy 0.7.8
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2319"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve trace readability

- .github/workflows/hackage.yml
- cabal-ghc901.project
- cabal-ghc921.project
- haskell-language-server.cabal
- test/utils/Test/Hls/Flags.hs
* As commented in https://github.com/haskell/haskell-language-server/issues/2317#issuecomment-956178685 it is an alternative to make plugin flags automatic to get hls buildable from hackage and ghc-9.0.1
* This pr:
* Encode explicitly what plugins are buildable for each ghc versions in `haskell-language-server.cabal`, the only config file seen by hackage builds
* Add a new flag `ignore-plugins-ghc-bounds` to allow custom builds out of hackage force the inclusion of plugins, supposelly adding `allow-newer` or `remote-source-packages` in a `cabal.project`
* Remove `all-plugins` and `all-formatters` as afaics they are almost useless with actual default values for them and individual plugin flags and being used with `||` in conditions
* Remove unused plugins conditions in `test-func` as …
> Add support for install hls from hackage using ghc 9.0.1

- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/test/data/hiding/HideFunctionWithoutLocal.expected.hs
- ghcide/test/data/hiding/HideFunctionWithoutLocal.hs
- ghcide/test/data/hiding/HidePreludeLocalInfix.expected.hs
- ghcide/test/data/hiding/HidePreludeLocalInfix.hs
- ghcide/test/exe/Main.hs
pull request for #2114
I'm new here so please point out if this fix has any problems
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2320"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Suggest hiding imports when local definition exists

- .github/workflows/test.yml
- plugins/hls-explicit-imports-plugin/hls-explicit-imports-plugin.cabal
- plugins/hls-explicit-imports-plugin/src/Ide/Plugin/ExplicitImports.hs
- plugins/hls-explicit-imports-plugin/test/Main.hs
- plugins/hls-explicit-imports-plugin/test/testdata/A.hs
- plugins/hls-explicit-imports-plugin/test/testdata/Exported.hs
- plugins/hls-explicit-imports-plugin/test/testdata/UsualCase.expected.hs
- plugins/hls-explicit-imports-plugin/test/testdata/UsualCase.hs
- plugins/hls-explicit-imports-plugin/test/testdata/hie.yaml
I attempted to fix #2079
I'm not familiar with GHC AST kind things. I'd be happy to get some advice if anyone has more smart way to implement this.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2329"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Not suggest exported imports

- .github/workflows/bench.yml
- .github/workflows/nix.yml
- test/functional/Main.hs
* It is working really well to the test workflow
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2335"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Cancel prev runs for bench and nix

- .github/workflows/bench.yml
- .github/workflows/nix.yml
- .github/workflows/test.yml
* To try make required checks work
* Before this if some post_job (from nix or bench workflows) was green and the test post_job did not start, the pr was incorrectly mergeable and mergifyio could merge it. This has happened with #2332 and #2321
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2337"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [skip circleci] Give unique names to post-jobs

- .github/dependabot.yml
Dependabot would weekly check updates for project's [.github/workflows/*](https://github.com/haskell/actions/blob/main/.github/workflows/workflow.yml) & send-in information & patch updates as PRs to be merged ([like these](https://github.com/haskell-nix/hnix-store/pull/169)).
PR to CI configuration run CI with changes applied, which is a self-test.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2339"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> add dependabot: add Actions CI merge requests automation

- docs/contributing/contributing.md
On my setups, the `gen-hie` tool was found to be irreplaceable.
Mainline documentation currently directs people to read lengthy HLS docs on cradle & then directs reading HIE-Bios docs on it & says to make all `hie.yaml` by hand. For every project person wants to contribute to.
<details><summary> & currently that means: </summary>
</p>
```yaml
cradle:
cabal:
- path: "./ghcide/src"
component: "lib:ghcide"
- path: "./ghcide/session-loader"
component: "lib:ghcide"
- path: "./ghcide/test/preprocessor/Main.hs"
component: "ghcide:exe:ghcide-test-preprocessor"
- path: "./ghcide/bench/hist/Main.hs"
component: "ghcide:bench:benchHist"
- path: "./ghcide/bench/lib/Main.hs"
component: "ghcide:bench:benchHist"
- path: "./ghcide/bench/hist/Experiments/Types.hs"
component: "ghcide:bench:benchHist"
- …
```
> contributing: add implicit-hie gen-hie > hie.yaml note

- ghcide/bench/lib/Experiments.hs
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Plugin/Test.hs
- ghcide/test/src/Development/IDE/Test.hs
- hls-graph/hls-graph.cabal
- hls-graph/src/Development/IDE/Graph/Database.hs
- hls-graph/src/Development/IDE/Graph/Internal/Types.hs
- hls-test-utils/src/Test/Hls.hs
This adds 5 new columns to the benchmark outputs:
- buildRulesBuilt   - for which the value didn't change
- buildRulesChanged - for which the value did change
- buildRulesVisited - for which the value was not even recomputed
- buildRulesTotal   - including the rules that were not visited in the last build
- buildEdges        - total number of edges in the build graph
Example output:
```
cabal exec cabal run ghcide-bench -- -- -s "edit" --samples 2 --no-clean --example-module Distribution/Simple.hs
Up to date
Config {verbosity = Normal, shakeProfiling = Nothing, otMemoryProfiling = Nothing, outputCSV = "results.csv", buildTool = Cabal, ghcideOptions = [], matches = ["edit"], repetitions = Just 2, ghcide = "ghcide", timeoutLsp = 60, example = Example {exampleName = "name", exampleDetails = …
```
> Show build graph statistics in ghcide-bench

- ChangeLog.md
- plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
- plugins/hls-hlint-plugin/test/Main.hs
* The plugin was not using the `getParsedModuleWithComments` so it was missing all info encoded in comments: pragmas, directives, etc and causing several issues
* Fixes #638
* Fixes #2042
* Fixes #2280
I was suspecting this so i added the regression tests in #2321 with the intent of fixing them in a ongoing pr, this one.
(I've included a minor correction of bullet lists suggested by markdown linting)
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2366"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix several hlint issues related with the use of parsed module without comments
