- ghcide/src/Development/IDE/Core/RuleTypes.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/test/data/THLoading/A.hs
- ghcide/test/data/THLoading/B.hs
- ghcide/test/data/THLoading/THA.hs
- ghcide/test/data/THLoading/THB.hs
- ghcide/test/data/THLoading/hie.yaml
- ghcide/test/exe/Main.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs
We cannot use GetModIfaceWithoutLinkable since the session might be reused later to load a module that needs linkables
Note that this does not have any effects on performance, since GetModIfaceWithoutLinkable is just a synonym for GetModIface that removes the linkable
Fixes #2379
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2380"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix regression in GhcSessionDeps

- ghcide/ghcide.cabal
2204a16bfbbdd3f0887cdfdab4b86cbd63ab051a broke backward compatibility between `ghcide` and `hls-plugin-api`
In addition to this PR, the following will need to be revised on hackage:
Versions `1.4.1.0` `1.4.2.0` `1.4.2.1` `1.4.2.2` `1.4.2.3` will need
`hls-plugin-api ^>= 1.2.0.0`
changed to
`hls-plugin-api >= 1.2.0.0 && < 1.2.0.2`
Version `1.5.0` will need
`hls-plugin-api ^>= 1.2.0.0`
changed to
`hls-plugin-api ^>= 1.2.0.2`
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2382"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ghcide: Update dependency on `hls-plugin-api`

- hls-test-utils/hls-test-utils.cabal
- plugins/hls-class-plugin/hls-class-plugin.cabal
- plugins/hls-fourmolu-plugin/hls-fourmolu-plugin.cabal
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-ormolu-plugin/hls-ormolu-plugin.cabal
- plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
- plugins/hls-splice-plugin/hls-splice-plugin.cabal
- plugins/hls-stylish-haskell-plugin/hls-stylish-haskell-plugin.cabal
- plugins/hls-tactics-plugin/hls-tactics-plugin.cabal
`hls-class-plugin-1.0.1.1` imports `Development.IDE.GHC.Compat.Util`, which doesn't exist until `ghcide-1.5.0`
```
Building library for hls-class-plugin-1.0.1.1..
[1 of 1] Compiling Ide.Plugin.Class ( src/Ide/Plugin/Class.hs, dist/build/Ide/Plugin/Class.o, dist/build/Ide/Plugin/Class.dyn_o )
src/Ide/Plugin/Class.hs:27:1: error:
Could not find module ‘Development.IDE.GHC.Compat.Util’
Perhaps you meant
Development.IDE.GHC.Compat (from ghcide-1.4.2.2)
Development.IDE.GHC.Util (from ghcide-1.4.2.2)
Use -v (or `:set -v` in ghci) to see a list of the files searched for.
|
27 | import           Development.IDE.GHC.Compat.Util
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2368"><img …
> Update ghcide dependency for various plugins

- .github/workflows/hackage.yml
- .github/workflows/test.yml
- ChangeLog.md
- GenChangelogs.hs
- cabal-ghc901.project
- cabal-ghc921.project
- cabal.project
- hls-test-utils/hls-test-utils.cabal
- plugins/hls-class-plugin/hls-class-plugin.cabal
- plugins/hls-eval-plugin/hls-eval-plugin.cabal
- plugins/hls-explicit-imports-plugin/hls-explicit-imports-plugin.cabal
- plugins/hls-fourmolu-plugin/hls-fourmolu-plugin.cabal
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-module-name-plugin/hls-module-name-plugin.cabal
- plugins/hls-ormolu-plugin/hls-ormolu-plugin.cabal
- plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
- plugins/hls-splice-plugin/hls-splice-plugin.cabal
- plugins/hls-stylish-haskell-plugin/hls-stylish-haskell-plugin.cabal
- test/functional/Main.hs
* The hackage check is [here](https://github.com/jneira/haskell-language-server/runs/4305202883?check_suite_focus=true). It is failing for ghc-8.6.5 with
```
cabal: Could not resolve dependencies:
[__0] trying: ghcide-1.5.0.1 (user goal)
[__1] rejecting: ghcide:!test (constraint from config file, command line flag,
or user target requires opposite flag selection)
[__1] trying: ghcide:*test
[__2] trying: lsp-test-0.14.0.1 (dependency of ghcide *test)
[__3] trying: conduit-parse-0.2.1.0 (dependency of lsp-test)
[__4] trying: parsers-0.12.10 (dependency of conduit-parse)
[__5] trying: semigroups-0.20 (dependency of parsers)
[__6] trying: text-1.2.3.1/installed-1.2.3.1 (dependency of ghcide)
[__7] next goal: sqlite-simple (dependency of ghcide)
[__7] rejecting: sqlite-simple-0.4.18.0 …
```
> Prepare 1.5.1

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/test/exe/Main.hs
- ghcide/test/src/Development/IDE/Test.hs
The checkProject setting introduces (even more) non determinism and leads to flaky tests as seen in #2153 
This PR disables it in the ghcide test suite, except in the tests that explicitly exercise the setting
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2397"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Disable check project in the ghcide test suite

- .github/workflows/hackage.yml
- cabal-ghc901.project
- cabal-ghc921.project
- cabal.project
* Updating hackage index and remove obsolete source-repository-packages
* Will backport changes to 1.5.1-hackage
* Hackage check workflow here: https://github.com/jneira/haskell-language-server/actions/runs/1515454378
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2412"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use dependent-sum from hackage

- docs/configuration.md
Fixed "equivalent"
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2417"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Configuration docs: Typo

- .github/workflows/cache-deps.yml
Discussed in: https://matrix.to/#/!oOjZFsoNYPAbTEgSOA:libera.chat/$ckv7h8SSMbimsa_5pCaCFn2uMm_nEVIy6gy0QyFgc8M?via=libera.chat&via=matrix.org&via=monoid.al
Short: Cabal builds deps from the source. Currently, cache gets saved only on the successful passing of the CI workflow pipeline (includes dependencies built, then all HLS projects built & then successful passing of all tests, core word is "successful" passing of all of that), while successful Cabal dependency build stage depends only on does Hackage snapshot state (success of Cabal dependency build stage).
Basic idea - is to run `cabal v2-build --only-dependencies`, which would ensure saving & sharing of the snapshot of successfully built dependencies into pull requests. To run on schedule & on `push` to `master`.
<a …
> Centralized caching workflow

- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- test/functional/Completion.hs
- test/testdata/completion/FieldsSharingSignature.hs
- test/testdata/completion/hie.yaml
Currently, HLS generates wrong completion snippets for a record with some fields sharing the same type signature.
For example, consider the following:
```hs
data Foo = Foo { arg1, arg2 :: Int, arg3 :: Int, arg4 :: Bool }
```
Above, `arg1, arg2` shares the same `Int` signature and this is a completely legitimate definition.
If this is defined in a local module, the current HLS generates the following record snippet for `Foo`, which lacks `arg2`:
```hs
Foo { arg1 = _arg1, arg3 = _arg3, arg4 = _arg4 }
```
The base cause of this seems as follows.
HLS handles record snippets for datatypes in a local module via parsed modules (`findRecordCompl` logic), especially from the `RecCon` constructor.
In `RecCon`, field information is stored as a list of `ConDeclField`s, which stores field label …
> Makes local record field completion respects the fields sharing one single type signature

- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/src/Development/IDE/Core/FileExists.hs
- ghcide/src/Development/IDE/Core/FileStore.hs
- ghcide/src/Development/IDE/Core/OfInterest.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/src/Development/IDE/Plugin/TypeLenses.hs
- haskell-language-server.cabal
- plugins/default/src/Ide/Plugin/Example.hs
- plugins/default/src/Ide/Plugin/Example2.hs
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
- test/utils/Test/Hls/Command.hs
Fourth instalment of #2357 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2434"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Lockless diagnostics

- docs/installation.md
* Amazingly it was not described anywhere afaics and we all were assuming users would know that machinery
* Maybe it would worth to have a speicifc section about the cli and executables but we could start with a brief description 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2445"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Describe hls installed binaries

- ghcide/src/Development/IDE/Core/FileExists.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/LSP/Notifications.hs
5th instalment from #2357 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2442"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Lockless FileExistsMap and position mapping

- ghcide/src/Development/IDE/Core/RuleTypes.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/Core/Tracing.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs
- plugins/hls-eval-plugin/test/Main.hs
- plugins/hls-eval-plugin/test/testdata/TLocalImport.expected.hs
- plugins/hls-eval-plugin/test/testdata/TLocalImport.hs
- plugins/hls-eval-plugin/test/testdata/TTransitive.expected.hs
- plugins/hls-eval-plugin/test/testdata/TTransitive.hs
Fixes #2438 and includes a regression test
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2441"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix regression in Eval plugin and add test

- haskell-language-server.cabal
Just a minor code-cleanup, unifies warning flags and removes some code repetition.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2447"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make heavy use of common sections

- .github/workflows/test.yml
* The cache of tasty logs to not repeat succesful tests between attempts of the same run was not working correctly
* `new` makes rerun all tests again, as succesful one in one attempt are "new" for the next one
* Logs are saved in each package root dir, so the cache should be `**./.tasty-rerun-log*`
* `func-tests` and `wrapper-tests` are from the same hls top level package so at least one of them needs a specific name (did it for wrapper tests)
* I've checked a second rerun does not run any effective test here: https://github.com/jneira/haskell-language-server/actions/runs/1550353254
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2450"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix rerun log cache handling

- .circleci/config.yml
- .github/workflows/bench.yml
- .github/workflows/build.yml
- .github/workflows/caching.yml
- .github/workflows/hackage.yml
- .github/workflows/nix.yml
- .github/workflows/test.yml
Be free at merging #2444, I would rebase this to whatever needed.
---
Using the same bootstrapping process so workflows have the same setup & so can share the caches between them.
<sub>(A work derived from #2427)</sub>
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2446"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> CI: organizing bootstraping

- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/src/Development/IDE/Core/OfInterest.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/Plugin/CodeAction/Args.hs
- ghcide/src/Development/IDE/Plugin/Completions.hs
- plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
- plugins/hls-retrie-plugin/src/Ide/Plugin/Retrie.hs
7th instalment from #2357 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2460"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Lockless iorefs

- .github/workflows/build.yml
Shortest path towards #2461
Moving to Gitlab CI binaries is still very much desirable but also much more work.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2463"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Build linux binaries in alpine container

- ghcide/src/Development/IDE/Core/Debouncer.hs
This is a safer, minimal change version of #2466 that simply removes the locking without altering the implementation of the async debouncer
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2469"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Lock-less debouncer (minimal change)

- ghcide/src/Development/IDE/Types/HscEnvEq.hs
Attempt at fixing https://github.com/haskell/haskell-language-server/issues/2451 based on @pepeiborra 's suggestion: https://github.com/haskell/haskell-language-server/issues/2451#issuecomment-991637640
This fixes the issue for me with GHC 8.10.7, let's see how it fares in CI..
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2468"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Handle re-exported modules when constructing ExportsMap

- docs/contributing/index.rst
This is a small change, but on reading the Contribution guide was wondering why the theme of Haskell dev is suddenly interrupted by maintenance docs & then continued again.
---
Before this:
-> Contributing to the project
-> Maintenance
-> Example developing of a new plugin
Considering that maintenance questions are not related to the main path of contributors & a meta project
questions for contributors which are promoted to maintainers.
-> Contributing to the project
-> Example developing of a new plugin
-> Maintenance
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2472"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Minor org to contribution doc

- .github/workflows/bench.yml
- .github/workflows/build.yml
- .github/workflows/caching.yml
- .github/workflows/hackage.yml
- .github/workflows/test.yml
* New code included & shares all source code that may be needed.
* New config includes & shares all compiled deps that may be needed in workflows.
* New config stores the source code separately, which means it gets stored one time.
Before this cache stored per Platform/GHC - the sources & compiled results
together. It is while sources not depend on platform or GHC, as sources are
platform & GHC agnostic. Because they were always bundled together
& sources took ~1/2-2/3 of that storage - cache stored multiple duplicates of the same
source code.
`caching` workflow now downloads, builds & shares all sources & all dependencies for all targets.
`dist-newstyle` so far is not included in to the cache, (what to cache from them can be looked into in the next updates).
---
<a …
> Caching process update

- plugins/hls-pragmas-plugin/src/Ide/Plugin/Pragmas.hs
- plugins/hls-pragmas-plugin/test/Main.hs
- plugins/hls-pragmas-plugin/test/testdata/BlockCommentThenMultiLineBlockHaddock.expected.hs
- plugins/hls-pragmas-plugin/test/testdata/BlockCommentThenMultiLineBlockHaddock.hs
In some editors, parenthesis completion can handle a language specific cases. For example, in my Emacs, when I type
```Haskell
{-#
```
it automatically gives
```Haskell
{-##-}
```
However, the current pragma completion plugin does not recognize this case, and completes
```Haskell
{-# LANGUAGE #- #-}
```
which is invalid. This PR cares the editors which fill `#-}` or `-}` for Haskell.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2474"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix some pragma completion cases

- ghcide/src/Development/IDE/Core/Compile.hs
- ghcide/src/Development/IDE/Core/ProgressReporting.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/test/exe/Progress.hs
Out of curiosity I put together a lock-less version of hls-graph using the sim-containers package as suggested by @wz1000 and others in IRC a few months ago. 
So far I haven't seen any perf. improvement, in fact the amount of work done (allocations) is much higher. Perhaps with more tuning it could be competitive? Leaving it here in case anyone wants to have a play
EDIT: The original PR was broken in chunks, and now that there is only one major change remaining, it's worth reviewing and merging this PR to preserve the discussion instead of extracting it into yet another PR.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2357"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Decrease contention in Progress reporting

- configuration-ghc-901.nix
- flake.lock
- flake.nix
- myst-parser.nix
Ref: #297
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2482"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update flake to use fourmolu plugin in GHC 9

- hls-graph/hls-graph.cabal
- hls-graph/src/Development/IDE/Graph/Internal/Paths.hs
Fix the hls-graph ide build when the `embed-files` flag is given. 
I also noticed that Alan's email is used as the maintainer for hls-graph, which seems a bit unfair since Alan knows little about this package, so change it to Haskell IDE Team
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2485"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix hls-graph ide build with embed-files

- ghcide/src/Development/IDE/GHC/Compat/Util.hs
- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/test/exe/Main.hs
Names starting with `_` is often used, for example, with `lens` among many others. However, the current redundant import action does not remove those even when they are redundant.
For instance,
```haskell
import Control.Lens ((^.), _1, _2)
myVal = (1, 2) ^. _1
```
Here, `_2` is redundant, but GHCIDE does not give any actions. Adding one more redundant import like
```haskell
import Control.Lens ((^.), _1, _2, use)
```
gives the action, but the action removes only `use`, not `_2`.
This PR resolves this issue.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2483"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix redundant import actions for names starting with _

- ghcide/src/Development/IDE/LSP/LanguageServer.hs
The LSP spec says:
> The shutdown request is sent from the client to the server. It asks the server to shut down, but to not exit (otherwise the response might not be delivered correctly to the client). There is a separate exit notification that asks the server to exit. Clients must not send any notifications other than exit or requests to a server to which they have sent a shutdown request. Clients should also wait with sending the exit notification until they have received a response from the shutdown request.
We are doing the shut down in the `Exit` notification handler, which is too late. 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2486"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Correctly handle LSP shutdown/exit

- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/LSP/LanguageServer.hs
Closes #2390
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2484"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Send unhandled exceptions to the user

- .github/workflows/bench.yml
- .github/workflows/nix.yml
- .github/workflows/test.yml
* To hopefully ensure the job does no terminate succesfully before the cancellation is effective
* This workflow was marked as succesful although the cancel action was succesful: https://github.com/haskell/haskell-language-server/runs/4549724494?check_suite_focus=true
* It seems the cancel request is asynchronous and here https://github.community/t/is-there-a-way-to-cancel-a-running-workflow-within-one-of-its-jobs/17493/4 uses this trick to ensure the cancel action is effective
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2493"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fail if main or pre jobs are cancelled

- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/LSP/LanguageServer.hs
* This reverts commit 0211f75c96402dda53be69473714134244763d95.
* That commit causes ghcide tests in windows hangs for all ghcs
* The test suite was marked incorrectly as ok due a bug in the workflows (fixed with #2493)
* See #2484 for more details
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2497"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Revert "Send unhandled exceptions to the user (#2484)"

- docs/conf.py
- flake.nix
It was out of date. This way it will always be read in from the file, so
we can forget about it.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2500"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Automatically read in the doc version from the cabal file

- .github/workflows/test.yml
- docs/features.md
- haskell-language-server.cabal
* Due to the performance issue reported here: https://github.com/haskell/haskell-language-server/issues/2490
* The plugin could be included in the build forcing the manual flag: `cabal install -falternateNumberFormat`
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2498"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Disable alternate numbers format plugin temporary

- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/Core/Tracing.hs
I misunderstood how [`OpenTelemetry.Eventlog.addEvent`](https://hackage.haskell.org/package/opentelemetry-0.7.0/docs/OpenTelemetry-Eventlog.html#v:addEvent) works, which is not totally surprising since there are no docs.
But it looks like, judging by other call sites, that the event goes in the second argument and the first argument is always "":
https://github.com/haskell/haskell-language-server/blob/779439876855872c523088e400526c6f1807bca2/ghcide/src/Development/IDE/Core/Tracing.hs#L123
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2505"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix tracing of recordDirtyKeys

- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/LSP/LanguageServer.hs
Revert of #2497 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2504"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Unhandled exceptions fixed

- ghcide/src/Development/IDE/GHC/Compat/Core.hs
- ghcide/src/Development/IDE/GHC/Compat/Outputable.hs
`mkPrintUnqualified` needs a `UnitEnv`, I have no idea where to get one.
I suspect we could use a different print function, for the only place this is called.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2511"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Sort out some compatibility issues

- install/stack.yaml
- stack-8.10.6.yaml
- stack-8.10.7.yaml
- stack.yaml
As discussed in chat.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2501"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> small stack yaml updates to ease maintenance

- .github/workflows/caching.yml
This PR allows to forget about cache pool exhaustion through internal branches.
Despite `caching` workflow runs on `master` only, GitHub caching is designed such that every workflow run that uses the cache `(test, bench)` can also save cache into the pool of own git repo. Which means the changes to the project configuration files inside PRs would produce caches for PR, which when there is enough internal branches PRs activity would push `master` cache out of the 10G FIFO pool because GitHub removes from the pool by the creation time. While PR caches that would stay - have a sharing & access scope limited to the PRs they are built for.
Removal of the `master` cache out of the pool means that cache that was shared for all PRs - no longer there, which `⇒ ∀` PRs to build & save their own …
> CI: caching: add early termination & run check on schedule

- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/test/exe/Main.hs
Adding missing tests mentioned here: https://github.com/haskell/haskell-language-server/pull/2519#discussion_r773149782
Fixing this code action to work in more cases
After this fix:
https://user-images.githubusercontent.com/2716069/147052667-2946d450-7d2b-46d9-a3a9-6e1aedf8570a.mp4
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2522"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve action for fixing import typo

- .github/workflows/caching.yml
- .github/workflows/test.yml
- cabal-ghc901.project
- cabal-ghc921.project
- cabal.project
Details are in the commit messages.
1. We not noticed the first specific of the CI, because the early cutoff behaved as it should. It was respected to return `'false'` to terminate early, but that check always returned `'false'`. When working in GHC 9.2 PR could not force the caching build to start, because check that I fix - always skipped the steps (always returned `False`). New check is done in the way how it is done in other `if: ... != 'true'` statements in the workflow.
2. The second specific is both Ubuntu-specific & maybe  GitHub specific. Some OSes run `alias cp='cp -i'` & when I tried to `rm` manually - `cabal.project` appeared to be protected from simple `rm` by setinning (most probably) of a "sticky bit" on `$HOME` directory. I found that-out by working in GHC 9.2 PR (where …
> CI: caching: fix early termination expression check & cabal.project replacement

- .github/workflows/build.yml
- .github/workflows/caching.yml
- .github/workflows/hackage.yml
* Those workflows are not being triggered on pull request and use branch names to trigger them is a little bit clumsy
* This way we could, for example, manually trigger caching on any branch, to control the cache behaviour: this can lead to slow ci builds so you have to know what are you doing (experimenting in your own fork if possible before)
* Here there is docs on how to do the manual trigger: https://docs.github.com/es/actions/managing-workflow-runs/manually-running-a-workflow
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2528"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Enable manual run for caching, hackage and build workflows

- .github/workflows/test.yml
Dont know why it is not here :facepalm:
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2530"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Test hls-pragmas-plugin in ci

- .github/workflows/caching.yml
This solves the `build all` problem when all projects can't infer the consitent
package version.
Also would allow caching workflow on manual start - to work & cache in a broken
or complex PRs.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2535"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> CI: caching: keep-going

- .github/workflows/bench.yml
- .github/workflows/caching.yml
- .github/workflows/test.yml
1. CI caches 3rd patry dependency binaries.
2. That is why we do not want to trigger on all `.cabal` changes. We want to
cache only when changes in `.cabal` descriptions lead to changes in versions of
deps used, or in their compilation flags. `freeze` files:
For example the bits of the resulting `.freeze` file:
```
active-repositories: hackage.haskell.org:merge
constraints: any.Boolean ==0.2.4,
...
any.HsYAML ==0.2.1.0,
HsYAML -exe,
any.HsYAML-aeson ==0.2.0.1,
HsYAML-aeson -exe,
any.JuicyPixels ==3.3.6,
JuicyPixels -mmap,
any.MemoTrie ==0.6.10,
MemoTrie -examples,
...
any.QuickCheck ==2.14.2,
QuickCheck -old-random +templatehaskell,
aeson -bytestring-builder -cffi -developer -fast,
...
any.aeson-pretty ==0.8.9,
aeson-pretty -lib-only,
bifunctors +semigroups +tagged,
any.blaze-textual …
```
> CI: {caching,test,bench}: mk cache aware of package dep versions

- .github/workflows/hlint.yml
- .github/workflows/test.yml
As I understand, CI installs executable & runs it.
HLint gives the same output regardless of the GHC versions, so there is no reason to run it inside GHC matrix. In fact HLint executable installed does not need GHC at all.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2537"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> CI: add hlint workflow

- .github/workflows/hlint.yml
As we have to add the *job* to branch pr merge checks and `Run` is too generic
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2544"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Set an unique name for Hlint job

- .github/workflows/bench.yml
- .github/workflows/caching.yml
- .github/workflows/test.yml
* Would note we have a `cabal v2-build all --enable-tests --enable-benchmark` problem - that command requires the level of dependency consistency guarantees that PR CI does not checks.
`test` workflow does essentially `cabal v2-build --enable-tests` on matrix by target.
`bench` workflow does `cabal v2-build --enable-benchmarks` by target.
`caching` used `all --enable-tests --enable-benchmarks` - requiring total consistency.
These changes are to make `caching` able to work when `test` & `bench` deps
versions are inconsistent (which is how CI & people use them - separately).
* "`Workaround to CI platform`" needs to be removed either way, since I found out post hooks does not run if any of (even marked `continue-on-error: true`) steps fail.
<a …
> CI: caching: closer match work/CI guarantees

- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/test/exe/Main.hs
I felt that since `hls-explicit-imports-plugin` puts spaces after commas then this code action should also do so for consistency.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2547"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add space after comma when exporting a name

- ghcide/src/Development/IDE/Core/Compile.hs
The issue here is that the `ModuleGraph` value is not forced eagerly, so
the EPS ends up loading an interface file for an external package and
retains a stale reference to the old HPT for the rest of the session.
The heap should always satisfy the invariant that no HomeModInfo are
reachable via the EPS.
See GHC issue #20509 for something similar.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2553"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix space leak where EPS retained HPTs from old HscEnv

- docs/conf.py
Fix links like `[foo](../bar.md#baz)` incorrectly linking to `../bar.md#baz` instead of `../bar.html#baz`.
E.g. in https://haskell-language-server.readthedocs.io/en/latest/contributing/contributing.html#using-hls-on-hls-code the link `Configuring project build` incorrectly links to https://haskell-language-server.readthedocs.io/en/latest/configuration.md#configuring-your-project-build instead of https://haskell-language-server.readthedocs.io/en/latest/configuration.html#configuring-your-project-build
[I checked with MyST parser people](https://github.com/executablebooks/MyST-Parser/issues/443) and this is the right fix.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2555"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> doc: Enable relative links with anchors

- stack-9.0.1.yaml
I somehow forgot to commit this change when I updated the settings related to the class plugin for GHC 9.0.1
(That's why I need Magit, haha)
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2556"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Apply missing update for stack-9.0.1.yaml

- flake.lock
- flake.nix
The nix flake was failing:
```
nix build .#haskell-language-server
```
Was failing because of bounds issue related to hackage `lsp`,
`lsp-types` and `lsp-test` projects.
I've bump theses version, introducing new flake input (so they can be
changed easily in the future) and now the build works.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2557"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix nix flake by explicit version for `lsp-xxx` packages

- .github/workflows/bench.yml
- .github/workflows/caching.yml
- .github/workflows/flags.yml
- .github/workflows/test.yml
* The problem with the freeze file in 9.2.1 was not the use of allow-newer: `cabal freeze` use the same solver as `cabal build` and it takes in account the same config. The problem was `cabal freeze` was being done before `cabal update` so it cant take in account the head.hackage updates
* So remove the freeze file as i did in #2552 is not needed but move the `cabal update` step
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2560"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix freeze cache key correctly

- flake.nix
Currently only GHC 8.10.7 builds on `aarch64-darwin` after this change
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2561"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Enable `aarch64-darwin` in `flake.nix`

- .github/workflows/bench.yml
- .github/workflows/caching.yml
- .github/workflows/flags.yml
- .github/workflows/hackage.yml
- .github/workflows/test.yml
* #2560 fixed the `cabal freeze` step putting `cabal update` before it
* But it had a unintended effect detected in the ghc-9.2 branch: the hackage index bump done by cabal update was being overwritten by the package sources cache restoring done immediately after
* Also reviewing ci logs i also checked the freeze file hash was not being computed. It seems the `${{ hasFiles('...') }}` is resolved before the script is run 🤦 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2562"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix ci update hackage index

- ghcide/test/exe/Main.hs
Continuing the work on #2569, this is regression test for type family completion.
I've implemented the tests in `ghcide` and `haskell-language-server`, not sure if that's the way or if I should drop one.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2576"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> test: Add regression tests for #2403

- .github/workflows/test.yml
- cabal-ghc901.project
- cabal-ghc921.project
- ghcide/ghcide.cabal
- haskell-language-server.cabal
- hie-compat/hie-compat.cabal
* I've removed grain coarsed allow-newer's and uncomment all subpackages to track what precise dependencies we need to get full ghc-9.2.1 support
* Some changes in .cabal has being unveiled
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2582"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Post ghc-9.2.1 config cleanup

- test/functional/Progress.hs
Fixes #2578.
Took way too long to find for how simple it was. The issue was that `getCodeLenses` was occasionally eating progress create messages, which caused any further messages with the same progress tokens to fail.
The implemented fix is to expect progress messages up to the point of the code lens response, do whatever we need the code lens response for, then pass the currently active progress tokens to the final expect progress messages function finishing up the expectations.
The other progress tests should be fine since they don't eat messages.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2590"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix progress eval test randomly failing

- .github/workflows/test.yml
- cabal-ghc921.project
- ghcide/.hlint.yaml
- ghcide/src/Development/IDE/GHC/Compat/ExactPrint.hs
- ghcide/src/Development/IDE/GHC/ExactPrint.hs
- ghcide/src/Development/IDE/Plugin/CodeAction/Args.hs
- ghcide/src/Development/IDE/Plugin/Completions.hs
- plugins/hls-haddock-comments-plugin/src/Ide/Plugin/HaddockComments.hs
- plugins/hls-rename-plugin/src/Ide/Plugin/Rename.hs
The rename plugin relies on SYB to find located AST trees that need renaming. This breaks in GHC 9.2 because the representation of located AST trees has changed: it now includes exactprint annotations.
To make the rename plugin work in 9.2, we need to adjust the SYB queries to look for the new located AST types.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2593"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [ghc-9.2] Fix rename plugin

- .github/workflows/test.yml
- cabal-ghc921.project
- haskell-language-server.cabal
- plugins/hls-module-name-plugin/hls-module-name-plugin.cabal
- plugins/hls-module-name-plugin/src/Ide/Plugin/ModuleName.hs
- stack-9.2.1.yaml
Actual fix mimics changes from #2503 ; config changes indiscriminately turn building with module-name on ghc-9.2.1 on.
I assume that bumping minor version of the plugin is useful for constraint configuration.
(AFAIU building 9.2.1 with stack is not ready yet, but why not turn module-name on in there too, in preparation.)
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2594"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix module-name plugin on ghc-9.2.1

- ghcide/src/Text/Fuzzy/Parallel.hs
Fixes #2577 and maybe other issues involving import module completions.
The superficial reason why the module completions test was failing is that `HashMap`'s `toList` ordering is not deterministic between runs. This meant that the list ordering of the target files/modules would occur in different orders.
Of course why should the order of module names affect anything with regards to completions? 
The test generates 3 targets, 2 `TargetModule`s and 1 `TargetFile`. Since we seem to only care about actual modules we convert `TargetFile`s to empty strings. This list of module names (including the empty string) eventually get passed to the fuzzy matcher which attempts to run the matcher on the names in parallel.
Interestingly different orders can cause the parallel strategy to give different …
> Fix some import module completions being dropped (and fix flaky test too)

- .github/workflows/test.yml
- cabal-ghc921.project
- plugins/hls-qualify-imported-names-plugin/README.md
- plugins/hls-qualify-imported-names-plugin/hls-qualify-imported-names-plugin.cabal
- plugins/hls-qualify-imported-names-plugin/src/Ide/Plugin/QualifyImportedNames.hs
- stack-9.2.1.yaml
ghc-9.2.1 assures me that `| otherwise` in `QualifyImportedNames.hs @ 100` is redundant; hope other ghcs agree.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2600"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [ghc-9.2] Fix qualify-imported-names plugin

- .github/workflows/test.yml
- cabal-ghc921.project
- ghcide/src/Development/IDE/GHC/Compat/Core.hs
- haskell-language-server.cabal
- plugins/hls-refine-imports-plugin/hls-refine-imports-plugin.cabal
- plugins/hls-refine-imports-plugin/src/Ide/Plugin/RefineImports.hs
- plugins/hls-rename-plugin/src/Ide/Plugin/Rename.hs
- stack-9.2.1.yaml
`newRdrName` in Rename.hs seems to be a debugging leftover.
> [ghc-9.2] Fix refine-imports plugin

- plugins/hls-qualify-imported-names-plugin/README.md
After seeing #2603 might as well improve the docs a little so we can maybe link to it.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2605"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve qualified import plugin readme

- plugins/hls-tactics-plugin/COMMANDS.md
- plugins/hls-tactics-plugin/src/Wingman/CodeGen.hs
- plugins/hls-tactics-plugin/src/Wingman/Judgements.hs
- plugins/hls-tactics-plugin/src/Wingman/Metaprogramming/Parser.hs
- plugins/hls-tactics-plugin/src/Wingman/Tactics.hs
- plugins/hls-tactics-plugin/test/CodeAction/RunMetaprogramSpec.hs
- plugins/hls-tactics-plugin/test/golden/MetaIdiom.expected.hs
- plugins/hls-tactics-plugin/test/golden/MetaIdiom.hs
- plugins/hls-tactics-plugin/test/golden/MetaIdiomRecord.expected.hs
- plugins/hls-tactics-plugin/test/golden/MetaIdiomRecord.hs
Idiom bracket support for Wingman metaprogramming.
Given:
```haskell
f :: a -> b -> Int
_ :: Maybe Int
```
running  `idiom (apply f)` will produce:
```haskell
f <$> (_ :: Maybe a) <*> (_ :: Maybe b)
```
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2607"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Wingman idioms

- plugins/hls-tactics-plugin/src/Wingman/GHC.hs
- plugins/hls-tactics-plugin/src/Wingman/Machinery.hs
- plugins/hls-tactics-plugin/src/Wingman/Tactics.hs
- plugins/hls-tactics-plugin/test/CodeAction/RunMetaprogramSpec.hs
- plugins/hls-tactics-plugin/test/golden/MetaFundeps.expected.hs
- plugins/hls-tactics-plugin/test/golden/MetaFundeps.hs
This PR fixes #2610 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2611"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Wingman: Fix fundeps

- hls-plugin-api/src/Ide/Types.hs
Nicer version as promised in
https://github.com/haskell/haskell-language-server/pull/2146.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2614"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use helpers from lsp to do code action prefixing

- docs/_static/theme_overrides.css
- docs/conf.py
- docs/features.md
- docs/supported-versions.md
- docs/what-is-hls.md
REMINDER: RTD provides a preview of the rendered documentation via a PR status.
This does a few things:
- Adds a clear listing of which LSP methods we support, and which we
don't (requested a couple of times recently).
- Lists every code action and code lens, which plugin provies them,
their status, and code action kind where applicable (apart from Wingman
because there are lots and I couldn't figure it all out).
Possibly some of this information belongs elsewhere, e.g. perhaps
instead of listing which versions don't have full support on this page,
we should instead add a page to the GHC support page that lists which
plugins work on which versions. Not sure.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2603"><img …
> Rework features documentation

- .github/actions/setup-build/action.yml
- .github/workflows/build.yml
- haskell-language-server.cabal
- src/Ide/Arguments.hs
- src/Ide/Version.hs
* [After diagnose the relese build was failing](https://github.com/haskell/haskell-language-server/pull/2606#issuecomment-1017227934) for alpine+ghc with integer-simple due to a new package requiring integer-gmp (https://hackage.haskell.org/package/mod)
* Pinged @maerwald and kindly added in ghcup the missinf ghc versions for alpine with integer-gmp (https://github.com/haskell/ghcup-metadata/pull/15)
* So we can remove the existing workaround here and let haskell/action download the new bindists
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2615"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use ghc+integer-gmp for alpine linux build release

- .github/workflows/test.yml
- hls-plugin-api/hls-plugin-api.cabal
- hls-plugin-api/src/Ide/PluginUtils.hs
- hls-plugin-api/test/Ide/PluginUtilsTest.hs
- hls-plugin-api/test/Main.hs
fix #2618
As `hls-plugin-api` doesn't have a test suite now, I add one. I think common utilities like this should have standalone unit tests. Maybe this can serve as a starting point.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2625"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix positionInRange

- plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
- plugins/hls-hlint-plugin/test/Main.hs
- plugins/hls-hlint-plugin/test/testdata/RightToLeftFixities.expected.hs
- plugins/hls-hlint-plugin/test/testdata/RightToLeftFixities.hs
Turns out we weren't applying the standard fixities to the parsed source before handing it over to `applyRefactorings'`. Standalone hlint works because it calls the refactor executable which does apply the fixities before doing the refactor.
This also fixes a class of issues where applying the hlint refactor does nothing.
Closed the previous PR because I rebased wrong.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2624"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix #2612 - hlint plugin - Apply fixities to parsed source before sending to apply-refact

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/Rules.hs
Applying the patch suggested by @Bodigrim https://github.com/haskell/haskell-language-server/issues/2583#issuecomment-1019375604
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2628"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Drop bytestring-encoding

- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
Apply the fix suggested by @Bodigrim in https://github.com/haskell/haskell-language-server/issues/2602#issuecomment-1019344264
Fixes https://github.com/haskell/haskell-language-server/issues/2602
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2629"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix off by one indexing error in openingBacktick

- ghcide/.editorconfig
This way `ghcide/.editorconfig` reproduces the root `.editorconfig`, except for line length restrictions.
Motivation: same as root, `ghcide/` contains some YAML files, which are de facto indented with 2 spaces.
> Specialize ghcide indent style to .hs

- configuration-ghc-921.nix
- flake.lock
- flake.nix
- flake_hackage/flake.nix
This is (partial) flake support for GHC 9.2.
This is in a limited state, especially:
- I have not repaired the support for a few plugins.
- `nix develop .#....-dev` target is not working, it pulls a few dependencies which are not overiden. I'll give another pass soon.
But the cool thing is that it allows to build `haskell-language-server` from flake in another project. I've just updated my work project to GHC 9.2 and I'm enjoying HLS thank to this flake.
Tell me if you prefer to merge "partial" support or if I need to work on the currently broken tasks. I cannot guarantee that I'll allocate time to this soon.
However, users can find this MR and point their flake to this commit and immediately get HLS in their project.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language- …
> Flake ghc 92

- .github/workflows/build.yml
- .gitlab/ci.sh
- haskell-language-server.cabal
* As commented in https://github.com/haskell/haskell-language-server/issues/2617#issuecomment-1019289588
* It seems binaries from the alpine build cant load files containing template haskell, checked in wsl/ubuntu by myself and in native ubuntu by @kokobd
```
Unexpected usage error
Dynamic loading not supported
```
* That behaviour was not noted explicitly in the pr (#2463) or the issue about (#2461)
* We have pending the release of 1.6.0 for January
* So this pr disables it until we clarificate the situation to unblock the release
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2638"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Disable alpine build by default

- ghcide/src/Development/IDE/Core/Rules.hs
- plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
- plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
- plugins/hls-retrie-plugin/src/Ide/Plugin/Retrie.hs
As documentation (https://hackage.haskell.org/package/text-2.0/docs/Data-Text-IO.html#v:readFile) explains, `T.readFile` is almost always a mistake. It's highly unlikely that files we try to read with `T.readFile` are in a locale encoding and not in UTF-8. Moreover, with `text-2.0` `fmap T.decodeUtf8 . BS.readFile` is up to 10x faster than `T.readFile`.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2637"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use T.decodeUtf8 + BS.readFile instead of T.readFile

- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/test/exe/Main.hs
Per the issue noted by @googleson78 - this fixes #2635, which deals with exporting Type Families.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2643"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Change Type Family Export pattern

- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
Shorter and potentially more efficient.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2645"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Implement stripPrefix via T.stripPrefix

- plugins/hls-tactics-plugin/src/Wingman/KnownStrategies/QuickCheck.hs
- plugins/hls-tactics-plugin/test/CodeAction/AutoSpec.hs
- plugins/hls-tactics-plugin/test/golden/GoldenArbitrarySingleConstructor.expected.hs
- plugins/hls-tactics-plugin/test/golden/GoldenArbitrarySingleConstructor.hs
Adds a special case in order to fix #1879
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2644"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Wingman: Fix #1879

- ChangeLog.md
* Eager to merge the fix, i forgot to push the changelog changes in #2647(although i used it in the release description)
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2658"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix changelog 1.6.1.0

- ghcide/test/exe/Main.hs
This is a repro for #2662.
I've tested with GHC 8.10.7, 9.0.2 and 9.2.1, using nix:
(Note: I do have to `export PATH` so it point to the correct `ghcide`. Is that the intended workflow or I missed something?)
GHC 9.2.1:
The import part is:
```diff
- "module ModuleB where\nimport Data.List.NonEmpty (fromList, NonEmpty ((:|)))\nmain = case (fromList []) of _ :| _ -> pure ()\n"
+ "module ModuleB where\nimport Data.List.NonEmpty (fromListNonEmpty ((:|)))\nmain = case (fromList []) of _ :| _ -> pure ()\n"
```
```
$ nix-shell -p haskell.compiler.ghc921 -p cabal-install -p zlib    
[nix-shell:~/srcs/haskell-language-server]$ export PATH=/home/guillaume/srcs/haskell-language-server/dist-newstyle/build/x86_64-linux/ghc-9.2.1/ghcide-1.6.0.0/x/ghcide/build/ghcide/:$PATH …
```
> test: repro for #2662: extend import list miss separator

- plugins/hls-hlint-plugin/README.md
- plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
- plugins/hls-hlint-plugin/test/Main.hs
Seems to fix #1279
All I did was not use the extensions that hlint turns on by default, and only use extensions found via the mod summary. The mod summary seems to also include extensions listed under the `extensions` stanza in the cabal file.
Not fully certain this doesn't break somebody's workflow.
If someone turns on an extension in the `hlint.yaml` and expects `hlint` to always consider it on I think that will conflict with this fix because I don't know how to disambiguate between an extension that is turned on by default by `hlint` and an extension turned on by the user in the `hlint.yaml`.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2671"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix hlint parsing file with disabled extension

- .github/workflows/hackage.yml
- docs/contributing/releases.md
Via a manual run setting publish=="true"
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2689"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Optionally publish packages definitely in the hackage workflow

- ghcide/test/exe/Main.hs
I cannot reproduce #2673 locally. Let's see if CI can
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2676"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add a test for #2673

- ghcide/test/exe/Main.hs
Should fix #2677
I could not reproduce it locally, but I found in the logs that it is possible for `getHover` to eat a `ghcide/reference/ready` custom message. If that happens the `skipManyTill` `ghcide/references/ready` will be starving until timeout. Not sure why this happens more often (or only?) on the 9.0.2 ubuntu-latest tests.
The fix skips messages until the hover response or `ghcide/reference/ready`, and depending on which was received skips messages until receiving the other.
In all the other places I could find where something similar happens they either do `getHover` or `skipManyTill` `ghcide/references/ready` but not both, and so that's why we don't see these problems in other tests.
As a side note at first I didn't realize more than one ghcide process was being run so the …
> Fix flaky boot def test

- cabal-ghc921.project
- ghcide/src/Development/IDE/GHC/Compat/Core.hs
- plugins/hls-alternate-number-format-plugin/README.md
- plugins/hls-alternate-number-format-plugin/hls-alternate-number-format-plugin.cabal
- plugins/hls-alternate-number-format-plugin/src/Ide/Plugin/Literals.hs
Didn't realize `hls-alternate-number-format-plugin` wasn't able to work with 9.2 yet. Added a `compat` function for upgrade. 
For reference, 9.2 updates the `FractionalLit` data type and the conversion from `FractionalLit -> Rational` is hidden behind the helper `rationalFromFractionalLit`. 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2696"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Build Alternate Number Format Plugin with GHC 9.2

- ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs
- ghcide/test/exe/Main.hs
The comma annotation was missing.
Close #2662.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2697"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix: handle comma in extend import list with ghc 9.2

- cabal-ghc921.project
- ghcide/src/Development/IDE/Core/Compile.hs
- ghcide/src/Development/IDE/GHC/Compat/Parser.hs
- plugins/hls-eval-plugin/hls-eval-plugin.cabal
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Rules.hs
- plugins/hls-eval-plugin/test/Main.hs
- plugins/hls-eval-plugin/test/testdata/T10.ghc92.expected
- plugins/hls-eval-plugin/test/testdata/T10.ghc92.expected.hs
- plugins/hls-eval-plugin/test/testdata/T11.ghc92.expected.hs
- plugins/hls-eval-plugin/test/testdata/T11.ghc92_expected.hs
- plugins/hls-eval-plugin/test/testdata/T12.ghc92.expected.hs
- plugins/hls-eval-plugin/test/testdata/T12.ghc92_expected.hs
- plugins/hls-eval-plugin/test/testdata/T13.ghc92.expected.hs
- plugins/hls-eval-plugin/test/testdata/T13.ghc92_expected.hs
- plugins/hls-eval-plugin/test/testdata/T15.ghc92_expected.hs
- plugins/hls-eval-plugin/test/testdata/T17.ghc92.expected.hs
- plugins/hls-eval-plugin/test/testdata/T17.ghc92_expected.hs
- plugins/hls-eval-plugin/test/testdata/T20.ghc92.expected.hs
- plugins/hls-eval-plugin/test/testdata/T20.ghc92_expected.hs
- plugins/hls-eval-plugin/test/testdata/TFlags.ghc92.expected.hs
- test/functional/Progress.hs
The eval plugin is building again and working partially. The codelens
(and evaluation) only happen for code in module comment, code appearing
in the top level comments / haddock are ignored. I need to walk the AST
to locate them.
This is work in progress for #2179.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2669"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Restore eval plugin build for GHC 9.2

- plugins/hls-class-plugin/hls-class-plugin.cabal
Earlier versions of ghc-exactprint lead to a build error:
```
[1 of 1] Compiling Ide.Plugin.Class ( src/Ide/Plugin/Class.hs, dist/dist-sandbox-fb36eb2d/build/Ide/Plugin/Class.o )
src/Ide/Plugin/Class.hs:36:59: error:
Module `Language.Haskell.GHC.ExactPrint.Utils' does not export `rs'
|
36 | import           Language.Haskell.GHC.ExactPrint.Utils   (rs)
|                                                           ^^
```
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2710"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix min bound for ghc-exactprint dependency in hls-class-plugin

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/Rules.hs
This will allow API clients (e.g. Sigma IDE) to customise the warning 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2712"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Expose DisplayTHWarning

- exe/Wrapper.hs
@jhrcek 
wrt https://github.com/haskell/haskell-language-server/pull/2675#issuecomment-1039053247
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2711"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve wrapper cradle errors

- .github/workflows/build.yml
Tested here: https://github.com/hasufell/haskell-language-server/releases
----
The idea here is that we pull the archives from the gitlab API instead of implementing pushing. That means a pipeline with the same tag as the release will have to have succeeded fully on gitlab CI.
----
Related: https://github.com/haskell/haskell-language-server/issues/2663
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2707"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix releasing

- .github/workflows/nix.yml
- configuration-ghc-901.nix
- configuration-ghc-921.nix
- flake.lock
- flake.nix
This is a work in progress.
This clean and fixs the `nix develop` shells for GHC 9.2 and GHC 9.0.
See individual commits for details, but in summary:
- `nix develop .#haskell-language-server-ghc921-dev` now works.
- When entering the shell, it creates an alias for `cabal` which points to the correct `cabal-xxx.project`
I'm planning on testing on GHC 9.0 soon too (but right now it is building the world of dependencies).
Future commits to this MR will (hopefully) includes:
- Support for GHC 9.0
- I'd like to restore the CI steps related to nix/flake, as an optionnal step which can be triggered on demand by developers. It will also populate the cachix cache.
- Additional cleanups. I'm trying to remove all the explicit "hacks" `if version == ...`
<a …
> Nix flake fix dev shells

- hls-test-utils/hls-test-utils.cabal
- hls-test-utils/src/Test/Hls/Util.hs
Remove hspec dependency
Closes: https://github.com/haskell/haskell-language-server/issues/1835
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2721"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove `getHspecFormattedConfig` which is no longer used

- plugins/hls-tactics-plugin/src/Wingman/Naming.hs
- plugins/hls-tactics-plugin/test/CodeAction/DestructSpec.hs
- plugins/hls-tactics-plugin/test/golden/DestructInt.expected.hs
- plugins/hls-tactics-plugin/test/golden/DestructInt.hs
Fixes #2667
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2717"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Wingman: Don't use keywords for variable names

- ghcide/src/Development/IDE/GHC/ExactPrint.hs
- ghcide/test/data/multi/a/A.hs
- ghcide/test/data/multi/a/a.cabal
- ghcide/test/data/multi/c/C.hs
- ghcide/test/data/multi/c/c.cabal
- ghcide/test/data/multi/cabal.project
- ghcide/test/data/multi/hie.yaml
- ghcide/test/exe/Main.hs
- ghcide/test/src/Development/IDE/Test.hs
This PR is just tests showing that packages of previously loaded components seem to be forgotten when loading a new component. I expect the tests to fail only in GHC 9.2
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2687"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Multi component issues in GHC 9.2

- ghcide/src/Development/IDE/Core/Service.hs
- ghcide/test/exe/Main.hs
Lower the verbosity of most plugin build actions to `Debug`, e.g. log lines like:
```
2022-02-19 08:49:46.711648 [ThreadId 9491] INFO hls:	finish: Wingman.judgementForHole.TypeCheck (took 0.00s)
2022-02-19 08:49:46.711712 [ThreadId 9492] INFO hls:	finish: Wingman.judgementForHole.False (took 0.00s)
2022-02-19 08:49:46.712412 [ThreadId 9493] INFO hls:	finish: Wingman.getIdeDynflags.GetModSummaryWithoutTimestamps (took 0.00s)
2022-02-19 08:49:46.71311 [ThreadId 9494] INFO hls:	finish: Wingman.judgementForHole.GetHieAst (took 0.00s)
2022-02-19 08:49:46.713207 [ThreadId 9495] INFO hls:	finish: Wingman.judgementForHole.GetBindings (took 0.00s)
2022-02-19 08:49:46.713284 [ThreadId 9497] INFO hls:	finish: Wingman.judgementForHole.False (took 0.00s)
2022-02-19 08:49:46.713254 [ThreadId 9496] INFO …
```
> Tone down logging of plugin rules

- ghcide/src/Development/IDE/Types/Logger.hs
- src/Ide/Main.hs
It's a bit non-standard, and moreover it's entirely dead.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2727"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Delete the Telemetry log level

- ghcide/.hlint.yaml
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/FileExists.hs
- ghcide/src/Development/IDE/Core/FileStore.hs
- ghcide/src/Development/IDE/Core/FileUtils.hs
- ghcide/src/Development/IDE/Core/RuleTypes.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/Core/Service.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/LSP/LanguageServer.hs
- ghcide/src/Development/IDE/Main.hs
- ghcide/src/Development/IDE/Types/Exports.hs
- ghcide/src/Development/IDE/Types/Shake.hs
- hls-plugin-api/hls-plugin-api.cabal
This patch does two things:
1. It allows us to track the versions of `Values` which don't come from the VFS, as long as those
particular `Values` depended on the `GetModificationTime` rule
This is necessary for the recompilation avoidance scheme implemented in #2316
2. It removes the VFSHandle type and instead relies on snapshots of the VFS state taken on every rebuild
of the shake session to ensure that we see a consistent VFS state throughout each individual build.
With regards to 2, this is necessary because the lsp library mutates its VFS file store as changes come
in. This can lead to scenarios where the HLS build session can see inconsistent views of the VFS.
One such scenario is.
1. HLS build starts, with VFS state A
2. LSP Change notification comes in and lsp updates its internal …
> Track file versions accurately.

- cabal-ghc90.project
- cabal-ghc921.project
- cabal.project
- flake.nix
- ghcide/ghcide.cabal
- stack-8.10.6.yaml
- stack-8.10.7.yaml
- stack-8.6.5.yaml
- stack-8.8.4.yaml
- stack-9.0.1.yaml
- stack-9.0.2.yaml
- stack-9.2.1.yaml
- stack.yaml
New hie-bios release!
Big thanks to @hasufell, @Kleidukos, @jneira and more who made this release possible.
Big Change:  https://github.com/haskell/hie-bios/pull/282
TLDR; hie-bios (consequentially HLS) will now honour the `with-compiler` field in `cabal.project`!
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2738"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Upgrade to hie-bios 0.9.0

- flake.lock
https://github.com/haskell/haskell-language-server/pull/2738 updated
`flake.nix` but not `flake.lock`.
`nix develop` will just modify `flake.lock` locally, but `nix-shell`
will actually fail without this.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2743"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix flake.lock

- .github/workflows/test.yml
- ghcide/src/Development/IDE.hs
- ghcide/src/Development/IDE/Core/Compile.hs
- ghcide/src/Development/IDE/Core/RuleTypes.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/GHC/Compat.hs
- ghcide/src/Development/IDE/GHC/Orphans.hs
- ghcide/src/Development/IDE/Import/DependencyInformation.hs
- ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs
- ghcide/src/Development/IDE/Types/Shake.hs
The old recompilation avoidance scheme performs quite poorly when code generation is needed. We end up needing to recompile modules basically any time anything in their transitive dependency closure changes.
Most versions of GHC we currently support don't have a working implementation of code unloading for object code, and no version of GHC supports this on certain platforms like Windows. This makes it completely infeasible for interactive use, as symbols from previous compiles will shadow over all future compiles.
This means that we need to use bytecode when generating code for Template Haskell. Unfortunately, we can't serialize bytecode, so we will always need to recompile when the IDE starts. However, we can put in place a much tighter recompilation avoidance scheme for subsequent …
> Improve recompilation avoidance in the presence of TH

- exe/Main.hs
- ghcide/exe/Main.hs
- ghcide/ghcide.cabal
- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/LSP/LanguageServer.hs
- ghcide/src/Development/IDE/Main.hs
- ghcide/src/Development/IDE/Plugin/LSPWindowShowMessageRecorder.hs
- ghcide/src/Development/IDE/Types/Logger.hs
- hls-graph/hls-graph.cabal
- hls-graph/src/Development/IDE/Graph/Internal/Types.hs
This PR adds a new `Recorder` that emits LSP `WindowShowMessage` notifications, and then uses it to surface errors to the user. 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2750"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> LSP window message log recorder

- ghcide/src/Development/IDE/Core/Shake.hs
- hls-graph/src/Development/IDE/Graph/Internal/Action.hs
- hls-graph/src/Development/IDE/Graph/Rule.hs
For a long time, `defineEarlyCutoff` has been accessing the `Values` store directly
to compute `GetModificationTime` values instead of calling `use`, breaking the
invariant. The values are used to associate the rule result to a file version,
which gets recorded in the `Value` as well as used as the key in the Diagnostics
store.
The problem here is that the `GetModificationTime` rule computes a new version and
mutates the Values store, so if `defineEarlyCutoff` peeks in the store before
`GetModificationTime` has run, it will grab the old version. This leads to lost
diagnostics and potentially to misversioned `Values`.
Fixing the problem is tricky, because we cannot simply use `GetModificationTime`
inside `defineEarlyCutoff` for all rules. There are three issues with this:
1. Creating a …
> Estimate file versions safely

- exe/Main.hs
- ghcide/src/Development/IDE/Plugin/LSPWindowShowMessageRecorder.hs
- ghcide/src/Development/IDE/Types/Logger.hs
- hls-graph/hls-graph.cabal
- hls-graph/src/Development/IDE/Graph/Internal/Types.hs
Follow-ups from #2750 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2755"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Adjust rendering of error logs and drop unneeded MonadUnliftIO instance

- .github/workflows/test.yml
- plugins/hls-alternate-number-format-plugin/README.md
- plugins/hls-alternate-number-format-plugin/hls-alternate-number-format-plugin.cabal
- plugins/hls-alternate-number-format-plugin/src/Ide/Plugin/AlternateNumberFormat.hs
- plugins/hls-alternate-number-format-plugin/src/Ide/Plugin/Literals.hs
- plugins/hls-alternate-number-format-plugin/test/Main.hs
- plugins/hls-alternate-number-format-plugin/test/testdata/TExpectBinaryFormat.hs
- plugins/hls-alternate-number-format-plugin/test/testdata/TExpectHexFloatFormat.hs
- plugins/hls-alternate-number-format-plugin/test/testdata/TExpectNoBinaryFormat.hs
- plugins/hls-alternate-number-format-plugin/test/testdata/TExpectNoHexFloatFormat.hs
- plugins/hls-alternate-number-format-plugin/test/testdata/TExpectNoNumDecimalFormat.hs
- plugins/hls-alternate-number-format-plugin/test/testdata/TExpectNumDecimalFormat.hs
- plugins/hls-alternate-number-format-plugin/test/testdata/TFindLiteralDoLet.hs
- plugins/hls-alternate-number-format-plugin/test/testdata/TFindLiteralDoReturn.hs
- plugins/hls-alternate-number-format-plugin/test/testdata/TFindLiteralIntCase.hs
- plugins/hls-alternate-number-format-plugin/test/testdata/TFindLiteralIntCase2.hs
- plugins/hls-alternate-number-format-plugin/test/testdata/TFindLiteralIntPattern.hs
- plugins/hls-alternate-number-format-plugin/test/testdata/TFindLiteralList.hs
This fixes alternate number format test-suite for 9.2.1 and enables it in github workflows. The plugin is already enabled in 9.2.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2752"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix test failure for AlternateNumberFormat

- .github/workflows/test.yml
- bindist/GNUmakefile.in
- plugins/hls-change-type-signature-plugin/README.md
- plugins/hls-change-type-signature-plugin/hls-change-type-signature-plugin.cabal
- plugins/hls-change-type-signature-plugin/src/Ide/Plugin/ChangeTypeSignature.hs
- plugins/hls-change-type-signature-plugin/test/Main.hs
- plugins/hls-change-type-signature-plugin/test/testdata/TLocalBinding.expected.hs
- plugins/hls-change-type-signature-plugin/test/testdata/TLocalBinding.hs
- plugins/hls-change-type-signature-plugin/test/testdata/TLocalBindingShadow1.expected.hs
- plugins/hls-change-type-signature-plugin/test/testdata/TLocalBindingShadow1.hs
- plugins/hls-change-type-signature-plugin/test/testdata/TLocalBindingShadow2.expected.hs
- plugins/hls-change-type-signature-plugin/test/testdata/TLocalBindingShadow2.hs
- plugins/hls-change-type-signature-plugin/test/testdata/ghc921-error1.txt
- plugins/hls-change-type-signature-plugin/test/testdata/ghc921-error2.txt
- plugins/hls-change-type-signature-plugin/test/testdata/ghc921-error3.txt
This should fix the test errors for 9.2.1 and adds new test cases specifically for 9.2.1.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2761"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix Change Type Signature Plugin test suite for 9.2.1

- .github/workflows/test.yml
- ghcide/exe/Main.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/Types/Options.hs
- hls-graph/hls-graph.cabal
- hls-graph/src/Development/IDE/Graph.hs
- hls-graph/src/Development/IDE/Graph/Database.hs
- hls-graph/src/Development/IDE/Graph/Internal/Action.hs
- hls-graph/src/Development/IDE/Graph/Internal/Database.hs
- hls-graph/src/Development/IDE/Graph/Internal/Options.hs
- hls-graph/src/Development/IDE/Graph/Internal/Rules.hs
- hls-graph/src/Development/IDE/Graph/Internal/Types.hs
- hls-graph/test/ActionSpec.hs
- hls-graph/test/DatabaseSpec.hs
- hls-graph/test/Example.hs
- hls-graph/test/Main.hs
- hls-graph/test/RulesSpec.hs
- hls-graph/test/Spec.hs
- hls-test-utils/src/Test/Hls.hs
- src/Ide/Main.hs
Almost completely lifted from Shake. 
I also started a barebones test suite for hls-graph and removed some legacy option placeholders (`shakeThreads` and `shakeFiles`)
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2756"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Implement cycle detection in hls-graph

- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/test/exe/Main.hs
Avoid parentheses in simple cases (`a`, `Char`, `()`,...).
The good news is, that getting types inside tuples and lists will not force you to apply hint "Redundant brackets":
```haskell
g :: a -> _
g x = (x, const x)
--------------------------
-- before
g :: a -> ((a, b -> a))
--------------------------
-- after
g :: a -> (a, b -> a)
```
The caveat is that it is still context unaware (works on text only) and the common use case of `f :: _` is not improved.
- Hopefully closes #2674 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2764"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Avoid extra parens for wildcard type signature

- docs/installation.md
Gentoo version is available via the overlay. These are the instructions to install.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2778"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add Gentoo installation details

- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- ghcide/test/exe/Main.hs
- test/functional/Completion.hs
Close #2786
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2788"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't show the redundant space

- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs
- ghcide/test/exe/Main.hs
This is for #2734 
Brief intro:
With 
```haskell
Module A where
data Foo = Foo | Bar
```
it will suggest import `Foo(..)` now, like `import A(Foo(..))` and `Add Foo(..) to the import list of A`.
---
Note:
Support Now!
~~This doesn't work for record fields, ideally, we should support this.~~
Example:
```haskell
data Foo = Bar {a :: Int}
```
if we have `f = a`, we should also have `import A(Foo(..))`. Maybe we can extend
https://github.com/haskell/haskell-language-server/blob/621c2bb2173d5231082e5e4c4f157b2efb4f94c7/ghcide/src/Development/IDE/Types/Exports.hs#L64-L70
with a field to indicate `a`'s data type if `a` is a record field.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2782"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Allow import all constructors

- ghcide/src/Development/IDE/Core/Rules.hs
I want to change the `LspT` action that gets run the first time that we run into unsupported Template Haskell. This can also be used to completely disable the TH warning (programmatically) .
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2781"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Customizable TH warning

- hls-graph/src/Development/IDE/Graph/Internal/Database.hs
`waitConcurrently` is being a bit dumb and delaying some of the synchronous work until the async comps. are done for no good reason. 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2805"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> [hls-graph] Optimise waitConcurrently

- ghcide/bench/lib/Experiments.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/Plugin/Test.hs
- ghcide/test/src/Development/IDE/Test.hs
- shake-bench/shake-bench.cabal
- shake-bench/src/Development/Benchmark/Rules.hs
Add columns to keep track of total GHC rebuilds, time for first response and
average time per response
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2814"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> bench: Add more metrics

- docs/troubleshooting.md
The existing command errors:
```
$ cabal install pkg:haskell-language-server
cabal: Internal error in target matching. It should always be possible to find
a syntax that's sufficiently qualified to give an unambiguous match. However
when matching 'pkg:haskell-language-server' we found haskell-language-server
(named-package) which does not have an unambiguous syntax. The possible syntax
and the targets they match are as follows:
'haskell-language-server' which matches haskell-language-server
(named-package)
'pkg:haskell-language-server' which matches haskell-language-server
(named-package), pkg:haskell-language-server (unknown-component),
:pkg:pkg:lib:pkg:file:haskell-language-server (unknown-file)
':pkg:haskell-language-server' which matches haskell-language-server
(named-package)
```
<a …
> Fix `cabal install` commands for local HLS build in docs

- plugins/hls-module-name-plugin/src/Ide/Plugin/ModuleName.hs
- plugins/hls-module-name-plugin/test/Main.hs
- plugins/hls-module-name-plugin/test/testdata/CorrectName.hs
- plugins/hls-module-name-plugin/test/testdata/hie.yaml
- test/functional/Progress.hs
Close #2797.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2826"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Should no related code lens if the module name is correct

- ghcide/src/Development/IDE/GHC/Compat/Outputable.hs
- ghcide/src/Development/IDE/Spans/Common.hs
- ghcide/test/exe/Main.hs
Close #2716.
GHC 9.2 changed the default `showSDocUnsafe` style from [`defaultUserStyle`](https://hackage.haskell.org/package/ghc-9.0.2/docs/src/GHC.Utils.Outputable.html#showSDoc) to [`defaultDumpStyle`](https://hackage.haskell.org/package/ghc-9.2.1/docs/src/GHC.Utils.Outputable.html#defaultSDocContext). This pr force `showGhc` with `defaultUserStyle`, hierarchy calling result shows the following functions are affected, but only [`atPoint`](https://github.com/haskell/haskell-language-server/blob/3c527431bc10879ffa80dfea23a80299992d87cc/ghcide/src/Development/IDE/Spans/AtPoint.hs#L249-L251)(The function returns type varibale) really render [`IfaceType`](https://hackage.haskell.org/package/ghc-9.2.1/docs/GHC-Iface-Type.html#t:IfaceType) type.
<a …
> Restore concise type variables in ghc-9.2

- exe/Main.hs
- ghcide/exe/Main.hs
- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/src/Development/IDE.hs
- ghcide/src/Development/IDE/Core/FileStore.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/LSP/Notifications.hs
- ghcide/src/Development/IDE/LSP/Server.hs
- ghcide/src/Development/IDE/Plugin/HLS.hs
- ghcide/test/exe/Main.hs
- hls-plugin-api/src/Ide/Types.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs
We need to take VFS snapshots as soon as we get a change notification.
Consider the following interleaving of events:
1. Change Notification A (updates LSP VFS)
2. Restart Shake Session (A changed) initiated
3. Change Notification B (updates LSP VFS)
4. Restart Shake Session (A changed) takes VFS snapshot and possibly performs more computation
5. Restart Shake Session (B changed)
In particular, between step 3 and 5, we took a snapshot for a previous build,
but this snapshot included changes from a newer VFS state that the build should
not have seen.
To fix this, we need to take snapshots as soon as a notification handler is
called, before forking any threads. This works because LSP calls all handlers
in a single threaded fashion and these handlers block message processing. It
is essential …
> Avoid race conditions with VFS and VFS versions

- ghcide/src/Development/IDE/Core/FileExists.hs
- ghcide/test/exe/Main.hs
"add missing modules (non workspace)" became flaky after the recent changes to snapshot VFS data.
The test calls `createDoc` to open a `module B imports A` where `A` does not exist, then waits for the missing module error and calls `createDoc` to open a `module A`. Importantly, both `B` and `A` live outside the workspace and thus are not subject to `FileWatched` notifications. 
Unfortunately, the test wasn't testing the right thing because `createDoc` sends a `FileWatched` notification right before sending a `DidOpen` notification! This was causing a race condition, where the `FileWatched` notification triggers a build that may or may not run the `FileExists ModuleA` key:
* If it does, then the key will resolve to `False` since `ModuleA` exists neither in the file system nor in VFS, and …
> Fix flaky test 

- flake.nix
Just a minor convenience thingy
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2841"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add HLS Cachix to `nixConfig` in flake

- plugins/hls-call-hierarchy-plugin/README.md
- plugins/hls-call-hierarchy-plugin/hls-call-hierarchy-plugin.cabal
- plugins/hls-call-hierarchy-plugin/src/Ide/Plugin/CallHierarchy/Internal.hs
These legacy codes are used to force update `hiedb` while querying hierarchy results, deleting now since users should save their changes before querying call hierarchy.
Will close #2843.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2844"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't refresh HieDb while querying hierarchy results

- docs/supported-versions.md
I linked someone to it on IRC and I noticed that it was out of date.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2840"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update plugin support table

- ghcide/src/Development/IDE/Core/Compile.hs
- ghcide/src/Development/IDE/GHC/Compat/Outputable.hs
- ghcide/src/Development/IDE/GHC/Orphans.hs
- ghcide/src/Development/IDE/GHC/Util.hs
- ghcide/src/Development/IDE/LSP/Outline.hs
- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs
- ghcide/src/Development/IDE/Plugin/Completions.hs
- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- ghcide/src/Development/IDE/Spans/AtPoint.hs
- ghcide/src/Development/IDE/Spans/Common.hs
- ghcide/src/Development/IDE/Spans/Documentation.hs
- ghcide/src/Development/IDE/Types/Exports.hs
- ghcide/test/exe/Main.hs
- plugins/hls-change-type-signature-plugin/src/Ide/Plugin/ChangeTypeSignature.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/GHC.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Util.hs
- plugins/hls-explicit-imports-plugin/src/Ide/Plugin/ExplicitImports.hs
- plugins/hls-pragmas-plugin/src/Ide/Plugin/Pragmas.hs
- plugins/hls-refine-imports-plugin/src/Ide/Plugin/RefineImports.hs
- plugins/hls-retrie-plugin/src/Ide/Plugin/Retrie.hs
- plugins/hls-tactics-plugin/src/Wingman/Debug.hs
We choose `printOutputable :: Outputable a => a -> Text` finally.
---
Extends #2828, this pr wrapped `showSDocUnsafe` and  unified all `SDoc` printing functions into the following four functions
1. `showGhc` has `defaultUserStyle` and `suppressUnique`, we'd use this as much as we can to print ghc internal.
2. `showGhcWithUniques` is the alias of `showSDocUnsafe`, it may have different behavior under different ghc versions, like #2716.
3. `prettyPrint` sames as `showGhc` but return `String` instead of `Text`.
4. `prettyPrintWithUnique`, the `String` version of `showGhcWithUniques`.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2830"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Unify showSDocUnsafe

- .gitlab/ci.sh
- release/upload.sh
- gitlab-ci: Fix executable extension on windows
- Also recognize gz files in upload script
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2861"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> release script fixes

- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/test/exe/Main.hs
I noticed that current code action that suggests to export otherwise unused toplevel name adds the name to module's export list in a very unsophisticated way which requires subsequent fix of style by hand, e.g.
```haskell
module Mod 
( foo
, bar
) where
```
becomes
```haskell
module Mod 
( foo
, bar, baz
) where
```
It occured to me that almost any style of the export list can be maintained if the code action will just look at the text between subsequest exported names, `"\n  , "` in the example above, and just use that as separator between exported entries.
One thing to look for is that separators between names can be different, e.g. there can be haddoc comments like
```haskell
module Mod 
( foo
, bar
-- * For testing
, baz
) where
```
but this can be resolved by just looking at all …
> Improve name export code action

- plugins/hls-call-hierarchy-plugin/hls-call-hierarchy-plugin.cabal
- plugins/hls-call-hierarchy-plugin/src/Ide/Plugin/CallHierarchy/Internal.hs
I want to build the call hierarchy plugin in a stockage LTS 16.11 system, which has an older version of `aeson`
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2868"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Compatibility with older aeson releases

- plugins/hls-call-hierarchy-plugin/hls-call-hierarchy-plugin.cabal
I want to make a Hackage release including the extended aeson compat. changes from #2868
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2873"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> hls-call-hierarchy-plugin Patch release

- ghcide/ghcide.cabal
fails with prettyprinter 1.6
```
[37 of 77] Compiling Development.IDE.Types.Logger ( src/Development/IDE/Types/Logger.hs, dist/build/Development/IDE/Types/Logger.o )
src/Development/IDE/Types/Logger.hs:57:1: error:
Could not find module `Prettyprinter'
Use -v (or `:set -v` in ghci) to see a list of the files searched for.
|
57 | import           Prettyprinter                 as PrettyPrinterModule
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
src/Development/IDE/Types/Logger.hs:58:1: error:
Could not find module `Prettyprinter.Render.Text'
Use -v (or `:set -v` in ghci) to see a list of the files searched for.
|
58 | import           Prettyprinter.Render.Text     (renderStrict)
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
cabal: Failed to build …
```
> ghcide needs prettyprinter-1.7 to build

- ghcide/ghcide.cabal
E. g., `instance Default EpaLocation` is not present in `ghc-exactprint-1.3`.
https://hackage.haskell.org/package/ghc-exactprint-1.3.0/docs/Language-Haskell-GHC-ExactPrint-Orphans.html
vs.
https://hackage.haskell.org/package/ghc-exactprint-1.4.0/docs/Language-Haskell-GHC-ExactPrint-Orphans.html
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2876"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ghcide requires ghc-exactprint >= 1.4

- ghcide/src/Development/IDE/GHC/Compat/Util.hs
- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/test/exe/Main.hs
Closes #2859
Revert partial changes from #2483
For redundant import actions, the code path ends up calling `wrapOperatorInParen` which under the hood makes a call to `is_ident` which is a low-level `Char -> Bool`. The function will panic when it's input falls out of ASCII range.
The fix is just to match directly on the '_' character. Outside of this codepath, the original
functionality has been restored (using `isAlpha`).
Also removes the now unnecessary `is_ident` compat layer.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2870"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix hanging redundant import on Unicode function 

- exe/Main.hs
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Types/Logger.hs
- stack-lts16.yaml
I intend to continue supporting LTS 16 for a little longer.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2877"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Restore compat. with prettyprinter 1.6

- .github/workflows/flags.yml
- cabal-ghc90.project
- cabal-ghc92.project
- cabal.project
- hie-compat/hie-compat.cabal
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-hlint-plugin/test/Main.hs
- stack-lts16.yaml
- stack-lts19.yaml
- stack.yaml
While working on #2866 I noticed that `hls-hlint-plugin`requires per-ghc-version flags. This prevents `cabal install haskell-language-server` from working across ghc versions.
I think we can get rid of these flags:
- the `ghc-lib` flag is unnecessary, there is no downside to using ghc-lib always for maximum compatibility
- the `hlint34` flag is unnecessary, cabal should be able to use the right version
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2867"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> simplify hlint plugin Cabal descriptor

- plugins/hls-change-type-signature-plugin/hls-change-type-signature-plugin.cabal
`hls-change-type-signature-plugin` appears to have a few `.txt` files that are necessary for running tests, but those files haven't been added to `extra-source-files` in `hls-change-type-signature-plugin`.
This appears to be causing errors when we try to build `hls-change-type-signature-plugin` in Nixpkgs: https://hydra.nixos.org/build/175155441/nixlog/1.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2887"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add .txt files as extra-source-files for hls-change-type-signature-plugin

- plugins/hls-pragmas-plugin/hls-pragmas-plugin.cabal
Otherwise `Development.IDE.printOutputable` is not available.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2884"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> hls-pragmas-plugin requires ghcide >= 1.7

- plugins/hls-change-type-signature-plugin/hls-change-type-signature-plugin.cabal
Reference #2884, I think hls-change-type-signature-plugin should also require ghcide >=1.7 since it uses `printOutputable`.
https://github.com/haskell/haskell-language-server/blob/6d319ba24d60d87677913a9c1a71279959c1b2c2/plugins/hls-change-type-signature-plugin/src/Ide/Plugin/ChangeTypeSignature.hs#L134-L138
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2889"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Modify ghcide requirements of hls-change-type-signature-plugin

- .github/workflows/test.yml
- stack.yaml
Surprised #2669 didn't enable the test.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2893"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Enable hls-eval-plugin test on ghc-9.2.2

- stack.yaml
It looks hls-alternate-number-format-plugin missed in stack.yaml
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2891"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Build hls-alternate-number-format-plugin with stack.yaml

- .github/workflows/test.yml
- plugins/hls-call-hierarchy-plugin/test/Main.hs
- plugins/hls-pragmas-plugin/hls-pragmas-plugin.cabal
Try to fix #2881.
This pr works fine on my machine, I'll rerun the test several times to evaluate the changes.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2888"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix hls-call-hierarchy-plugin tests

- .github/workflows/flags.yml
- cabal.project
- docs/contributing/contributing.md
- ghcide/.hlint.yaml
- ghcide/exe/Arguments.hs
- ghcide/exe/Main.hs
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/Service.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/Main.hs
- ghcide/src/Development/IDE/Monitoring/EKG.hs
- ghcide/src/Development/IDE/Monitoring/OpenTelemetry.hs
- ghcide/src/Development/IDE/Types/Monitoring.hs
- hls-graph/src/Development/IDE/Graph/Database.hs
- hls-graph/src/Development/IDE/Graph/Internal/Database.hs
Install a metrics server at port 8000 via EKG with the following metrics:
- `ghcide.values_count`- count of build results in the store
- `ghcide.database_count` - count of build keys in the store (these two would be the same in the absence of GC)
- `ghcide.build_count` - build count. A key is GC'ed if it is dirty and older than 100 builds
- `ghcide.dirty_keys_count` - non transitive count of dirty build keys
- `ghcide.indexing_pending_count` - count of items in the indexing queue
- `ghcide.exports_map_count` - count of identifiers in the exports map.
Unfortunately the EKG packages need allow-newer entries for GHC 9. This is also the case for the snap-server packages and dependencies. Since it doesn't look like these are getting resolved in Hackage any time soon, let's hold back on merging …
> Expose runtime metrics via EKG

- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/Core/Shake.hs
This used to fail in the CLI with
```
Internal error, getIdeGlobalExtras, no entry for DisplayTHWarning
```
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2895"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix DisplayTHWarning error

- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs
- plugins/hls-eval-plugin/test/Main.hs
- plugins/hls-eval-plugin/test/testdata/TMultiResult.expected.hs
- plugins/hls-eval-plugin/test/testdata/TMultiResult.hs
- fix multiline eval padding (`concatMap lines`)
- add test for multiline show instance
---
- closes #2907
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2910"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix multiline eval plugin padding

- docs/requirements.txt
- support Python 3.10 with newer Sphinx
- make the bounds less strict
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2918"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump documentation requirements

- ghcide/session-loader/Development/IDE/Session/VersionCheck.hs
- fixes #1777 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2819"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> ghcide: remove redundant env NIX_GHC_LIBDIR

- docs/features.md
- mention `std[in|out|err]` problems
- #2913
- #1977
- link to differences with doctest
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2917"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Document eval plugin limitations

- ghcide/src/Development/IDE/Plugin/CodeAction.hs
- ghcide/test/exe/Main.hs
This is a followup to #2764
I noticed that for cases like `foo :: _` the GHC always prints `• In the type signature:`, but when part of a subtype it will print a stack of contexts ending with `In the type signature:` but without `•`. Also for the 'toplevel' case the type signature in the `In the type signature` bit will be normalized into `foo :: _\n` which can be checked for.
For instance this is the message when hole is not 'toplevel' - there's a stack of where the hole was located ending with `In the type signature`
```
source/library/Language/Haskell/Brittany/Internal.hs:130:20: error:
• Found type wildcard ‘_’ standing for ‘GhcPs’
To use the inferred type, enable PartialTypeSignatures
• In the first argument of ‘HsDecl’, namely ‘_’
In the type ‘HsDecl _’
In the type signature: decl …
```
> Omit more parens for wildcard type signature

- docs/installation.md
Updated Archlinux installation section:
- re-worded AUR package section to be more accurate wrt distribution changes in 1.7.0.0,
- removed the mention of the "official" package (it hasn't been updated beyond 1.3.0.0 and is practically unmaintained; its usefulness for the actual development is very limited)
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2933"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update Archlinux installation section

- ghcide/src/Development/IDE/Core/FileStore.hs
Quick typo fix, "dependecies" -> "dependencies"
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2934"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Typo fix, dependecies -> dependencies

- flake.lock
I've had errors with the current HLS built via nix since it uses an older
nixpkgs than mine with a different glibc
```
Unexpected usage error
/nix/store/lyl6nysc3i3aqhj6shizjgj0ibnf1pvg-glibc-2.34-210/lib/libc.so.6: undefined symbol: _dl_audit_symbind_alt, version GLIBC_PRIVATE
```
NB: Maybe I should add pre-commit to the devShell since I got:
```
`pre-commit` not found.  Did you forget to activate your virtualenv?
```
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2937"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> chore(nix): bump nixpkgs to prevent glibc issues

- plugins/hls-fourmolu-plugin/hls-fourmolu-plugin.cabal
- plugins/hls-fourmolu-plugin/src/Ide/Plugin/Fourmolu.hs
- stack.yaml
This PR adds support for `fourmolu-0.7`
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2944"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Support `fourmolu ^>= 0.7`

- .github/workflows/caching.yml
- .github/workflows/flags.yml
- .github/workflows/test.yml
- .gitlab-ci.yml
- bindist/ghcs
- bindist/ghcs-Msys
- cabal.project
- ghcide/ghcide.cabal
- haskell-language-server.cabal
- plugins/hls-ormolu-plugin/hls-ormolu-plugin.cabal
- stack-lts19.yaml
- stack.yaml
Dropped ghc-8.10.6 and ghc-9.0.1, keep supporting ghc-9.2.2.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2936"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Support ghc-9.2.3

- ghcide/exe/Arguments.hs
- ghcide/exe/Main.hs
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/Compile.hs
- ghcide/src/Development/IDE/Core/FileStore.hs
- ghcide/src/Development/IDE/Core/RuleTypes.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/GHC/Compat.hs
- ghcide/src/Development/IDE/GHC/Compat/Core.hs
- ghcide/src/Development/IDE/GHC/Compat/Outputable.hs
- ghcide/src/Development/IDE/GHC/CoreFile.hs
- ghcide/src/Development/IDE/GHC/Orphans.hs
- ghcide/src/Development/IDE/Types/Options.hs
- ghcide/test/data/THCoreFile/THA.hs
- ghcide/test/data/THCoreFile/THB.hs
- ghcide/test/data/THCoreFile/THC.hs
- ghcide/test/data/THCoreFile/hie.yaml
- ghcide/test/data/THUnboxed/THA.hs
- ghcide/test/exe/Main.hs
- hls-graph/hls-graph.cabal
- hls-graph/src/Development/IDE/Graph/Internal/Types.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs
- plugins/hls-retrie-plugin/src/Ide/Plugin/Retrie.hs
Serialize core to core files
Add a `.hi.core` file format to which we serialize out compiled core after generating it.
This core is then read back in on subsequent runs and compiled to bytecode.
This greatly speeds up startup times when we need compilation, as we can simply read bytecode
off the disk instead of having to recompile a lot of modules
This is based off Fat Interface files in GHC: https://gitlab.haskell.org/ghc/ghc/-/merge_requests/7502
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2813"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Serialize Core

- exe/Plugins.hs
- plugins/hls-class-plugin/hls-class-plugin.cabal
- plugins/hls-class-plugin/src/Ide/Plugin/Class.hs
- plugins/hls-class-plugin/test/Main.hs
- plugins/hls-class-plugin/test/testdata/T6.1.expected.hs
- plugins/hls-class-plugin/test/testdata/T6.2.expected.hs
- plugins/hls-class-plugin/test/testdata/T6.hs
Before this change, the `hls-class-plugin` would offer to create placeholders for methods which were already implemented. This change walks through the AST of the instance and figure out which methods exist and only offer to implement those which don't already exist.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2956"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> hls-class-plugin: Only create placeholders for unimplemented methods

- ghcide/src/Development/IDE/LSP/HoverDefinition.hs
- ghcide/src/Development/IDE/LSP/LanguageServer.hs
- ghcide/src/Development/IDE/Plugin/HLS/GhcIde.hs
- hls-plugin-api/src/Ide/Types.hs
Don't hard-wire handlers, but make sure all handlers are associated to a
PluginDescriptor, s.t. we can check that the handler is actually enabled
for a given request.
Extracted from #2945 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2977"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Implement PluginMethod for hard-wired in handlers

- exe/Plugins.hs
- ghcide/src/Development/IDE/Plugin/HLS.hs
- ghcide/test/exe/Main.hs
- haskell-language-server.cabal
- hls-plugin-api/hls-plugin-api.cabal
- hls-plugin-api/src/Ide/Types.hs
- plugins/default/src/Ide/Plugin/ExampleCabal.hs
This PR is the foundation for #2940 and as such, I'd be really happy if we could get a review here before ZuriHac :)
I am working on a minimal example Plugin, that should illustrate that stuff works by tomorrow.
The Idea is to teach `PluginDescriptors` about the file-extension.
This PR is currently untested and only cherry-picked from #2047, the example plugin will have to suffice as tests.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2945"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Teach HLS about different file extensions

- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- test/functional/Completion.hs
- test/testdata/completion/AssociatedTypeFamily.hs
Currently, completing exported associated type families defined in the current module incorrectly adds an import, while non-exported ones do not show up at all. This PR fixes both of these issues.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2987"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add associated type families to local completions

- ghcide/src/Development/IDE/Plugin/HLS.hs
I made a boo-boo and changed only one instance of `Error` to `Warning` when it should have been changed here as well...
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3009"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Revert back to Warning not Error in Logging `ResponseErrors`

- ghcide/test/exe/Main.hs
I don't think anyone is going to fix this soon, let's just disable it so
we can move on.
Fixes #2997.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3008"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Disable flaky test on Windows

- cabal.project
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
Currently, we disable `-haddock` option in `cabal.project` because `ghc-lib` 9.2 doesn't build on GHC 8.10.
For now, we can remove the dependency on `ghc-lib` in `hls-hlint-plugin`, using `ghc-lib-parser` instead. (actually `hlint` itself doesn't depend on `ghc-lib`) Meanwhile, I've opened an issue in `ghc-lib`, see: https://github.com/digital-asset/ghc-lib/issues/391
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3015"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> re-enable haddock

- plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
> A quick fix should be marked preferred if it properly addresses the underlying error. A refactoring should be marked preferred if it is the most reasonable choice of actions to take.
For hlint it is the likeliest choice to apply the fix. Ignore the rule
for the complete module is preferred less.
Related to https://github.com/haskell/haskell-language-server/issues/2057
The client - in my case Vim/Coc - can respect `isPreferred`. In case of CoC it will be reflected in the sort order of code actions.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3018"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Hlint: CodeAction with isPreferred

- .hlint.yaml
- plugins/hls-alternate-number-format-plugin/test/Main.hs
Turns out that for functions which are typically imported in multiple ways, you need to list both explicitly, and you can't combine them (see the linked HLint issue). So I did that and added some more exceptions.
I also banned `Debug.Trace`, removing a couple of dead usages and adding exceptions for the existing (!) usages.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3000"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Hlint more partial functions, and Debug.Trace

- hls-graph/hls-graph.cabal
`Control.Concurrent.Async` is not available before `async-2.0`.
As a Hackage trustee, I made a matching revision:
https://hackage.haskell.org/package/hls-graph-1.7.0.0/revisions/
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3021"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> hls-graph: add lower bound for async

- flake.nix
In #2967, @teto points out `nix flake show` is broken due to some usages of `pre-commit-check` were not removed. As `pre-commit-check` is already removed from flake input, I believe we can remove the remaining usages of it safely.
However, `nix flake show` and `nix flake check` still fail due to our implicit use of IFD(import from derivation), see: https://github.com/NixOS/nix/issues/4265. With IFD, these commands are trying to build all systems listed in `flake-utils.lib.eachSystem`.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3024"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> remove all usages of pre-commit-check in nix

- hls-plugin-api/hls-plugin-api.cabal
Before `opentelemetry-0.4` `SpanInFlight` is not exported.
Before `dependent-sum-0.7` `GCompare` is not coming from `some`, but is defined elsewhere, which leads to incompatibility with `lsp`.
As a Hackage trustee, I made a matching revision:
https://hackage.haskell.org/package/hls-plugin-api-1.4.0.0/revisions/
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3022"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> hls-plugin-api: add lower bounds

- plugins/hls-fourmolu-plugin/hls-fourmolu-plugin.cabal
There is no `System.Process.Run` before `process-extras-0.7.1`
Matching revision:
https://hackage.haskell.org/package/hls-fourmolu-plugin-1.0.3.0/revisions/
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3028"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> hls-fourmolu-plugin: add lower bound for process-extras

- haskell-language-server.cabal
- stack-lts16.yaml
The type of `tGitInfoCwdTry` has been different before `githash-0.1.6.1`.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3030"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> haskell-language-server: add lower bound for githash

- plugins/hls-eval-plugin/hls-eval-plugin.cabal
`manyTill_` was introduced only in `parser-combinators-1.2`.
Matching revision:
https://hackage.haskell.org/package/hls-eval-plugin-1.2.2.0/revisions/
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3029"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> hls-eval-plugin: add lower bound for parser-combinators

- flake.nix
Before the change the build was failing:
```
$ stack --nix build --keep-going
hfsevents          > Configuring hfsevents-0.1.6...
hfsevents          > build
hfsevents          > Preprocessing library for hfsevents-0.1.6..
hfsevents          > Building library for hfsevents-0.1.6..
hfsevents          > [1 of 1] Compiling System.OSX.FSEvents
hfsevents          > /private/tmp/stack-51fbae1892ce366f/hfsevents-0.1.6/In file included from cbits/c_fsevents.m:1:0: error:
hfsevents          >
hfsevents          > /private/tmp/stack-51fbae1892ce366f/hfsevents-0.1.6/In file included from /nix/store/yynq1crbdnd6fyaajv7d0zicf0bgb46y-apple-framework-CoreServices/Library/Frameworks/CoreServices.framework/Headers/CoreServices.h:19:0: error:
hfsevents          >
hfsevents          >
hfsevents          > …
```
> Fix Stack build with Nix on macOS

- .hlint.yaml
Apparently I was just doing it wrong and naming multiple functions this
way does work properly!
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3038"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Simplify hlint config

- .gitpod.Dockerfile
- .gitpod.yml
- ghcide/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs
- ghcide/test/exe/Main.hs
fix #2958 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3035"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> handle trailing comma in import list properly

- .github/ISSUE_TEMPLATE/enhancement_request.md
- .github/ISSUE_TEMPLATE/support.md
- Add a support issue template
- Ask questions about versions of GHC and HLS
- Add some heuristic details fields to help people pick an issue type
I thought it would be nice to have an issue template for support issues, to encourage people to distinguish those.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3044"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update issue templates

- ghcide/test/exe/Main.hs
Makes the record-dot-syntax tests to apply to future versions of GHC
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3051"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> fix record-dot-syntax test

- ghcide/src/Development/IDE/Core/Rules.hs
- plugins/hls-refine-imports-plugin/src/Ide/Plugin/RefineImports.hs
Also add an assertion to check that we never use non-FOI rules
Fixes #2962
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2995"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Don't use typecheck rule for non FOIs in refine imports plugin

- ghcide/src/Development/IDE/Core/Rules.hs
It's logged as a warning, it shouldn't duplicate the severity in the
message.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3055"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove redundant WARNING prefix

- docs/configuration.md
- the way in which -> how
- which any -> that any
- perfomance -> performance
- diganostics -> diagnostics
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3056"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix grammar and spelling errors in configuration.md

- .github/workflows/pre-commit.yml
- .pre-commit-config.yaml
- plugins/hls-stan-plugin/src/Ide/Plugin/Stan.hs
Add Github workflow to check code formatting in pull requests.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3060"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add Github precommit workflow

- exe/Plugins.hs
- haskell-language-server.cabal
fix #3064 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3065"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> add a prefix to plugin CPP definitions

- .github/workflows/bench.yml
- ghcide/bench/config.yaml
As @kokobd noticed in #3046 the benchmark suite is not running in 9.x
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3069"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Run the benchmark suite on GHC 9.2.3

- plugins/hls-fourmolu-plugin/hls-fourmolu-plugin.cabal
- plugins/hls-fourmolu-plugin/src/Ide/Plugin/Fourmolu.hs
- plugins/hls-fourmolu-plugin/src/Ide/Plugin/Fourmolu/Shim.hs
Also includes some clean up. Will we always be supporting every version of Fourmolu, or will HLS ever remove support for old versions of Fourmolu?
cc @parsonsmatt @georgefst 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3078"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add support for Fourmolu 0.8

- plugins/hls-stan-plugin/src/Ide/Plugin/Stan.hs
Solves #3089
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3090"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Stan: Avoid terminal colors in messages

- exe/Wrapper.hs
- src/Ide/Version.hs
The ghc version on the $PATH is often not relevant for stack projects. The ghc version stack is using is printed in addition.
```
haskell-language-server version: 1.7.0.0 (GHC: 9.2.4) (PATH: [...]/haskell-language-server-wrapper) (GIT hash: 0e74593e8df9665067174ca27543006c9a6ad230)
Tool versions found on the $PATH
cabal:          3.8.1.0
stack:          2.7.5
ghc:            9.2.4
stack ghc:      8.10.7
```
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3093"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
@michaelpj Followup to [this comment](https://github.com/haskell/haskell-language-server/pull/3090#issuecomment-1212146888) to sketch the idea for a change. Do you have something like this change in mind?
> Probe-tools: Print stack ghc version

- plugins/hls-fourmolu-plugin/src/Ide/Plugin/Fourmolu/Shim.hs
~Merging now: https://github.com/fourmolu/fourmolu/pull/226~
~This should be all that's required, but I'll test when released~
Tested that it builds locally with fourmolu 0.8.1
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3103"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Support fourmolu-0.8.1.0

- .github/workflows/bench.yml
- ghcide/bench/config.yaml
- ghcide/bench/lib/Experiments.hs
The lsp-types benchmark definition needs some fixes in ghc 9.2
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3079"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
Also fixes #3102 by tar'ing the benchmark artefacts before upload
> fix lsp-types benchmark

- plugins/hls-class-plugin/src/Ide/Plugin/Class.hs
- plugins/hls-class-plugin/src/Ide/Plugin/Class/CodeLens.hs
- plugins/hls-class-plugin/src/Ide/Plugin/Class/ExactPrint.hs
- plugins/hls-class-plugin/src/Ide/Plugin/Class/Types.hs
- plugins/hls-class-plugin/test/Main.hs
While looking on #3105, I found type lens itself has a config filed, see `haskell-language-server generate-default-config`
Remove a duplicate one, although I don't know where is the another one from now.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3107"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove unused config in hls-class-plugin

- exe/Main.hs
It interferes with the ability of lsp-test to detect timeouts in e.g. benchmarks
The assumption is that logging them to stderr serves the purpose they
were designed for.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3111"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Do not send Heap Stats to the LSP log

- ghcide/src/Development/IDE/Core/ProgressReporting.hs
Currently the Begin progress message is sent asynchronously, so it can
happen that it's never sent if the async is cancelled immediately
because a new kick has started. This causes trouble in tests and
benchmarks which make assumptions about progress updates.
To address this, we send the Begin progress message synchronously,
and only then do the rest of the progress reporting stuff
(including waiting for the response) asynchronously
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3110"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Send begin progress message synchronously

- exe/Plugins.hs
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/LSP/Notifications.hs
- ghcide/src/Development/IDE/Main.hs
- ghcide/src/Development/IDE/Plugin/Completions.hs
- ghcide/src/Development/IDE/Plugin/HLS.hs
- ghcide/test/exe/Main.hs
- hls-plugin-api/src/Ide/Plugin/ConfigUtils.hs
- hls-plugin-api/src/Ide/PluginUtils.hs
- hls-plugin-api/src/Ide/Types.hs
- plugins/hls-explicit-fixity-plugin/src/Ide/Plugin/ExplicitFixity.hs
- plugins/hls-pragmas-plugin/src/Ide/Plugin/Pragmas.hs
- src/Ide/Main.hs
- test/functional/Format.hs
Use a smart constructor to prevent duplicated plugins. We cannot use a
set since order matters for plugin execution.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3112"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Deduplicate HLS plugins

- ghcide/src/Development/IDE/Plugin/HLS.hs
- hls-plugin-api/src/Ide/PluginUtils.hs
- plugins/hls-alternate-number-format-plugin/src/Ide/Plugin/AlternateNumberFormat.hs
- plugins/hls-call-hierarchy-plugin/src/Ide/Plugin/CallHierarchy/Internal.hs
- plugins/hls-change-type-signature-plugin/src/Ide/Plugin/ChangeTypeSignature.hs
- plugins/hls-class-plugin/src/Ide/Plugin/Class/CodeAction.hs
- plugins/hls-class-plugin/src/Ide/Plugin/Class/CodeLens.hs
- plugins/hls-explicit-fixity-plugin/src/Ide/Plugin/ExplicitFixity.hs
- plugins/hls-gadt-plugin/src/Ide/Plugin/GADT.hs
The error message displayed by `prettyResponseError` in
`Development.IDE.Plugin.HLS` looks awkward with the pluginId. This error
is not the fault of plugins anyways, so let's just be generic (we also should never see this message anyway).
New message:
```
2022-08-20T16:30:21.473621Z | Warning | InternalError: Failed converting file:///path/haskell-language-server/hls-plugin-api/src/Ide/PluginUtils.hs to NormalizedFilePath
```
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3118"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove pluginId from getNormalizedFilePath error message

- hie-compat/hie-compat.cabal
I had a build failure locally trying to get GHC 9.4 going with our project, and had a very odd error for `hie-compat`. Missing these links made it harder to figure out how to diagnose and report this.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3119"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add link to homepage and issues for `hie-compat`

- flake.nix
This is required for nix-based dev shells to work.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3125"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> flake.nix Add ghcide-bench to sourceDirs

- .github/workflows/test.yml
- cabal.project
- ghcide/ghcide.cabal
- ghcide/test/exe/Main.hs
- hie-compat/hie-compat.cabal
- Revert "drop windows for 9.4.2"
- Fix entropy to 0.4.1.10 to fix build on windows
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3132"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Enable support for 9.4 on windows

- .github/workflows/test.yml
- haskell-language-server.cabal
- plugins/hls-alternate-number-format-plugin/hls-alternate-number-format-plugin.cabal
- plugins/hls-alternate-number-format-plugin/src/Ide/Plugin/Literals.hs
This enables the Alternate Number Format plugin to build/work with 9.4
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3138"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Alternate Number Format Plugin buildable with GHC 9.4

- ghcide/test/ghcide-test-utils.cabal
- haskell-language-server.cabal
- Add base bound for ghcide-test-utils
- Remove internal library haskell-language-server:plugins
> Allow hackage upload

- flake.nix
Was trying to build HLS 1.8.0 with nix via the flake and noticed that the versions of the input deps were not in sync with the required cabal bounds. 
ghcide needs hie-bios-0.11.0 [here](https://github.com/haskell/haskell-language-server/blob/master/ghcide/ghcide.cabal#L108)
ghcide needs lsp-types-1.6.0.0 [here](https://github.com/haskell/haskell-language-server/blob/5a734dfb7f2ae12a1dc85a3bc0d0ef0a16125862/ghcide/ghcide.cabal#L72)
hls-plugin-api needs lsp-1.6.0.0 [here](https://github.com/haskell/haskell-language-server/blob/master/hls-plugin-api/hls-plugin-api.cabal#L52)
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3163"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fixes the flake deps to align with cabal bounds

- ghcide/src/Development/IDE/GHC/Compat/Outputable.hs
- ghcide/src/Development/IDE/GHC/Util.hs
- hls-plugin-api/hls-plugin-api.cabal
- hls-plugin-api/src/Ide/PluginUtils.hs
- hls-plugin-api/test/Ide/PluginUtilsTest.hs
This should fix #3115. It works. I will add tests later if the idea is okay.
Maybe a more proper fix is to modify the `Outputable` instance for `IfaceTyLit` in GHC?
Demo:
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3140"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> unescape printable characters

- configuration-ghc-90.nix
- configuration-ghc-94.nix
- flake.lock
- flake.nix
This is a work in progress, I'm trying to restore the build with nix.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3133"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> nix: fix nix environment for GHC 9.4

- docs/configuration.md
Minor, but as mentioned in #3157 the stan plugin is not listed in list of existing plugins in the documentation. This change will add it.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3180"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Docs: List stan plugin

- plugins/hls-stan-plugin/hls-stan-plugin.cabal
- plugins/hls-stan-plugin/src/Ide/Plugin/Stan.hs
Respects `globalOn` in stan plugin configuration and won't show hints anymore if the plugin is disabled. Solves #3157
```json
"stan": { "globalOn": false }
```
Could verify the `globalOn` setting will be respected with a local project.
Solves the issue (respecting if the plugin is disabled) the same way it is done [in the hlint plugin][hlint], as hinted to by @pepeiborra in [this comment][2]  thanks
[hlint]: https://github.com/haskell/haskell-language-server/blob/master/plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs#L199-L205
[2]: https://github.com/haskell/haskell-language-server/issues/3157#issuecomment-1247766075
@uhbif19 Since you wanted to take a look - hope it's okay and I ddin't take it away from you - is this fine? Any doubts? Also feel free to take over. 
<a …
> Stan: Respect plugin configuration globalOn

- docs/configuration.md
- ghcide/README.md
* Check on close modes were removed
* Moving docs to configuration and away from ghcide README
Solves #3156
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3184"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Docs: Fix checkParents documentation

- docs/configuration.md
I wasn't aware how to properly configure CoC language servers so that they're recognized by haskell language server (see https://github.com/haskell/haskell-language-server/issues/3157#issuecomment-1247795588). Might be possible that the configuration changed. Therefore I'd suggest to add an example showing how to configure settings for plugins. I chose to add a second example in order to keep the default example minimal and avoid confusing people who want an easy way to start with.
This suggestion is open for discussion. I can see how this could somehow be redundant, or more than necessary for a minimal example. At the same time when I did want to look up how the configuration should be defined, [I didn't find any information](https://github.com/haskell/haskell-language-server/issues/3157# …
> Configuration: more advanced Vim / Coc example (suggestion)

- .pre-commit-config.yaml
- .stylish-haskell.yaml
- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/src/Development/IDE/GHC/Compat/Iface.hs
- ghcide/src/Development/IDE/Import/FindImports.hs
- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- plugins/hls-haddock-comments-plugin/src/Ide/Plugin/HaddockComments.hs
- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction.hs
- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction/Util.hs
- plugins/hls-stan-plugin/src/Ide/Plugin/Stan.hs
* CPP language extension
* Manually fix some files with duplication
* Fixed ignored filepaths in pre-commit config (ExactPrint was moved)
```shell
pre-commit run --show-diff-on-failure --all-files
plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs: <string>:7:1: error: parse error on input `#'
plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction/Util.hs: <string>:14:1: error: parse error on input `#'
plugins/hls-refactor-plugin/src/Development/IDE/GHC/Compat/ExactPrint.hs: <string>:5:1: error: parse error on input `#'
plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction.hs: <string>:90:1: error: parse error on input `#'
```
stylish-haskell 0.14.2.0
* Related to #3170
* Followup of #3171
* If there would be a way to tell …
> Stylish Haskell: CPP parse issues

- docs/contributing/contributing.md
Some wrapper tests fail in the absence of `stack` on the system. This PR adds a small note in the _testing_ section of the _contributing_ page regarding that.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3212"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Document the `stack` requirement in wrapper tests

- plugins/hls-stan-plugin/src/Ide/Plugin/Stan.hs
This has effect only when generating the config schema and won't change anything for the Stan plugin schema at all
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3213"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add diagnostics to Stan descriptor

- ghcide-bench/ghcide-bench.cabal
- hie-compat/hie-compat.cabal
- plugins/hls-alternate-number-format-plugin/hls-alternate-number-format-plugin.cabal
- plugins/hls-brittany-plugin/hls-brittany-plugin.cabal
- plugins/hls-call-hierarchy-plugin/hls-call-hierarchy-plugin.cabal
- plugins/hls-change-type-signature-plugin/hls-change-type-signature-plugin.cabal
- plugins/hls-class-plugin/hls-class-plugin.cabal
- plugins/hls-code-range-plugin/hls-code-range-plugin.cabal
- plugins/hls-explicit-fixity-plugin/hls-explicit-fixity-plugin.cabal
- plugins/hls-explicit-imports-plugin/hls-explicit-imports-plugin.cabal
- plugins/hls-floskell-plugin/hls-floskell-plugin.cabal
- plugins/hls-gadt-plugin/hls-gadt-plugin.cabal
- plugins/hls-haddock-comments-plugin/hls-haddock-comments-plugin.cabal
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-module-name-plugin/hls-module-name-plugin.cabal
- plugins/hls-ormolu-plugin/hls-ormolu-plugin.cabal
- plugins/hls-pragmas-plugin/hls-pragmas-plugin.cabal
- plugins/hls-qualify-imported-names-plugin/hls-qualify-imported-names-plugin.cabal
- plugins/hls-refactor-plugin/hls-refactor-plugin.cabal
- plugins/hls-refine-imports-plugin/hls-refine-imports-plugin.cabal
- plugins/hls-rename-plugin/hls-rename-plugin.cabal
- plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
- plugins/hls-splice-plugin/hls-splice-plugin.cabal
- plugins/hls-stan-plugin/hls-stan-plugin.cabal
- plugins/hls-stylish-haskell-plugin/hls-stylish-haskell-plugin.cabal
- plugins/hls-tactics-plugin/hls-tactics-plugin.cabal
- shake-bench/shake-bench.cabal
Add a `source-repository` stanza to any `.cabal` files in the project that are missing it.
This metadata can be useful for package maintainers.
See: https://cabal.readthedocs.io/en/stable/cabal-package.html#source-repositories
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3219"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add `source-repository` to all cabal files

- plugins/hls-hlint-plugin/README.md
Remove warning about hlint restrictions, as #1340 has been merged.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3216"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> hls-hlint-plugin: Update README.md

- ghcide/src/Development/IDE/Plugin/Completions.hs
- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- ghcide/src/Development/IDE/Plugin/Completions/Types.hs
- test/functional/Completion.hs
- test/testdata/completion/RecordDotSyntax.hs
When a user dots a record type with OverloadedRecordDot enabled, shows all possible record selectors for that type.
Todo:
* write test
* make completion items more complete
Notes
* Requires fresh HieAst to work, which shouldn't be a problem since we are dotting an actively worked on file
* Doesn't support HasField (virtual fields)
* Moves getCompletionPrefix, PosPrefixInfo in from LSP.Language.VFS (and patches them to support records in addition to modules)
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3080"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Feat: basic record dot completions

- flake.lock
- flake.nix
Fixes #3211  
This PR replaces manually specified `myst-parser` and `sphinx_rtd_theme` packages with their counterparts already packaged on nixpkgs. With this change, `poetry2nix` is no more used, therefore that is removed as well.
The documentation build via Nix (`nix build .#docs`) still fails. However, the cause of failure is not related to the Nix infrastructure, but a warning in the documentation source. Nix build of the documentation promotes warnings to errors, hence the failure. We need to either lift this restriction, or actually fix the warning. Either way, that should be handled in a separate PR.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3227"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Use nixpkgs variants of Sphinx packages

- GNUmakefile
- bindist/wrapper.in
- haskell-language-server.cabal
This still makes sure that ghc has been compiled with the same core
libraries as hls while it allows runtime environments where other
packages have been added to the ghc-pkg database.
This commit also adds that file to the sdist, so that distro
packagers can use it.
Compare: https://github.com/NixOS/nixpkgs/pull/192540 and
https://github.com/NixOS/nixpkgs/issues/175565 as motivations for this from
nixpkgs.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3214"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
>  wrapper.in: Require runtime ghc-pkgs to be an abi compatible superset of bootpkgs

- README.md
fix dead link on Read the Docs
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3242"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update link to supported versions in README

- flake.lock
- flake.nix
Upgrade a few packages which needed upgrade and avoid building hiedb in nix as it has a dependency on a package in this repository (hie-compat).
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3257"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Fix nix developement shell

- docs/contributing/plugin-tutorial.md
Addresses  #2901
Also, it was mentioning freenode, but now it is libera chat
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3266"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Update plugin tutorial

- configuration-ghc-94.nix
Broken by: https://github.com/haskell/haskell-language-server/pull/3257
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3265"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> configuration-ghc-94.nix: Fix references to lsp and lsp-types source

- plugins/hls-explicit-imports-plugin/src/Ide/Plugin/ExplicitImports.hs
This PR has the following changes:
* create a constant function to document the `"import (implicit) Prelude"`- Prefix
* exclude an import that starts with `"import (implicit) Prelude"` inside `minimalImportsRule`
* closes #2798 
Before this PR changes:
After this PR changes:
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3277"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Exclude the implicit prelude import (#2798)

- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction.hs
* fixes #3234
* creates an importance score function for import suggestions based on similarity and module length
* wraps the computed score and the previous result tuple (`CodeAction`, `NewImport`) into an  `ImportSuggestion`
* orders the `ImportSuggestion` first based on the score in descending order and second based on the import module names in alphabetic order
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3271"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
Before the PR changes:
After the PR changes:
> Use an importance score to order the suggested import code action

- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction.hs
This PR removes the unlawful `Ord` instance mentioned in #3271.
Since `CodeActionKind` does not implement `Ord` it is not so easy to provide a clean `Ord` instance for `ImportSuggestion`.
Currently the ordering is moved to a function which also documents this problem.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3279"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove unlawful Ord instance and replace it by a compare function

- ghcide/src/Development/IDE/Main.hs
- 9.2 is now fully supported
- 9.4 is partially supported
https://github.com/haskell/haskell-language-server/issues/2982#issuecomment-1277918636
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3286"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump partial ghc support warning to 9.4

- docs/installation.md
The command `cabal install haskell-language-server`, present in `docs/installation#instalation-from-source` fails with the following error:
```
Error: cabal: Ambiguous target 'haskell-language-server'. It could be:
exe:haskell-language-server (component)
lib:haskell-language-server (component)
```
This PR only changes the documentation so that it points to `exe:haskell-language-server`
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3298"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Change default cabal install target name on docs/installation.md

- plugins/hls-explicit-fixity-plugin/hls-explicit-fixity-plugin.cabal
- plugins/hls-explicit-fixity-plugin/src/Ide/Plugin/ExplicitFixity.hs
Simplify and improve the performance and memory usage behaviour or hls-fixity-plugin.
Also restore the property that hover is immediately available on startup using the cached hie file data and `IdeAction` mechanism.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3205"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve hls-fixity-plugin

- .hlint.yaml
- ghcide/src/Development/IDE/Core/FileStore.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/Types/Shake.hs
- hls-graph/hls-graph.cabal
- hls-graph/src/Development/IDE/Graph.hs
- hls-graph/src/Development/IDE/Graph/Database.hs
- hls-graph/src/Development/IDE/Graph/Internal/Action.hs
- hls-graph/src/Development/IDE/Graph/Internal/Database.hs
- hls-graph/src/Development/IDE/Graph/Internal/Profile.hs
- hls-graph/src/Development/IDE/Graph/Internal/Types.hs
- hls-graph/src/Development/IDE/Graph/KeyMap.hs
- hls-graph/src/Development/IDE/Graph/KeySet.hs
- hls-graph/test/ActionSpec.hs
On large projects, duplicate Keys start to comprise a significant (~5-10%) fraction of the heap.
This becomes better if we use `Int`s as keys and de-duplicate the actual values by storing them
in maps. `Key`s are mostly just compared and hash during usual operation, printing them out is
rare so a lookup shouldn't pessimize it much.
Also use HashSets to keep track of dependencies.
However, this means that the underlying value for `Key`s will never be garbage collected once allocated.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3206"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Implement sharing for hls-graph Keys

- ghcide/src/Development/IDE/Core/Shake.hs
I have seen unexpected duplicate diagnostics leading to a failure in the ghcide testsuite: what seems to happen here is that both `Typecheck` and `GetModIfaceFromDisk` contribute the same diagnostics. But this should never happen, because we never run both these rules for the same file:
* `GetModIfaceFromDisk` is only run for non FOIs via `GetModIface`
* `Typecheck` is only run for FOIs, either via `GetModIface` or on demand by code actions 
This PR adds more testing-only logging to help diagnostics when this happens again next time
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3301"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Record diagnostics source rule when testing

- .github/workflows/test.yml
- docs/support/plugin-support.md
- haskell-language-server.cabal
- plugins/hls-refactor-plugin/src/Development/IDE/GHC/ExactPrint.hs
- plugins/hls-splice-plugin/src/Ide/Plugin/Splice.hs
I don't really know what I'm doing, but I did the minimal amount to make the splice plugin compatible with GHC 9.2.
I import from `GHC.Types.Error` to extract the warnings and errors, I'm not sure if that's okay, or if the idea is to avoid plugins depending directly on `GHC` modules?
Good chance I've done something wrong here, feedback welcome.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2816"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make splice plugin compatible with GHC 9.2

- docs/installation.md
Closes #3182 
Removes all mentions of stack from the installation docs
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3314"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Remove stack from installation docs since it is not supported anymore

- flake.nix
… so that it's easier to add and remove overlays by creating a list of overlays to compose.
This should be a behavior-preserving change.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3323"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Refactor overlay composition

- flake.lock
- flake.nix
The main motivation for this change is to enable development of HLS plugins by generating a `.env` shell for every package in this repository.
Example usage:
```ShellSession
$ nix develop .#haskell-language-server-dev-env.hls-fourmolu-plugin
```
This is a plain shell, though, without any tooling installed, identical to the one that Nixpkgs provides by default.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3322"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add support for `.env` shells to `flake.nix`

- .github/workflows/test.yml
- CODEOWNERS
- cabal.project
- docs/features.md
- docs/support/plugin-support.md
- haskell-language-server.cabal
- hls-plugin-api/src/Ide/Plugin/Config.hs
- hls-plugin-api/src/Ide/Types.hs
- hls-test-utils/src/Test/Hls.hs
- plugins/hls-cabal-fmt-plugin/LICENSE
- plugins/hls-cabal-fmt-plugin/hls-cabal-fmt-plugin.cabal
- plugins/hls-cabal-fmt-plugin/src/Ide/Plugin/CabalFmt.hs
- plugins/hls-cabal-fmt-plugin/test/Main.hs
- plugins/hls-cabal-fmt-plugin/test/testdata/commented_testdata.cabal
- plugins/hls-cabal-fmt-plugin/test/testdata/commented_testdata.formatted_document.cabal
- plugins/hls-cabal-fmt-plugin/test/testdata/hie.yaml
- plugins/hls-cabal-fmt-plugin/test/testdata/lib_testdata.cabal
- plugins/hls-cabal-fmt-plugin/test/testdata/lib_testdata.formatted_document.cabal
- plugins/hls-cabal-fmt-plugin/test/testdata/simple_testdata.cabal
- plugins/hls-cabal-fmt-plugin/test/testdata/simple_testdata.formatted_document.cabal
- plugins/hls-cabal-fmt-plugin/test/testdata/src/MyLib.hs
- plugins/hls-cabal-fmt-plugin/test/testdata/src/MyOtherLib.hs
- src/HlsPlugins.hs
- stack-lts19.yaml
- stack.yaml
- test/functional/Format.hs
This allows formatting of cabal files with hls.
~~Currently waiting for merges on [cabal-fmt](https://github.com/phadej/cabal-fmt/pull/33) and [stylish haskell](https://github.com/haskell/stylish-haskell/pull/375).~~ We gave up on this, also it makes maintenance harder as cabal-fmt supports only one Cabal version at a time.
Closes #183 and part of #2964.
Builds on top of #2945 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2047"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add formatting plugin for cabal files which uses cabal-fmt

- ghcide/test/exe/Main.hs
- hls-test-utils/src/Test/Hls.hs
- plugins/hls-refactor-plugin/test/Main.hs
"iface-error-test-1" fails occasionally in CI. The problem is that progress reporting and diagnostics arrive in non-deterministic ordering: a test that waits for both is creating a race condition.
Ideally we would solve the non-determinism problem for all tests, but I'm not sure how to do that. In the meantime, we should review all tests in the ghcide test suite. When fixing a test, prefer diagnostics over progress reporting since the former are more reliable.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3300"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Make a test more reliable

- ghcide/src/Development/IDE/Main.hs
Fixes #2457
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3334"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Ensure at least 1 capability 

- .github/workflows/hackage.yml
- haskell-language-server.cabal
This slipped through
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3335"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add hls-cabal-fmt-plugin to hackage release CI script and HLS library

- docs/configuration.md
* Separate sections for Neovim and Vim.
* Add more up-to-date information for Neovim (with a bit of shameless self-promotion).
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3342"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Docs: update and split neovim/vim configurations

- .github/actions/setup-build/action.yml
- .github/workflows/caching.yml
- .github/workflows/pre-commit.yml
- .github/workflows/test.yml
CI is insanely slow. Only *some* caching of build dependencies.
Caching should take care of it, why are the caches not hit in some cases?
This PR is meant to investigate #3318 
Moreover, dependabot seems not to work for our custom defined github action?
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3366"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Bump gha versions in setup-build/action.yml

- .github/workflows/hlint.yml
Running HLint is failing, likely due to https://github.com/haskell/actions/issues/133#issue-1477449436, the ubuntu-latest version points to ubuntu-22.04. Probably breaks the pre-packaged hlint binary.
If this doesn't work, we will follow the suggestions from https://github.com/haskell/unix/pull/266#discussion_r1040654412
> Bump hlint version CI flow

- ghcide/src/Development/IDE/Core/Compile.hs
- ghcide/src/Development/IDE/Core/Rules.hs
We need to unload old linkables before we can load in new linkables. However,
the `unload` function in the GHC API takes a list of linkables to **keep** (i.e.
not unload). Earlier we `unload`ed right before loading in new linkables, which
is effectively once per splice. This can be slow as `unload` needs to walk over
the list of all loaded linkables, for each splice.
Instead, now we unload old linkables right after we generate a new linkable and
just before returning it to be loaded. This has a substantial effect on recompile
times as the number of loaded modules and splices increases.
> Unload once per linkable instead of once per splice

- .github/workflows/caching.yml
- .github/workflows/test.yml
Small addition to #3396, exclude list wasn't completely up-to-date
Fixes Caching CI run https://github.com/haskell/haskell-language-server/actions/runs/3693755201/jobs/6254126700
> Correct list of GHC versions in caching.yml to match test.yml

- flake.nix
on current master, `.#haskell-language-server-925-dev-nix` shell is broken. 
```
% nix develop .#haskell-language-server-925-dev-nix
warning: Using saved setting for 'extra-substituters = https://haskell-language-server.cachix.org' from ~/.local/share/nix/trusted-settings.json.
warning: Using saved setting for 'extra-trusted-public-keys = haskell-language-server.cachix.org-1:juFfHrwkOxqIOZShtC4YC1uT1bBcq2RSvC7OMKx0Nz8=' from ~/.local/share/nix/trusted-settings.json.
[1/44/249 built, 3 copied (1489.5 MiB), 127.6 MiB DL] building HsYAML-0.2.1.1 (buildPhase): [ 4 of 14] Compiling Data.YAML.Token  ( src/Derror: interrupted by the user
ianwookim@IANWOOs-MacBook-Pro haskell-language-server % nix develop -j auto .#haskell-language-server-925-dev-nix
warning: Using saved setting for …
```
> Fix fourmolu with -f-fixity-th in nix env

- ghcide/src/Development/IDE/Core/Compile.hs
- ghcide/src/Development/IDE/GHC/Compat.hs
- ghcide/src/Development/IDE/GHC/Compat/Core.hs
- ghcide/src/Development/IDE/Plugin/Completions.hs
- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- ghcide/src/Development/IDE/Plugin/Completions/Types.hs
- ghcide/src/Development/IDE/Spans/Documentation.hs
- ghcide/test/exe/Main.hs
- hls-plugin-api/src/Ide/Types.hs
- plugins/hls-call-hierarchy-plugin/hls-call-hierarchy-plugin.cabal
- plugins/hls-call-hierarchy-plugin/test/Main.hs
- plugins/hls-refactor-plugin/test/Main.hs
- plugins/hls-tactics-plugin/new/src/Wingman/Machinery.hs
- plugins/hls-tactics-plugin/old/src/Wingman/Machinery.hs
- test/functional/Completion.hs
Implement `completionItem/resolve` to lazily resolve types and documentation for completion items.
This results in very big memory usage improvments while also improving the responsiveness of completions.
Usually when GHC typechecks code, it reads in and deserializes interfaces lazily, so if the code imports
a bunch of modules, the interfaces will only be read in and deserialized if a particular name is actually
required for typechecking.
However, when we greedily generate completion lists, the act of querying for types and documentation results
in sucking in and deserializing interface sections for every single name in scope. This is very bad for
memory usage as it negates virtually all the benefits of lazy deserialization.
Instead, we can compute types and documentation on demand for …
> Implement completionItem/resolve

- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/GHC/Compat.hs
- ghcide/src/Development/IDE/Plugin/Completions.hs
- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- ghcide/src/Development/IDE/Types/Exports.hs
- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction.hs
- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/Plugins/ImportUtils.hs
- plugins/hls-refactor-plugin/test/Main.hs
Storing rendered names as `Text`, especially for parents, adds a lot of duplication to the ExportsMap.
Instead we store the `OccName`s directly, which have hash-consed symbols due stored as `FastStrings`
and render it out on demand (which is just decoding the UTF-8 FastString to UTF-16 text for text <2.0,
and essentially free on text >2.0).
This PR depends on #3204, ignore that commit while reviewing.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3231"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Improve memory characteristics of ExportsMap

- .github/mergify.yml
After a bit of digging I've worked out what's up with mergify. It's
still working fine, but it's not updating PRs very often now. The reason
for that is that it updates PRs that are in the queue, but to get
_into_ the queue you have to pass CI, which is hard ATM because of our
flaky CI. So we can add a separate update rule that just updates the
labelled PRs, so that they are at least kept up-to-date with master.
> Add a mergify action to update PRs

- ghcide/ghcide.cabal
Since HLS 1.7, prettyprinter 1.7 is actually needed in order to build:
```
src/Development/IDE/Plugin/HLS.hs:44:1: error:
Could not load module ‘Prettyprinter.Render.String’
It is a member of the hidden package ‘prettyprinter-1.7.1’.
Perhaps you need to add ‘prettyprinter’ to the build-depends in your .cabal file.
It is a member of the hidden package ‘prettyprinter-1.7.1’.
Perhaps you need to add ‘prettyprinter’ to the build-depends in your .cabal file.
Use -v (or `:set -v` in ghci) to see a list of the files searched for.
|
44 | import           Prettyprinter.Render.String  (renderString)
| ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Error: cabal: Failed to build ghcide-1.9.0.0 (which is required by
exe:haskell-language-server-wrapper from haskell-language-server-1.9.0.0 …
```
> ghcide needs prettyprinter 1.7

- plugins/hls-cabal-fmt-plugin/hls-cabal-fmt-plugin.cabal
- plugins/hls-code-range-plugin/hls-code-range-plugin.cabal
- plugins/hls-explicit-record-fields-plugin/hls-explicit-record-fields-plugin.cabal
Missing testdata breaks tests when running them from the hackage sdist. This affects nixpkgs because we run tests by default.
> various plugins: Add testdata to sdist

- docs/support/plugin-support.md
I checked fourmolu and hlint work fine with HLS 1.9, ghc 9.4. Other plugins are updated according to the following issues and release notes: 
ghc 9.2: https://github.com/haskell/haskell-language-server/issues/2982, [release note of HLS 1.8](https://github.com/haskell/haskell-language-server/releases/tag/1.8.0.0)
ghc 9.4: https://github.com/haskell/haskell-language-server/issues/3190, [release note of HLS 1.9](https://github.com/haskell/haskell-language-server/releases/tag/1.9.0.0)
> Update list of unsupported plugins

- plugins/hls-fourmolu-plugin/hls-fourmolu-plugin.cabal
See #3425.
I'll make a Hackage revision once this is merged.
> Correct Fourmolu plugin's lower bound on Ghcide

- .hlint.yaml
- ghcide/src/Development/IDE/Core/Compile.hs
- ghcide/src/Development/IDE/Core/FileStore.hs
- ghcide/src/Development/IDE/GHC/Compat.hs
1. Recompilation avoidance regresses in GHC 9.4 due to interactions between GHC and HLS's implementations.
Avoid this by filtering out the information that causes the conflict
See #3450.
2. The recompilation avoidance info GHC stores in interfaces can blow up to be
extremely large when deserialised from disk. See https://gitlab.haskell.org/ghc/ghc/-/issues/22744
Deduplicate these filepaths.
> Two recompilation avoidance related bug fixes

- cabal.project
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
- plugins/hls-ormolu-plugin/hls-ormolu-plugin.cabal
Fixes #3241 by upgrading to apply-refact 0.12.0 for compatible GHC versions. Other GHC versions are not affected.
> Use apply-refact 0.12.0

- ghcide/src/Development/IDE/GHC/CoreFile.hs
- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- ghcide/src/Development/IDE/Spans/AtPoint.hs
- ghcide/test/data/hover/GotoHover.hs
- ghcide/test/exe/Main.hs
This addresses https://github.com/haskell/haskell-language-server/issues/3280 by checking if names associated with a Haskell source file location follow particular prefix patterns used by generated Core variables. The two prefixes used are: `$d` and `$c`. If a name is prefixed with either of those strings then it is removed from the list of names used to generate the hovertip documentation content.
This change has been tested with the cases mentioned in the associated issue.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3316"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Filter generated Core variable names from hovertip documentation

- ghcide/src/Development/IDE/Types/Logger.hs
I am trying to run HLS/Ghcide without giving it stdin/stdout/stderr. We can currently redirect stdout and stderr by passing appropriate values in `Arguments.argsHandleIn` and `argsHandleOut`, but we can't redirect the recorder anywhere but stderr.
> Expose `makeDefaultHandleRecorder`

- ChangeLog.md
- cabal.project
- ghcide/ghcide.cabal
- haskell-language-server.cabal
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
> Bump versions and add changelogs for 1.9.1.0

- .github/workflows/test.yml
- .hlint.yaml
- ghcide/src/Development/IDE/Core/Compile.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/GHC/Compat.hs
- ghcide/src/Development/IDE/GHC/Compat/Core.hs
- ghcide/src/Development/IDE/GHC/Compat/Outputable.hs
- ghcide/src/Development/IDE/GHC/Compat/Util.hs
- haskell-language-server.cabal
- plugins/hls-eval-plugin/hls-eval-plugin.cabal
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Code.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Util.hs
- plugins/hls-eval-plugin/test/Main.hs
Supersedes #3249 and depends on #3390
> Eval plugin for GHC 9.4

- configuration-ghc-90.nix
- configuration-ghc-92.nix
- configuration-ghc-94.nix
- flake.lock
- flake.nix
- plugins/hls-ormolu-plugin/hls-ormolu-plugin.cabal
- plugins/hls-ormolu-plugin/src/Ide/Plugin/Ormolu.hs
This branch includes #3373, which was approved, but needed to be rebased. Only the last two commits need to be reviewed.
>  Update flake to GHC 9.2.6 and 9.4.4

- plugins/hls-fourmolu-plugin/hls-fourmolu-plugin.cabal
- plugins/hls-rename-plugin/hls-rename-plugin.cabal
These plugins depend on the `usePropertyAction` api that was introduced first in ghcide 1.9
> Fix lower ghcide bounds of rename and fourmolu plugins

- docs/configuration.md
Based on the discussion at https://github.com/haskell/haskell-language-server/issues/3157
> Docs: update Emacs section: add eglot with config example

- exe/Main.hs
- exe/Wrapper.hs
- ghcide/exe/Main.hs
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Types/Logger.hs
- ghcide/test/exe/Main.hs
- haskell-language-server.cabal
- hls-test-utils/src/Test/Hls.hs
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
Building on top of #3524 
Last dependency on hslogger is in implicit-hie-cradle which seemingly doesn't use it, see https://github.com/Avi-D-coder/implicit-hie-cradle/pull/14
> Remove HsLogger

- plugins/hls-class-plugin/src/Ide/Plugin/Class/CodeLens.hs
- plugins/hls-class-plugin/test/Main.hs
- plugins/hls-class-plugin/test/testdata/TH.hs
- plugins/hls-class-plugin/test/testdata/THDef.hs
- plugins/hls-class-plugin/test/testdata/hie.yaml
Close #3319.
Long time no see!
Coming back with a minor improvement that cut off lenses for TH-generated instances.
@michaelpj You may be interested in this :)
> Don't show lenses for TH generated instances

- haskell-language-server.cabal
- hie-compat/hie-compat.cabal
- hls-test-utils/hls-test-utils.cabal
- plugins/hls-alternate-number-format-plugin/hls-alternate-number-format-plugin.cabal
- plugins/hls-cabal-fmt-plugin/hls-cabal-fmt-plugin.cabal
- plugins/hls-cabal-plugin/hls-cabal-plugin.cabal
- plugins/hls-call-hierarchy-plugin/hls-call-hierarchy-plugin.cabal
- plugins/hls-change-type-signature-plugin/hls-change-type-signature-plugin.cabal
- plugins/hls-class-plugin/hls-class-plugin.cabal
- plugins/hls-code-range-plugin/hls-code-range-plugin.cabal
- plugins/hls-eval-plugin/hls-eval-plugin.cabal
- plugins/hls-explicit-fixity-plugin/hls-explicit-fixity-plugin.cabal
- plugins/hls-floskell-plugin/hls-floskell-plugin.cabal
- plugins/hls-fourmolu-plugin/hls-fourmolu-plugin.cabal
- plugins/hls-gadt-plugin/hls-gadt-plugin.cabal
- plugins/hls-haddock-comments-plugin/hls-haddock-comments-plugin.cabal
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-module-name-plugin/hls-module-name-plugin.cabal
- plugins/hls-ormolu-plugin/hls-ormolu-plugin.cabal
- plugins/hls-pragmas-plugin/hls-pragmas-plugin.cabal
- plugins/hls-qualify-imported-names-plugin/hls-qualify-imported-names-plugin.cabal
- plugins/hls-refactor-plugin/hls-refactor-plugin.cabal
- plugins/hls-rename-plugin/hls-rename-plugin.cabal
- plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
- plugins/hls-splice-plugin/hls-splice-plugin.cabal
- plugins/hls-stan-plugin/hls-stan-plugin.cabal
- plugins/hls-stylish-haskell-plugin/hls-stylish-haskell-plugin.cabal
- plugins/hls-tactics-plugin/hls-tactics-plugin.cabal
Some things that were left out of the release
> HLS 1.10 packaging fixes

- configuration-ghc-90.nix
- configuration-ghc-92.nix
- configuration-ghc-94.nix
- flake.lock
- flake.nix
Not sure about the details, I am just making CI green.
Feel free to make changes.
> Make nix ghc927 buildable

- plugins/hls-module-name-plugin/src/Ide/Plugin/ModuleName.hs
- plugins/hls-module-name-plugin/test/Main.hs
- plugins/hls-module-name-plugin/test/testdata/Stale.hs
> Keep stale lenses for module name

- ghcide/src/Development/IDE/Plugin/TypeLenses.hs
- ghcide/test/exe/Main.hs
I got the same effect without using `PositionMapping` compared to instance lenses, but don't know why.
Can anyone explain this?
> Keep type lenses stable

- .github/actions/setup-build/action.yml
- .github/workflows/test.yml
Dont rerun CI with various `lsp-test` flags to increase the output verbosity.
In my opinion, it makes it unnecessarily hard to find the failing test-case in CI, and I don't think anyone is reading these logs to actually *debug* test-cases.
Also, we don't want to fail fast.
We used to fail fast, to avoid caches of failing PRs to overpopulate the CI
caches, evicting known good build caches.
However, PRs do not cache anything any more, and can only use the caches from the current master.
See 'caching.yml' for our caching set up.
> CI: Simplify to read CI output and don't fail fast

- ghcide/src/Development/IDE/LSP/LanguageServer.hs
The commented log is also used to identify if HLS is started in vscode-haskell, and leave a warning to make the test more stable.
> Warn log modification

- cabal.project
Only remaining `allow-newer`'s are now regarding ekg-* stuff which we do not ship on hackage.
> Drop allow-newer for GHC 9.4 and 9.6

- hls-plugin-api/src/Ide/Types.hs
While investigating issue #3613, I found some hard to understand comments and some typos and decided to fix them while I was already reading through the code.
> Fix some grammar mistakes and typos

- ghcide/src/Development/IDE/Core/Compile.hs
If any exception was happening in `withHieDb`, the `post` action was never called, leading to a stale `Indexing` message in the client.
By using `bracket`, we ensure that the `post` message is called in the event of an exception, cleaning the confusing message in the client.
It does not change the well behaving of the indexing (i.e. if it was crashing, it is still crashing), but at least user won't be confused by a stale `Indexing` message.
See https://github.com/haskell/haskell-language-server/issues/2931 for an example when an exception can happen during the indexing.
> fix: remove the `Indexing` progress message when exeption in withHieDb

- hls-plugin-api/src/Ide/Types.hs
- src/HlsPlugins.hs
Add documentation to note that these values are to be kept in sync
Fixes #3613
> Keep plugin id of cabal-fmt in sync with default config id

- flake.nix
PR #3555 removes `cabal-install` from `flake.nix` in order to "make CI green" but that makes it impractical to build the project using nix. Since the PR mentions not being sure of the details and more people at ZuriHac are having trouble with this, I suggest reintroducing it.
> Reintroduce cabal-install in flake.nix

- hls-plugin-api/src/Ide/PluginUtils.hs
- plugins/hls-class-plugin/src/Ide/Plugin/Class/CodeAction.hs
- plugins/hls-class-plugin/src/Ide/Plugin/Class/Types.hs
- plugins/hls-class-plugin/test/Main.hs
- plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
- plugins/hls-refactor-plugin/src/Development/IDE/GHC/ExactPrint.hs
- plugins/hls-rename-plugin/hls-rename-plugin.cabal
- plugins/hls-rename-plugin/src/Ide/Plugin/Rename.hs
- plugins/hls-splice-plugin/src/Ide/Plugin/Splice.hs
- plugins/hls-splice-plugin/src/Ide/Plugin/Splice/Types.hs
- plugins/hls-tactics-plugin/old/src/Wingman/AbstractLSP.hs
- plugins/hls-tactics-plugin/old/src/Wingman/AbstractLSP/TacticActions.hs
- plugins/hls-tactics-plugin/old/src/Wingman/AbstractLSP/Types.hs
- plugins/hls-tactics-plugin/old/src/Wingman/EmptyCase.hs
- plugins/hls-tactics-plugin/old/src/Wingman/LanguageServer.hs
This is an attempt at a continuation of #3566 because I don’t have rights to push to that branch.
Sadly, while I can’t reproduce the concrete error message we are trying to fix here. There are still a lot of files in which hlint fixes don’t get applied for me.
> Correctly pass VersionedTextDocumentIdentifier through hls

- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Parse/Comments.hs
Resolves the following build error when building HLS with GHC 9.2.8 via haskell.nix:
```
hls-eval-plugin-lib-hls-eval-plugin> src/Ide/Plugin/Eval/Parse/Comments.hs:500:39: error:
hls-eval-plugin-lib-hls-eval-plugin>     • Could not deduce (Monad m) arising from a use of ‘getSourcePos’
hls-eval-plugin-lib-hls-eval-plugin>       from the context: (Ord v, TraversableStream s)
hls-eval-plugin-lib-hls-eval-plugin>         bound by the type signature for:
hls-eval-plugin-lib-hls-eval-plugin>                    getPosition :: forall v s (m :: * -> *).
hls-eval-plugin-lib-hls-eval-plugin>                                   (Ord v, TraversableStream s) =>
hls-eval-plugin-lib-hls-eval-plugin>                                   ParsecT v s m Position
hls-eval-plugin-lib-hls-eval-plugin>         at …
```
> Add missing Monad constraint in the eval plugin

- plugins/hls-pragmas-plugin/src/Ide/Plugin/Pragmas.hs
- plugins/hls-pragmas-plugin/test/Main.hs
- src/HlsPlugins.hs
> Split pragmas plugin by providers + decrease disable-warning priority

- exe/Main.hs
- ghcide/src/Development/IDE/Types/Logger.hs
- src/Ide/Arguments.hs
- test/functional/Config.hs
This adds arguments to HLS to allow the user to select whether to send logs to any or all of:
- a file
- stderr
- the client
Importantly, we can toggle off the default stderr logging, so the vscode extension can turn it off to avoid the double logging that arises from logging to both the client and stderr.
I've set the default to _not_ log to the client. This is a change of behaviour (today we log to the client by default), but I think it gives the best experience by default, since most clients do show stderr output somewhere, and then we probably want to make a case-by-case decision on whether to use the client logging instead.
> Add arguments to direct logs to various locations

- .github/workflows/test.yml
- docs/support/plugin-support.md
- haskell-language-server.cabal
- plugins/hls-ormolu-plugin/hls-ormolu-plugin.cabal
- plugins/hls-ormolu-plugin/src/Ide/Plugin/Ormolu.hs
And note that `fourmolu` already works for 9.6.
> Bump supported ormolu, allow for 9.6

- .github/workflows/test.yml
- cabal.project
- docs/support/plugin-support.md
- haskell-language-server.cabal
- plugins/hls-stylish-haskell-plugin/hls-stylish-haskell-plugin.cabal
There is a 9.6-compatible release now.
> Enable stylish-haskell for 9.6

- src/Ide/Arguments.hs
I meant to leave the old options in place. The short option is only there for the hidden old option, so it's not shown. That means what new users see is consistent across all the options.
> Restore short option for logfile

- .github/workflows/test.yml
- cabal.project
- docs/support/plugin-support.md
- haskell-language-server.cabal
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-hlint-plugin/test/Main.hs
I really want this so I can upgrade my development environment to ghc-9.6.😄
> Ship hls-hlint-plugin for ghc-9.6

- ghcide/src/Development/IDE/Core/Compile.hs
- plugins/hls-class-plugin/src/Ide/Plugin/Class/CodeAction.hs
- plugins/hls-class-plugin/test/Main.hs
- plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
- plugins/hls-pragmas-plugin/src/Ide/Plugin/Pragmas.hs
- test/functional/FunctionalCodeAction.hs
> Fixes pragma plugin offering incorrect code actions #3673

- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/Types/HscEnvEq.hs
Submitting this at the request of @wz1000 
Instead of calling `newHscEnvEqWithImportPaths` again in `ghcSessionDepsDefinition`, we only generate a new `Unique` for the `HscEnvEq` and update the `envUnique` field.
> Remove extra call to newHscEnvEqWithImportPaths

- docs/support/plugin-support.md
Quick passing-by fix for `hls-overloaded-record-dot-plugin`.
> docs (plugin-support): fix plugin name typo

- CODEOWNERS
I haven't touched this codebase in over a year, and it's now bitrotten and doesn't compile on any modern targets, so I think it's time to move on!
> Remove isovector as an owner

- hls-plugin-api/src/Ide/Types.hs
- plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
I missed some of michealpj's pr suggestions from last pr, so this pr addresses them.
> Further hlint resolve changes.

- ghcide/src/Development/IDE/Core/Actions.hs
- test/functional/Definition.hs
- test/testdata/definition/Bar.hs
- test/testdata/definition/Foo.hs
- test/testdata/definition/hie.yaml
In my work on gotoDefinition for dependencies I found a bug that predates my code. In the first few seconds of startup for big projects, gotoDefinition uses the persistent rule for GetHieAst and gets its PositionMapping from that. This PositionMapping gets used on any location a definition is found, even if that definition is in a different file. This doesn't usually cause a problem, except when the definition in the other file is found on a line that is greater than the number of lines in the file we are coming from. In this case, the PositionMapping will end up nullifying the result returned by AtPoint.gotoDefinition.
If you want to see this bug in action, try opening ghcide/src/Development/IDE/LSP/Outline.hs and try to immediately do gotoDefinition on `extract_cons` on line 115.
This …
> Fix other file goto definition

- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/src/Development/IDE/Import/FindImports.hs
- plugins/hls-call-hierarchy-plugin/test/Main.hs
1. Only bring units actually depended on into scope on 9.4+
2. Cabal uses `main` as the unit id of all executable packages. This confused multi component sessions.
Solution: include the hash of the options in the unit id when the unit id is called "main".
Fixes https://github.com/haskell/haskell-language-server/issues/3513
> Some fixes for multi component stuff

- ghcide/src/Development/IDE/Plugin/Completions.hs
- ghcide/src/Text/Fuzzy/Parallel.hs
- plugins/hls-cabal-plugin/hls-cabal-plugin.cabal
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/Completer/FilePath.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/Completer/Module.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/Completer/Simple.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/Completer/Snippet.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/Completer/Types.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/Completions.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/Data.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/Types.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/LicenseSuggest.hs
- plugins/hls-cabal-plugin/test/Completer.hs
- plugins/hls-cabal-plugin/test/Context.hs
- plugins/hls-cabal-plugin/test/Main.hs
- plugins/hls-cabal-plugin/test/Utils.hs
- plugins/hls-cabal-plugin/test/testdata/exposed.cabal
- plugins/hls-cabal-plugin/test/testdata/filepath-completions/.hidden
- plugins/hls-cabal-plugin/test/testdata/filepath-completions/dir1/f1.txt
- plugins/hls-cabal-plugin/test/testdata/filepath-completions/dir1/f2.hs
- plugins/hls-cabal-plugin/test/testdata/filepath-completions/dir2/dir3/MARKDOWN.md
- plugins/hls-cabal-plugin/test/testdata/filepath-completions/textfile.txt
- stack-lts21.yaml
- stack.yaml
Related to  #3664, by suggestion of #2940.
* sensitive to stanzas
We implement completion according to the [cabal package description](https://cabal.readthedocs.io/en/stable/cabal-package.html).
* Various simple static values
* Name field (based on cabal file name)
* Licenses
* Files
* Directories 
* Exposed modules
* Other modules
* Snippet for common keywords in cabal file
* Snippets for stanzas and their required fields
* Snippet for `common-warnings`
Keyword completion inside a stanza:
Value completion for existing keyword:
Snippet for library stanza
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3268"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Cabal file completions

- bench/MultiLayerModules.sh
- bench/config.yaml
- ghcide-bench/src/Experiments.hs
- ghcide-bench/src/Experiments/Types.hs
- ghcide/src/Development/IDE/Core/Compile.hs
- ghcide/src/Development/IDE/Core/RuleTypes.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/GHC/Orphans.hs
- ghcide/src/Development/IDE/Import/DependencyInformation.hs
- plugins/hls-eval-plugin/hls-eval-plugin.cabal
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Rules.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Types.hs
Remove GetDependencyInformation in favour of GetModuleGraph
Computing and storing GetDependencyInformation for each file essentially individually means
that we perform downsweep on each file individually, wasting a lot of work and using an excessive
amount of memory to store all these duplicated graphs individually.
However, we already have the `GetModuleGraph` rule, which we need to compute before compiling
files any way due to being depended on by `NeedsCompilation`, which needs to know if any reverse
dependencies of the module we are compiling requires TH, which meant that each file already depends on
the results of downsweep for the whole project.
Instead, we can compute the whole graph once when we execute the `GetModuleGraph` rule and even use this inside `HscEnv.hsc_mod_graph` to …
> Share ModuleGraphs for all files

- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/Completions.hs
- plugins/hls-cabal-plugin/test/Completer.hs
- plugins/hls-cabal-plugin/test/Main.hs
- plugins/hls-cabal-plugin/test/Utils.hs
- plugins/hls-cabal-plugin/test/testdata/completer.cabal
> Remove suggestion of stanzas inside of stanza context

- plugins/hls-cabal-fmt-plugin/hls-cabal-fmt-plugin.cabal
- plugins/hls-cabal-fmt-plugin/src/Ide/Plugin/CabalFmt.hs
- plugins/hls-cabal-fmt-plugin/test/Main.hs
Reported in https://github.com/haskell/vscode-haskell/issues/945
The fix is basic: don't read from disk.
> hls-cabal-fmt-plugin: Use the file contents of the LSP request

- plugins/hls-module-name-plugin/src/Ide/Plugin/ModuleName.hs
In one of my projects HLS sometimes suggests bogus module names such as `src.Foo.Bar` or `test.Foo.Quux`. It's not quite clear what's exactly going on: it's a complex project with a custom `shake`-based build system and intricate environment, so I cannot distill a reproducer to share. It might very well be a deeper issue (with dysfunctional GHC session?), but what I propose here is a simple sanity check: under no circumstances we should suggest malformed module names with components starting from lower-case characters.
> Do not suggest bogus module names

- .cirrus.yml
- .github/workflows/release.yaml
- RELEASING.md
- docs/installation.md
- scripts/release/create-yaml-snippet.sh
- scripts/release/download-gh-artifacts.sh
Drops GHC 8.10.7 from the release CI.
Unifies the download directory for release binaries and the upload directory for uploading the binaries to downloads.haskell.org.
> Clean up Release CI

- cabal.project
- plugins/hls-fourmolu-plugin/hls-fourmolu-plugin.cabal
- plugins/hls-fourmolu-plugin/src/Ide/Plugin/Fourmolu.hs
This was just released: https://github.com/fourmolu/fourmolu/releases/tag/v0.14.0.0
Also includes some minor refactoring. I think it should be pretty uncontroversial, but if not, I can break out into a separate PR
> Add support for Fourmolu 0.14.0.0

- plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
Fixes #3807 
Adds the files in the `test/` directory to the resulting package via the `extra-source-files`
> Add test directories to hls-retrie-plugin

- test/functional/HieBios.hs
- test/testdata/hieBiosError/Foo.hs
- test/testdata/hieBiosMainIs/Main.hs
- test/testdata/hieBiosMainIs/cabal.project
- test/testdata/hieBiosMainIs/hieBiosMainIs.cabal
Some integration tests for hie-bios have been very flaky.
This PR fixes the flakiness and removes a test that has been disabled for over a year with no intention (from my end) to fix it.
> Fix flaky hie bios test

- README.md
> Switch chat room to matrix

- cabal.project
GHC 8.10 was dropped in the last release. This constraint is not needed anymore.
Fixes (with ghc 9.6.2):
==> cabal v2-install --with-compiler=/opt/homebrew/opt/ghc/bin/ghc --flags=-dynamic --jobs=4 --max-backjumps=100000 --install-method=copy --installdir=/opt/homebrew/Cellar/haskell-language-server/2.3.0.0/bin
Error: cabal: Could not resolve dependencies:
[__0] trying: ekg-json-0.1.0.7 (user goal)
[__1] trying: base-4.18.0.0/installed-4.18.0.0 (dependency of ekg-json)
[__2] trying: ghcide-2.3.0.0 (user goal)
[__3] trying: stm-containers-1.2.0.2 (dependency of ghcide)
[__4] next goal: stm-hamt (dependency of stm-containers)
[__4] rejecting: stm-hamt-1.2.0.11, stm-hamt-1.2.0.10 (constraint from project
config
/private/tmp/haskell-language-server-20231005-27723-12xdk3f/haskell-language-serve …
> Remove constraint on stm-hamt

- cabal.project
- haskell-language-server.cabal
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- shake-bench/shake-bench.cabal
- stack-lts21.yaml
- stack.yaml
- entropy has had bounds revised in
- basement/hw-prim bounds empirically unnecessariy
- hyphenation was for wingman
- bound hlint to a version that uses ghc-lib by default
- stylish-haskell has never had a ghc-lib flag
- none of the versions of fourmolu that we use have a fixity-th flag
- remove some other things that lack justification speculatively
- make shake-bench buildable on later GHCs
> Simplify cabal.project

- .github/actions/setup-build/action.yml
- cabal.project
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/Shake.hs
- haskell-language-server.cabal
- hie-compat/hie-compat.cabal
- hls-plugin-api/hls-plugin-api.cabal
- hls-plugin-api/src/Ide/Plugin/RangeMap.hs
- hls-test-utils/hls-test-utils.cabal
- plugins/hls-alternate-number-format-plugin/hls-alternate-number-format-plugin.cabal
- plugins/hls-cabal-plugin/hls-cabal-plugin.cabal
- plugins/hls-call-hierarchy-plugin/hls-call-hierarchy-plugin.cabal
- plugins/hls-explicit-fixity-plugin/hls-explicit-fixity-plugin.cabal
- plugins/hls-floskell-plugin/hls-floskell-plugin.cabal
- plugins/hls-gadt-plugin/hls-gadt-plugin.cabal
- stack-lts21.yaml
- stack.yaml
Bump to
- lsp-2.3
- lsp-types-2.1
- hiedb-0.4.4
- hie-bios-12.1
- hie-compat-0.3.1.2
> Remove head.hackage

- cabal.project
- docs/support/plugin-support.md
- haskell-language-server.cabal
- plugins/hls-floskell-plugin/hls-floskell-plugin.cabal
- plugins/hls-fourmolu-plugin/hls-fourmolu-plugin.cabal
- plugins/hls-ormolu-plugin/hls-ormolu-plugin.cabal
- plugins/hls-overloaded-record-dot-plugin/hls-overloaded-record-dot-plugin.cabal
- stack.yaml
Fixes https://github.com/haskell/haskell-language-server/issues/3897
> Remove some buildability blockers that aren't needed

- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/test/exe/DiagnosticTests.hs
If a target file has multiple possible locations, then we
assume they are all separate file targets.
This happens with '.hs-boot' files if they are in the root directory of the project.
GHC reports options such as '-i. A' as 'TargetFile A.hs' instead of 'TargetModule A'.
In 'fromTargetId', we dutifully look for '.hs-boot' files and add them to the
targetLocations of the TargetDetails. Then we add everything to the 'knownTargetsVar'.
However, when we look for a 'Foo.hs-boot' file in 'FindImports.hs', we look for either
* TargetFile Foo.hs-boot
* TargetModule Foo
If we don't generate a TargetFile for each potential location, we will only have
'TargetFile Foo.hs' in the 'knownTargetsVar', thus not find 'TargetFile Foo.hs-boot'
and also not find 'TargetModule Foo'.
It took a while, but this …
> Generate FileTarget for all possible targetLocations

- docs/support/ghc-version-support.md
2.5.0 added support for 9.4.8 but this isn't listed on the supported versions page yet. Adding it and saying that 9.4.7 is deprecated per the deprecation policy below.
> Update ghc-version-support.md for 2.5.0

- plugins/hls-stan-plugin/src/Ide/Plugin/Stan.hs
- plugins/hls-stan-plugin/test/Main.hs
> Disable stan plugin by default

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/Core/PositionMapping.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/test/exe/PositionMappingTests.hs
Fix https://github.com/haskell/haskell-language-server/issues/3919#issue-2054752246
> Fix positionMapping in stale data

- haskell-language-server.cabal
- test/functional/ConfigSchema.hs
- test/functional/Format.hs
- test/functional/FunctionalBadProject.hs
- test/functional/HieBios.hs
- test/functional/Main.hs
- test/functional/Progress.hs
- test/testdata/schema/ghc92/default-config.golden.json
- test/testdata/schema/ghc92/vscode-extension-schema.golden.json
- test/testdata/schema/ghc94/default-config.golden.json
- test/testdata/schema/ghc94/vscode-extension-schema.golden.json
- test/testdata/schema/ghc96/default-config.golden.json
- test/testdata/schema/ghc96/vscode-extension-schema.golden.json
- test/testdata/schema/ghc98/default-config.golden.json
- test/testdata/schema/ghc98/vscode-extension-schema.golden.json
- test/utils/Test/Hls/Command.hs
Changes to the vscode schema need to be communicated to vscode-haskell plugin maintainers, otherwise users can't make use of the new configurations.
In general, changes to the schema need to be done consciously when new plugin or features are added. We add these golden tests as an additional contract to inform relevant parties whenever the configs change.
To fix a failing of these tests, review the change. If it is expected, accept the change via:
TASTY_PATTERN="generate schema" cabal test func-test --test-options=--accept
As changes need to be applied for all GHC version specific configs, you either need to run this command for each GHC version that is affected by the config change, or manually add the change to all other golden config files. Likely, the easiest way is to run CI and …
> Add golden tests for public configs

- CODEOWNERS
- haskell-language-server.cabal
- plugins/hls-floskell-plugin/CHANGELOG.md
- plugins/hls-floskell-plugin/hls-floskell-plugin.cabal
- plugins/hls-floskell-plugin/src/Ide/Plugin/Floskell.hs
- stack-lts21.yaml
- stack.yaml
Closes: #3927 
`hls-floskell-plugin` updated to `floskell` 0.11.* . The reason is that `floskell` 0.11.* supports `aeson` 2.2.* : https://hackage.haskell.org/package/floskell-0.11.0
There is a small change required in `plugins/hls-floskell-plugin/src/Ide/Plugin/Floskell.hs`. The easy change breaks compatibility with `floskell` 0.10. So I have bumped the version of `hls-floskell-plugin` from `2.5.0.0` to `2.5.1.0`.
`haskell-language-server` 2.5.0.0 is pinned to `hls-floskell-plugin` 2.5.0.0 exactly. This PR changes the bound on `hls-floskell-plugin` to `2.5.*`.
- This could be a revision to `haskell-language-server` 2.5.0.0
- or a fix version, `haskell-language-server` 2.5.0.1.
- I believe `haskell-language-server` 2.5.0.1 is compatible with both:
- `hls-floskell-plugin` 2.5.0.0 and …
> update Floskell to 0.11.*

- CODEOWNERS
Removing some people who we haven't seen in a long time:
- @Ailrun 
- @berberman 
- @OliverMadine 
- @Anton-Latukha 
(also `.gitlab` is defunct so I deleted it from the file, and a few logical additions)
We have a lot of plugins without an active maintainer, we should put out a call.
> Remove some people from CODEOWNERS

- hls-plugin-api/src/Ide/Plugin/ConfigUtils.hs
- test/testdata/schema/ghc92/vscode-extension-schema.golden.json
- test/testdata/schema/ghc94/vscode-extension-schema.golden.json
- test/testdata/schema/ghc96/vscode-extension-schema.golden.json
- test/testdata/schema/ghc98/vscode-extension-schema.golden.json
Follow up to #3917, where the command `hls vscode-extension-schema` did not to honour the default values of the plugin description.
The first commit of this PR fixes that shortcoming.
The second commit unifies the plugin config generation. I am not sure whether that's a good idea, as I feel it obfuscates the code more. I am leaving it in for discussion, but I am completely open to dropping the second commit.
> Make vscode-extension-schema honour default values

- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/Types.hs
Relevant for #3939 
(I didn't test this change, but it is identical to https://github.com/haskell/haskell-language-server/blob/master/plugins/hls-stan-plugin/src/Ide/Plugin/Stan.hs#L82)
> Don't produce diagnostics if plugin is turned off

- hls-plugin-api/src/Ide/Plugin/Properties.hs
After removal of unsafe coerce the api would not be affected
> Properties API: Remove unsafe coerce in favor of type class based method in 

- plugins/hls-semantic-tokens-plugin/src/Ide/Plugin/SemanticTokens/Query.hs
- plugins/hls-semantic-tokens-plugin/test/Main.hs
- plugins/hls-semantic-tokens-plugin/test/testdata/TRecordDuplicateRecordFields.expected
- plugins/hls-semantic-tokens-plugin/test/testdata/TRecordDuplicateRecordFields.hs
fix omitting record field and {-# LANGUAGE DuplicateRecordFields #-}
and add test case for it
> fix: semantic token omitting record field in `{-# LANGUAGE DuplicateRecordFields  #-}` #3950

- .github/workflows/flags.yml
- .github/workflows/test.yml
- ghcide/ghcide.cabal
- haskell-language-server.cabal
- hie-compat/hie-compat.cabal
- hie-compat/src-ghc90/Compat/HieAst.hs
- plugins/hls-class-plugin/hls-class-plugin.cabal
- plugins/hls-fourmolu-plugin/hls-fourmolu-plugin.cabal
- plugins/hls-overloaded-record-dot-plugin/hls-overloaded-record-dot-plugin.cabal
Since we're supporting GHCs 9.2+ we can assume that impl(ghc >= 9.2) will be true going forward.
> Cleanup conditional build logic pertaining to pre 9.2 GHCs

- plugins/hls-refactor-plugin/hls-refactor-plugin.cabal
- plugins/hls-refactor-plugin/test/Main.hs
I'd like to do general cleanup of unused dependencies (stuff reported by `-Wunused-packages`).
This PR starts by just doing this for one plugin and checking that people agree with the approach to removing unused ghc  (direct - I know that most plugins actually do depend on GHC transitively) dependency.
If you find such initiative useful, I can continue with other plugins.
> Remove unused dependencies in hls-refactor-plugin

- cabal.project
New version of ghc-trace-events with bumped bounds has been released to hackage:
https://github.com/maoe/ghc-trace-events/pull/13
> Remove allow-newer for ghc-trace-events

- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal.hs
- test/testdata/schema/ghc92/default-config.golden.json
- test/testdata/schema/ghc92/vscode-extension-schema.golden.json
- test/testdata/schema/ghc94/default-config.golden.json
- test/testdata/schema/ghc94/vscode-extension-schema.golden.json
- test/testdata/schema/ghc96/default-config.golden.json
- test/testdata/schema/ghc96/vscode-extension-schema.golden.json
- test/testdata/schema/ghc98/default-config.golden.json
- test/testdata/schema/ghc98/vscode-extension-schema.golden.json
I missed that, and preemptively added the options in https://github.com/haskell/vscode-haskell/pull/1032 and https://github.com/haskell/vscode-haskell/pull/1031
> Document cabal diagnostic options

- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/session-loader/Development/IDE/Session/Implicit.hs
- ghcide/src/Development/IDE/Core/Compile.hs
- ghcide/src/Development/IDE/Core/FileStore.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/GHC/Compat/Outputable.hs
- ghcide/src/Development/IDE/GHC/Compat/Units.hs
- ghcide/src/Development/IDE/GHC/CoreFile.hs
- ghcide/src/Development/IDE/GHC/Orphans.hs
- ghcide/src/Development/IDE/GHC/Util.hs
- ghcide/src/Development/IDE/Import/FindImports.hs
- ghcide/src/Development/IDE/LSP/LanguageServer.hs
- ghcide/src/Development/IDE/LSP/Outline.hs
- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- ghcide/src/Development/IDE/Plugin/TypeLenses.hs
If nothing else, I hope this will reduce the amount of hlint warnings that are showing up in unrelated PRs.
> Fix most hlint warnings in ghcide

- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/Types.hs
> chore: Fix typo s/occured/occurred

- .github/workflows/test.yml
- cabal.project
- docs/support/plugin-support.md
- plugins/hls-floskell-plugin/hls-floskell-plugin.cabal
- plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
- plugins/hls-hlint-plugin/test/Main.hs
- plugins/hls-stylish-haskell-plugin/hls-stylish-haskell-plugin.cabal
- New stylish-haskell release supports 9.8
- Ormolu and fourmolu were updated but the test matrix hadn't been
- New version of floskell supports 9.8
- New version of hlint supports 9.8, small test wrangling required
9.8 support shaped up a lot in the last few days!
> Various 9.8 compat

- ghcide/ghcide.cabal
- haskell-language-server.cabal
> Update base lower bounds for HLS

- plugins/hls-module-name-plugin/hls-module-name-plugin.cabal
- plugins/hls-module-name-plugin/src/Ide/Plugin/ModuleName.hs
- plugins/hls-module-name-plugin/test/Main.hs
- plugins/hls-overloaded-record-dot-plugin/hls-overloaded-record-dot-plugin.cabal
- plugins/hls-overloaded-record-dot-plugin/src/Ide/Plugin/OverloadedRecordDot.hs
I'm lumping these together because there's relatively few changes required and to save on CI resources ..
> Fix -Wall and -Wunused-packages in module name and overloaded record dot plugins

- plugins/hls-refactor-plugin/hls-refactor-plugin.cabal
- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/Plugins/Diagnostic.hs
- plugins/hls-refactor-plugin/test/Main.hs
- plugins/hls-refactor-plugin/test/Test/AddArgument.hs
- adding reproducer for https://github.com/haskell/haskell-language-server/issues/3795
- fixing the bug
- fixing bunch of warnings in refactor plugin tests
> refactor plugin: add reproducer and fix for #3795

- .github/workflows/hlint.yml
- .hlint.yaml
This is a following up of #3901
I dig a bit into hlint. 
1. We can only ignore-glob in commandline. config file missing the options for ignore glob.
2. hlint 3.8 can ignore files more correctly.
> update hlint to 3.8 and prevent linting on testdata dir

- docs/contributing/contributing.md
- docs/contributing/index.rst
- docs/features.md
I built the docs locally and fixed most sphinx warnings.
> Fix documentation/image links

- haskell-language-server.cabal
- plugins/hls-stan-plugin/src/Ide/Plugin/Stan.hs
This PR is part of larger effort where I try to reduce the amount of compiler warnings across all packages.
> Fix -Wall and -Wunused-packages in stan plugin

- .github/workflows/caching.yml
Not sure if this is desirable, but @michaelpj recently disabled tests for this combination (see [PR](https://github.com/haskell/haskell-language-server/pull/3976/files#diff-faff1af3d8ff408964a57b2e475f69a6b7c7b71c9978cccc8f471798caac2c88R81-R83))  and said something like this would be needed to prevent failures of caching job on master.
> Disable caching job with ghc 9.2 on windows

- ghcide/test/ghcide-test-utils.cabal
We need this so we can release a version compatible with 2.6.0.0
I will need to make hackage revisions to all the plugin packages that depend on it
> Bump ghcide-test-utils to 2.0.0.0

- plugins/hls-class-plugin/test/Main.hs
I don't think we need to pass in the source to match the result, since its result is throwed away.
switching from `waitForDiagnosticsFromSource` to `waitForDiagnosticsFrom` improve the test speed by magnitude.
before
`All 29 tests passed (88.71s)`
after
`All 29 tests passed (5.74s)`
> Improve hls class plugin test

- .github/actions/setup-build/action.yml
Was confused about why I keep seing `-w ghc-9.6.3` in CI when we're supposed to be on 9.6.4.
This explains it: https://github.com/haskell-actions/setup/releases/tag/v2.6.1
> Bump haskell-actions/setup to get GHC 9.6.4 in CI

- .circleci/config.yml
- stack-lts21.yaml
- stack.yaml
Motivation:
this week I saw several instances of stack CI jobs failing with errors ala "failed to download stack binaries from fpcomplete servers".
I propose we switch to official haskell images which have latest stack preinstalled so we can avoid this class of failures altogether.
> stack CI: switch to offic. haskell images, bump to lts-22.9 (ghc 9.6.4)

- .github/workflows/bench.yml
> benchmarks: switch from deprecated haskell/actions/setup to haskell-actions/setup

- ghcide/src/Development/IDE/Core/Rules.hs
This doesn't change any behaviour, but ensures we have a more informative error message
if we somehow request a linkable that does not exist.
> ghcide: Only try `stat`ing a core file after we ensure it actually exists

- ghcide/ghcide.cabal
- haskell-language-server.cabal
- stack-lts21.yaml
- stack.yaml
The main appeal of this bump is that it fixes the [issue](https://github.com/wz1000/HieDb/issues/61) with duplicate typeref indexing, making indexing noticably faster (>2x) and resulting hiedb sqlite files smaller (~7x on our work codebase) which likely also improves the speed of querying.
> Bump to hiedb 0.6.0.0

- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction.hs
- plugins/hls-refactor-plugin/test/Main.hs
Fixes https://github.com/haskell/haskell-language-server/issues/4079
The problem was that the original regex was mistakenly using `.` as a regex metacharacter, whereas the GHC error  contains a literal `.`
In cases where GHC error contains further `)`'s this led to 3rd match group (which is used to extract srcspan) to contain too much stuff, leading to errors described in the issue.
If the tests pass, would you still recommend adding a test case for this or is it ok like this?
> refactor plugin: fix regex for extracting import suggestions

- haskell-language-server.cabal
Tested with `cabal build --constraint='fourmolu==0.15.0.0'`
> Add support for fourmolu 0.15

- plugins/hls-semantic-tokens-plugin/test/SemanticTokensTest.hs
- plugins/hls-semantic-tokens-plugin/test/testdata/TModuleA.hs
- plugins/hls-semantic-tokens-plugin/test/testdata/TModuleB.hs
Fix #4102
Since hackage does not accept non-ascii filename.
> remove non-ascii name

- haskell-language-server.cabal
- hls-plugin-api/src/Ide/Types.hs
- plugins/hls-rename-plugin/src/Ide/Plugin/Rename.hs
- plugins/hls-rename-plugin/test/Main.hs
- plugins/hls-rename-plugin/test/testdata/Comment.expected.hs
- plugins/hls-rename-plugin/test/testdata/Comment.hs
First step towards improving behavior when renaming unsupported things (e.g. keywords or words within comments).
Instead of throwing plugin error (reporte here https://github.com/haskell/haskell-language-server/issues/3915)
we detect that there is no Name to rename under cursor and throw less scary looking Invalid Param warning.
Behavior after this PR:
EDIT: Actually in the end I included @michaelpj's suggestion to implement [Prepare Rename](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_prepareRename) handler that "prefilters" invalid requests on the client and doesn't even allow creating rename request for them.
> Improve handling of nonsense rename attempts

- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Rules.hs
- plugins/hls-eval-plugin/test/Main.hs
- plugins/hls-eval-plugin/test/testdata/T28.expected.hs
- plugins/hls-eval-plugin/test/testdata/T28.hs
Fixes https://github.com/haskell/haskell-language-server/issues/3500 and https://github.com/haskell/haskell-language-server/issues/3312
The problem in those issues can be illustrated by this simpler reproducer.
The issue is that the "end of line comment" is associated with the 2nd match group of function definition (confirmed this by compiling with `-ddump-parsed-ast -dkeep-comments`), which was part of AST  that eval plugin was ignoring when extracting comments, thus it didn't create "Evaluate..." code lens.
By using `biplate` combinator from lens we can more simply extract all occurrences of LEpaComment from the parsed source, wherever they might be.
> eval: more robust way to extract comments from ParsedModule

- .github/scripts/test.sh
- exe/Wrapper.hs
As reported by https://github.com/haskell/haskell-language-server/pull/3748#discussion_r1508794998, the tests are not run correctly, since there is no GHC installed. We install the recommended GHC version to make sure one (hopefully) supported GHC version is installed for running the wrapper test.
Further, if setup fails, HLS-wrapper launches an LSP server that allows users to restart the server once they have fixed potential setup issues. That's only desired if we are indeed launching as an LSP server. Thus, we exit with a non-zero exit code if setup fails and we are not launching in LSP mode.
> Exit with non-zero exitcode if wrapper fails to launch

- hls-test-utils/hls-test-utils.cabal
- hls-test-utils/src/Test/Hls.hs
Even though we copy test files into temporary directories, we used to reuse the same cache directory for build artefacts, hiedb and compilation artefacts. While there is practially no chance this causes any issues for the test runs themselves, it litters the cache directory with a lot of files. So, we create one main directory in the temporary directory, and generate all caches and in there. This makes it trivial to delete all test caches, without risking deleting the cache that is still used.
> Improve isolation of build artefacts of test runs

- haskell-language-server.cabal
- plugins/hls-hlint-plugin/src/Ide/Plugin/Hlint.hs
The ghc-lib flag was removed in #3015, but it's still useful to be able
to compile hls-hlint-plugin using the GHC API if you've done so for
hlint and ghc-lib-parser-ex, rather than using ghc-lib-parser.
A lot of the HLINT_ON_GHC_LIB gated code which has probably been
bitrotting since this flag was removed has also been removed, and is
probably from when hlint used to work on haskell-src-exts. As
ghc-lib-parser has the same API as GHC itself, there's no need for code
to be cpp gated.
I've also updated the `configuration-ghc94.nix` file to show how it can be built
using the GHC libraries instead of ghc-lib-parser.
> Reintroduce ghc-lib flag for hlint plugin

- .github/workflows/bench.yml
- bench/config.yaml
- ghcide-bench/ghcide-bench.cabal
- ghcide-bench/src/Experiments.hs
- haskell-language-server.cabal
- shake-bench/shake-bench.cabal
- shake-bench/src/Development/Benchmark/Rules.hs
~~  Enable 4 version to do bench seems to be taking too long, considering picking two: highest and lowest  ~~
Fix bench for newer ghc versions
The following have been done:
1. No longer use the implicit-hie to generate the hie.yaml for the bench examples and in favor of using "cradle:\n cabal:\n", seems to be working with modern cabal.
2. upgrade benchmark to use 9.6, 9.8 (The latest two we support for now).
3. upgrade bench examples to `Cabal version: 3.10.2.1, lsp-types version: 2.1.1.0`
4. fix minor error that `*.hp` files duplicates its extension name
> Benchmark: Enable 9.6, 9.8

- cabal.project
- haskell-language-server.cabal
The version of stylish-haskell where @michaelpj added support for ghc 9.8 is on hackage:
https://hackage.haskell.org/package/stylish-haskell-0.14.6.0/changelog
Let's enable it in hls!
> Integrate stylish-haskell into hls executable with ghc 9.8

- haskell-language-server.cabal
- test/testdata/schema/ghc98/default-config.golden.json
- test/testdata/schema/ghc98/vscode-extension-schema.golden.json
Followup on https://github.com/haskell/haskell-language-server/pull/4124
two more plugins that I think we can now allow to be integrated into hls with ghc 9.8
> Enable floskell and hlint plugins for ghc 9.8

- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/src/Development/IDE/LSP/LanguageServer.hs
- ghcide/src/Development/IDE/Types/Exports.hs
- ghcide/test/src/Development/IDE/Test.hs
- plugins/hls-alternate-number-format-plugin/src/Ide/Plugin/AlternateNumberFormat.hs
- plugins/hls-code-range-plugin/src/Ide/Plugin/CodeRange/ASTPreProcess.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs
- plugins/hls-explicit-imports-plugin/src/Ide/Plugin/ExplicitImports.hs
- plugins/hls-qualify-imported-names-plugin/src/Ide/Plugin/QualifyImportedNames.hs
- plugins/hls-retrie-plugin/test/Main.hs
- plugins/hls-stan-plugin/src/Ide/Plugin/Stan.hs
`Set.member` is generally more efficient because it can use Ord constraint unlike `Foldable.elem` which can only use Eq class and has to traverse the whole thing if the element is not present.
using Set/Map.singleton is less important but I still find it useful because it reduces visual noise.
> Use Set.member instead of Foldable.elem

- .github/workflows/test.yml
- CODEOWNERS
- docs/features.md
- docs/support/plugin-support.md
- flake.nix
- ghcide/src/Development/IDE/Core/Compile.hs
- ghcide/src/Development/IDE/Core/FileExists.hs
- ghcide/src/Development/IDE/Core/RuleTypes.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/GHC/Error.hs
- ghcide/src/Development/IDE/Plugin/HLS.hs
- haskell-language-server.cabal
- hie-compat/src-ghc92/Compat/HieAst.hs
- hls-plugin-api/src/Ide/Plugin/Resolve.hs
- hls-plugin-api/src/Ide/Types.hs
- plugins/hls-notes-plugin/README.md
- plugins/hls-notes-plugin/src/Ide/Plugin/Notes.hs
- plugins/hls-notes-plugin/test/NotesTest.hs
- plugins/hls-notes-plugin/test/testdata/NoteDef.hs
- plugins/hls-notes-plugin/test/testdata/Other.hs
- plugins/hls-notes-plugin/test/testdata/hie.yaml
- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction.hs
- src/HlsPlugins.hs
For some reason I could not reopen the other pull request, so I have to open a new one (#3629). Sorry there were a lot of real live issues compounding a few days ago and closing this was just irrational.
In case you are still interested in this, I would still like to have this merged and would maintain it in the future.
> hls-notes-plugin: Initial implementation

- .github/workflows/test.yml
- CODEOWNERS
- haskell-language-server.cabal
- hls-plugin-api/src/Ide/Types.hs
- plugins/hls-cabal-fmt-plugin/src/Ide/Plugin/CabalFmt.hs
- plugins/hls-cabal-fmt-plugin/test/Main.hs
- plugins/hls-cabal-gild-plugin/src/Ide/Plugin/CabalGild.hs
- plugins/hls-cabal-gild-plugin/test/Main.hs
- plugins/hls-cabal-gild-plugin/test/testdata/commented_testdata.cabal
- plugins/hls-cabal-gild-plugin/test/testdata/commented_testdata.formatted_document.cabal
- plugins/hls-cabal-gild-plugin/test/testdata/hie.yaml
- plugins/hls-cabal-gild-plugin/test/testdata/lib_testdata.cabal
- plugins/hls-cabal-gild-plugin/test/testdata/lib_testdata.formatted_document.cabal
- plugins/hls-cabal-gild-plugin/test/testdata/simple_testdata.cabal
- plugins/hls-cabal-gild-plugin/test/testdata/simple_testdata.formatted_document.cabal
- plugins/hls-cabal-gild-plugin/test/testdata/src/MyLib.hs
- plugins/hls-cabal-gild-plugin/test/testdata/src/MyOtherLib.hs
- src/HlsPlugins.hs
- test/testdata/schema/ghc92/default-config.golden.json
- test/testdata/schema/ghc92/vscode-extension-schema.golden.json
- test/testdata/schema/ghc94/default-config.golden.json
- test/testdata/schema/ghc94/vscode-extension-schema.golden.json
- test/testdata/schema/ghc96/default-config.golden.json
- test/testdata/schema/ghc96/vscode-extension-schema.golden.json
- test/testdata/schema/ghc98/default-config.golden.json
- test/testdata/schema/ghc98/vscode-extension-schema.golden.json
> Add cabal-gild as a cabal file formatter plugin

- plugins/hls-semantic-tokens-plugin/src/Ide/Plugin/SemanticTokens/Internal.hs
- plugins/hls-semantic-tokens-plugin/src/Ide/Plugin/SemanticTokens/Types.hs
Switch `use_` to `useE` to capture meaningful error.
> improve logging in semantic tokens rule

- docs/contributing/contributing.md
- don't mention discord (can't find any haskell-tooling channel in there, maybe I'm just searching incorrectly)?
- replace the generic haskell-tooling matrix with haskell-language-server which seems more appropriate for hls documentation
- move IRC down in the list to incentivize people to join matrix as first option (I'm ok with deleting IRC as @michaelpj suggested, just waiting for some feedback). EDIT got feedback from geekosaur that he's maintaining the irc bridge, so I'd just keep it for now.
> Update contact info in docs

- plugins/hls-refactor-plugin/test/Main.hs
I guess that's about as much as we can do with https://github.com/haskell/haskell-language-server/issues/4134
The code action still works, it just suggests not-defaulted types.
Another possible alternative to consider would be to simplify the test by switching to something not-typeclass-polymorphic (e.g. use && instead of + to remove the conditional in test).
> Update comment in refactor tests

- plugins/hls-notes-plugin/src/Ide/Plugin/Notes.hs
Otherwise this would also trigger when trying to go to a function definition.
> hls-notes-plugin: Do not error if no note is under the cursor

- ghcide/test/exe/ExceptionTests.hs
- ghcide/test/exe/TestUtils.hs
- hls-test-utils/src/Test/Hls.hs
Fixes #4036
The tests weren't strictly speaking incorrect, as they were testing what they aim to, but using the cabal directory of ghcide is not correct.
> Run ExceptionTests in temporary directory

- haskell-language-server.cabal
This ensures that cabal does not consider them at all, and won't try to solve for their dependencies. So if we turn off the fourmolu plugin, cabal really won't consider fourmolu at all.
This gets us some of the benefits of #4156 with much less work.
Fixes #4100.
> Mark plugins as not buildable if the flag is disabled

- haskell-language-server.cabal
- plugins/hls-eval-plugin/test/cabal.project
- test/functional/Progress.hs
- test/utils/Test/Hls/Flags.hs
Picks up where https://github.com/haskell/haskell-language-server/pull/4129 left off + includes test fixes.
One of the fixed tests seems to be flaky so might require some stabilization..
> Fix references to old CPP names in tests, update tests

- ghcide/src/Development/IDE/LSP/LanguageServer.hs
It contribute to a hang in #4152
we discover it when doing #4153
> get rid of the `unsafeInterleaveIO` at start up

- exe/Wrapper.hs
- ghcide/exe/Main.hs
- ghcide/src/Development/IDE/Core/OfInterest.hs
- ghcide/src/Development/IDE/Core/RuleTypes.hs
- ghcide/src/Development/IDE/Core/Service.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/Core/Tracing.hs
- ghcide/src/Development/IDE/LSP/HoverDefinition.hs
- ghcide/src/Development/IDE/LSP/LanguageServer.hs
- ghcide/src/Development/IDE/LSP/Notifications.hs
- ghcide/src/Development/IDE/Main.hs
- ghcide/src/Development/IDE/Plugin/HLS/GhcIde.hs
- ghcide/test/exe/ExceptionTests.hs
- ghcide/test/exe/Main.hs
- ghcide/test/exe/UnitTests.hs
- hls-plugin-api/src/Ide/Logger.hs
- hls-test-utils/src/Test/Hls.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/CodeLens.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Rules.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Types.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Util.hs
- plugins/hls-retrie-plugin/src/Ide/Plugin/Retrie.hs
- plugins/hls-retrie-plugin/test/Main.hs
- plugins/hls-stylish-haskell-plugin/src/Ide/Plugin/StylishHaskell.hs
- plugins/hls-stylish-haskell-plugin/test/Main.hs
- src/HlsPlugins.hs
- src/Ide/Main.hs
Move ghcide completely to colog-logging style.
Move plugins that were relying on `ideLogger` to colog style logging.
Move opentelemetry to colog-logging style.
This allows us to drop legacy code and unify the logging experience in
HLS.
We add a bunch of new Log constructors at various locations that aim to
be identical to their previous `Logger` statements.
Just a bit of busy work. It started out as migrating `ekg` to colog style logging. ~~Now only the telemetry logger uses `Logger`.~~ Fixed.
> Drop Legacy Logger from Codebase

- hls-plugin-api/src/Ide/Logger.hs
- hls-test-utils/src/Test/Hls.hs
It seems we do have it already, I enable it for default when testing.
> enable ThreadId for when testing

- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/src/Development/IDE/GHC/Compat/Core.hs
~GHC gives a default "main" home unit, and it is difficult to avoid this as
each ghc session must have an active home unit at all times, but in a multiple
component session, there is no other good choice for a default unit. We could
pick one arbitrarily, but this is ugly and complicates the code a lot.~
~We never use this default "main" unit for anything, as the GHC sessions
corresponding to any file/component have the active unit set to the correct one
for that component.~
~When checking for home unit closure, we must make sure to include only the
actual units in the project, not the bogus "main" unit that GHC forces us to
have. Including the main unit seems to make the `checkHomeUnitsClosed` function loop
forever for some reason.~
Use a faster implementation of checkHomeUnitsClosed
GHC …
> Replace checkHomeUnitsClosed with a faster implementation

- cabal.project
- ghcide/ghcide.cabal
- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- haskell-language-server.cabal
- hls-plugin-api/src/Ide/Plugin/Config.hs
- hls-plugin-api/src/Ide/Types.hs
- stack-lts21.yaml
- stack.yaml
- test/testdata/schema/ghc92/default-config.golden.json
- test/testdata/schema/ghc94/default-config.golden.json
- test/testdata/schema/ghc96/default-config.golden.json
- test/testdata/schema/ghc98/default-config.golden.json
We add an option to `Config` that allows clients to specify how HLS should load components.
The three options are:
* SessionLoadSingleComponent: Always load only a single component when a new component is discovered.
* SessionLoadMultipleComponents: Always allow the cradle to load multiple components at once. This might not be always possible, e.g., if the tool doesn't support multiple components loading. The cradle can decide how to handle these situations.
* SessionAuto: Leave the decision to the individual cradle type. Some cradles have good support for loading multiple components, while others do not. So use multiple components loading for tools, such as cabal, and force single component loading for tools that do not support multiple components, such as stack.
This allows users to …
> Allow users to specify whether to use `cabal`'s multi-repl feature

- ghcide/test/exe/DependentFileTest.hs
- ghcide/test/src/Development/IDE/Test.hs
part of #4173 
This is specially flalky see #4194
> [Migrate DependentFileTest] part of #4173 Migrate ghcide tests to hls test utils

- ghcide/test/exe/Config.hs
- ghcide/test/exe/IfaceTests.hs
- hls-test-utils/src/Test/Hls.hs
- hls-test-utils/src/Test/Hls/FileSystem.hs
I am adding `canonicalizePath tmpDir'` to hls-test-utils, since it is doing so in ghcide-test-utils,
migration would break some tests if we are not canonicalizePath the temp dir
> [Migrate IfaceTests] part of #4173 Migrate ghcide tests to hls test utils and use canonicalizePath path in tmp dir in hls-test-utils

- .github/workflows/bench.yml
- bench/Main.hs
- bench/README.md
- shake-bench/src/Development/Benchmark/Rules.hs
add something like this in benchmark result to easily view the performance diffferent like what we did for the svg.
```
Configuration, name, success, samples, startup, setup, userT, delayedT, 1stBuildT, avgPerRespT, totalT, rulesBuilt, rulesChanged, rulesVisited, rulesTotal, ruleEdges, ghcRebuilds, maxResidency, allocatedBytes
All, edit-header, True,0.00%,2.21%,Nah,-98.75%,Nah,67.50%, NaN,67.50%,-1.89%,-1.81%,-1.80%,-1.24%,0.39%,1650.00%,169.44%,49.89%
All, edit, True,0.00%,0.56%,Nah,3.66%,Nah,3.66%, NaN,3.66%,1.10%,1.10%,1.10%,0.00%,0.00%,0.00%,72.22%,-0.18%
All, hover, True,0.00%,0.57%,Nah,-43.57%,Nah,-43.57%, NaN,-43.57%,0.13%,0.13%,0.13%,1.07%,-0.39%,-94.29%,-61.50%,-33.32%
All, semanticTokens, True,0.00%,1.10%,Nah,2.22%,Nah,2.22%, …
```
> Add performace diff benchmarks

- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/GHC/CoreFile.hs
- ghcide/src/Development/IDE/GHC/Orphans.hs
- ghcide/src/Development/IDE/LSP/Notifications.hs
> Force complete pattern in ghcide

- .github/workflows/flags.yml
- .hlint.yaml
- ghcide/exe/Main.hs
- ghcide/test/exe/DiagnosticTests.hs
- ghcide/test/exe/TestUtils.hs
- haskell-language-server.cabal
- hls-test-utils/hls-test-utils.cabal
- plugins/hls-alternate-number-format-plugin/src/Ide/Plugin/Literals.hs
- plugins/hls-change-type-signature-plugin/test/Main.hs
- plugins/hls-class-plugin/test/Main.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Parse/Comments.hs
- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction.hs
As found in https://github.com/haskell/haskell-language-server/pull/4223 we're not actually enabling pedantic in CI at all.
This enables it for all cabal projects for which most warnings have been fixed so far (not yet for ghcide).
> Actually enable pedantic flag in ci flags job

- ghcide/test/exe/FindDefinitionAndHoverTests.hs
I think we can enable the test for #717  now. Not sure why it won't work before, but it should work now
> Enable test for #717

- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/Completer/Paths.hs
- plugins/hls-cabal-plugin/test/Completer.hs
- plugins/hls-cabal-plugin/test/Context.hs
Fix for the issue #3774
To solve it I have created a wrapper of the `Posix.splitFileName` function.
The function by default [tends to add unnecessary trailing slash](https://hackage.haskell.org/package/filepath-1.5.2.0/docs/System-FilePath-Posix.html#g:4)
> Shorter file names completion

- ghcide/test/exe/RootUriTests.hs
- hls-test-utils/src/Test/Hls.hs
What's done
* Add testClientRoot and testServerRoot to TestConfig
* Migrate RootUriTests
> Migrate RootUriTests

- plugins/hls-cabal-plugin/CHANGELOG.md
- plugins/hls-explicit-record-fields-plugin/CHANGELOG.md
- plugins/hls-floskell-plugin/CHANGELOG.md
- plugins/hls-overloaded-record-dot-plugin/CHANGELOG.md
- plugins/hls-retrie-plugin/changelog.md
The CHANGELOG files in plugins are neither up-to-date nor can they even be displayed in Hackage (since plugins are all internal libraries and Hackage). I also don't think they are displayed in flora.
Thus, delete them, so users aren't confused why the ChangeLogs contain barely any information.
Thanks to @Kleidukos, who kindly told me that we had CHANGELOGs :)
> Remove unused and outdated CHANGELOG files

- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- haskell-language-server.cabal
- hls-test-utils/hls-test-utils.cabal
- hls-test-utils/src/Test/Hls.hs
- hls-test-utils/src/Test/Hls/Util.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/Completions.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/Types.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Diagnostics.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Orphans.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Parse.hs
- plugins/hls-cabal-plugin/test/Completer.hs
- plugins/hls-cabal-plugin/test/Context.hs
Replace the more brittle parser with cabal's `readFields`.
Ready for review :)
> hls-cabal-plugin: refactor context search to use `readFields`

- .github/workflows/bench.yml
We already have the `performance` label
> CI change, only run bench on performance label

- cabal.project
- exe/Wrapper.hs
- ghcide-bench/src/Experiments.hs
- ghcide-bench/test/Main.hs
- ghcide/ghcide.cabal
- ghcide/src/Development/IDE/LSP/LanguageServer.hs
- ghcide/src/Development/IDE/LSP/Server.hs
- ghcide/src/Development/IDE/Plugin/HLS.hs
- ghcide/test/exe/Config.hs
- ghcide/test/exe/ExceptionTests.hs
- haskell-language-server.cabal
- hls-plugin-api/hls-plugin-api.cabal
- hls-plugin-api/src/Ide/Plugin/Resolve.hs
- hls-test-utils/hls-test-utils.cabal
- hls-test-utils/src/Development/IDE/Test.hs
- hls-test-utils/src/Test/Hls.hs
- hls-test-utils/src/Test/Hls/Util.hs
- plugins/hls-code-range-plugin/test/Main.hs
- plugins/hls-explicit-imports-plugin/src/Ide/Plugin/ExplicitImports.hs
- plugins/hls-refactor-plugin/test/Main.hs
- plugins/hls-rename-plugin/test/Main.hs
- plugins/hls-semantic-tokens-plugin/test/SemanticTokensTest.hs
- stack-lts21.yaml
- stack.yaml
- test/functional/Format.hs
- test/functional/FunctionalBadProject.hs
- test/functional/HieBios.hs
- test/functional/Progress.hs
Proof that https://github.com/haskell/lsp/pull/587 is okay.
> Bump to new lsp versions

- ghcide/session-loader/Development/IDE/Session.hs
> Remove redudant absolutization in session loader

- ghcide/src/Development/IDE/Import/FindImports.hs
- ghcide/test/data/multi-unit/b-1.0.0-inplace
- ghcide/test/data/multi-unit/b/B.hs
This bug prevents package imports from working within a multi unit session.
> FindImports: ThisPkg means some home unit, not "this" unit

- ghcide/src/Development/IDE/GHC/Compat.hs
- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/Plugins/FillHole.hs
- plugins/hls-refactor-plugin/test/Main.hs
> Limit number of valid hole fits to 10

- hls-graph/src/Development/IDE/Graph/Internal/Types.hs
> 4301 we need to implement utility to wait for all runnning keys in hls graph done

- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/src/Development/IDE/Core/Rules.hs
- ghcide/src/Development/IDE/Core/Shake.hs
- ghcide/src/Development/IDE/Plugin/Completions.hs
- ghcide/src/Development/IDE/Types/KnownTargets.hs
At startup `GetLocatedImports` is called on all known files. Say you have 10000 modules in your project then this leads to 10000 calls to GetLocatedImports running concurrently.
In `GetLocatedImports` the known targets are consulted and the targetsMap is created by mapping the known targets. This map is used for introducing sharing amongst filepaths.  This operation copies a local copy of the `target` map which is local to the rule.
```
let targetsMap = HMap.mapWithKey const targets
```
So now each rule has a hashmap of size 10000 held locally to it and depending on how the threads are scheduled there will be 10000^2 elements in total allocated in hashmaps. This used a lot of memory.
Solution: Return the normalising map in the result of the `GetKnownTargets` rule so it is shared across …
> Fix quadratic memory usage in GetLocatedImports

- docs/support/ghc-version-support.md
https://github.com/haskell/haskell-language-server/pull/3434
> Refine GHC deprecation policy

- cabal.project
- haskell-language-server.cabal
> Remove final allow-newer for 9.10

- cabal.project
Time travel back since the new release cabal-install 12 is not happy with us and refuse to build
> Fix cabal.project index-state

- ghcide/src/Development/IDE/Core/Compile.hs
- ghcide/src/Development/IDE/Core/OfInterest.hs
- ghcide/src/Development/IDE/Core/ProgressReporting.hs
- ghcide/src/Development/IDE/Core/Shake.hs
follow up of https://github.com/haskell/haskell-language-server/pull/4205
This is intended to remove the useless `inProgress` when tracking the `inProgressState` from the outside.
1. Add kind `data ProgressStateTrackingType = ProgressStateInsideTracking | ProgressStateOutsideTracking` to distinguish the two type of `inProgressState` tracking.
2. Spread the `TProgressState` to related type location to mark what kind of tracking we used. Then we won't have `inProgress` for `ProgressStateOutsideTracking`
> Formalize the ProgressReporting Type

- ghcide/src/Development/IDE/Core/WorkerThread.hs
Fix #4340
let the caller handle the error happened during `awaitRunInThread`. In such case the HLS won't be stuck if the session setup fails and the LSP should be able to show the error to the client as other error cases happening in the rule system.
cc @fendor
> capture error in worker thread

- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/src/Development/IDE/Core/Compile.hs
- ghcide/src/Development/IDE/Core/Rules.hs
Fix #4145
The error case is demonstrated in https://github.com/haskell/haskell-language-server/issues/4145#issuecomment-2206965649
1. Include ModLocation in the `ModSummaryResult`  fingerprint.
2. Instead of getting the core file location from `GetModSummary`, get it from the result of `GetModIface` directly since that is the actual location the core file written to. While the `GetModSummary` contains the future core file location that would be written only if we would have made some change cause the rewrite. See Note [Avoiding bad interface files]
> Fix core file location in `GetLinkable`

- .github/workflows/release.yaml
- ChangeLog.md
- docs/support/ghc-version-support.md
- ghcide/ghcide.cabal
- haskell-language-server.cabal
- hls-graph/hls-graph.cabal
- hls-plugin-api/hls-plugin-api.cabal
- hls-test-utils/hls-test-utils.cabal
This is a bindist only release.
- There is currently a list of GHC versions for each major platform. Search for `ghc: [` to find all lists.
- Look for `TODO:` to find locations that require extra care for GHC versions.
- HLS uses lockstep versioning. The core packages and all plugins use the same version number, and only support exactly this version.
- Exceptions:
- `hie-compat` requires no automatic version bump.
- `shake-bench` is an internal testing tool, not exposed to the outside world. Thus, no version bump required for releases.
- For updating cabal files, the following script can be used:
- ```sh
./release/update_versions.sh <OLD_VERSION> <NEW_VERSION>
```
- It still requires manual verification and review
- Generate a ChangeLog via `./GenChangelogs.hs <api-key> <tag>`
- `<tag>` …
> Release 2.9.0.1

- ghcide/session-loader/Development/IDE/Session.hs
componentInternalUnits is always `[]`, we can safely remove it.
> Remove componentInternalUnits

- haskell-language-server.cabal
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/FieldSuggest.hs
- plugins/hls-cabal-plugin/test/Main.hs
- plugins/hls-cabal-plugin/test/Utils.hs
- plugins/hls-cabal-plugin/test/testdata/code-actions/FieldSuggestions.cabal
- plugins/hls-cabal-plugin/test/testdata/code-actions/FieldSuggestions.golden.cabal
Depends on  #3268 (and transitively on #2954).
Adds codeactions for misspelled field names in cabal files.
This change moves some inner workings of completions change, to use same logic (and same data).
examples:
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3273"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
> Add codeactions for cabal field names

- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/CabalFields.hs
- plugins/hls-cabal-plugin/test/Main.hs
- plugins/hls-cabal-plugin/test/testdata/goto-definition/simple-with-common.cabal
- plugins/hls-cabal-plugin/test/testdata/hie.yaml
This PR is the start of a go to definition code action for cabal files.
> Add Goto Definition for cabal common sections

- .github/actions/setup-build/action.yml
In some actions, we are seeing runners running out of disk space, for example https://github.com/haskell/haskell-language-server/actions/runs/10438536948/job/28905967511
Let's try to get to the bottom of this.
Fixes #4386
> Clear GHCup caches in CI to not run out of space in CI

- exe/Wrapper.hs
Addresses #4336. When resolving the runtime GHC throws an error, print it. Otherwise show the GHC version.
```
> haskell-language-server-wrapper --probe-tools
haskell-language-server version: 2.9.0.1 (GHC: 9.6.5) (PATH: /home/sgillespie/dev/haskell/haskell-language-server/dist-newstyle/build/x86_64-linux/ghc-9.6.5/haskell-language-server-2.9.0.1/x/haskell-language-server-wrapper/build/haskell-language-server-wrapper/haskell-language-server-wrapper) (GIT hash: 6f6f75bc410c51352e56a87a38a5345bdd44d0bb)
Tool versions found on the $PATH
cabal:          3.10.3.0
stack:          2.15.7
ghc:            9.6.5
Tool versions in your project
2024-08-20T20:42:48.640305Z | Debug | cabal exec -v0 -- ghc --print-libdir
Failed to find the GHC version of this Cabal project.
Error when calling cabal exec …
```
> Improve error message for `--probe-tools`

- cabal.project
- stack-lts22.yaml
- stack.yaml
The temporary dependency solution should be changed since `cabal-add` was released on [Haskage](https://github.com/Bodigrim/cabal-add/issues/7).
>  Update cabal-add dependency

- plugins/hls-cabal-fmt-plugin/src/Ide/Plugin/CabalFmt.hs
I introduced these typos in #4101
> Fix typos in hls-cabal-fmt-plugin

- ghcide/test/exe/Config.hs
- ghcide/test/exe/FindDefinitionAndHoverTests.hs
- ghcide/test/exe/ReferenceTests.hs
- hls-test-utils/src/Test/Hls.hs
- plugins/hls-cabal-fmt-plugin/test/Main.hs
- plugins/hls-cabal-fmt-plugin/test/testdata/commented_testdata.formatted_document.cabal
- plugins/hls-cabal-plugin/test/CabalAdd.hs
- plugins/hls-eval-plugin/test/Main.hs
- plugins/hls-eval-plugin/test/testdata/T20.expected.hs
- plugins/hls-explicit-fixity-plugin/src/Ide/Plugin/ExplicitFixity.hs
- plugins/hls-explicit-fixity-plugin/test/Main.hs
- plugins/hls-explicit-imports-plugin/test/Main.hs
- plugins/hls-refactor-plugin/test/Main.hs
- plugins/hls-refactor-plugin/test/data/import-placement/MultiLinePragma.expected.hs
- plugins/hls-refactor-plugin/test/data/import-placement/OptionsNotAtTopWithSpaces.expected.hs
- plugins/hls-refactor-plugin/test/data/import-placement/OptionsPragmaNotAtTop.expected.hs
- plugins/hls-refactor-plugin/test/data/import-placement/PragmaNotAtTopMultipleComments.expected.hs
- plugins/hls-refactor-plugin/test/data/import-placement/PragmaNotAtTopWithCommentsAtTop.expected.hs
- plugins/hls-refactor-plugin/test/data/import-placement/ShebangNotAtTop.expected.hs
- plugins/hls-refactor-plugin/test/data/import-placement/ShebangNotAtTopNoSpace.expected.hs
- plugins/hls-refactor-plugin/test/data/import-placement/ShebangNotAtTopWithSpaces.expected.hs
- test/functional/Config.hs
Replace _some_ `expectFail` references with explicit checks.  Note that there are some remaining references that should probably be changed.
Addresses #4130 
I've added TODO comments to most of the tests to explain what's wrong (that is, if I could correctly guess it). I wonder if it would be better to have issue numbers instead.
> Avoid expectFail in the test suite

- docs/contributing/contributing.md
I added two things to the `contributing.md`:
- How to run tests for a specific plugin
- How to pass a `tasty` pattern using `TASTY_PATTERN`
> Add docs about running tests for newbies

- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction.hs
- plugins/hls-refactor-plugin/test/Main.hs
This PR addresses #4379.
- Adds a few tests for exporting pattern synonyms with operator names.
- Parenthesizes any name to be exported if it starts with an operator character.
The last commit restructures the code such that any name is parenthesized regardless of what it is exported as.
> Fix exporting operator pattern synonym

- .github/workflows/pre-commit.yml
According to https://github.com/pre-commit/action, we need to use `actions/setup-python@v3` in CI, since GHA did something wonky.
> Fix pre-commit in CI

- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/CabalAdd.hs
- plugins/hls-cabal-plugin/test/CabalAdd.hs
- plugins/hls-cabal-plugin/test/testdata/cabal-add-testdata/cabal-add-packageYaml/cabal-add-bench.cabal
- plugins/hls-cabal-plugin/test/testdata/cabal-add-testdata/cabal-add-packageYaml/src/Main.hs
- plugins/hls-cabal-plugin/test/testdata/cabal-add-testdata/cabal.project
Solves: #4400
Modifies `findResponsibleCabalFile` function to add `guardAgainstHpack` function which checks if a `package.yaml` file exists in the same directory as the `.cabal` file and handles the response in the cabal plugin.
Prevents stack from not more re-generating .cabal file if package.yaml is changed.
> Cabal plugin: implement check for package.yaml in a stack project

- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/Data.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Diagnostics.hs
- plugins/hls-cabal-plugin/test/Main.hs
- plugins/hls-cabal-plugin/test/testdata/unsupportedVersion.cabal
This PR makes sure that line number 0 returned from cabal is handled correctly.
This caused the  marking of the whole cabal file if the cabal version is not supported as described in #4401
> gracefully handle errors for unsupported cabal version

- docs/features.md
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal.hs
Add docs for `cabal-add` based CodeAction
> Enhance formatting of the `cabal-version` error message

- .hlint.yaml
- docs/features.md
- ghcide/src/Development/IDE/Core/Actions.hs
- ghcide/src/Development/IDE/LSP/HoverDefinition.hs
- ghcide/src/Development/IDE/Plugin/HLS/GhcIde.hs
- ghcide/src/Development/IDE/Spans/AtPoint.hs
- ghcide/src/Development/IDE/Spans/Common.hs
- ghcide/test/data/hover/GotoImplementation.hs
- ghcide/test/data/hover/hie.yaml
- ghcide/test/exe/Config.hs
- ghcide/test/exe/FindDefinitionAndHoverTests.hs
- ghcide/test/exe/FindImplementationAndHoverTests.hs
- ghcide/test/exe/InitializeResponseTests.hs
- ghcide/test/exe/Main.hs
- haskell-language-server.cabal
- hls-plugin-api/src/Ide/Types.hs
Rebased and slightly modified version of #1983
Still requires some tests and docs.
> Jump to instance definition and explain typeclass evidence

- plugins/hls-pragmas-plugin/src/Ide/Plugin/Pragmas.hs
- plugins/hls-pragmas-plugin/test/Main.hs
- plugins/hls-pragmas-plugin/test/testdata/DeferredOutOfScopeVariables.expected.hs
- plugins/hls-pragmas-plugin/test/testdata/DeferredOutOfScopeVariables.hs
Fixes #4440
This does the trick, I don't get the code action on my local branch.
~I'm just unsure if those tests do what they are supposed to do.~
~If I disable blacklist~
```haskell
warningBlacklist :: [T.Text]
warningBlacklist =
-- Don't suggest disabling type errors as a solution to all type errors.
[ --"deferred-type-errors"
-- Don't suggest disabling out of scope errors as a solution to all out of scope errors.
--, "deferred-out-of-scope-variables"
]
```
~they do pass on my machine. The list is empty anyway, also in the case of deferred-type-errors. But that is beyond my current knowledge of the codebase.~
Edit: fixed.
> Don't suggest -Wno-deferred-out-of-scope-variables

- cabal.project
- ghcide/src/Development/IDE/GHC/Compat/Core.hs
Can't add CI as https://github.com/haskell-actions/setup doesn't support 9.8.3, yet
> Build HLS with GHC 9.8.3

- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/CabalAdd.hs
- plugins/hls-cabal-plugin/test/CabalAdd.hs
- plugins/hls-cabal-plugin/test/testdata/cabal-add-testdata/cabal-add-multitarget/bench/Main.hs
- plugins/hls-cabal-plugin/test/testdata/cabal-add-testdata/cabal-add-multitarget/cabal-add-multitarget.cabal
- plugins/hls-cabal-plugin/test/testdata/cabal-add-testdata/cabal-add-multitarget/lib/InternalLib.hs
- plugins/hls-cabal-plugin/test/testdata/cabal-add-testdata/cabal-add-multitarget/lib/MyLib.hs
- plugins/hls-cabal-plugin/test/testdata/cabal-add-testdata/cabal-add-multitarget/src/Main.hs
- plugins/hls-cabal-plugin/test/testdata/cabal-add-testdata/cabal-add-multitarget/test/Main.hs
- plugins/hls-cabal-plugin/test/testdata/cabal-add-testdata/cabal.project
This is a continuation of #4393
The PR adds more tests that better reflect implemented cabal-add solution
and adds come changes to the documentation and title of the `CodeActon`.
> More tests and better docs for cabal-add

- docs/requirements.txt
I noticed in #4433 that the read-the-docs build was failing. Let's try upgrading our dependencies :upside_down_face:
> Update python read-the-docs dependencies to latest

- cabal.project
See https://github.com/digital-asset/ghc-lib/issues/572 for the additional constraints.
> Allow building with GHC 9.8.4

- ghcide/src/Development/IDE/GHC/Orphans.hs
- plugins/hls-explicit-record-fields-plugin/src/Ide/Plugin/ExplicitFields.hs
- plugins/hls-explicit-record-fields-plugin/test/Main.hs
- plugins/hls-explicit-record-fields-plugin/test/testdata/PositionalConstruction.expected.hs
- plugins/hls-explicit-record-fields-plugin/test/testdata/PositionalConstruction.hs
Resolves #4391, resolves #4212.
> Support record positional construction inlay hints

- cabal.project
Dramatically decreases linking times and shaves 6 of 14G off HLS' `dist-newstyle` directory on my machine by producing way smaller executables.
While `cabal build`ing HLS after switching a branch I've noticed linking test executables takes minutes, plural, _each_. Then I've checked the size of a freshly-built test binary and it was 150-something megabytes, no wonder linker took a while. With `executable-dynamic` enabled, linking is lightning fast and binaries are a megabyte at most, which should probably improve the developer experience and decrease the feedback loop time.
UPD: https://github.com/haskell/haskell-language-server/issues/2659 seems related, not sure how up-to-date though
> link executables dynamically to speed up linking

- ghcide/src/Development/IDE/Plugin/HLS.hs
- ghcide/test/exe/CompletionTests.hs
- ghcide/test/exe/Config.hs
- ghcide/test/exe/Main.hs
- ghcide/test/exe/ResolveTests.hs
- haskell-language-server.cabal
We had multiple reports, where `resolve` requests (such as `completion/resolve` and `codeAction/resolve`) are rejected by HLS since the `_data_` field of the respective LSP feature has not been populated by HLS.
This makes sense, as we only support `resolve` for certain kinds of `CodeAction`/`Completions`, when they contain particularly expensive properties, such as documentation or non-local type signatures.
So what to do? We can see two options:
1. Be dumb and permissive: if no plugin wants to resolve a request, then just respond positively with the original item! Potentially this masks real issues, but may not be too bad. If a plugin thinks it can handle the request but it then fails to resolve it, we should still return a failure.
2. Try and be smart: we try to figure out requests …
> Implement fallback handler for `*/resolve` requests

- ghcide/session-loader/Development/IDE/Session.hs
- ghcide/src/Development/IDE/GHC/Util.hs
- ghcide/src/Development/IDE/Main.hs
I am currently reading through the ghcide code, and I noticed some supposed dead code, as `unsafeDynFlags` don't exist any more, [`setUnsafeDynFlags`](https://hackage.haskell.org/package/ghc-9.12.1/docs/src/GHC.Driver.Session.html#setUnsafeGlobalDynFlags) (and for [`9.4.8`](https://hackage.haskell.org/package/ghc-9.4.8/docs/src/GHC.Driver.Session.html#setUnsafeGlobalDynFlags)) just sets a couple of `Outputable` `IORef`s, which we likely don't want/need.
Thus, just delete and see whether CI is happy.
> Remove Unsafe Dynflags deadcode, they don't exist any more!

- flake.lock
- flake.nix
Hi! This PR contains a few minor changes to the Nix Flake.
b473c731 * Nix: Update lock files (GHC 9.6.5 -> 9.6.6)
a1b5c431 * Nix Flake: Small fixes, make comments a bit more consistent
39df6247 * Nix Flake: Remove `hlint`
I also removed `hlint` from the flake (last commit). However, this is an opinion up for debate:
We do not really need the `hlint` executable because it is integrated in HLS.
However, `hlint` is used by a GitHub Action, which we may want to replicate locally.
Also, the `fmt.sh` script is downloading an (unknown) `hlint` version which will
not work on NixOS anyways. In my opinion, if `fmt.sh` is still used (I can not
find any usages) we should fix the script so it is reproducible.
> Nix tooling (minor changes)

- .readthedocs.yaml
- docs/Makefile
- docs/contributing/contributing.md
- docs/index.rst
- docs/what-is-hls.md
- flake.nix
Contains opinionated changes, please check!
I was compiling the documentation using  `nix build .#docs`. Two observations:
1. The Nix build command uses a different `sphinx-build` command than the one used in `docs/Makefile`.
2. The Nix build command actually failed because warnings were treated as errors.
So I fixed the warnings (duplicate IDs etc.) and thought, why not use the Makefile to build the documentation also with Nix?
However, that was not easily possible because the Makefile passed on all arguments (i.e., even arguments to the `make` command itself) to `sphinx-build`. (I think that is/was actually a bug.)
Anyways, I ended up changing the Makefile in ways that you may not agree with. In particular,
- I added the -n and -W flags to the `sphinx-build` invocation (warnings are …
> Documentation: Imrpove "Contributing" (and amend Sphinx builders)

- .gitignore
- ghcide/test/exe/ResolveTests.hs
- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction.hs
- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/Plugins/FillHole.hs
- plugins/hls-refactor-plugin/test/Main.hs
Fixes #4508. I am not sure if I caught all usages, there might also be other phrases I did not look for (i.e., other than "Replace ...").
Also, I had to hide an import (`resolveCompletion`) which is a bit werid.
I also ignored an editor configuration file.
> Capitalization of "Replace"

- .github/workflows/bench.yml
- cabal.project
- haskell-language-server.cabal
- shake-bench/shake-bench.cabal
- shake-bench/src/Development/Benchmark/Rules.hs
1. Fix the dependency problem preventing 9.10 from building bench 
2. Enable the bench to build even not for performance label, still need performance label if we need to run it.
3. bump up to actions/checkout-v4 in bench
> Enable bench for 9.10

- .pre-commit-config.yaml
using https://www.geeksforgeeks.org/json-to-yaml-converter/ .
The new YAML configuration appears to be fine:
```
$ pre-commit run --all-files
stylish-haskell..........................................................Passed
mixed line ending........................................................Passed
```
This matches the standard YAML config of the tool: https://pre-commit.com/#installation
------
However, I am not certain `.pre-commit-config.yaml` is working as intended, on `master` or this PR. Can I fix this in a separate PR?
After putting some spaces into `Experiments.hs`
```
module Experiments
( Bench(..)
, BenchRun(..)
, Config(..)
, Verbosity(..)
...
import           Data.Either                        (fromRight)
import           Data.List
import           Data.Maybe
...
```
```
$ …
```
> convert `pre-commit-config.yaml` from JSON to YAML

- ghcide/src/Development/IDE/Types/Shake.hs
- unsafeCoerce was used where `eqTypeRep` could be used, this was corrected
- an incorrect instance for NFData existed which was removed because it's unused
> refactor: remove unnecessary instance and use of unsafeCoerce

- haskell-language-server.cabal
The current `haskell-language-server.cabal` fails when running `cabal check` for `cabal-install  3.12.1.0`. 
I don't know which `cabal` version is used on Hackage, but I know that this `cabal check` was an issue for the last Hackage release.
We need to add a check to the release CI, but it is quite annoying since `cabal check` doesn't accept `all` as a target.
> Fix cabal check for Hackage release

- .github/generate-ci/gen_ci.hs
- .github/scripts/common.sh
- .github/workflows/release.yaml
- ChangeLog.md
- RELEASING.md
- docs/support/ghc-version-support.md
- ghcide/ghcide.cabal
- haskell-language-server.cabal
- hls-graph/hls-graph.cabal
- hls-plugin-api/hls-plugin-api.cabal
- hls-test-utils/hls-test-utils.cabal
- HLS uses lockstep versioning. The core packages and all plugins use the same version number, and only support exactly this version.
- Exceptions:
- `hie-compat` requires no automatic version bump.
- `shake-bench` is an internal testing tool, not exposed to the outside world. Thus, no version bump required for releases.
- For updating cabal files, the following script can be used:
- ```sh
./release/update_versions.sh <OLD_VERSION> <NEW_VERSION>
```
- It still requires manual verification and review
- Generate a ChangeLog via `./GenChangelogs.hs <api-key> <tag>`
- `<tag>` is the git tag you want to generate the ChangeLog from.
- `<api-key>` is a github access key: https://github.com/settings/tokens
- `git switch -c wip/<version>`
- `git tag <version>`
- this creates a draft release
- `git …
> Prepare release 2.10.0.0

- cabal.project
This reverts commit 2df8775fa6062073904e96c48b456045511f05b5.
The PR #4423 seems to have introduced issues for release binaries. Thus, we are reverting the changes as advised in https://github.com/haskell/haskell-language-server/issues/4533#issuecomment-2774883109
We still want to benefit from the reduced test-times, so we might want to enable this option for our test-CI only.
> Revert "link executables dynamically to speed up linking (#4423)"

- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/CabalAdd.hs
- plugins/hls-cabal-plugin/test/CabalAdd.hs
- plugins/hls-cabal-plugin/test/testdata/cabal-add-testdata/cabal-add-tests/cabal-add-tests.cabal
- plugins/hls-cabal-plugin/test/testdata/cabal-add-testdata/cabal-add-tests/test/MainPackageImports.hs
Fix: #4479
TODO: Probably I need to add more tests.
CC @VeryMilkyJoe @fendor
https://github.com/user-attachments/assets/692f441e-19be-46ac-8197-a74bfe6c481c
Here is the string being matched.
With `PackageImports`
```
not found: Could not find module ‘Data.List.Split’
Perhaps you meant
Data.List.Split (needs flag -package-id split-0.2.5)
Data.List.Split (needs flag -package-id split-0.2.5)
```
Without `PackageImports`
```
not found: Could not load module ‘Data.List.Split’
It is a member of the hidden package ‘split-0.2.5’.
Perhaps you need to add ‘split’ to the build-depends in your .cabal file.
It is a member of the hidden package ‘split-0.2.5’.
Perhaps you need to add ‘split’ to the build-depends in your .cabal file.
```
I also notice that the "not found" error remains even after the …
> Support PackageImports in hiddenPackageSuggestion

- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction.hs
- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/Plugins/Diagnostic.hs
- plugins/hls-refactor-plugin/test/Main.hs
This MR contains 3 commits which improves the import suggestion code actions:
- suggests to import a module when the `newtype` constructor is not in scope. This usually happen when `coerce`ing `newtype`.
- suggests to import a module when all the data constructors for a type are not in scope. This usually happen when creating an instance of a type from another module. For example, `deriving instance Generic Bar` when `Bar` (the type) may be in scope, but not the construtors (e.g. requiring `Bar(..)`).
- suggests to import a module when a field of a type is not in scope and used in an `OverloadedRecordDot` context, such as `foo.bar` where `foo :: Foo` and `Foo(bar)` is not in scope. Note that this is already partially handled by HLS in the case where the module containing `Foo` is already …
> Import suggestion for missing newtype constructor, all types constructor and indirect overloadedrecorddot fields

- .github/workflows/test.yml
- haskell-language-server.cabal
- plugins/hls-refactor-plugin/src/Development/IDE/GHC/ExactPrint.hs
- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction.hs
- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs
- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/Plugins/AddArgument.hs
- plugins/hls-refactor-plugin/test/Main.hs
- plugins/hls-refactor-plugin/test/Test/AddArgument.hs
- test/testdata/schema/ghc912/default-config.golden.json
- test/testdata/schema/ghc912/vscode-extension-schema.golden.json
These changes allow the hls-refactor plugin to compile and pass the tests with ghc-9.12
> porting hls-refactor to ghc-9.12

- scripts/release/create-yaml-snippet.sh
Fixes #4539 by changing the URLs of the release binaries on GitHub release and downloads.haskell.org/~hls from now on.
> Update the ghcup-metadata generation script

- .circleci/config.yml
- cabal.project
- ghcide/ghcide.cabal
- haskell-language-server.cabal
- stack-lts22.yaml
- stack.yaml
Using GHC 9.12 compatible version of hiedb released yesterday.
> Remove allow-newer for hiedb

- docs/support/plugin-support.md
Demote `hls-refactor-plugin` to tier 2, as we regularly ship the initial GHC support without it.
> Update plugin support table for GHC 9.12.2

- haskell-language-server.cabal
> add ghcide-bench flag to .cabal file

- .github/workflows/test.yml
- docs/support/plugin-support.md
- haskell-language-server.cabal
- plugins/hls-hlint-plugin/test/Main.hs
- test/testdata/schema/ghc912/default-config.golden.json
- test/testdata/schema/ghc912/vscode-extension-schema.golden.json
@fendor : I know this fails a test, but could you check it out? It seems to not be doing what the test is checking that it doesn't do, and the added space is actually what I would expect to happen so before I dive for a bug that might actually be a feature, I'd rather have your advice.
P.S.: Not enabling for ghc-9.10 as apply-refact doesn't work with ghc-9.10.
P.P.S.: apparently I've done something wrong with the flags :( . Happy for some pointers.
> enable hlint for ghc-9.12

- .pre-commit-config.yaml
- docs/features.md
- haskell-language-server.cabal
- plugins/hls-eval-plugin/README.md
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval.hs
- plugins/hls-eval-plugin/src/Ide/Plugin/Eval/Handlers.hs
- plugins/hls-eval-plugin/test/Main.hs
- test/testdata/schema/ghc912/default-config.golden.json
- test/testdata/schema/ghc912/vscode-extension-schema.golden.json
- test/testdata/schema/ghc94/default-config.golden.json
- test/testdata/schema/ghc94/vscode-extension-schema.golden.json
- test/testdata/schema/ghc96/default-config.golden.json
- test/testdata/schema/ghc96/vscode-extension-schema.golden.json
- test/testdata/schema/ghc98/default-config.golden.json
- test/testdata/schema/ghc98/vscode-extension-schema.golden.json
Code action and lens are provided at the same time.
In addition, a file is excluded from stylish-haskell pre-commit hook due to a CPP issue introduced in #4527.
Fix: #496
> Provide code action in hls-eval-plugin

- .github/workflows/test.yml
- cabal.project
- docs/support/plugin-support.md
- haskell-language-server.cabal
- plugins/hls-stylish-haskell-plugin/src/Ide/Plugin/StylishHaskell.hs
With the release of stylish-haskell-0.15.0.0, it now builds with ghc-lib-parser-9.10, so we can enable the plugin for ghc-9.10.
Note that a ghc-lib-parser-9.12 version should be released soon.
> Enable stylish-haskell for ghc-9.10 and ghc-9.12

- cabal.project
Few more dependencies now have GHC 9.12 versions / revisions available.
> Remove no longer needed allow-newer

- .github/workflows/test.yml
- docs/support/ghc-version-support.md
- docs/support/plugin-support.md
- haskell-language-server.cabal
- plugins/hls-gadt-plugin/src/Ide/Plugin/GHC.hs
- test/testdata/schema/ghc912/default-config.golden.json
- test/testdata/schema/ghc912/vscode-extension-schema.golden.json
Unless I'm mistaken, that's the last tier 2 plugin for ghc-9.12
> Enable hls-plugin-gadt for ghc-9.12

- plugins/hls-explicit-imports-plugin/src/Ide/Plugin/ExplicitImports.hs
- plugins/hls-explicit-record-fields-plugin/src/Ide/Plugin/ExplicitFields.hs
resolve #4561.
fixed `hls-explicit-imports-plugin`, `hls-explicit-record-fields-plugin`.
> Fix misplaced inlay hints by applying PositionMapping

- docs/support/plugin-support.md
Closes #4578 
I think it is fine to update the release branch, as the tag is not updated. This is a documentation change, only.
> Fix Plugin support table for 9.12.2

- .github/actions/setup-build/action.yml
- .github/workflows/bench.yml
- cabal.project
- ghcide/ghcide.cabal
- ghcide/session-loader/Development/IDE/Session/Diagnostics.hs
- stack-lts22.yaml
- stack.yaml
This allows us to benefit from the `cabal path` command in hie-bios for improved start-up time.
Also, update CI to use `cabal 3.14` so that we actually test the `cabal path` code path.
Closes #4562
> Use hie-bios 0.15.0

- docs/configuration.md
- docs/features.md
Also add doc for `sessionLoading` since it is needed by project-wide renaming.
Doc for `cabalFormattingProvider` is also added.  It is not tightly connected to the theme of this PR though.
related: #2193 #3738
closes: #4355
> Add doc for project-wide renaming

- ghcide-test/data/watched-files/reload/reload.cabal
- ghcide-test/data/watched-files/reload/src/MyLib.hs
- ghcide-test/exe/WatchedFileTests.hs
- ghcide/session-loader/Development/IDE/Session.hs
- plugins/hls-cabal-plugin/test/Main.hs
This patch fixes #1068 when the cabal plugin is not used.
---
The code change in Session.hs is written by @fendor.  Tests and comments are added by me.
> Make cradle dependencies absolute paths

- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/Completer/Paths.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/Data.hs
- plugins/hls-cabal-plugin/test/Completer.hs
- plugins/hls-cabal-plugin/test/testdata/completion/autogen-completion.cabal
Adds completions 'autogen-incudes' and 'autogen-modules'.
Supersedes both #4534 and #4535
> Add "autogen-" field completions and tests for cabal files

- plugins/hls-explicit-record-fields-plugin/src/Ide/Plugin/ExplicitFields.hs
- plugins/hls-explicit-record-fields-plugin/test/Main.hs
- plugins/hls-explicit-record-fields-plugin/test/testdata/noop/PartiallyAppliedCon.hs
Fixes #4564.
"Positional record expansion" only makes sense if the constructor application has all the required arguments provided, otherwise invalid code is generated as demonstrated in the linked issue. This PR augments the collected records with "saturation" information, so that unsatured applications can be filtered out during the code action generation.
(cc: @jetjinser, do you mind taking a look into this, as you were the author of #4447)
> Only expand positional records if the DataCon application is fully saturated

- .github/workflows/test.yml
- docs/contributing/plugin-tutorial.lhs
- docs/contributing/plugin-tutorial.md
- flake.lock
- ghcide/src/Development/IDE/GHC/Compat/Core.hs
- haskell-language-server.cabal
- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction.hs
Some changes are mine, but many have been cherry picked and amended from PR #3655 by Christian Georgii <cgeorgii@gmail.com>. @cgeorgii 
This PR now includes most changes of #3655. I did not include the last sections which are behind a "what shall we do with those" comment in the aforementioned PR. I am not sure how to deal with those.
Another issue is that the link to the gist is outdated (and still links to the original one by Pepe Iborra). So I think we either have to remove the link or write a new gist and replace the link. What are your opinions?
I did not implement the literate file stuff, it seems too complicated to achieve in one PR.
Supersedes #3655.
> Plugin tutorial, more changes

- ghcide/src/Development/IDE/GHC/CoreFile.hs
- ghcide/src/Development/IDE/GHC/Util.hs
- ghcide/src/Development/IDE/Plugin/Completions/Logic.hs
- plugins/hls-explicit-record-fields-plugin/src/Ide/Plugin/ExplicitFields.hs
- plugins/hls-explicit-record-fields-plugin/test/Main.hs
- plugins/hls-explicit-record-fields-plugin/test/testdata/ConstructionDuplicateRecordFields.hs
- plugins/hls-explicit-record-fields-plugin/test/testdata/HsExpanded1DuplicateRecordFields.hs
- plugins/hls-explicit-record-fields-plugin/test/testdata/PositionalConstructionDuplicateRecordFields.hs
Fix for: https://github.com/haskell/haskell-language-server/issues/4547
DuplicateRecordFields adds `$sel:...:fieldName`  to disambiguate record selectors. The selectors are included in the inlay hints making them slightly confusing:
> Strip prefixes added by DuplicateRecordFields 

- flake.nix
GCC is provided in dev shell. External `curl` is incompatible with dev shell-provided GCC, resulting in `GLIBC` error. Solution is for dev shell to provide both GCC and `curl`.
> provide `curl` in dev shell

- plugins/hls-class-plugin/src/Ide/Plugin/Class/CodeAction.hs
- plugins/hls-class-plugin/src/Ide/Plugin/Class/Types.hs
Split off from #4433, this PR moves the `hls-class-plugin` to use the structured diagnostics. 
It worked well in my tests, but unfortunately it is incompatible with GHC 9.4, because the error message the plugin cares about is not structured in 9.4.
We can either wait until we drop support for 9.4 or maintain both paths until we drop support for 9.4.
Unfortunately, the only way to push GHC into the direction we want, is to do the latter and report any lacking error messages to GHC ASAP.
FYI, only the last commit matters.
> Migrate `hls-class-plugin` to use structured diagnostics

- ghcide/ghcide.cabal
- haskell-language-server.cabal
- hls-plugin-api/hls-plugin-api.cabal
https://hackage.haskell.org/package/Diff
Compilation succeeds with `Diff ^>= 1.0`
```
cabal test --enable-tests --constraint 'Diff>=1.0'
```
1 test fails:
```
1 out of 376 tests failed (535.93s)
```
```
FAIL (1.74s)
plugins/hls-refactor-plugin/test/Main.hs:3966:
CodeAction with title "add signature: hello :: GHC.Types.Any -> IO ()" not found in ["add signature: hello :: GHC.Types.ZonkAny 0 -> IO ()"]
Use -p '/hello = print/' to rerun this test only.
```
> allow Diff 1.x

- ghcide-test/exe/Main.hs
- haskell-language-server.cabal
- stack-lts22.yaml
This reverts commit 349ff6e18cbd35a502e05780f0bc6bca4bbc1074.
I don't know why, but this change breaks the usage of `TASTY_PATTERN` and `-p` for filtering by pattern.
> Revert "Switch ghcide tests to sequential execution (#4307)"

- plugins/hls-eval-plugin/test/testdata/TPropertyError.ghc910.expected.hs
`hls-eval-plugin` tests are currently failing in CI with:
```
Test output was different from 'plugins/hls-eval-plugin/test/testdata/TPropertyError.ghc910.expected.hs'. Output of ["git","-c","core.fileMode=false","diff","--no-index","--text","--exit-code","plugins/hls-eval-plugin/test/testdata/TPropertyError.ghc910.expected.hs","/tmp/TPropertyError.ghc910.expected89418-27.actual"]:
diff --git a/plugins/hls-eval-plugin/test/testdata/TPropertyError.ghc910.expected.hs b/tmp/TPropertyError.ghc910.expected89418-27.actual
index e3208e3..87fbda0 100644
--- a/plugins/hls-eval-plugin/test/testdata/TPropertyError.ghc910.expected.hs
+++ b/tmp/TPropertyError.ghc910.expected89418-27.actual
@@ -10,4 +10,8 @@ module TProperty where
--     errorEmptyList, called at …
```
> CI: Fix hls-eval-plugin tests for GHC-9.10

- ghcide/session-loader/Development/IDE/Session.hs
> Bump up hiedb version #4639

- ghcide-test/data/references/Fields.hs
- ghcide-test/data/references/Main.hs
- ghcide-test/data/references/hie.yaml
- ghcide-test/exe/ReferenceTests.hs
- ghcide/src/Development/IDE/Spans/AtPoint.hs
Fix #4412
Very small change, Change `getNamesAtPoint` to only include names in the source.
> Add tests for references to record fields and update symbol retrieval to only include source nodes

- ghcide/src/Development/IDE/GHC/Compat/Error.hs
This was introduced in #4632. The constructor for `TypeEqMismatch` changed at 9.10.2 (not at 9.12 as I previously thought)
Previously, this would fail on GHC 9.10.2 (`nix-shell -p haskell.compiler.ghc9102 --command "cabal build all"`):
```
src/Development/IDE/GHC/Compat/Error.hs:111:41: error: [GHC-27346]                                                                                                                                                                                             
• The data constructor ‘TypeEqMismatch’ should have 7 arguments, but has been given 8                                                                                                                                                                      
• In the pattern: TypeEqMismatch _ _ _ _ expected _ …
```
> Fix build for GHC 9.10.2

- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction/ExactPrint.hs
- plugins/hls-refactor-plugin/src/Development/IDE/Plugin/CodeAction/Util.hs
- plugins/hls-refactor-plugin/test/Main.hs
For now it is just a repro for #4648
Tested with ghc 9.12.2, it seems to fail as expected:
```
[guillaume@gecko:~/srcs/haskell-language-server]$ cabal run hls-refactor-plugin-tests -- -p haddock
Configuration is affected by the following files:
- cabal.project
refactor
code actions
add function constraint
preexisting constraint, with haddock comment in type signature: FAIL (0.84s)
plugins/hls-refactor-plugin/test/Main.hs:3122:
expected: "module Testing where\ndata Pair a b = Pair a b\neq \n    :: (Eq a, Eq b)\n    =>\n   -- This is the first argument\n   Pair a b ->\n   -- And this is the second\n   Pair a b ->\n   -- And this is the result\n   Bool\neq (Pair x y) (Pair x' y') = x == x' && y == y'\n"
but got: "module Testing where\ndata Pair a b = Pair a b\neq \n    :: (Eq a,\n\n   -- …
```
> fix: add context code action with trailing comment

- cabal.project
- ghcide-test/data/multi-unit/a-1.0.0-inplace
- ghcide-test/data/multi-unit/c-1.0.0-inplace
- ghcide-test/exe/CradleTests.hs
- ghcide/ghcide.cabal
- ghcide/session-loader/Development/IDE/Session.hs
- stack-lts22.yaml
- stack.yaml
Adds support for `cabal repl --with-repl`, see https://github.com/haskell/hie-bios/issues/467 and https://github.com/haskell/cabal/issues/9115 for context.
This tests whether HLS uncovers any errors already.
Closes #4590 and closes #3730
> Use hie-bios 0.16

- ghcide/src/Development/IDE/Spans/Common.hs
- Replace fallback messages with raw LaTeX math expressions using `$...$` and `$$...$$`.
- This lets editors display the original math content even if they don't render LaTeX.
- No sanitization is performed, raw LaTeX is output as-is.
- Related to #201
> Show LaTeX math expressions in haddockToMarkdown

- ghcide/ghcide.cabal
- ghcide/src/Text/Fuzzy/Levenshtein.hs
- ghcide/src/Text/Fuzzy/Parallel.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/Completer/Module.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/Completer/Simple.hs
- plugins/hls-cabal-plugin/src/Ide/Plugin/Cabal/Completion/Completer/Types.hs
- plugins/hls-cabal-plugin/test/Completer.hs
- plugins/hls-cabal-plugin/test/Main.hs
- plugins/hls-cabal-plugin/test/testdata/code-actions/FieldSuggestions.cabal
- plugins/hls-cabal-plugin/test/testdata/code-actions/FieldSuggestions.golden.cabal
- plugins/hls-cabal-plugin/test/testdata/code-actions/FieldSuggestionsTypos.cabal
- plugins/hls-cabal-plugin/test/testdata/code-actions/FieldSuggestionsTypos.golden.cabal
Closes #4357.
This adds a pretty simple function for calculating the edit distance between two strings and uses it to score suggestions in completion lists. Some 
- I increased the cost of substitutions, otherwise the suggestions would very often lean towards nonsense.
- Kind of hackily injected the `Matcher` that's used in scoring texts into `CompleterData`. Couldn't really massage that into the `weightedConstantCompleter` that's used for licenses.
- This new scoring function doesn't do any filtering, so I had to adjust the cabal codeaction golden test to pick the top action per diagnostic.
> Use edit-distance to fix typos in cabal fields

- ghcide/src/Development/IDE/Core/Rules.hs
Since the latest HLS release, I am getting spammed with log messages such as: 
```
2025-10-06T11:16:14.121738Z | Info | Add dependency /home/hugin/Documents/haskell/cabal/Cabal/src/Distribution/Simple/PreProcess.hs
[ /home/hugin/Documents/haskell/cabal/Cabal/Cabal.cabal
, /home/hugin/Documents/haskell/cabal/cabal.project
, /home/hugin/Documents/haskell/cabal/cabal.project.local
, /home/hugin/Documents/haskell/cabal/hie.yaml ]
2025-10-06T11:16:14.121891Z | Info | Add dependency /home/hugin/Documents/haskell/cabal/Cabal/src/Distribution/Simple/ShowBuildInfo.hs
[ /home/hugin/Documents/haskell/cabal/Cabal/Cabal.cabal
, /home/hugin/Documents/haskell/cabal/cabal.project
, /home/hugin/Documents/haskell/cabal/cabal.project.local
, /home/hugin/Documents/haskell/cabal/hie.yaml ] …
```
> Remove overly chatty log message
