haskell/haskell-language-server

exe/Main.hs, src/Ide/Plugin/Example.hs
Proof of concept external plugin
=> Use ndmitchell plugin refactor

README.md
Acting as a background context to project
=> Link to Neil's post in README

cabal-ide-install, cabal-ide-install.cmd, install/src/Cabal.hs, install/src/Stack.hs
=> Install only haskell-ide executables in install.hs

.circleci/config.yml, README.md
We can merge when CI passes :)
This is a smoke test setup, until we decide on a final setup.
And convenient for enabling against private forks
=> Add circleci

stack-8.6.4.yaml, stack-8.6.5.yaml, stack-8.8.2.yaml, stack.yaml
* To not build, test and install it by default
=> Change ghcide from local package to extra-dep

stack-8.6.4.yaml, stack-8.6.5.yaml, stack-8.8.2.yaml, stack.yaml
I've keep the filepath seps cause they work in both sections
=> Move ghcide to local packages again

src/Ide/Cradle.hs
* commit [9f5bce](https://github.com/haskell/haskell-ide-engine/commit/9f5bce46deda9fc4fecf74b0e037deab66f1bd95 ) from the pr https://github.com/haskell/haskell-ide-engine/pull/1654
=> Port 9f5bce by @fendor from hie

haskell-language-server.cabal, src/Ide/Plugin/Formatter.hs, src/Ide/Plugin/Ormolu.hs
=> Remove CPP directives supporting GHC 8.4

.circleci/config.yml
* Added stack one for ghc-8.8.3 too
=> Add jobs for stack and cabal using ghc-8.10.1

install/src/HlsInstall.hs, install/src/Stack.hs
* `stack install haskell-language-server-wrapper` fails, you have to prepend a `:` to make stack happy
=> Fix install script dev target

cabal.project, stack-8.10.1.yaml, stack-8.6.4.yaml, stack-8.6.5.yaml, stack-8.8.2.yaml, stack-8.8.3.yaml, stack.yaml
* It fixes #90 (tested locally)
=> Update ghc-lib-parser version

.gitmodules, exe/Main.hs, stack-8.6.4.yaml, stack-8.6.5.yaml, stack-8.8.2.yaml, stack-8.8.3.yaml, stack.yaml
To
commit 326e3e32f8b5e46088257f8df5cb5b42d1a3cd59 wz1000/hls-2
=> Bump ghcide

haskell-language-server.cabal, stack-8.10.1.yaml, stack-8.6.4.yaml, stack-8.6.5.yaml, stack-8.8.2.yaml, stack-8.8.3.yaml, stack.yaml
hls tests are passing. The ghcide tests don't pass for me on master.
=> Bump ormolu to 0.1.2.0

.github/workflows/build.yml
=> Add static binaries for ghc-8.8.4

.github/workflows/build.yml
* Testing release: https://github.com/jneira/haskell-language-server/actions/runs/193999363
=> Add exe extension to win executables

shell.nix
=> tech(nix): Allow broken as retrie is marked as broken

README.md
use-package is used in the block below
=> Add use-package to the list of emacs packages

.gitmodules
=> Update the ghcide upstream to be in haskell/ghcide

plugins/default/src/Ide/Plugin/Retrie.hs
=> [retrie] Fix uris in workspace edit

cabal.project, stack-8.10.1.yaml, stack-8.10.2.yaml, stack-8.6.4.yaml, stack-8.6.5.yaml, stack-8.8.2.yaml, stack-8.8.3.yaml, stack-8.8.4.yaml, stack.yaml
=> Use implicit-hie-cradle-0.2.0.1

.github/workflows/test.yml
* To see we can workaround the compiler segfault in windows+ghc-8.10.1
=> Retry the build three times

plugins/default/src/Ide/Plugin/Retrie.hs
Fixes the duplicate rule action spotted in #533
=> [retrie] Fix code action title

.github/workflows/test.yml
* The last test invocation fails otherwise
=> Use bash shell to allow its idioms

.github/workflows/build.yml
=> Preserve file permissions in tar bundles

.github/workflows/test.yml
* As https://github.com/actions/setup-haskell/issues/44 is closed
=> Remove workaround in github actions not longer needed

nix/default.nix
Brings a very noticeable performance improvement to `nix-shell`
=> [nix-shell] Actually use gitignore

haskell-language-server.cabal, src/Ide/Main.hs
Fix https://github.com/haskell/haskell-language-server/issues/676
Another indicator that we should probably merge ghcide and HLS.
=> Restore kick (#676)

cabal.project, exe/Plugins.hs, haskell-language-server.cabal, hie-cabal.yaml, hie-stack.yaml, nix/default.nix, plugins/hls-class-plugin/LICENSE, plugins/hls-class-plugin/hls-class-plugin.cabal, plugins/hls-class-plugin/src/Ide/Plugin/Class.hs, shell.nix, stack-8.10.1.yaml, stack-8.10.2.yaml, stack-8.6.4.yaml, stack-8.6.5.yaml, stack-8.8.2.yaml, stack-8.8.3.yaml, stack-8.8.4.yaml, stack.yaml, test/functional/Class.hs, test/functional/Main.hs, test/testdata/class/T1.eq.expected.hs, test/testdata/class/T1.hs, test/testdata/class/T1.ne.expected.hs, test/testdata/class/T2.fmap.expected.hs, test/testdata/class/T2.hs, test/testdata/class/T3.1.expected.hs, test/testdata/class/T3.2.expected.hs, test/testdata/class/T3.hs
Resolves #652, and related to #653.
- Two disjoint minimal sets:
- Multiple methods in minimal sets (which are not disjoint):
=> Implement basic Class plugin

.github/workflows/bench.yml, .github/workflows/nix.yml, .github/workflows/test.yml
Reverts haskell/haskell-language-server#1154 as it runs into permission issues (see #1155)
=> Revert "Auto cancel redundant workflows (attempt #2)"

plugins/hls-splice-plugin/hls-splice-plugin.cabal
Just a minor correction to Cabal file, which had an incomplete sentence.
=> Preparation for Uploading Splice Plugin to Hackage

.gitignore
Ignore the `.shake` folder (created by `cabal bench ghcide`)
=> Ignore .shake folder

ghcide/CHANGELOG.md
Somehow I failed to notice: 2020 is over!
=> Fix changelog dates

.github/workflows/bench.yml
Forgot to include this change in #1253
=> Update bench.yml to include all the relevant artifacts

ghcide/src/Development/IDE/Plugin/CodeAction.hs
The error call was only for diagnostics, so I have replaced
it with a debug trace (commented out)
=> Do not error out on failed rewrite

ghcide/src/Development/IDE/Import/FindImports.hs
=> FindImports typo (minor)

plugins/hls-retrie-plugin/changelog.md, plugins/hls-retrie-plugin/hls-retrie-plugin.cabal
=> hls-retrie-plugin 0.1.1.0

plugins/hls-explicit-imports-plugin/hls-explicit-imports-plugin.cabal
=> Bump explicit-imports plugin

cabal.project, ghcide/ghcide.cabal, stack-8.10.2.yaml, stack-8.10.3.yaml, stack-8.10.4.yaml, stack-8.6.4.yaml, stack-8.6.5.yaml, stack-8.8.2.yaml, stack-8.8.3.yaml, stack-8.8.4.yaml, stack.yaml
Should fix https://github.com/haskell/haskell-language-server/issues/1374
=> Use lsp-1.1.1

install/src/Env.hs, install/src/Print.hs
Fix to the issue mentioned [here](https://github.com/haskell/haskell-language-server/pull/1227#issuecomment-781912241)
=> Fix install script after hlint fixes

cabal.project, stack-8.10.2.yaml, stack-8.10.3.yaml, stack-8.10.4.yaml, stack-8.6.4.yaml, stack-8.6.5.yaml, stack-8.8.2.yaml, stack-8.8.3.yaml, stack-8.8.4.yaml, stack.yaml
Closes #1403
Required for #1402
=> Update to hie-bios 0.7.4

nix/default.nix
=> Fix pre-commit-hook

install/src/Env.hs, install/src/Print.hs, install/src/Stack.hs
=> Remove custom 'trim' implementation

plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
* To include the fix for #591
* ~~I would upload this version to hackage directly (without uploading 1.0.0.0)~~ no, see #1470
=> Bump up hlint plugin version

ghcide/ghcide.cabal, hls-plugin-api/hls-plugin-api.cabal, plugins/hls-eval-plugin/hls-eval-plugin.cabal, plugins/hls-hlint-plugin/hls-hlint-plugin.cabal
=> Add bounds for Diff

ghcide/ghcide.cabal, ghcide/src/Development/IDE/Spans/Common.hs, stack-8.10.2.yaml, stack-8.10.3.yaml, stack-8.10.4.yaml, stack-8.8.3.yaml, stack-8.8.4.yaml
Will need a Hackage release after landing
=> Restore compat. with haddock-library 1.8

plugins/hls-tactics-plugin/README.md, plugins/hls-tactics-plugin/src/Wingman/FeatureSet.hs
This PR ungates three features, since they've now been baking for a release with no problem reported by the beta testers.
=> Wingman feature release

plugins/hls-class-plugin/hls-class-plugin.cabal, plugins/hls-eval-plugin/hls-eval-plugin.cabal, plugins/hls-hlint-plugin/hls-hlint-plugin.cabal, plugins/hls-retrie-plugin/hls-retrie-plugin.cabal, plugins/hls-splice-plugin/hls-splice-plugin.cabal
These don't seem to be required, so trim them down.
=> Remove unnecessary Shake dependencies

ghcide/src/Development/IDE/GHC/ExactPrint.hs
=> Fix reduction depth

README.md
* Add a badge to encourage issue triaging via https://www.codetriage.com/haskell/haskell-language-server
* It will send you a selection of random (but uniformly distributed on time) issues to take a look on
=> Add codetriage badge

hls-test-utils/src/Test/Hls.hs
=> Ignore filemode in diff

plugins/hls-splice-plugin/hls-splice-plugin.cabal
* As commented in #1808 this version is needed to upload a new hackage tarball with lf line endings
=> Bump up hls-splice-plugin to 1.0.0.2

plugins/hls-tactics-plugin/COMMANDS.md, plugins/hls-tactics-plugin/hls-tactics-plugin.cabal, plugins/hls-tactics-plugin/src/Wingman/Metaprogramming/Parser.hs, plugins/hls-tactics-plugin/src/Wingman/Metaprogramming/Parser/Documentation.hs
This PR annotates every command exposed via the metaprogram parser with documentation. It also includes a little pretty printer to generate a markdown file of that documentation.
=> Wingman metaprogram command documentation

.github/workflows/nix.yml
I talked to the cachix guy, who said our old cachix install URL got garbage collected. He gave me this one instead.
=> Fix nix.yaml

plugins/hls-tactics-plugin/hls-tactics-plugin.cabal
=> Fix Wingman dependency on extra

FUNDING.yml, README.md
* Closes #1440 
* This have to add the FUNDING.yml as described at https://docs.github.com/en/github/administering-a-repository/managing-repository-settings/displaying-a-sponsor-button-in-your-repository#about-funding-files
=> Include sponsorship section

README.md
To help users see the difference between hackage and github released versions
=> Add badge with github release

plugins/hls-ormolu-plugin/hls-ormolu-plugin.cabal, plugins/hls-stylish-haskell-plugin/hls-stylish-haskell-plugin.cabal
* Fixes #2206 
* Fixes #2205 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2207"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Relax upper bounds over ormolu and stylish-haskell

flake.nix
since it is helpful to help troubleshoot hie.yaml issues and since the binaries are built anyway.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2221"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> feat(flake): expose hie-bios

.github/workflows/test.yml
It does not work for prs from external repos like #2324 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2325"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Remove automatic comment to [skip circleci]

hls-graph/hls-graph.cabal, hls-graph/src/Development/IDE/Graph/Internal/Paths.hs, hls-graph/src/Development/IDE/Graph/Internal/Profile.hs
Fix an oversight in the hls-graph profiling code
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2395"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix hls-graph build with embed-files flag

haskell-language-server.cabal
* I forgot to do it in the previous pr 🤦 
* hackage check:  https://github.com/jneira/haskell-language-server/actions/runs/1512981182
* build check: https://github.com/jneira/haskell-language-server/actions/runs/1512982093
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2409"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Bum up hls version to 1.5.1

stack-9.0.1.yaml
Update to latest nightly snapshot and remove/update extra deps where possible.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2489"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> stack-9.0.1: update/cleanup

src/Ide/Arguments.hs
=> Correct typo in Ide.Arguments:listPluginsParser

CODEOWNERS
Due to this comment: https://github.com/haskell/haskell-language-server/pull/2619#issuecomment-1025237395
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2661"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Assign ourmolu to @georgefst

CODEOWNERS
Sorry for being absent for a few days, I'm glad to keep track of call-hierarchy-plugin :)
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2708"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Add @July541 for call-hierarchy-plugin

bindist/GNUmakefile.in
https://gitlab.haskell.org/maerwald/haskell-language-server/-/pipelines/48465
=> Fix FreeBSD bindist build

exe/Wrapper.hs
https://github.com/haskell/hie-bios/pull/337
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/2757"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix the tower of Babel

docs/configuration.md
Add [Helix](https://github.com/helix-editor/helix) editor to configuration docs.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3014"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> add Helix to configuration.md

flake.lock
to avoid the issue specified at https://github.com/NixOS/nixpkgs/issues/179172
=> build(nix): bumped gitignore dependency

src/Ide/Main.hs
Fix the --testing flag for HLS to correctly link the ghcide test plugin.
Requires #3112 to work correctly.
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3113"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Fix --testing

CODEOWNERS
Cause i am getting lot of notifications i dont have time to attend and i dont expect that will change in the foresee future
Thanks in advance!
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3230"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [skip ci] Remove myself from codeowners

docs/support/plugin-support.md
Tiny typo, but plugin name needs to be corrected 😅
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3251"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> Docs: Plugin Support hls-explicit-fixity-plugin

docs/support/index.rst
:facepalm: 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3252"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> GCH -> GHC

ghcide/ghcide.cabal, ghcide/src/Development/IDE/Spans/Common.hs, ghcide/test/exe/Main.hs
solve #3222 
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3303"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> support haddock-library 1.11

CODEOWNERS
https://github.com/haskell/haskell-language-server/pull/3304#issuecomment-1310161944
<a href="https://gitpod.io/#https://github.com/haskell/haskell-language-server/pull/3329"><img src="https://gitpod.io/button/open-in-gitpod.svg"/></a>
=> [skip ci] Add myself to CODEOWNERS

haskell-language-server.cabal, plugins/hls-call-hierarchy-plugin/hls-call-hierarchy-plugin.cabal
I missed bumping this while preparing the release.
=> Bump hls-call-hierarchy-plugin (#3427)

.github/actions/setup-build/action.yml, .github/workflows/bench.yml, .github/workflows/caching.yml, .github/workflows/test.yml
Also drop 9.4.3, 9.4.2 and 9.2.3
=> Add CI for 9.4.4

hie-compat/hie-compat.cabal
ghc 8.8 is no longer supported
=> Fix ghc min bounds for hie-compat

.github/actions/setup-build/action.yml, .github/workflows/bench.yml
Hopefully this will help with the Windows issues.
=> Bump haskell/actions

cabal.project, plugins/hls-stan-plugin/hls-stan-plugin.cabal
Fixes: https://github.com/haskell/haskell-language-server/issues/3885
=> Update index-state to get latest stan version

.github/workflows/bench.yml, .github/workflows/release.yaml
The other PRs are failing, I suspect they need to be updated in sync.
=> Bump both upload and download artifact

docs/support/ghc-version-support.md, docs/support/plugin-support.md
Now @wz1000 has fixed the exactprint plugins I think we can declare full support for 9.8.
=> Update support tables

plugins/hls-class-plugin/test/Main.hs
=> Fix document version test in hls-class-plugin

CODEOWNERS
We should stop spamming him. Thanks for everything, @pepeiborra !
=> Remove Pepe from CODEOWNERS

ghcide/src/Development/IDE/Main.hs
I think I dropped this for testing, but it should be set to what it says it is.
=> Fix progress start delay

plugins/hls-cabal-plugin/test/Main.hs
#3333 should be fixed by #4190
=> Enable cabal flaky test

plugins/hls-refactor-plugin/test/Main.hs
Documents behavior described in #806
=> test: add test documenting #806

docs/contributing/plugin-tutorial.md
Amend the HLS plugin tutorial.
Some of these changes are opinionated, feel free to discuss or reject them.
@pepeiborra
=> Documentation: HLS plugin tutorial improvements
